### ISSUE TITLE
Move the roadmap to a gh project

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#10]
I made things more complicated than they needed to be, move the roadmap to projects within this repo so everything is in one place.

https://speedtest-tracker-roadmap.alexjustesen.dev/

**Comment by alexdelprete** [comment]
You mean you moved it from that site to GH repo? I don't see it...yet...

**Comment by alexjustesen** [comment]
Roadmap will be moved to this repo so eventually I'll shutdown https://speedtest-tracker-roadmap.alexjustesen.dev/

**Comment by alexjustesen** [comment]
Moved active tasks to https://github.com/alexjustesen/speedtest-tracker/projects
