### ISSUE TITLE
Since v0.14.x - slow upload results?

### ISSUE THREAD

**Issue by luckman212** [alexjustesen/speedtest-tracker#1006]
Not even sure how this would be possible, but it is what it is. Nothing else changed on my Docker host (a Synology) side, just updated my container from 0.13.4 to 0.14.0 around Dec 18 (and now 0.14.1)

<img width="1019" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/1992842/e15ea3bf-6f43-415b-b465-9b7fccf2baec">

Any idea why the Upload side seems sort of capped around 50-60MBps now?

**Comment by alexjustesen** [comment]
That's a good question, I've also got mine running on a Synology DS920+ and haven't noticed any changes since `v0.14.x`.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/dc701daf-0c71-46b7-96e6-34842e5c50ee)

Try the following to see if things improve:

1. Open the terminal of the container
2. Run `php artisan optimize:clear`
3. Run `php artisan optimize`

This will reset anything that's cached to at least rule that out.

**Comment by luckman212** [comment]
Thanks - I ran those optimizations, will see if it does anything.

Also just noticed that the tests are running every hour, even though my crontab is set to every 4 hours

```
*/240 * * * *
```

Is the above not a valid syntax? Do I need to use `0 */4 * * *` instead?

**Comment by alexjustesen** [comment]
I'd lean towards `0 */4 * * *` as it just reads better but I don't see why "every 240 minutes" wouldn't work.

**Comment by luckman212** [comment]
They are subtly different - `*/240 * * * *` should be every 4 hours from whenever the cron daemon starts, which could be at 33 minutes past the hour, etc. Whereas `n */4 * * *` would be _exactly_ at n minutes past the hour every 4th hour. I guess it doesn't much matter, but I prefer the randomness of `*/240 * * * *`

Long story short, it's not working though.

<img width="832" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/1992842/98c938df-ca9b-4a5f-b6fa-359e2ab58971">

**Comment by alexjustesen** [comment]
Just to confirm you tried a different server ID too right?

**Comment by luckman212** [comment]
I did run speedtest from the shell and select a specific server, and that worked. I didn't want to hardcode a server in the GUI because I prefer the autoselection... But, after clearing the php caches the speeds are back up to normal. So 🤷 

<img width="529" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/1992842/949b598e-f6ad-497d-b11b-f8592908b9dc">

**Comment by alexjustesen** [comment]
🤷‍♂️ I think I'm going to implement more aggressive cache clearing on probably a weekly schedule, just to make sure it's always clean.
