### ISSUE TITLE
Multifactor authentication for admin panel

### ISSUE THREAD

**Issue by Lammiwinks** [alexjustesen/speedtest-tracker#1010]
Hey Alex! Love this app - thank you! A wonderful tool.

Quick one - could we enable MFA on the admin panel? Would like to be able to set this as I'm planning to expose this publicly and don't want to rely on just a username and password. 

Cheers!

**Comment by alexjustesen** [comment]
Thank you, really appreciate it! 

I'm linking this to #344 and going to close it as a dup, def still on the roadmap just not sure when it will get added.
