### ISSUE TITLE
No update detected on Synology

### ISSUE THREAD

**Issue by JKusber** [alexjustesen/speedtest-tracker#1029]
Hi all,

my speedtest-tracker is running on a synology for a longer time already. Today I noticed, that I am still on version 13.1. I saw here on github, that the latest tag is on version 14.1. But my Synology (build via the new container manager including image: 'ghcr.io/alexjustesen/speedtest-tracker:latest' isn't finding a new version. Also in the image view, there is no update available:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/12516802/3abbc31c-54a3-4e76-86bb-da25a48c4a74)

For some other images, I already did updates after the notification in the images tab.

Any idea what I am doing wrong?

**Comment by alexjustesen** [comment]
I have the same issue with Synology CM, I've been specifying a specific version in my `docker-compose.yml` file. I'm going to add this as a note under the Synology docs.

**Comment by JKusber** [comment]
Ok, then I will also go this way. Can I directly update from 13.1 to 14.1 or have I go via another version?

**Comment by alexjustesen** [comment]
You can go right to the latest build, I have migrations setup that run whenever there's an update in order.

**Comment by hoorna** [comment]
@JKusber, when using WatchTower, you will receive a notification for a new speedtest-tracker version. It is possible to have WatchTower automatically download the image and notify you, while you then create a new, updated container yourself.

**Comment by alexjustesen** [comment]
👆 and #1005 will notify you as well.
