### ISSUE TITLE
Default dashboard to weekly view?

### ISSUE THREAD

**Issue by luckman212** [alexjustesen/speedtest-tracker#1036]
Sorry if this is a dupe - I feel like I have seen this discussed before, but now I can't find it.

Is there any way to get the dashboard to by default open up to the **weekly** view? I only run 3 tests per day, so "last 24h" isn't that useful.

Running v0.14.2 currently...

**Comment by alexjustesen** [comment]
Going to link this to #738 because I only test once a day and yeah it drives me crazy too
