### ISSUE TITLE
admin panel - These credentials do not match our records

### ISSUE THREAD

**Issue by Geert-69** [alexjustesen/speedtest-tracker#1037]
**Describe the bug**
When going to the ADMIN PANEL > **localhost/admin/login**  I can not register with any credentials.
Also when I put something in it reports back with: These credentials do not match our records.
How can I register as admin to get access to the admin panel ?

**To Reproduce**
1. Go to 'http://localhost:9080/admin/'
2. It opens ''http://localhost:9080/admin/login'
3. Put in email address ans password
4. See error: These credentials do not match our records.

**Expected behavior**
A posibility to register

**Environment (please complete the following information):**
 Synology NAS
 - Browser Firefox and Chrome where tested
 
**Screenshots**
![Speedtest tracker admin login error](https://github.com/alexjustesen/speedtest-tracker/assets/9799682/216225de-b677-4feb-91c9-fe49736695a9)

**Logs**
If applicable, check the logs for any error that might of occurred.
No errors

> 
> 
> --------------------------------------------------------------------
> 
>  _______                       __ __                __
> |     __|.-----.-----.-----.--|  |  |_.-----.-----.|  |_
> |__     ||  _  |  -__|  -__|  _  |   _|  -__|__ --||   _|
> |_______||   __|_____|_____|_____|____|_____|_____||____|
>          |__|
>  _______                   __
> |_     _|.----.---.-.----.|  |--.-----.----.
>   |   |  |   _|  _  |  __||    <|  -__|   _|
>   |___|  |__| |___._|____||__|__|_____|__|
> 
> 
> --------------------------------------------------------------------
> 
> To support Speedtest Tracker visit:
> https://github.com/alexjustesen/speedtest-tracker
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1027
> User gid:    100
> -------------------------------------
> 
> 🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
> 
> 🐇  Configuring Speedtest Tracker...
> 
> 🔒  Fixing app path file permissions...
> ✅  Permissions fixed.
> 
> 🧹  Clearing any previous caches...
> ✅  Cache cleared.
> 
> ✅  Environment file exists.
> 
> 🔗  Creating symlinks for config and log files...
> ✅  Symlinks created.
> 
> ⏳  Generating an application key...
> ⚠️  An application key was generated at start up, no environment variable was set.
> 👀  To set an application key that persists, read the docs: https://docs.speedtest-tracker.dev/
> 
> 💰  Building the cache...
> ✅  Cache set.
> 
> 🚛  Migrating the database...
> ✅  Database migrated.
> 
> ✅  All set, Speedtest Tracker started.
> 
> [04-Jan-2024 21:54:57] NOTICE: fpm is running, pid 127
> [04-Jan-2024 21:54:57] NOTICE: ready to handle connections
> [04-Jan-2024 21:54:57] NOTICE: systemd monitor interval set to 10000ms
> 172.25.0.1 - - [04/Jan/2024:21:55:14 +0100] "GET / HTTP/1.1" 200 2196 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:21:57:13 +0100] "GET / HTTP/1.1" 200 2196 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:21:57:31 +0100] "GET /admin/login HTTP/1.1" 200 6043 "http://192.168.1.202:9080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:21:57:35 +0100] "GET /livewire/livewire.js?id=f121a5df HTTP/1.1" 200 71154 "http://192.168.1.202:9080/admin/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:21:58:57 +0100] "POST /livewire/update HTTP/1.1" 200 4040 "http://192.168.1.202:9080/admin/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:21:59:53 +0100] "GET / HTTP/1.1" 200 2196 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:22:00:04 +0100] "GET /admin/login HTTP/1.1" 200 6037 "http://192.168.1.202:9080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:22:00:14 +0100] "POST /livewire/update HTTP/1.1" 200 4042 "http://192.168.1.202:9080/admin/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:22:02:14 +0100] "POST /livewire/update HTTP/1.1" 200 4034 "http://192.168.1.202:9080/admin/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:22:02:31 +0100] "GET /admin/login HTTP/1.1" 200 6041 "http://192.168.1.202:9080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:22:02:50 +0100] "GET / HTTP/1.1" 200 5051 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:22:03:16 +0100] "GET /admin HTTP/1.1" 302 406 "http://192.168.1.202:9080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:22:03:19 +0100] "GET /admin/login HTTP/1.1" 200 6037 "http://192.168.1.202:9080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:22:03:27 +0100] "POST /livewire/update HTTP/1.1" 200 4041 "http://192.168.1.202:9080/admin/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 172.25.0.1 - - [04/Jan/2024:22:04:19 +0100] "GET / HTTP/1.1" 200 5052 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 

**Additional context**
Nope

**Comment by Geert-69** [comment]
It looks like I missed the part where the login and password were given :-)
Login: **admin@example.com**
PW: **password**

**Comment by alexjustesen** [comment]
If you're all set go ahead and close the issue
