### ISSUE TITLE
add option to enable auto refresh the dashboard webpage

### ISSUE THREAD

**Issue by Geert-69** [alexjustesen/speedtest-tracker#1038]
**Is your feature request related to a problem? Please describe.**
It's not a problem but it would be nice to have such feature.

**Describe the solution you'd like**
In the settings page add an option to auto page refresh every 15 minutes or so.

**Additional context**
Or add a sellectable button at the dashboard to enable auto refresh.

**Comment by alexjustesen** [comment]
You can accomplish this with the dashboard polling variable: https://docs.speedtest-tracker.dev/getting-started/environment-variables

**Comment by Geert-69** [comment]
Thanks !
