### ISSUE TITLE
[Feature Request] Add button to export results

### ISSUE THREAD

**Issue by RedSparr0w** [alexjustesen/speedtest-tracker#1040]
Would be great if there was a quick way to export the results to a csv or similar from the dashboard or results page.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7288322/1e67fee5-6425-4013-af76-958806cb6fbd)

**Comment by alexjustesen** [comment]
Export results is available when you select multiple records in the results table: 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/2243f366-8cf8-4a88-827f-6f9f411be9e4)
