### ISSUE TITLE
Integrate docker secrets capability

### ISSUE THREAD

**Issue by Marco674** [alexjustesen/speedtest-tracker#1041]
Hi,

Is it possible to integrate docker secrets capability,
Currently postgres password is in clear in compose file

It would be nice to be able to use secrets with files as described in :
https://docs.docker.com/compose/use-secrets/

So DB_PASSWORD_FILE would be able to read from /run/secrets/<secret_name>

Thanks :)

**Comment by alexjustesen** [comment]
Currently I'm not planning on adding file support (got a lot ahead of that). But I'll keep this in the log for down the road.

**Comment by alexjustesen** [comment]
Since secrets are supported at the Docker Compose level you should have no issue passing those configs as env vars.
