### ISSUE TITLE
Ability to remove a user

### ISSUE THREAD

**Issue by marnunez** [alexjustesen/speedtest-tracker#1042]
**Is your feature request related to a problem? Please describe.**
Can't remove a user

**Describe the solution you'd like**
A little trash can to the right of the user on the Users Panel, where if you're an admin, you can delete users

**Comment by leddie24** [comment]
Could someone help me please? I don't see where I can delete a user from this screen, thanks.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1291968/0904bf39-75a6-4ba1-a1c9-c5cb3996a44b)

**Comment by alexjustesen** [comment]
Make sure you're deleting a user from the admin account.

**Comment by leddie24** [comment]
I am logged in as an admin user in the screenshot. There's only two users, the example admin and then the one I just created.

**Comment by alexjustesen** [comment]
You can't delete an admin, change the role first  and you should be good
