### ISSUE TITLE
Time zone problem

### ISSUE THREAD

**Issue by somera** [alexjustesen/speedtest-tracker#1050]
**Describe the bug**
The time in the dashboard is not the same as the results. When I open the dashborad. When I go to results and than back to dashboard, than the time is correct. Looks like on the opening the dashboard for the first time, the configured time zone is ignored.

**Environment (please complete the following information):**
 - OS: Ubuntu
-  Architecture: amd64
 - Version v0.14.2

**Screenshots**
Dashboard:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8334250/79b2d922-7879-4b01-b273-06e66a09e94f)

Results:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8334250/dc2ef434-9913-4734-bee9-c84123ceda0d)

Time Zone Setting
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8334250/d76c09f9-0451-4b0d-a360-c6854bd2680e)

**Comment by alexjustesen** [comment]
It's likely the cache, I'll put together an update to clear the cache when a setting is updated.

**Comment by somera** [comment]
I updated to 14.4.4 but I see wrong time. This is when I start with the Dashboard.

**Comment by alexjustesen** [comment]
Also make sure to check the DB time zone option if your database has a time zone set.

**Comment by somera** [comment]
PG
```
$ grep Berlin postgresql.conf
log_timezone = 'Europe/Berlin'
timezone = 'Europe/Berlin'
```

Settings
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8334250/6af78357-2281-4299-8ea4-f9b236488bd7)

Dashboard
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8334250/ffaa1b5a-9084-4746-81e5-bf1a8420b35f)

Results
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8334250/afe10bb7-4fb8-4c8e-90cc-d6917c0090a3)

**Comment by alexjustesen** [comment]
Just to confirm if you refresh it's then fine?

**Comment by somera** [comment]
When I go to
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8334250/50534689-7291-4b28-b536-ace37dfb6358)
than I see the right date.

**Comment by somera** [comment]
Exactly.

**Comment by alexjustesen** [comment]
It'll be a couple of weeks before I circle back around to this project. Getting ready for a vacation and looking forward to disconnecting.

**Comment by somera** [comment]
This is a "bug" which make no problems.

Have a nice vacation.

**Comment by alexjustesen** [comment]
Going to close this out, publish dashboard is getting a refactor _Soon™_(ish)

**Comment by somera** [comment]
I updated today to 0.20.7
```
    -e DISPLAY_TIMEZONE=Europe/Berlin \
    -e APP_TIMEZONE=Europe/Berlin \
```
and it looks good. Thx for the new solution!
