### ISSUE TITLE
Column of the date and time of the test

### ISSUE THREAD

**Issue by gaoo90** [alexjustesen/speedtest-tracker#1057]
Good afternoon! 

Is it possible to add a column of the date and time of the test on the left/right, as was the case with the version from henrywhitaker3?

![image](https://github.com/alexjustesen/speedtest-tracker/assets/114869482/2abf6b25-c163-4ad3-8965-cc675ec67420)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/114869482/e39f2336-a80a-4086-8ae0-c775a07c1123)

**Comment by alexjustesen** [comment]
"Created" is when the test was run, all the way to the right

**Comment by gaoo90** [comment]
Thanks a lot!
