### ISSUE TITLE
Possibility to disable authentication altogether

### ISSUE THREAD

**Issue by lordvandal** [alexjustesen/speedtest-tracker#1058]
Hi,

I only use speedtest-tracker internally for myself, without any external access.
It would be really useful to be able to disable authentication altogeher, and to have only one (default) admin user.

Could you please consider a solution for this?
Perhaps a switch in settings, a configuration item in a file or an evironment variable.

Thanks in advance!

**Comment by alexjustesen** [comment]
Dup of #401 

At this time authentication is core to the application, there is a public dashboard that does not require auth to view the data though which might be what you're looking for.
