### ISSUE TITLE
Timeout opening Resultspage

### ISSUE THREAD

**Issue by zackmuc** [alexjustesen/speedtest-tracker#1060]
**Describe the bug**
After some time if you try to open the Result page you get an 504 Gateway timeout

**To Reproduce**
1. Go to 'Results'
2. 504 error

**Expected behavior**
List with all results should show

**Environment (please complete the following information):**
 - OS: Raspbian
-  Architecture: arm64
 - Browser Firefox

**Screenshots**

**Logs**

@/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"

NOTICE: PHP message: PHP Fatal error:  Maximum execution time of 99 seconds exceeded in /var/www/html/storage/framework/views/3868f28c9601d12bdfe1af7343f0e127.php on line 197

[2024-01-16 19:39:23] production.ERROR: Maximum execution time of 99 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 99 seconds exceeded at /var/www/html/storage/framework/views/3868f28c9601d12bdfe1af7343f0e127.php:197)

[stacktrace]

#0 {main}

"} 

172.32.0.10 - - [16/Jan/2024:19:39:35 +0000] "POST /livewire/update HTTP/1.1" 200 2676 "https://speedtest.**** /admin/users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"

2024/01/16 19:39:41 [error] 159#159: *269 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.32.0.10, server: _, request: "GET /admin/results HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "speedtest.****", referrer: "https://speedtest.****/admin"

**Comment by alexjustesen** [comment]
Can you open the terminal within the container and run `php artisan optimize:clear` and let me know if it helps.

**Comment by alexjustesen** [comment]
@zackmuc any luck on this?

**Comment by PaliKinG3** [comment]
> @zackmuc any luck on this?

i currently have the same issue and ive tried php command and that didnt solve my issue, as of right now i had to uninstall the container for the time being until this is fixed since its using like 10% cpu because of this issue
