### ISSUE TITLE
Simple file Download

### ISSUE THREAD

**Issue by Churator** [alexjustesen/speedtest-tracker#1080]
In addition to Ookla tests, may be add a possibility to grab file over http, and display results.
could be very nice addition! thank you for the work so far.

**Comment by alexjustesen** [comment]
What are you thinking, like I have X file (say it's 200MB) and it took me Y long to download it?

**Comment by Churator** [comment]
yeah, more "simple" download test, sometimes speedtests are being Mocked (rerouted by ISPs), and such test can give another aspect

**Comment by alexjustesen** [comment]
I'm planning on adding iPerf, would that help alleviate the mock concerns?

Rolling my own is probably more complex

**Comment by Churator** [comment]
Its good, yeah, sometime could be harsh finding reliable iPerf server in the public.

**Comment by alexjustesen** [comment]
What if you setup your own? My plan was to show how to configure one on a vps provider

**Comment by Churator** [comment]
yeah, again, its nice addon definitely.

**Comment by mmomjian** [comment]
Love the idea of adding iPerf support!
