### ISSUE TITLE
Working on Kubernetes

### ISSUE THREAD

**Issue by simonspg** [alexjustesen/speedtest-tracker#1089]
Speedtest-tracker is **The Best**!  Links to handy pages, good looking pages, useful logging.  But I gush.  Just one more thing: A world-wide current list of servers!  Incredible!  
Anyway, I have it working on my k3s home-lab cluster.  I'll post details if anyone is interested.

**Comment by alexjustesen** [comment]
Please do... I'd like to get those added to the docs as well (https://docs.speedtest-tracker.dev/getting-started/installation/kubernetes) as I'm just referencing community examples at the moment.

Selfishly I'm about to nuke my Docker Swarm for K3s so I'd like to see it.

**Comment by alexjustesen** [comment]
Also https://github.com/alexjustesen/speedtest-tracker/discussions/245 will have any discussions for a concise list of servers when I get to it.

**Comment by alexjustesen** [comment]
@simonspg if you're still working on K8s docs can you base it off the new LSIO image?

**Comment by simonspg** [comment]
I would be happy to!  I have run into a problem with cloudnative Postgres and am down that rabbit hole.  I will post the docs using generic environment variable values.

**Comment by simonspg** [comment]
I am learning about cloud native Postgres and have an improved installation.  I am trying the LSIO image and am seeing what others have reported more accurately than I can.  This is what I see when I try http on port 80.  When I use https on port 443, I receive a 500 error code.  I have not modified the configuration, and have based my deployment on the 'kubernetes' installation that the documentation points to.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/47188715/e5481a2a-bf33-4ba7-916f-5687264ac108)
