### ISSUE TITLE
Error 500/cURL error 28

### ISSUE THREAD

**Issue by ShirazAdama91** [alexjustesen/speedtest-tracker#1101]
**Describe the bug**
Good evening,

I just installed speedtest tracker via docker with mariabd.
The instance launches fine and I can access the interface.

On the other hand, when I try in the "General" settings, I get an error 500/cURL error 28.

And I am also unable to run a test, it systematically fails.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'General'
3. See error

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/64169336/4a2ee586-d8ec-42e8-bd76-3abd16cfa171)

**Comment by alexjustesen** [comment]
Try hitting the URL in a browser, looks like it took too long to respond.

Going to add some safety code here to prevent this in the future...

**Comment by ShirazAdama91** [comment]
Hello, the problems are resolved, the problem came from the docker network :/

**Comment by alexjustesen** [comment]
Thanks for the update, I'm going to build in some safety anyways.
