### ISSUE TITLE
[Feature] Don't run tests when the public IP exists in a list

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#1111]
I have a backup internet connection that runs over a metered 4G SIM card. After 20GB is used up, the carrier starts billing me for each additional GB of usage. This can add up fairly quickly with speedtests running every 30 minutes.

It would be great if there was a field in the UI where we could put in e.g 166.141.144.0/22 and it would skip the test if the public IP falls inside that subnet.

_Originally posted by @luckman212 in https://github.com/alexjustesen/speedtest-tracker/issues/513#issuecomment-1686192485_

**Comment by alexjustesen** [comment]
To get a valid IP address I'll use https://ifconfig.co/ which responds with the public IP address. This can be done either using a standard get curl request or using a get request with a json response.

**curl example**
```bash
curl ifconfig.co/
```

**http client example**
```php
use Illuminate\Support\Facades\Http;
 
$response = Http::acceptJson()
    ->get('https://ifconfig.co/');
```

**Comment by luckman212** [comment]
Some other good ones that I use:

4.ipquail.com/ip

And here's neat trick to get it via DNS - this is probably the fastest and the most reliable since it's operated by a large org and less likely to disappear or fail

```
dig +short A myip.opendns.com @208.67.220.220
```

**Comment by alexjustesen** [comment]
Interesting, I'll evaluate that method as well.

**Comment by luckman212** [comment]
If you don't want to use hardcoded IPs `208.67.220.220` or `208.67.222.222` you can instead resolve the IPs by querying for the `A` record of `resolver1.opendns.com` or `resolver2.opendns.com`

**Comment by alexjustesen** [comment]
Do we think that's adding complexity? Without writing any code `curl`ing an external service with the expectation that the response is an IP address feels the easiest. 

Trying to keep stuff as simple as possible.

**Comment by luckman212** [comment]
You're decision! But in general a DNS query is a faster than a round trip HTTPS request-response. We're probably splitting hairs though talking about milliseconds.

**Comment by alexjustesen** [comment]
F1 team level of performance here where ms matters hahaha.

**Comment by luckman212** [comment]
Another good one

https://checkip.amazonaws.com

**Comment by ArthurHuyghe** [comment]
[https://icanhazip.com/](url)?

**Comment by luckman212** [comment]
@ArthurHuyghe I wouldn't use that, it could disappear at any time. Also, it returns an IPv6 address when the computer has one, which is not desirable in most cases.

**Comment by ArthurHuyghe** [comment]
@luckman212 I wasn't aware of these issues, thanks for letting me know!

**Comment by gaby** [comment]
@luckman212 @ArthurHuyghe That's not true. Icanhazip is owned/managed by Cloudflare since 2019.

Source: https://major.io/p/a-new-future-for-icanhazip/

The cloudflare docs even tell you to use it: https://developers.cloudflare.com/cloudflare-one/policies/gateway/egress-policies/dedicated-egress-ips/

It works both with http and https, also:

> Determine the source IPv4 address of your device by going to https://ipv4.icanhazip.com/.
> Determine the source IPv6 address of your device by going to https://ipv6.icanhazip.com/.

**Comment by luckman212** [comment]
@gaby Good info, thanks. Always good to have multiple options.

**Comment by publi0** [comment]
@svenvg93 Wow! I've been waiting for this for a long time! Thank you so much!
