### ISSUE TITLE
Speedtest-tracker Linuxserver Version

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#1116]
Hi, has your project been taken over by Linuxserver? Will your development continue the same? And also are there any advantages of having the image on Linuxserver?

https://github.com/linuxserver/docker-speedtest-tracker

I tried to pull and saw that the Linuxsercer image is 164MB while your project is about 310MB
Thank you

**Comment by alexjustesen** [comment]
#1117 crossed streams 😉
