### ISSUE TITLE
Time Format not being acknowledged

### ISSUE THREAD

**Issue by PowershellScripter** [alexjustesen/speedtest-tracker#1121]
**Describe the bug**

When setting time format, regardless of what is placed, the format never changes. Timezone is correct, but format not being leveraged.

**To Reproduce**
Set Time Format

**Expected behavior**
Format Applied

**Environment (please complete the following information):**
 Docker
App Version: 0.15.2

**Screenshots**

![image](https://github.com/alexjustesen/speedtest-tracker/assets/71091773/6ca80d90-fc14-4fbc-a899-df287a379613)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/71091773/c3112058-629b-4021-8db5-3cc47c69a220)

**Comment by alexjustesen** [comment]
This is correct, datetime format doesn't change on the graphs to keep the axes simpler. Only applies to the tables.
