### ISSUE TITLE
Error 500 when click on "Test Telegram Channel"

### ISSUE THREAD

**Issue by garanda21** [alexjustesen/speedtest-tracker#1129]
**Describe the bug**
Error 500 when click on **"Test Telegram Channel"**

**To Reproduce**
1. Go to 'Notifications'
2. Click on 'Enable telegram notifications'
3. Add new recipient
4. Save
5. Click 'Test Telegram Channel' 

**Expected behavior**
Send a test notification.

**Environment (please complete the following information):**
 - OS: Synology Docker
-  Architecture: [e.g. arm64, amd64]
 - Browser Safari
 - Version 0.15.3

**Screenshots**
<img width="372" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/9530250/a035c6fa-e4f6-4770-a220-2d3c414f9ce7">

**Logs**
```
production.ERROR: Too few arguments to function App\Notifications\Telegram\TestNotification::__construct(), 0 passed in /var/www/html/app/Actions/Notifications/SendTelegramTestNotification.php on line 27 and exactly 1 expected {"userId":1,"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\Notifications\\Telegram\\TestNotification::__construct(), 0 passed in /var/www/html/app/Actions/Notifications/SendTelegramTestNotification.php on line 27 and exactly 1 expected at /var/www/html/app/Notifications/Telegram/TestNotification.php:22)
```

**Additional context**
Notifications works perfect on schedule, the 500 error only occurs on **Test Channel**

**Comment by alexjustesen** [comment]
To confirm you followed the setup instructions in the [docs](https://docs.speedtest-tracker.dev/settings/notifications/telegram)?

**Comment by garanda21** [comment]
> To confirm you followed the setup instructions in the [docs](https://docs.speedtest-tracker.dev/settings/notifications/telegram)?

Like I said on the Additional Context: **"Notifications works perfect on schedule, the 500 error only occurs on Test Channel"**
