### ISSUE TITLE
Crashes on Saturday nights - Error 500

### ISSUE THREAD

**Issue by jeffmcm64** [alexjustesen/speedtest-tracker#1134]
Every week, the script seems to crash.  It shows an Error 500 in the web GUI and the tests stop automatically occurring.

Restarting it resolves it.

**Comment by alexjustesen** [comment]
Can you share what version you're using and the the first couple of lines from the log output?

Ref: https://github.com/alexjustesen/speedtest-tracker/issues/1065

**Comment by jeffmcm64** [comment]
> Can you share what version you're using and the the first couple of lines from the log output?
> 
> Ref: #1065

0.14.4 is the version.

To support Speedtest Tracker visit:
https://github.com/alexjustesen/speedtest-tracker
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
🐇  Configuring Speedtest Tracker...
🔒  Fixing app path file permissions...
✅  Permissions fixed.
🧹  Clearing any previous caches...
✅  Cache cleared.
✅  Environment file exists.
🔗  Creating symlinks for config and log files...
✅  Symlinks created.
⏳  Generating an application key...
⚠️  An application key was generated at start up, no environment variable was set.
👀  To set an application key that persists, read the docs: https://docs.speedtest-tracker.dev/
💰  Building the cache...
✅  Cache set.
🚛  Migrating the database...
✅  Database migrated.
✅  All set, Speedtest Tracker started.
[16-Feb-2024 07:06:11] NOTICE: fpm is running, pid 116
[16-Feb-2024 07:06:11] NOTICE: ready to handle connections
[16-Feb-2024 07:06:11] NOTICE: systemd monitor interval set to 10000ms
192.168.1.232 - - [16/Feb/2024:07:09:11 -0700] "POST /livewire/update HTTP/2.0" 419 6609 "https://192.168.1.137:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

**Comment by jeffmcm64** [comment]
I just read the thread you referenced, it looks like this was fixed in the latest version.  I'll try updating.

**Comment by alexjustesen** [comment]
If it fixes your issue feel free to close this issue
