### ISSUE TITLE
[FR] Option to seperate diagrams for download and upload speeds

### ISSUE THREAD

**Issue by squromiv** [alexjustesen/speedtest-tracker#1135]
There are some ISP offers, where disproportion between download and upload speeds is very big. So it is almost impossible to estimate the plot in detail in this case.

As for example, Download should be about 15 Mbs, and Upload speed - 1 Mbs. Upload diagram is really not clear.

![screen_2024 02 16 001](https://github.com/alexjustesen/speedtest-tracker/assets/15985877/04963cc0-16f7-4184-86b6-0c260129df5d)

It should be great to have a separate picture for Upload metric with different scale/reference point.

**Comment by alexjustesen** [comment]
Dup of #258
