### ISSUE TITLE
Docker compose fails

### ISSUE THREAD

**Issue by maddler** [alexjustesen/speedtest-tracker#1136]
**Describe the bug**
Docker compose fails with 
`failed to solve: process "/bin/sh -c groupadd --force -g $WWWGROUP sail" did not complete successfully: exit code: 3` 

**To Reproduce**
1. download the repo
2. execute `docker-compose up -d`

**Expected behavior**
Container(s) successfully built and app started

**Environment (please complete the following information):**
 - OS: Ubuntu 23.04
-  Architecture: amd64

**Additional context**
Just tried to download and install but compose fails with the above message.

**Comment by alexjustesen** [comment]
Downloading the repo and trying to run a Docker container from there should only be done if you intend on developing within the codebase.

If you're looking to stand up the application via Docker follow the [install](https://docs.speedtest-tracker.dev/getting-started/installation) instructions in the docs.
