### ISSUE TITLE
 Table or view not found

### ISSUE THREAD

**Issue by crower19** [alexjustesen/speedtest-tracker#1163]
Suddenly i receive this error on container. to test i remove all containers, all volumes and start again and again i recevie this error and container not start.

```log
 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speed_tracker.results_bad_json' doesn't exist (Connection: mysql, SQL: select count(*) as a  
  ggregate from `results_bad_json`)  
```

**Comment by alexjustesen** [comment]
What build are you on? 0.16.1 has an error, recommend 0.16.2.

**Comment by crower19** [comment]
latest image. and also i try with the new linuxserver image

**Comment by alexjustesen** [comment]
Doesn't look like `v0.16.2` has been built yet by LSIO, once it does that should fix the issue: https://github.com/linuxserver/docker-speedtest-tracker/releases

**Comment by zackmuc** [comment]
16.2 is still shown in the webui as 16.1

**Comment by masterwishx** [comment]
No info in influxDBv2 passed

**Comment by crower19** [comment]
after update the linux server image the issue is resolved (and run very quick)
Thanks!
