### ISSUE TITLE
influxDBv2 Error connecting to the API on 0.16.2 after update and migrate

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#1164]
using lasted version in docker in Unraid 
after updated to 0.16.2 and migrate , There is no info sended to InfluxDBv2:   

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/463f02d8-0956-4f35-987e-dce5849034ce)

**Comment by alexjustesen** [comment]
Have I said this quarter how much I hate InfluxDB?

**Comment by masterwishx** [comment]
> Have I said this quarter how much I hate InfluxDB?

Sorry to here, was always working fine, also this is only the way to have grafana dashboard

**Comment by alexjustesen** [comment]
#1170 should fix this, if it doesn't tag me and we'll reopen this issue. Got one more thing to fix before rolling this into `v0.16.3`.

**Comment by masterwishx** [comment]
seems to be fine now

**Comment by masterwishx** [comment]
but then found some different values in uploads and downloads https://github.com/alexjustesen/speedtest-tracker/pull/1160#issuecomment-1953567183

**Comment by masterwishx** [comment]
@alexjustesen same error in 0.19.0 https://github.com/alexjustesen/speedtest-tracker/issues/1391
