### ISSUE TITLE
Download and Upload measurement Issue in ResultPage

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#1166]
There is a problem with measurement of download and upload . 
In the dashboard the values are correct but they are incorrect in the results page. Ping value is correct

Thanks
![Cattura1](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/d1d82639-1d86-4b1a-ba1a-9cfc0a0ac2c2)
![Cattura2](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/0005bd16-f2bf-4fe8-95f1-c95562aed18e)

**Comment by alexjustesen** [comment]
Fixed in #1160 👍

**Comment by corasaniti** [comment]
Thanks
Oh one more thing. You tagged version 0.16.2 but version 0.16.1 is reported in the footer
Thanks again

**Comment by alexjustesen** [comment]
Yeah... Me and code are fighting today.
