### ISSUE TITLE
Results Table - DL/UL Speeds Discrepancy

### ISSUE THREAD

**Issue by xPoP** [alexjustesen/speedtest-tracker#1167]
**Describe the bug**
When updated to latest 0.16.2 (though it saying 0.16.1 in the UI), the results table is reporting incorrect DL/UL speeds. The "View" page reports correctly, and matches the Ookla test link. See below for screenshots.

**To Reproduce**
1. Go to speedtest-tracker admin page
2. Click on "Results"
3. Review download and upload speeds in table
4. Click "View" on result.
5. Cross reference download and upload speeds to the table.
6. See discrepancy.

**Expected behavior**
The DL/UL speed results in the table should report the correct speeds.

**Environment (please complete the following information):**
Server:
 - OS: Docker (debian-bullseye)
 - Architecture: amd64

User:
 - Browser: Chrome
 - Version 121.0.6167.185 (Official Build) (64-bit)

**Screenshots**
See: ID 16 at top and inside "view" page DL/UL speeds differ.
https://i.imgur.com/sxbWFAT.png

Ookla result: https://www.speedtest.net/result/c/16fcd5c7-ffd5-4068-8da8-c5b308959c2c

**Logs**
N/A

**Additional context**
N/A

**Comment by alexjustesen** [comment]
Fixed in #1160

**Comment by alexjustesen** [comment]
Looks like someone beat ya to it #1169 and I'll be working on that shortly. Will have the fix in `v0.16.3`.

**Comment by Magelo** [comment]
> Looks like someone beat ya to it #1169 and I'll be working on that shortly. Will have the fix in `v0.16.3`.

Me, I'm having Peta-bit internet speed! Which would surely be awesome if it was true!
