### ISSUE TITLE
Speed shown in Gbps (Dashboard), Mbps (Result list) and even in Pbps (API - Homepage)

### ISSUE THREAD

**Issue by Magelo** [alexjustesen/speedtest-tracker#1169]
**Describe the bug**
An ancient bug is reappering with Speedtest-Tracker (lscr.io/linuxserver/speedtest-tracker:latest - 0.16.2).

On dashboard:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/10362303/bf9b27f4-5da6-4a1a-863b-0fb762e4a946)

On result list:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/10362303/34e9b825-6963-4f3e-97f9-1e5168f77e15)

On Homepage:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/10362303/d0f4dedf-2bd9-4b6f-a610-c08ccbb77d38)

All these screen captures are showing the same speedtest. Using a notification threshold with these results is not useful.

Another small annoyance, even if I made sure I was up to date with docker version 0.16.2, still showing 0.16.1 in the lower left of the Dashboard.

**Comment by Magelo** [comment]
Because the sqlite database upgrade went wrong. I tried a new install and followed the documentation to use speedtest-tracker with mysql. Is it mysql related my problem?

**Comment by Magelo** [comment]
If only it was true! Having a peta bit internet feed would be awesome!

**Comment by alexjustesen** [comment]
So looks like Homepage is expecting to receive the value in bits which it then converts. I'll circle back around to this after a couple more fixes seeing how it's just a "view" issue and the underlying data is good.

https://github.com/gethomepage/homepage/blob/841c74d58a5735d66d136870fe9133e5d4253f75/src/widgets/speedtest/component.jsx#L30-L34

**Comment by Magelo** [comment]
A while back this bug was introduce then resolved. I think you used Mbsp everywhere and it worked everywhere, even with Homepage. Showing 2 Gpbs is nice instead of 2000 Mbps, but if it's more practical to standardize to Mbps, I'm OK with that.

**Comment by alexjustesen** [comment]
You're probably right and now I'm dynamically setting the postfix in my `Numbers` helper.

**Comment by Magelo** [comment]
0.16.3 (I know, it's shown in the lower left corner) is now installed and the Dashboard and Results are showing the same speeds in the same units. Homepage is still broken.

> You're probably right and now I'm dynamically setting the postfix in my `Numbers` helper.

If you can manage to keep dynamically showing the units, but return Mbps to the API request, it would be great.

On a positive note, wow, you're reacting really fast. My first working result (after I managed to bypass the data migration error) was at 8h15 EST, and managed to find time to log a bug at 18h55 EST (after work)... and 0.16.3 is already available! thanks.

**Comment by Magelo** [comment]
> So looks like Homepage is expecting to receive the value in bits which it then converts. I'll circle back around to this after a couple more fixes seeing how it's just a "view" issue and the underlying data is good.
> 
> https://github.com/gethomepage/homepage/blob/841c74d58a5735d66d136870fe9133e5d4253f75/src/widgets/speedtest/component.jsx#L30-L34

Why in the homepage widget code they are multiplying : * 1000 * 1000... should be at least * 1024 * 1024...

Maybe you should keep your Numbers helper as is and ask to modify the homepage widget instead. removing * 1000 * 1000 would make more sense.

**Comment by Magelo** [comment]
Using Homepage Custom API :

![image](https://github.com/alexjustesen/speedtest-tracker/assets/10362303/39ef8061-835d-4dc5-942b-48893787046f)

`        widget:
          type: customapi
          url: {url}/api/speedtest/latest
          mappings:
            - field: 
                data: download
              label: Download
              format: float
              scale: 1/1073741824
              suffix: Gbit/s
            - field:
                data: upload
              label: Upload
              format: float
              scale: 1/1073741824
              suffix: Gbit/s
            - field:
                data: ping
              label: Ping
              format: float
              suffix: ms`

The scale could be ajusted to fit your ISP. Mine give me aound 2Gbit/s download and around 4Gbit/s upload. So I prefer having 
the speed shown in GBit/s. My scale is 1 / 1024 / 1024 / 1024. This is a temporary fix. I could use format: bitrate with no scale, but the result is rounded to the nearest whole number (1.83Gbit/s is shown 2Gbits/s).

**Comment by v1rusnl** [comment]
Not sure if this is related, but in the Results Page, the values shown are in MByte/s, but are advertised as MBit/s.
On the Dashboard, everything seems to be finde though. ![IMG_20240220_092316.jpg](https://github.com/alexjustesen/speedtest-tracker/assets/18641204/55b49168-0c34-4188-81dd-608e1fd11ff6)

![IMG_20240220_092302.jpg](https://github.com/alexjustesen/speedtest-tracker/assets/18641204/45a39e6a-8af4-4cb1-9fb7-0f68dd8e1103)

**Comment by Jens-Wymeersch** [comment]
@Magelo thank you for the custom widget. Somehow I only get the ping value and not download nor upload. Please advice ?
