### ISSUE TITLE
Migration results in 'failed' status for past speedtests

### ISSUE THREAD

**Issue by mmomjian** [alexjustesen/speedtest-tracker#1177]
I updated from 0.15.5 to 0.16.3, using the LSIO image. The migration moved all the tests over to results successfully, but with a status of `failed`. They appeared in the results log but not on the graph. I was able to recover the old data by running `update results set status = 'completed' where status = 'failed';` in Postgres. Thought this might help other people, I'm not sure why the migration changed the status.

**Comment by alexjustesen** [comment]
I wonder if this has something to do with postgres and assessing 1 as not true which causes the match statement to default to Failed. 

https://github.com/alexjustesen/speedtest-tracker/blob/main/app%2FActions%2FMigrateBadJsonResults.php#L64-L78
