### ISSUE TITLE
Wrong Download and Upload Value

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#1180]
Hi, 
Again incorrect values
There are still incorrect download and upload values between the dashboard/chart and the values on the results page
Thanks in advance
PC
![Immagine1](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/600dd9e1-5b4a-4967-80cd-6447e50fbfdd)
![Immagine2](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/5f0801bf-5808-486b-9f9c-c4264a325947)
![Cattura3](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/8ddb2af0-e03f-48b1-8602-9a1c0e058e95)
![Cattura4](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/da950dad-2f10-43d1-9a7d-406c7eb09035)

**Comment by corasaniti** [comment]
![Cattura](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/03569d64-7a52-454a-921d-b6c294ef6c22)

**Comment by zackmuc** [comment]
I have the same problem.

**Comment by skyeci-draytek** [comment]
My figures aren't matching either for live or historical data between the 2 presented charts.Version 0.16.3 

My results page is showing 1.87gb but the graph shows the correct value of  2011gb (I'm 2gb symmetrical connection)..

**Comment by ShlomiD83** [comment]
@alexjustesen now download is shown in Gbps and u
![Screenshot_20240220_162120_Firefox](https://github.com/alexjustesen/speedtest-tracker/assets/17053215/b1ad1ac8-1132-4cf4-9778-111a77a95cc7)
pload in Mbps.

**Comment by alexjustesen** [comment]
I'd expect that, calc will show the next postfix when it's greater than .9

**Comment by ShlomiD83** [comment]
> I'd expect that, calc will show the next postfix when it's greater than .9

So that's expected behavior?

**Comment by skyeci-draytek** [comment]
Mine seems to be working. Thank you 
![Screenshot_20240220_145211_Samsung Internet](https://github.com/alexjustesen/speedtest-tracker/assets/81510309/5811e8d1-2e49-4b40-bca0-8f076cc6c658)

**Comment by alexjustesen** [comment]
> > I'd expect that, calc will show the next postfix when it's greater than .9
> 
> So that's expected behavior? 

Yep

**Comment by ShlomiD83** [comment]
> > > I'd expect that, calc will show the next postfix when it's greater than .9
> > 
> > 
> > So that's expected behavior?
> 
> Yep

How about addind a setting to chose between Gb or Mb?

**Comment by corasaniti** [comment]
In my opinion it doesn't make much sense to have download in GB and upload in MB
Thanks

![306295816-b1ad1ac8-1132-4cf4-9778-111a77a95cc7](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/4a6e8a04-b347-4a91-b61b-6d6321d9f732)

**Comment by alexjustesen** [comment]
I explained it more here https://github.com/alexjustesen/speedtest-tracker/issues/1186 but it's how the Number helper rounds to the next prefix. It's currently done at the tenth.
