### ISSUE TITLE
Data Reporting differences

### ISSUE THREAD

**Issue by MartynKeigher** [alexjustesen/speedtest-tracker#1186]
**Is your feature request related to a problem? Please describe.**
_Logging this as a Feature Request, as it's not really a 'bug'._

I have just done a clean install of the new version (0.16.4) using the new LinuxServer hosted image and the results are displayed in **Gbps**, where the older version that I still having running show results in **Mbps**. 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/0b050cb2-bc59-43c6-afd7-f349f6b4895b)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/8067e016-11d8-4aad-8dd0-aacd497d7eff)
_(Also, please ignore the values of the results themselves, had some ISP issues - which is EXACTLY why 'm using this app!! 😉)_

Additionally, if you run a curl command to get the latest result via the API '/api/speedtest/latest'...
- it's returned in **bytes** in the current version.
- it's returned in **megabytes** in the older version.

**Describe the solution you'd like**
- An option to swap the results between Gbps & Mbps values, in the grid. I can format the data (for my use-case) that's returned from the API.

**Additional context**
Both of my Speedtest Tracker instances are using the same server to run their speed tests.

**Comment by alexjustesen** [comment]
So this is intentional, the new Number helper rounds to the next postfix when it's greater than 9 tenths (> .9). So 910 Mbps now shows as 0.91 Gbps in stats and tables. 

Source: https://github.com/alexjustesen/speedtest-tracker/blob/main/app%2FHelpers%2FNumber.php

As for the API result this is currently incorrect as it seems Homepage and Heimdall convert to Mbps always regardless if Kbps or Gbps. Fix incoming for the data provided during the API call later today.

**Comment by MartynKeigher** [comment]
Awesome & thank you for the quick reply. Just for the sake of completeness.. here is the repsonse i'm getting from the API on the current version...

```
curl 192.168.0.5:8081/api/speedtest/latest
{"message":"ok","data":{"id":1,"ping":8.947,"download":909015896,"upload":919079536,"server_id":XXXXX,"server_host":"<REDACTED>","server_name":"Frontier","url":"<REDACTED>","scheduled":false,"failed":false,"created_at":"2024-02-20T10:41:50.000000+00:00","updated_at":"2024-02-20T10:41:50.000000+00:00"}}
```

**Comment by Jiriteach** [comment]
> So this is intentional, the new Number helper rounds to the next postfix when it's greater than 9 tenths (> .9). So 910 Mbps now shows as 0.91 Gbps in stats and tables.
> 
> Source: https://github.com/alexjustesen/speedtest-tracker/blob/main/app%2FHelpers%2FNumber.php
> 
> As for the API result this is currently incorrect as it seems Homepage and Heimdall convert to Mbps always regardless if Kbps or Gbps. Fix incoming for the data provided during the API call later today.

So theres no way of having an option to show as Gbps or Mbps?

**Comment by alexjustesen** [comment]
It's automatic. I could change the round up function to be tighter though and round at the 100th (> 0.99).

**Comment by Jiriteach** [comment]
> It's automatic. I could change the round up function to be tighter though and round at the 100th (> 0.99).

Thanks. Now its a mixture  which looks weird - 

<img width="834" alt="Screenshot 2024-02-21 at 8 42 16 AM" src="https://github.com/alexjustesen/speedtest-tracker/assets/2116446/cd4067fd-178a-4a4f-9063-e16c1a28b3b8">

**Comment by alexjustesen** [comment]
I'm going to spike that out as a separate issue as to me its not "broken" just not preferred. Hyper focused on getting DQ issue wrapped up at the moment.

**Comment by MartynKeigher** [comment]
Updated to v.0.16.5 and this is now working as expected. 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/aba9f6a6-faf4-4f2d-8a75-689550fc1710)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/a4c7102c-611c-431a-9f2b-128f25ac510a)
