### ISSUE TITLE
Wrong data display

### ISSUE THREAD

**Issue by skubi23t** [alexjustesen/speedtest-tracker#1189]
I have a problem after the latest update and migration. 

The "Result" section display wrong data compare to the reality. 
The "Dashboard" display correct data. 

Let's focus on the latest manually triggered speed test result.
Here is the link to the result: https://www.speedtest.net/result/c/f1d1e10c-b234-4268-b839-b102d602e779

 DOWNLOAD Mbps
385.92
 UPLOAD Mbps
96.13

Main screen Dashboard:
Top display wrong values - dashboard good 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/57182727/b35db8c2-d666-4d91-bd76-eac979781877)

Results page:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/57182727/42c5fe92-03a7-4a7e-84c6-854f55f83f89)

Details of the latest result shows proper data:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/57182727/48f6d368-d6e9-41e5-a092-87488bc125fd)

**Comment by alexjustesen** [comment]
To confirm are you running `0.16.4`?

**Comment by skubi23t** [comment]
Ok I didn't notice my version was 0.16.3. After the update to 0.16.4, all seems to be in place. Closing.
