### ISSUE TITLE
Thresholds wrongly triggering a notification

### ISSUE THREAD

**Issue by alexdelprete** [alexjustesen/speedtest-tracker#119]
**Describe the bug**
When setting thresholds, from what I interpret, if the values of the test are lower than thresholds for speed, and higher for ping, a notification should be created. Instead, I'm receiving notification for threshold every time, but test values do not hit those thresholds.

**To Reproduce**
Set threshold and do a test.

**Expected behavior**
I expect notifications to be fired only if test speed values are lower than thresholds or ping is higher.
Would also be good in the notification to describe which thresholds triggered it.

**Screenshots**
![image](https://user-images.githubusercontent.com/7027842/199735126-16e36d59-944c-4d40-b0b4-9b0d20118dcc.png)
![image](https://user-images.githubusercontent.com/7027842/199735153-93c2a358-7840-48fa-8322-e2393ebd8a33.png)

**Comment by stepanov1975** [comment]
Same issue here

**Comment by alexjustesen** [comment]
I'm planning on overhauling the event system this weekend (maybe, priority is going to be breweries). Currently is a little hacked together and won't scale well.

I like the idea of saying which threshold triggered as well so I'll be introducing that too.

**Comment by alexdelprete** [comment]
Drink a good beer for me too. Cheers. :)

**Comment by alexjustesen** [comment]
@alexdelprete needs a little more work but the PR below fixes the absolute notifications and the preview is up so you can see what per threshold notifications looks like https://github.com/alexjustesen/speedtest-tracker/pull/138.

thanks for the suggestion!

**Comment by alexdelprete** [comment]
So the notification will be for each specific threshold? great!

**Comment by alexjustesen** [comment]
> So the notification will be for each specific threshold? great!

bingo

**Comment by alexdelprete** [comment]
where's the preview? did you publish a beta tag?

**Comment by alexdelprete** [comment]
> Pulled latest version and the problem is still here

0.2.1 doesn't contain the fixes, I applied them manually just to do a quick test.

**Comment by alexjustesen** [comment]
> Pulled latest version and the problem is still here

Haven't done a release yet for that code. Currently sitting in PR #138 and will be probably a `v0.3.0` tag

**Comment by alexdelprete** [comment]
> Haven't done a release yet for that code. Currently sitting in PR #138 and will be probably a `v0.3.0` tag

0.2.1 contained the first fix by @adamus1red, and it's working here:

```
fix sending data to influxdb by @adamus1red in https://github.com/alexjustesen/speedtest-tracker/pull/130
```

but 0.3.0 will be much better I bet. :)

**Comment by JFPCreations** [comment]
I have that bug right now with Speedtest Tracker v0.11.1

![croppedImage](https://user-images.githubusercontent.com/10256543/216740084-2b676bad-a1d1-4088-8d74-786571d8d2f1.png)
![Screenshot_20230203-204717](https://user-images.githubusercontent.com/10256543/216740093-8e687fe1-df14-41b7-bec3-c872b0ddcd56.png)

Thresholds is in Mbps but my speed is reported in Gbps could this be a calculation error?

Thank you.
