### ISSUE TITLE
[DOCS] Adding latest results to StreamDeck

### ISSUE THREAD

**Issue by MartynKeigher** [alexjustesen/speedtest-tracker#1191]
**Is your feature request related to a problem? Please describe.**
Documentation for adding 'latest result' to StreamDeck.

1. Download the 'APINinja' extension from the Elgato Marketplace.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/fcdd1fa5-c49e-4140-ab1d-8649d9e16dc2)

2. Select 'BarRadier > APINinja' from the action selector on the right-hand side and drag\drop it into a vacant spot on your StreamDeck Panel.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/617558a8-646d-4c4a-8cd3-60b8e09d66d8)

3. To add the latest download result to the button, set the following APINinja fields as follows:
- Request Type: GET
- API URL: http://_Your-Speedtest-Tracker-IP_/api/speedtest/latest
- Content type: application/json
- Response Shown: **data.download**
- Parse/Format 'Response shown': checked
- Format: {0:N0}
- _(Optional) Title Suffix: Mbps_
- Response Type: Text
- Autorun every: _Your preference!_
- _(Optional) Hide green success indicator: checked._

4. To add the latest upload result to the button, copy\paste the download button you just created to a vacant spot on your StreamDeck panel, and adjust the following field:
- Response Shown: **data.upload**

5. If you did this correctly, you should now have 2 buttons that look something like this... 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/140f9399-df7f-415e-a938-21b973f70d05)
_The icons I used for down\up are part of the '[Font Awesome: Solid Icons](https://marketplace.elgato.com/product/font-awesome-solid-7b41d489-c90a-4ad7-ab42-b60d8f760238)' icon pack._

**Comment by alexjustesen** [comment]
This is awesome, I'm doing it tonight!

**Comment by OddSquirrel** [comment]
Another grave reminder that I really, really should have bought a StreamDeck **XL** instead of the regular one. 🙈

Dear <insert applicable deity here>, please give me more buttons! 🙏

**Comment by alexjustesen** [comment]
> Another grave reminder that I really, really should have bought a StreamDeck **XL** instead of the regular one. 🙈
> 
> Dear [insert applicable deity here], please give me more buttons! 🙏

Same, half of my first page is buttons to other pages.

**Comment by OddSquirrel** [comment]
@MartynKeigher is that the formatting you currently get using v.0.16.4? I am wondering because it shows up in bytes for me.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/39886438/1eef938a-df90-4725-bbd5-9e1664422ad2)

I also just learned that I'll probably need to make a blank icon in order to see everything properly, since API Ninja doesn't let me simply hide it. How odd. 🤔

**Comment by MartynKeigher** [comment]
@OddSquirrel - _"is that the formatting you currently get using v.0.16.4?"_... No, that formatting is for 'previous' versions of SpeedTracker. There is an open issue regarding the different responses between versions which is going to get addressed, so once the current version gets "fixed" _(and I do use that term loosely!)_, then you're display will be fine. 

However, if you wanting to see a 'clean ###Mbps' on your button for now, then you could play around with the `Format` field to massage the response. I'll have a play with it now and see if I can get it right. If I can... I'll update the guide above.

**Comment by MartynKeigher** [comment]
@OddSquirrel - Given the latest update, **v0.16.5**, this extra formatting is no longer required and the instructions in the orig post here will work just fine! 👍🏼

**Comment by OddSquirrel** [comment]
I gave it a shot with v0.16.5 and v0.16.6, and this is what I end up with when using the settings above, including `{0:N0}`:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/39886438/fc3e9250-2b6d-41f3-830a-c3875a4ff420)

When I remove `{0:N0}`, I get this instead:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/39886438/ccfa1c86-25f2-4fc3-88be-d49868cd231f)

These values are supposed to represent `"download":933.16` from the API.

**Comment by MartynKeigher** [comment]
Interesting. For me.. adding `{0:N0}` effectively removes the decimal places, and leaves me a whole number. 

With that said, its only massaging the data that i get back in the API response from `data.download` which for me is `"download":828.85`. What does your api return when you run ` curl 'SpeedTracker.IP'/api/speedtest/latest`

**Comment by MartynKeigher** [comment]
@OddSquirrel ... So thinking about this a little more... 

`{0:N0}` first takes the value `933.16` and 'stores' it in `0`.
It then uses the formatter `:` and then rounds the decimal value to the nearest whole number and formats it with zero decimal places `N0`.

The only thing I can think of is that your APINinja plugin is out of date and you're falling foul to a bug in an older version ??? ... but that said... the latest (v1.3) was released over 2 years ago, so I doubt you have an old version, but definitely check that to rule it out. 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/275cf92e-cb2b-4245-b3ba-76e45fb0d097)

**Comment by OddSquirrel** [comment]
IKR? Makes zero sense. And the most hilarious part is, that it does work now. I fumbled around for an hour, trying everything in the book, all kinds of formattings, nothing would stick. And here we are after trying it just once more and everything is fine.

Whatever caused this, I thank you very much for taking your time to help me figure this out. Crawling all over GitHub certainly has a way of making me aware of my lack of knowledge, and without kind folks like you my therapist would certainly rack up quite some overtime. 😊

**Comment by MartynKeigher** [comment]
That really is very bizarre! 🤔🤔🤔🤔

Try this...
- Delete your down\up buttons. 
- Uninstall APINinja
- Restart Streamdeck app
- Download APINinja 1.3 from [their discord server](https://cdn.discordapp.com/attachments/545898345286336513/853354237219569694/com.barraider.apininja.v1.3.streamDeckPlugin.zip?ex=65e37d10&is=65d10810&hm=297446a001c0ef7c147f3a9d99357e9f03789c594cfe63314bb0988dd3b219aa&), and re-install it.
- Try again?

**Comment by OddSquirrel** [comment]
It sure is. Maybe this is due to cultural parameters, with the dot being used as a decimal separator and a comma in mine?
I see that the linked syntax info provides some details about cultural settings, but I have no idea how to use that within API Ninja.

This is what I did instead:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/39886438/a934a9a0-d6db-4e9c-a92f-13359cd1f18b)

That way, the dot and whatever follows it simply gets truncated. Yes, it won't round 849.63 to 850, but I can live with that. I'm not running an atomic clock for NASA, after all. 😋

**Comment by alexjustesen** [comment]
Added to the docs: https://docs.speedtest-tracker.dev/other/stream-deck

**Comment by MartynKeigher** [comment]
Thanks for adding the SteamDeck setup to the offical docs! :) 

I've attached PNG's for you - and others - who want to customize their buttons a little more! ;p

Download: 
![download](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/d6ac5c09-5a45-4420-9b93-df3ce43590be)

Upload:  
![upload](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/210043ad-00bd-4bd6-bedf-1c2b1f6547b4)

Ping: 
![ping](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/e72c0e3a-55c1-4706-ab8d-c6d1e457029e)

Just adds a little more polish to the look! 😉 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/c5d60a8b-b604-42a9-95f9-0f75b8d34876)


Couple of extra's that you might want to add to the docs, to look like screenshot...

Title Settings:
- Title: _blank_
- Show Title: checked. (The 'result' IS the title!)
- Position: Top
- Font: Verdana, 11pt, bold.
