### ISSUE TITLE
More Statistics like  variance

### ISSUE THREAD

**Issue by AleksCee** [alexjustesen/speedtest-tracker#1194]
What about more statistic data on the dashboard like the https://en.wikipedia.org/wiki/Variance of the test over time to show the deviation in up-/downloads? Now at the top there is only the deviation in % to the test befor. But a chart over the time would be nice too.

**Comment by svenvg93** [comment]
Hi @AleksCee, 

Can you clarify more what you would like to see. 

Like a chart with the average per day over x time range.

**Comment by AleksCee** [comment]
@svenvg93 the variance is the average deferral from the values. Here is a example:
![IMG_4285](https://github.com/user-attachments/assets/89978e0c-fa80-4141-a0aa-62048a86f951)

**Comment by svenvg93** [comment]
Then it might be coming in https://github.com/alexjustesen/speedtest-tracker/pull/1669

**Comment by AleksCee** [comment]
Cool, a variance also will be nice too. 
here the formular from my example chart:

```
                minDownload = Math.round(Math.min.apply(null, data.map(function(val){return parseFloat(val);})));
                maxDownload = Math.round(Math.max.apply(null, data.map(function(val){return parseFloat(val);})));
                avgDownload = Math.round(data.reduce(function(sum,val){return sum += parseFloat(val);},0)/data.length);
                stddiffDownload = Math.round(Math.sqrt(data.map(function(val){return parseFloat(val) - avgDownload;}).map(function(val){return val * val;}).reduce(function(sum,val){return sum += val;},0)/data.length));
```

stddiff is the diff from the average to a smoothed min/Max values
