### ISSUE TITLE
Need InfluxDB data sample

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#12]
I need a sample of the data from the abandoned project so I can match or improve upon the data reported.

**Comment by alexdelprete** [comment]
I still use the old project and export data to influx. How can I provide you a sample? Not an expert on influx and stuff...

**Comment by alexjustesen** [comment]
@alexdelprete if you can do a screenshot of the data provided to InfluxDB and it's format that'll work I think

**Comment by alexdelprete** [comment]
ok, I thought you needed a data export. Be back with the screenshot.

**Comment by alexdelprete** [comment]
Here's the screenshot...if I add to the query the fields `scheduled / server_host / server_name` I have an error and can't see the table with data.

![image](https://user-images.githubusercontent.com/7027842/190214309-afaee043-51de-48c6-9f93-f48da35d3517.png)

**Comment by alexdelprete** [comment]
Got all the fields now...

![image](https://user-images.githubusercontent.com/7027842/190215681-66db32e3-3156-477b-89cd-f67bd7966f3d.png)

**Comment by masterwishx** [comment]
im also use the old version with influxdbv2 on influxdv1 ,  the guide in https://github.com/henrywhitaker3/Speedtest-Tracker/issues/996
will be glad to help if still needed
