### ISSUE TITLE
Service cannot start, (SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client)

### ISSUE THREAD

**Issue by AxReds** [alexjustesen/speedtest-tracker#1205]
**Describe the bug**
Since yesterday the  service became unavailable...

**To Reproduce**
Just restart the service/docker container...

**Expected behavior**
Service to run and display data, executes tests.

**Environment (please complete the following information):**
 - OS: docker container (both the original one from  ghcr.io/alexjustesen/speedtest-tracker:latest and lscr.io/linuxserver/speedtest-tracker:latest
-  Architecture: arm64
 - Browser: browser independent
 - Version: 0.16.5

**Screenshots**
not relevant

**Logs**
attached below.

**Additional context**

======

⏳  Generating an application key...
⚠️  An application key was generated at start up, no environment variable was set.
👀  To set an application key that persists, read the docs: https://docs.speedtest-tracker.dev/
💰  Building the cache...
✅  Cache set.
🚛  Migrating the database...
[2024-02-21 06:28:45] production.ERROR: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'speedtest_tracker' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2054): SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'speedtest_tracker' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)

[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\\Database\\Connection->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(401): Illuminate\\Database\\Connection->select()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(41): Illuminate\\Database\\Connection->selectFromWriteConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(165): Illuminate\\Database\\Schema\\MySqlBuilder->getTables()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\Builder->hasTable()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): retry()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#20 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#22 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#23 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#24 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#26 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}
[previous exception] [object] (PDOException(code: 2054): SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)

[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1339): call_user_func()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(528): Illuminate\\Database\\Connection->getPdo()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(423): Illuminate\\Database\\Connection->getPdoForSelect()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\\Database\\Connection->run()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(401): Illuminate\\Database\\Connection->select()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(41): Illuminate\\Database\\Connection->selectFromWriteConnection()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(165): Illuminate\\Database\\Schema\\MySqlBuilder->getTables()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\Builder->hasTable()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): retry()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#29 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#31 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#32 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#33 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#35 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#36 {main}
"} 
In Connection.php line 829:
                                                                               
  SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Pleas  
  e, report to the developers (Connection: mysql, SQL: select table_name as `  
  name`, (data_length + index_length) as `size`, table_comment as `comment`,   
  engine as `engine`, table_collation as `collation` from information_schema.  
  tables where table_schema = 'speedtest_tracker' and table_type in ('BASE TA  
  BLE', 'SYSTEM VERSIONED') order by table_name)                               
                                                                               
In Connector.php line 65:
                                                                               
  SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Pleas  
  e, report to the developers                                                  
                                                                               
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.

**Comment by alexjustesen** [comment]
Can you please share your Docker Compose file?

**Comment by zackmuc** [comment]
I have the same problem here my compose file

[dockercompose.txt](https://github.com/alexjustesen/speedtest-tracker/files/14359910/dockercompose.txt)

**Comment by zackmuc** [comment]
It is the new Mariadb which causes this problem (had the same error with Nextcloud)
change your docker.compose to:

```
  speedtestdb:
        container_name: speedtestdb
        image: mariadb:11.3.2
        command: --character-set-server=utf8 
```


then it works

**Comment by luckman212** [comment]
Came to report the same. I was on 0.16.5 and just tested 0.16.6 as well

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1992842/ac55bb67-cd8a-44de-9ee6-1475b0fd03eb)

**Comment by zackmuc** [comment]
@luckman212 try it as i described

**Comment by hoorna** [comment]
@zackmuc, your proposed solution works perfectly! Thank you for the tip!

**Comment by luckman212** [comment]
Yes @alexjustesen, I'm using `:latest`

I am trying (must be doing something wrong) to add the `character-set-server=utf8` to my compose but it's not working. I think the version of docker compose on Synology may be too old (it uses `docker-compose` instead of `docker compose`)

**Comment by luckman212** [comment]
Hmm I fiddled around with it enough and it's working now! I added `character-set-server=utf8` as an environment var as well, not sure if that was necessary.

Thanks @zackmuc and @alexjustesen

**Comment by alexjustesen** [comment]
I'm going to roll this up to the framework, I bet others are having this issue too.

**Comment by hoorna** [comment]
@alexjustesen, for your information: people are working on a patch. See this [link](https://github.com/MariaDB/mariadb-docker/issues/560#issuecomment-1956761221).
It seems to me that this in short term will be solved in a updated MariaDB image.

**Comment by alexjustesen** [comment]
> @alexjustesen, for your information: people are working on a patch. See this [link](https://github.com/MariaDB/mariadb-docker/issues/560#issuecomment-1956761221).
> It seems to me that this in short term will be solved in a updated MariaDB image. 

Thanks for the link, I'm going to lock this issue because it's out of my hands and will close it when the base image is fixed.

**Comment by alexjustesen** [comment]
Looks like the MariaDB team has resolved the issue with the latest build: https://github.com/MariaDB/mariadb-docker/issues/560#issuecomment-1958709372
