### ISSUE TITLE
Log fills up with livelier/Message when the web interface is being used

### ISSUE THREAD

**Issue by mainlyrock** [alexjustesen/speedtest-tracker#121]
**Describe the bug**
every click on the web interface seems to trigger an angry in the log file like this:

> 172.19.0.1 - - [03/Nov/2022:19:51:44 +0000] "POST /livewire/message/filament.core.notifications HTTP/2.0" 200 132 "https://192.168.178.120:8443/admin/results" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" | stdout

I am not sure this is very useful....

**Comment by mainlyrock** [comment]
This is what it looks like
![image](https://user-images.githubusercontent.com/117273343/199822811-648d2557-83fa-4272-b7a5-1eaa50535f4e.png)

**Comment by alexjustesen** [comment]
Yeah it's something that's been bugging me too, on the radar to look into it
