### ISSUE TITLE
[FEATURE REQUEST] Exclude servers for testing (blacklist ?)

### ISSUE THREAD

**Issue by comassky** [alexjustesen/speedtest-tracker#1215]
**Is your feature request related to a problem? Please describe.**

Due to Speedtest's choice of servers, there is a wide variation in results depending on the server.

The speed is supposed to be stable, but the fact that some servers are really weak pollutes the results.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/48486646/9cdfc139-f54d-4af3-a3aa-974a74e28013)

**Describe the solution you'd like**

Add the ability to exclude servers. Excluded servers cannot be used for testing.

Maybe add an option to this menu ?

![image](https://github.com/alexjustesen/speedtest-tracker/assets/48486646/cfa1d8a1-d0f3-49bf-93ae-2d76d3f12ef6)

**Additional context**

**Comment by alexjustesen** [comment]
There actually isn't a way to block servers unfortunately. When a test is run using Ookla's speedtest CLI it will choose a server for you if you don't specify one and we don't know what the server is until the results are returned.

For that reason I've been thinking of crowdsourcing #245 so we can have a good allow-list that isn't dependent on location.
