### ISSUE TITLE
Dashboard not refreshing automatically

### ISSUE THREAD

**Issue by luk6173** [alexjustesen/speedtest-tracker#122]
Hi,

I don't know if this is really implemented, but If I let the Dashboard opened and a new speedtest runs in this time, then the latest result values doesn't appear on the Dashobard, it's not automatically refreshed

Regards,
Lukas

**Comment by alexjustesen** [comment]
So just to be clear, you'd like to see `/dashboard` or `/results` refresh after a test has been run automatically?

**Comment by luk6173** [comment]
`/dashboard`

**Comment by alexjustesen** [comment]
Oh and fyi, if you're using DB notifications you'll see a notification under the bell shortly after a test runs.

**Comment by luk6173** [comment]
Yes, notification is working fine. Thank you for all!
