### ISSUE TITLE
🛑 Deprecating `alexjustesen/speedtest-tracker` Docker image 

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#1224]
## 📃 Description

With LinuxServer.io now building a new image the `v0.17.x` release cycle will be the last I build under `alexjustesen/speedtest-tracker`. To continue to get updates from `v0.20.0` on please cut over to using the new images.

Transition docs can be found here in the pinned issue: #1117

**Comment by alexjustesen** [comment]
Push out the cutover to `v0.20.0` to give people more time to switch.

**Comment by AleksCee** [comment]
If I use MySQL/MariaDB can I also only switch the image to lscr.io/linuxserver/speedtest-tracker:latest ? Or is there something else to review?

**Comment by alexjustesen** [comment]
> If I use MySQL/MariaDB can I also only switch the image to lscr.io/linuxserver/speedtest-tracker:latest ? Or is there something else to review?

If you're using an external DB like MySQL all you need to do is replace the app image and you'll be all set.
