### ISSUE TITLE
[Feature Request] - Ability to change from gbps to mbps

### ISSUE THREAD

**Issue by modem7** [alexjustesen/speedtest-tracker#1227]
Heya, 

Would it be possible to have the ability to switch between gbps to mbps?

Thanks!

**Comment by modem7** [comment]
Odd.....it changed back to mbps. 

Eh. Closing for now!

**Comment by hansenc0705** [comment]
seems as it gets closer to 1 gbps it starts displaying that way but now that i say that i see mine is showing mbps too so maybe this was a fix in .17

**Comment by modem7** [comment]
That makes sense! Thanks for getting back to me!

**Comment by alexjustesen** [comment]
I changed when rounding happens 😉 https://github.com/alexjustesen/speedtest-tracker/pull/1217

**Comment by modem7** [comment]
Legend, thank you so much!
