### ISSUE TITLE
Influx DB export - Upload/Download bits error

### ISSUE THREAD

**Issue by Ja50n-Kru** [alexjustesen/speedtest-tracker#1234]
**Describe the bug**
Download and upload bits on InfluxDB export no longer a number?

Has something changed in the last few updates for the Influx DB update? I have been using Grafana to plot the data, and in the last day or so after an update (to v16, I think) download and upload data is now longer being plotted from the data in Grafana - all other metrics like ping, jitter etc. are. It appears through data for download_bits and upload_bits is no longer being output as a number field?

**Comment by masterwishx** [comment]
please try in console to run : `php artisan cache:clear`

**Comment by masterwishx** [comment]
> I think I'm going to need to rip the band aid off and get this fixed back to a float or int
Strange for me all working fine in influxdb but also one time all notifications get off also influxdb with exception but after cleared cache all fine now but not treshold for discord as in https://github.com/alexjustesen/speedtest-tracker/issues/1235#issuecomment-1961275845

**Comment by skyeci-draytek** [comment]
Care to share how it looks in grafana please?  Thanks

**Comment by masterwishx** [comment]
> Care to share how it looks in grafana please? Thanks

https://grafana.com/grafana/dashboards/17808-speedtest-tracker-v2-influxdbv2/

**Comment by skyeci-draytek** [comment]
Thank you. Really hope I can figure this out ad I would like to use it.

**Comment by masterwishx** [comment]
> Thank you. Really hope I can figure this out as I would like to use it.

It's really not a problem, just follow the steps...

**Comment by skyeci-draytek** [comment]
@masterwishx - do you still have to to do the "InfluxDBv1 client connect steps"? - I have a db in influxv2 which has fields but no data?

**Comment by masterwishx** [comment]
> @masterwishx - do you still have to to do the "InfluxDBv1 client connect steps"? - I have a db in influxv2 which has fields but no data?

No, no need steps for InfluxDBv1 ! (it was for old speedtest-tracker https://github.com/henrywhitaker3/Speedtest-Tracker)

Here we use InfluxDBv2

**Comment by masterwishx** [comment]
Please post logs of speedtest-tracker and what you have in influxdbv2
befor try this https://github.com/alexjustesen/speedtest-tracker/issues/1234#issuecomment-1961201847

**Comment by skyeci-draytek** [comment]
> Please post logs of speedtest-tracker and what you have in influxdbv2 befor try this [#1234 (comment)](https://github.com/alexjustesen/speedtest-tracker/issues/1234#issuecomment-1961201847)

To save going off topic I wil put a post in the discussion area. I would appreciate it if you can help in there. 

Can you clarify where the logs are found. Many thanks

**Comment by skyeci-draytek** [comment]
@masterwishx - thanks for the guides - finally got it going - new data is working and generated on grafana after sorting out my influx dbase name to match. Is there anyway to import past tests as I used the program before setting it up with grafana?

**Comment by skyeci-draytek** [comment]
@masterwishx - thanks for the guides. finally got it going. I needed to match my dbase to yours - all good now with new data being uploaded.
![grafana1](https://github.com/alexjustesen/speedtest-tracker/assets/81510309/caf35c34-ae00-4f0e-979e-478ed92004c5)
