### ISSUE TITLE
Flattened chart for download and upload 0.17.2 version

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#1238]
Flattened chart for download and upload with separate axes... Ok for ping and jitter in 0.17.2 version
Server Error remains in the Notification section
Downgrade to 0.16.6 last stable

Thanks
PC

![Cattura](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/5de168cc-63d5-4513-9505-524fdaf4c936)
![Cattura2](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/43318f85-a4b3-4e5c-8588-75471a8299de)
![Cattura3](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/63403852-f1f8-4e1b-98db-232e87130b47)

**Comment by corasaniti** [comment]
Hi Alex (@alexjustesen)
the graph seems appears to be flat for download and upload only and all the detail is lost.
Why the choice to have separate axes when I could exclude the display of download and upload in a single graph at will? :-(
Thank you

**Comment by alexjustesen** [comment]
The graphs were separated to take into account those who have symmetric internet plans. I found that my 1 Gbit service was overlapping on itself which caused me to lose context of the data in the charts.

**Comment by corasaniti** [comment]
@alexjustesen 
in this way, those like me who have a NON-symmetrical figure are putting themselves at a disadvantage. You should provide a parameter to be able to configure a single graph or separate graphs for DOWNLOAD and UPLOAD.
For me the graph is now very flat and I lose the detail.
Thanks in advance
PC

**Comment by corasaniti** [comment]
Hi Alex @alexjustesen 

I attach two new images. I hope I explain myself well. With version 0.17.2 graphs with separate axes, I expected to get the same result as the single graph with download disabled, instead I get a flattened graph...
Thank you

![Screenshot 2024-02-23 141618](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/61ef1bc6-8d33-4021-85bc-27dc7fd00eaf)

![Screenshot 2024-02-23 142304](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/32a4040d-b742-4363-8480-36509a23c6e5)

**Comment by hansenc0705** [comment]
> @alexjustesen in this way, those like me who have a NON-symmetrical figure are putting themselves at a disadvantage. You should provide a parameter to be able to configure a single graph or separate graphs for DOWNLOAD and UPLOAD. For me the graph is now very flat and I lose the detail. Thanks in advance PC
> 
> PS: remeber fix server error 500 in notificatio section

Did you try running this within the container to fix the 500 error in notification section

`cd /app/www
php artisan cache:clear`

**Comment by jordant2722** [comment]
> 
> Did you try running this within the container to fix the 500 error in notification section
> 
> `cd /app/www` 
>`php artisan cache:clear`

Running `php artisan cache:clear` inside the container worked  for me, thanks!

**Comment by jordant2722** [comment]
> In #1225 I standardized the charts so they all have a Y axis that starts at zero. I also have a generally stable connection which makes my charts look "flat", the intent here to to help visually represent when there is a significant deviation in performance (see beginning of my uploads chart) and if performance is improving or degrading over time to make that easier to understand from a view perspective.
> 

Is there an environment variable that we can set to combine them again?

**Comment by mmomjian** [comment]
Starting at zero is good practice for graphs. Why would you need to know about such a small difference between 938 and 945 Mb/s? Starting at zero allows the graph to actually show a true representation of the stability and speed of your connection.

**Comment by corasaniti** [comment]
@mmomjian  @alexjustesen 
all the graphs I have have the Y axis resized. Here you can see my Grafana and InfluxDB2 graphs. Which one do you think has more detail? The flat graph does not provide any information...

Grafana
![Cattura2](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/bcae815e-d5e3-44a8-bdf7-50a35da202ef)


InfluxDB2
![Cattura1](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/3cae13eb-c900-415b-b9c5-280ea1cf72da)

**Comment by mmomjian** [comment]
With all due respect, an upload speed between 311.2 and 311.5 Mb/s is not "detail"  -- it is noise. Regardless, this is not our project, so it's not our decision. I am in favor of the new graphs.

**Comment by corasaniti** [comment]
@mmomjian 
Of course you're right but it would be nice to have an environment variable to choose whether or not to have the double graph and/or the renumbering of the Y axis scale
Thanks

**Comment by alexjustesen** [comment]
Gave a little thought about this over my tech-detox weekend. 

The main goal of the charts is to provide a high level overview of performance over a given time period and to visualize significant deviations from the norm. I want to provide a simple and consistent picture of data in the app but I also recognize that everyone has their data visualization preferences. 

If you're looking to customize your data's story I suggest integrating with InfluxDB and charting in Grafana.

Now that I'm on the other side of the data quality issue expect to see improvements to how you can leverage your data soon (i.e. InfluxDB improvements and an API).
