### ISSUE TITLE
External link button for inbound ping charts

### ISSUE THREAD

**Issue by skyeci-draytek** [alexjustesen/speedtest-tracker#1241]
Just wondered if its possible to have a button on the dashboard page which you can add an external link to a ping chart for example.

E.g I use an external ping chart to monitor my wan port from the Internet. Coming from a previous dashboard I used in Grafana it has the ability to add a button which would then open a page of your choice. The button/text box was shown on the dashboard. You would enter the link details via the settings page.

Thank you.

**Comment by alexjustesen** [comment]
Thanks for the suggestion, at this time I don't think it's possible within the Filament package to do that but I'll keep an eye on the feature set in case that gets added.
