### ISSUE TITLE
Adding a New Feature for Tracking Average WAN Speeds

### ISSUE THREAD

**Issue by carlosdurante** [alexjustesen/speedtest-tracker#1244]
Right now, we can see a lot of useful stuff, but what I’m really missing is the average download and upload speeds over the time periods we select. 

It would be super helpful to have these averages right there on our dashboard. It’s like having the right ammo to challenge our ISP whenever our service doesn’t live up to the mark.

Imagine being able to look at the dashboard and instantly know if we’re getting the speeds we’re paying for, over any period we choose  – not to mention it would make our discussions with the ISP more interesting. 😄

Congrats for the system, I really thing you guys did a great job!

**Comment by alexjustesen** [comment]
Great suggestion! Not sure when I'll implement it but also will add we should have a notification should the average over a period of time exceed a threshold.

**Comment by alexjustesen** [comment]
Later Alex will be looking for line annotations when he goes to implement it: https://www.chartjs.org/chartjs-plugin-annotation/master/samples/line/lowerUpper.html

**Comment by phyzical** [comment]
I was looking at actioning this from the notification side of things, i.e a "daily" and a "weekly" average notification. (the one feature i miss from the original)

@alexjustesen any tips around getting the jobs to run locally?

Ive got around most of the issues and have it running but every job just ends up being marked as "failed" with no logs anywhere?

**Comment by alexjustesen** [comment]
@phyzical #1443 will fix incorrectly creating a new record for failed jobs, also #1444 will provide an actual message for when WAN connection isn't available.

If you're looking to create a new notification with that summery data please hold off, I'm working through a couple of core changes between other projects and don't want to complicate it at the moment.

**Comment by phyzical** [comment]
no worries, no rush just lmk when. 👍
