### ISSUE TITLE
Negative Thresholds and notifications to measure speed loss

### ISSUE THREAD

**Issue by mannbadal** [alexjustesen/speedtest-tracker#1246]
**Is your feature request related to a problem? Please describe.**
Currently, thresholds seem to only work based on values greater than a certain threshold. It would be beneficial to be able to set thresholds based on values less than a certain threshold to ensure constant speed is achieved and there is no congestion or speed loss on the link.

**Describe the solution you'd like.**
If we can set a threshold based on values greater or less than a certain value, this would give users the option to measure speed in different ways. For instance, users could choose to receive alerts if the speed exceeds or falls below a certain threshold at certain times.

**Additional context.**
To further explain the use case, consider this example: if I set a threshold of 500 Mbps, but my connection speed is 1 Gbps, I will receive notifications for each speed test that is run. However, because most of the results will be above 500 Mbps, the notifications become pointless. If there is a way to set a threshold lower than 500 Mbps, then I would receive notifications only if the speed is less than 500 Mbps, indicating an issue with the link.

**Comment by alexjustesen** [comment]
So thresholds are as follows, I think this matches your ask...

- `download` and `upload` are a threshold "floor". So if it's **_below_** the set value it'll trigger the notification.
- `ping` is a threshold "ceiling". So if it's **_above_** the set value it'll trigger the notification.

Hope this helps.

**Comment by mannbadal** [comment]
That makes sense, unsure why it didn't work as expected before. I just tested again and it's working as expected now. Thanks for clarifying 👍
