### ISSUE TITLE
Site name is not reflected on public dashboard

### ISSUE THREAD

**Issue by ilium007** [alexjustesen/speedtest-tracker#1247]
**Describe the bug**
Configuring a "Site Name" in the General settings screen does not reflect on the public dashboard

**To Reproduce**
Set a site name and visit public dashboard - it still says "Dashboard - Speedtest Tracker"

**Expected behavior**
The site name should reflect what is saved in the settings

**Environment (please complete the following information):**
linio Docker image

**Screenshots**

![image](https://github.com/alexjustesen/speedtest-tracker/assets/732766/10d3f437-6f00-4163-9c31-93616bc39b31)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/732766/8cdcc462-8ef8-44a7-a70d-1b7a824236b4)

**Logs**

**Additional context**

**Comment by alexjustesen** [comment]
Pass `APP_NAME` as an environment variable or change it in `.env` file, in the future I'll be removing the UI setting for changing the app name.

**Comment by ilium007** [comment]
Before this is closed maybe the APP_NAME environment variable info should be added to the website documentation. It does not appear anywhere that I can see.
