### ISSUE TITLE
172.21.0.3 is not allowed to connect to this MariaDB server error

### ISSUE THREAD

**Issue by Rigwald** [alexjustesen/speedtest-tracker#1250]
I'm trying to get the speedtest-tracker working.  An old version was working and then it stopped, so then I uninstalled it and attempted to install the new version on my Synology (after an update).  After following all the steps, I am getting a 500 Internal Server Error, with the following debug info:

Illuminate\Database\QueryException {#824 ▼
  +errorInfo: array:3 [▼
    0 => "HY000"
    1 => 1130
    2 => "Host '172.21.0.3' is not allowed to connect to this MariaDB server"
  ]
  +connectionName: "mysql"
  #sql: "select * from `sessions` where `id` = ? limit 1"
  #bindings: array:1 [▼
    0 => "Au8rtQRUcb25gjz1zrs47IX0ZHeRj7DUx6EmdNkx"
  ]
}

I am not a programmer, so I have no idea what is wrong.

Thanks in advance!

**Comment by alexjustesen** [comment]
Are you deploying with Container Manager on your Synology NAS?

**Comment by alexjustesen** [comment]
To me this looks like you might of changed the password after initially starting the database container. On initial start it'll take whatever your first credentials were and create that username/password. 

If you don't care about the data in your database I'd stop the project, delete the `speedtest-db` volume and start the project again.

**Comment by Rigwald** [comment]
Thanks!  I redid everything and we're up and running. :-)
