### ISSUE TITLE
Results are very different from what Speedtest.com shows

### ISSUE THREAD

**Issue by BornInTheUSA** [alexjustesen/speedtest-tracker#126]
Screenshot from Speedtest-Tracker
![Screen Shot 2022-11-05 at 12 07 35 PM](https://user-images.githubusercontent.com/53592632/200132596-023de77b-fbb4-4ba8-bc33-dea470eec93e.png)
Screenshot from Speedtest.com
![Screen Shot 2022-11-05 at 12 07 15 PM](https://user-images.githubusercontent.com/53592632/200132623-811b0bf4-fd45-4122-8d54-b309611583a8.png)

**Comment by alexdelprete** [comment]
Is the selected server the same? Try specifying the same server if you want to compare results.

**Comment by BornInTheUSA** [comment]
Selecting the same server on Speedtest.com shows even larger differences.
![Screen Shot 2022-11-05 at 4 05 53 PM](https://user-images.githubusercontent.com/53592632/200141315-58b401fe-8f11-4490-b821-0ddd7ee5a347.png)

**Comment by alexdelprete** [comment]
Did you set the serverid in speedtest-tracker? Can you show the screenshot of both speedtes-tracker AND speedtest web site with server-id visible? I only see speeds here, can't compare anything.

What platform are you on? Describe the environment a little bit...thanks.

**Comment by BornInTheUSA** [comment]
Screenshots of of server id's.
![Screen Shot 2022-11-05 at 4 48 50 PM](https://user-images.githubusercontent.com/53592632/200142659-522c9e2e-a19a-4b85-a39f-b18e
![Screen Shot 2022-11-05 at 4 49 34 PM](https://user-images.githubusercontent.com/53592632/200142667-14a37c8a-13f5-4829-9778-f43b27cdb403.png)
54ffe5a8.png)

This is on a Mac Pro Mid 2012

![MacPro](https://user-images.githubusercontent.com/53592632/200142692-679b21b4-435b-440f-9f98-90ada9a13eed.png)

**Comment by BornInTheUSA** [comment]
![Screen Shot](https://user-images.githubusercontent.com/53592632/200142843-8adf7ec3-b9d1-48b4-a75b-1ce44741fdb6.png)

**Comment by alexdelprete** [comment]
Can you do the test on mac's shell with [speedtest-cli](https://www.speedtest.net/apps/cli) from ookla?

Install instructions:

```
brew tap teamookla/speedtest
brew update
brew install speedtest --force
```

Then you use this command to specify the server id (12190 is the one you used in speedtest-tracker):

```
speedtest -s 12190
```

And post the results, thanks.

**Comment by BornInTheUSA** [comment]
![Screen Shot 2022-11-05 at 5 12 04 PM](https://user-images.githubusercontent.com/53592632/200143272-e422ceab-a2e9-4a7a-87a2-62bfc2cc094a.png)

**Comment by alexdelprete** [comment]
```
speedtest --server 12190
```

**Comment by BornInTheUSA** [comment]
![Screen Shot 2022-11-05 at 5 25 44 PM](https://user-images.githubusercontent.com/53592632/200143637-7c6af2fc-95e9-4725-b11d-e421357582c5.png)

**Comment by BornInTheUSA** [comment]
Fixed OOla cli
![Screen Shot 2022-11-05 at 5 50 36 PM](https://user-images.githubusercontent.com/53592632/200144298-0e1c54c4-ce2f-4429-93eb-6c4a5c783d00.png)

**Comment by alexdelprete** [comment]
And you have 12190 in the Speedtest server field in General Settings, right?

![image](https://user-images.githubusercontent.com/7027842/200148856-bd9fd82b-2d28-446f-a248-c548fd139951.png)

If so...that is really strange. You're using latest version of speedtest-tracker (v0.2.0), right?

**Comment by BornInTheUSA** [comment]
The latest version for MAC is 1.2.0.84.  That is what was installed from brew.

![Screen Shot 2022-11-05 at 8 01 56 PM](https://user-images.githubusercontent.com/53592632/200149202-2a2eb871-c1cb-4365-bbd8-3e9cde59f38f.png)

**Comment by alexdelprete** [comment]
I was referring to speedtest-tracker, this project, not speedtest-cli. :)

**Comment by BornInTheUSA** [comment]
I just redeployed from this repo and same results.

**Comment by alexdelprete** [comment]
how are you deploying, docker-compose? can you show me the docker-compose.yml file? thanks.

**Comment by BornInTheUSA** [comment]
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - '/Users/rmartin/Docker/config:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:

**Comment by alexdelprete** [comment]
ok, you used tag latest, so it should be 0.2.0. In the UI I think there's no indication of the version, it should be added somewhere.

I don't know what to advice, sorry, on my installation the speed results are in line to what I observe  with speedtest-cli. I hope @alexjustesen can help you more than I could.

**Comment by JohnnyDeeee** [comment]
I had the same problem, so i tried running `speedtest` inside the speedtest-tracker docker container, which showed the same problem (~ 100mbps)

I then ran the same `speedtest` on my host machine (Intel NUC10) which showed the same low speeds!
After a couple hours searching i found out that this machine somehow doesn't use the right Advertised speed on it's network card. You can check what speed it is at by running

```bash
ethtool <your network interface>
```

To get the network interface run `ifconfig` and check which one has your local IP address.

Mine showed a speed of `100`, but the `Supported link modes` showed

```
Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
```

So i looked around and found this command

```
ethtool -s <your network interface> advertise 0x1800000001028
```

which should "fix" the wrong advertised speeds. When i run this i got `1000Mb/s` as my speed.

This change is not permanent though. If you reboot the change is gone..
In Ubuntu 22.04 i had to create the following file

```
/etc/networkd-dispatcher/configured.d/<whatever you want to call it, i used my interface name here>
```

and put this inside

```
#!/bin/sh
ethtool -s eno1 advertise 0x1800000001028 || true
```

i then restarted my machine and noticed that my speeds were still at `1000Mb/s`

You probably don't have the exact same setup but i hope this will point you in a direction.

**Comment by BornInTheUSA** [comment]
I used ifconfig command and the connection speed is advertised as 1 Gbit/s

![Screen Shot 2022-11-08 at 8 53 24 AM](https://user-images.githubusercontent.com/53592632/200597075-cf5da3d8-cbb9-473c-b146-08baecbe30c8.png)

**Comment by alexdelprete** [comment]
> You probably don't have the exact same setup but i hope this will point you in a direction.

he observed values well above 100Mb/s, so that could not be his specific issue.

**Comment by psyko-gh** [comment]
For the records, I have the same issue:
- Setup: Docker using the `latest` image
- Server configured to use the suggested one by speedtest.net
-  Speedtest-tracker results: 
    Down: 260Mbps     Up: 375Mbps     Ping: 11ms
- Speedtest app (for Windows)
    Down: 860 Mbps     Up: 540 Mbps     Ping: 10ms

So ping is consistent, but speeds are not..
Both ran on the machine hosting the docker container.
I tried with other servers ids and the results vary the same way.


Let me know if you need more information

**Comment by alexdelprete** [comment]
> It looks like Docker for windows may have some performance issues ? I'll have to dig into that.

@BornInTheUSA is using a Mac, so I would exclude that it's docker on windows.

**Comment by alexjustesen** [comment]
> > It looks like Docker for windows may have some performance issues ? I'll have to dig into that.
> 
> @BornInTheUSA is using a Mac, so I would exclude that it's docker on windows.

I also have the issue for Docker on Windows but it's not something I've dug deep into yet as it's likely out of the control of the app.

**Comment by alexdelprete** [comment]
> I also have the issue for Docker on Windows but it's not something I've dug deep into yet as it's likely out of the control of the app.

if you do a speedtest-cli from the inside of the container on windows, the results are different vs the app?

**Comment by alexjustesen** [comment]
> > I also have the issue for Docker on Windows but it's not something I've dug deep into yet as it's likely out of the control of the app.
> 
> if you do a speedtest-cli from the inside of the container on windows, the results are different vs the app?

by "different" they're slower than they should be for sure

**Comment by psyko-gh** [comment]
> if you do a speedtest-cli from the inside of the container on windows, the results are different vs the app?

A speedtest-cli from the speedtest-tracker docker give the same result as the speedtest-tracker app (3 to 4 times slower than the dedicated speedtest app).
I tried the `Get-netadpaterRSC | Disable-netadapterRSC` command, but no success

**Comment by alexdelprete** [comment]
> by "different" they're slower than they should be for sure

so inside the container it's slower, and a speedtest from the host side is normal. so it looks like it's something related to docker, but only on windows and mac...very interesting.

**Comment by BornInTheUSA** [comment]
On Ubuntu results are correct.
![Screen Shot 2022-11-09 at 7 17 05 PM](https://user-images.githubusercontent.com/53592632/200976769-f2eb8a5e-0f46-487e-837f-185f8d243c33.png)

**Comment by alexdelprete** [comment]
> On Ubuntu results are correct. And this Ubuntu is running as a VM on my MAC.

Do you have a windows VM to try the same test? Would be interesting to compare.

**Comment by BornInTheUSA** [comment]
Docker will not run on a Windows VM since it requires Windows HyperV or WSL.

**Comment by alexdelprete** [comment]
> Docker will not run on a Windows VM since it requires Windows HyperV or WSL.

https://github.com/StefanScherer/windows-docker-machine

**Comment by BornInTheUSA** [comment]
I am using Parallels for my VM's and do not feel the need to install https://github.com/StefanScherer/windows-docker-machine 
You should just mark speedtest-tracker not for Windows or MACOS

**Comment by alexdelprete** [comment]
> You should just mark speedtest-tracker not for Windows or MACOS

I don't think that is the solution, it's just a way to bypass problems.

Didn't want to force you doing anything, we're trying to understand what the problem is.

Thanks for the help.
