### ISSUE TITLE
More information for failed Runs

### ISSUE THREAD

**Issue by zackmuc** [alexjustesen/speedtest-tracker#1260]
If a run failes, could there be a better log about the failure and the connected server?

**Comment by alexjustesen** [comment]
So when a speedtest fails it'll fail for one of two reasons:

1. Application failed to run a speedtest via the cli which will throw an application level error or timeout and that error will end up in logs.
2. Ookla's CLI will  fail to execute a speedtest which returns an error json payload with the message `Configuration - Could not retrieve or read configuration (ConfigurationError)` ([docs](https://docs.speedtest-tracker.dev/help/error-messages#configuration-could-not-retrieve-or-read-configuration-configurationerror)).

If you're specifying a server when running the CLI command we could capture the server ID but if you let the CLI choose your server it's not returned until the command completes successfully.

**Comment by alexjustesen** [comment]
Also to add, `v0.16.0` branch brought in the concept of a speedtest status so that in the future we can at least log when something starts regardless of it's final state.

#1141 expands on this with implement the status but will likely spike this logic out into a separate PR.

**Comment by hansenc0705** [comment]
> So when a speedtest fails it'll fail for one of two reasons:
> 
> 1. Application failed to run a speedtest via the cli which will throw an application level error or timeout and that error will end up in logs.
> 2. Ookla's CLI will  fail to execute a speedtest which returns an error json payload with the message `Configuration - Could not retrieve or read configuration (ConfigurationError)` ([docs](https://docs.speedtest-tracker.dev/help/error-messages#configuration-could-not-retrieve-or-read-configuration-configurationerror)).
> 
> If you're specifying a server when running the CLI command we could capture the server ID but if you let the CLI choose your server it's not returned until the command completes successfully.

so out of no where my speed tests for my VZW 5G stopped working. If I send the traffic out my Spectrum it works but doesnt work via 5G. I've reset the container to rule out config issue and still not working.

Where can I find the commands to run manually or the logs to see what might be going on? Right now the results just say failed but no additional detail.

Thanks

**Comment by alexjustesen** [comment]
Commands can be found here https://docs.speedtest-tracker.dev/other/commands but you'll want to directly test the CLI from the container. To do that you can run:

```bash
speedtest --accept-license --accept-gdpr
```

**Comment by Bag72** [comment]
I've had a few failed entries and there is nothing in the logs.  At the same time I'm connected via ssh to a remote server and it doesn't drop the link so I don't believe there is anything wrong with the link.    
imo the log should at least show the server used.  If it is the same one then I could work around it but not knowing anything I'm stuck.

**Comment by marcosvrs** [comment]
I'm also trying to understand why I see a lot of failures in my results.
There is no error message logged in UI:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/10147574/6f0855d2-8599-4a12-8858-4310ed3a0871)

I have enabled APP_DEBUG, but it doesn't seems to give me much.
No errors in the console:
```
speedtest-tracker-1  | [migrations] started
speedtest-tracker-1  | [migrations] 01-nginx-site-confs-default: skipped
speedtest-tracker-1  | [migrations] done
speedtest-tracker-1  | usermod: no changes
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  |       ██╗     ███████╗██╗ ██████╗
speedtest-tracker-1  |       ██║     ██╔════╝██║██╔═══██╗
speedtest-tracker-1  |       ██║     ███████╗██║██║   ██║
speedtest-tracker-1  |       ██║     ╚════██║██║██║   ██║
speedtest-tracker-1  |       ███████╗███████║██║╚██████╔╝
speedtest-tracker-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
speedtest-tracker-1  | 
speedtest-tracker-1  |    Brought to you by linuxserver.io
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  | To support the app dev(s) visit:
speedtest-tracker-1  | speedtest-tracker: https://github.com/sponsors/alexjustesen
speedtest-tracker-1  | 
speedtest-tracker-1  | To support LSIO projects visit:
speedtest-tracker-1  | https://www.linuxserver.io/donate/
speedtest-tracker-1  | 
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | GID/UID
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  | User UID:    911
speedtest-tracker-1  | User GID:    911
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  | using keys found in /config/keys
speedtest-tracker-1  | An application key was generated at start up, as no environment variable was set.
speedtest-tracker-1  | To set an application key that persists, read the docs: https://docs.speedtest-tracker.dev/
speedtest-tracker-1  | [custom-init] No custom files found, skipping...
speedtest-tracker-1  | [ls.io-init] done.
```

No errors in the log files.

**Comment by alexjustesen** [comment]
If you're not seeing anything in the logs it could be the job timed out or something is hung up with your job queue. I'd try restarting the container and seeing if that helps.

Also you'll want to set an `APP_KEY`, just to have "one less" warning.

**Comment by marcosvrs** [comment]
I have restarted the container a couple of times already, sometimes it helps, sometimes doesn't...
But isn't this thread about giving more details on failures and errors?

I mean, thanks for the workaround, but we should have more detailed logs.

**Comment by alexjustesen** [comment]
Yes and no, so far I've been treating this one to collect more error messages from the CLI because Ookla doesn't share those.

**Comment by marcosvrs** [comment]
Then, here is a new error where I reached their rate limit:
```
[2024-03-25 16:50:22.043] [error] Limit reached:

Speedtest CLI. Too many requests received. To maintain a fair and stable environment, please review and adjust the frequency of your requests.
```

**Comment by marcosvrs** [comment]
Yep... At one point they would be overloaded
I was too "enthusiastic" 😄
I was running it every minute... Now I'm reducing to check what is the minimum frequency I can run not to end on the rate limit. Will share here my findings :)

**Comment by Bag72** [comment]
Once a minute?   If we all did that then the speedtest servers would all grind to a halt and our speeds would drop.

I thought I was over zealous at 15 Mins.and I'm considering 20 or 30 mins

**Comment by alexjustesen** [comment]
I do every 4 hours, I'm actually testing ping as a better light weight test for indicating if there's network performance issues.

**Comment by alexjustesen** [comment]
Closing this out as we're now documenting failure messages here https://docs.speedtest-tracker.dev/help/error-messages
