### ISSUE TITLE
Consistently Slower Speeds for Scheduled Tests

### ISSUE THREAD

**Issue by GarrettBlackmon** [alexjustesen/speedtest-tracker#1263]
**Describe the bug**
It seems that any time a speedtest is triggered from cron, I get much slower results compared to manually triggering a speedtest.

**Expected behavior**
I'd expect to see a fairly normal graph considering every time i test manually on this client or my desktop machine I'm getting consistently close to 1gbps up/down.

**Environment (please complete the following information):**
 - OS: Ubuntu Server 23.04
-  Architecture: x86_64
 - Browser chrome
 - Version @latest

**Screenshots**
![image (6)](https://github.com/alexjustesen/speedtest-tracker/assets/5715535/841b89db-7fa5-42c2-b2e8-848e75538ba6)

**Logs**.
Available upon request

**Additional context**
You'll notice I'm seeing consistently lower speeds when a scheduled speedtest runs, especially on feb28 when my upload was in the 10's of mbps. When I test my network via ookla in a browser from another client, this is never the case. When I manually que a speedtest on your software, I see high speeds there as well. It seems this only happens if the test is triggered by cron.

I realize this issue may be related specifically to my config, but perhaps this issue comes up often enough that it is worth noting in docs or FAQ if we can figure it out.

My theories are that perhaps there is some kind of low power mode my NIC/device is entering and is slow to wake up from, or there is some permission weirdness with the docker image I installed from.

**Comment by alexjustesen** [comment]
Check out #1073 and #1108 to see if these topics help you out. Going to leave the issue open for the time being but I agree if we can narrow this down it should be added to the docs. 

Hopefully I don't have to deal with some "warming" of the connection.

**Comment by GarrettBlackmon** [comment]
Some observations from the tickets you linked:

Seems some users saw an improvement by adjusting the cron to run at a time different from the top of the hour.

I ran `speedtest --accept-license --accept-gdpr` as you suggesed in [#1073](https://github.com/alexjustesen/speedtest-tracker/discussions/1073) and this was my result. My thought was the flags might accept these permanently for this client but it seems this is just a way to run the test from within the docker container.
![image (6)](https://github.com/alexjustesen/speedtest-tracker/assets/5715535/bdc59465-6f65-4aed-bfd7-76e7116f2684)

I will wet my cron to run every hour and offset it by a random number of minutes, (I'll do 17 for this test) to see if there is any change.

Will continue to update this issue with my findings though it may take longer since this only occurs on scheduled tests.

**Comment by alexjustesen** [comment]
I definitely suggest running "off-hour", I run mine at 42min past the hour and have seen better stability in results. 

`speedtest --accept-license --accept-gdpr` is the exact command that the job runs from the cron so it's a good way to rule out the application being the bottleneck and start thinking about other pieces of the data pipeline between your server and the speedtest server.

**Comment by GarrettBlackmon** [comment]
Big discovery!

I bet its "Energy Efficient Ethernet"

I found a topic about disabling it here: [ask ubuntu thread](https://askubuntu.com/questions/1411536/how-do-i-turn-off-energy-efficient-ethernet-on-my-ethernet-card)

I ran `ethtool --show-eee enp2s0`

and got this
![2024-02-29_10-14](https://github.com/alexjustesen/speedtest-tracker/assets/5715535/bdde755d-7394-451a-9499-29bcc41334d8)

Indicating to me that it's enabled which seems like a bad idea on a server. I'll not disable this at the moment in order to not change too many variables at once but I will try this and update here as well.

**Comment by GarrettBlackmon** [comment]
Well interestingly, just setting it to run at an offset from the hour totally fixed the issue at first glance.
![2024-02-29_11-20](https://github.com/alexjustesen/speedtest-tracker/assets/5715535/64530636-1c53-4f5b-b9f4-5042d5d8dfa9)

If you'd like me to, I'll set it back to run with a 0 offset, see if the issue comes back, and if so, try disabling eee.

This will probably take a whole day to collect enough datapoints to be certain before you share definantive solutions but I'm happy to test if it would be useful to you.

**Comment by alexjustesen** [comment]
Congestion has been the root cause to probably 95% of the issues opened with "slow" speedtest performance, but I want to prove out `eee` as well. Let's collect the data and report back with your findings, I'll then add those to the doc site.

**Comment by MartynKeigher** [comment]
@GarrettBlackmon @alexjustesen - I'm STILL getting reduced speeds since my initial theory (more info on that in #1108), so I'll disable 'Energy Efficient Ethernet' and get back to you on this one! 👍🏼 

Excellent find... now let's hope this is it! 🤞🏼

**Comment by GarrettBlackmon** [comment]
@MartynKeigher awesome, I'm still collecting data about running the tests with a minute offset. so far so good as pictured
![image](https://github.com/alexjustesen/speedtest-tracker/assets/5715535/9780a62d-c834-43ad-8000-a5f6eb4bf9fd)


I think it may also be possible that these speed test servers just have to serve a lot of users who have an hour-aligned cron/script running and don't have enough throughput themselves considering how dramatically my speeds seemed to have normalized by setting an offset.

Let me know how it goes at first glance. I'll take the slower approach to make sure we are correct.

**Comment by MartynKeigher** [comment]
> I think it may also be possible that these speed test servers just have to serve a lot of users who have an hour-aligned cron/script running and don't have enough throughput themselves

OMG, @GarrettBlackmon ... Now that you mention it... 🤔 That's actually a ridiculously, OBVIOUS, thing that I... DID NOT THINK OF AT ALL!! 🤦🏽‍♂️haha! Great shout bud!

I'll see how it goes overnight first, then... I'll shift the test to some 'random minute of the hour' and observe again! T-minus 8 minutes for the first 'regularly-scheduled' test after disabling eee & rebooting.

**Comment by GarrettBlackmon** [comment]
@MartynKeigher 

Right? Its just a back box we expect to return our network speeds. It wasn't until I set an offset and saw a huge difference that this occured to me.

**Comment by MartynKeigher** [comment]
OK, so first results are in after the change (Disabling EEE) and here they are... 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/88af89ce-0927-46a2-9e6e-fe62d4ec88ac)

Definitely the BETTER result of the day, but of course ... now we wait! I disabled EEE, rebooted the Pi & updated STT just 10 mins before that 'better' test, so... let's see what the morning brings. 

Additionally, for fun... I use my main Windows 11 PC as a 'control' for speedtests as well as WSL2 on that Win11 OS. I ran a speedtest to the same serverID from them shortly before 6pm and here are those results...

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/b47268e7-41c3-49ba-b241-801848ff0d0e)
_Windows 11 OS_
![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/218732d7-0502-4c90-8b11-b33023a5ecc0)
_WSL on Windows 11_

**Comment by GarrettBlackmon** [comment]
Very nice. If we see an average improvement after disabling eee it may be worth doing for a server that shouldn't be lazy even if it isn't the core issue.

After I collect a days worth of normalized speeds with my offset I'll disable eee for the next 24 hours and see if there is a difference.

**Comment by MartynKeigher** [comment]
Got bored... Spun up an instance of STT (running on docker in my 'WSL on Win11')... 😄 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/16660c0a-98a2-4394-a32b-e4d568bdba50)

Given that THIS is my 'control' & will give me expected results at all\most times... all issues point to the network interface config\ on the Pi... and... the timing of the speedtest itself. 👍🏼

**Comment by skyeci-draytek** [comment]
I see this issue of slower speeds on my debian n100 build. Manual test is faster than scheduled job. For me it seems to affect the upload more than the download.

**Comment by GarrettBlackmon** [comment]
Been busy this weekend, but I came back to this.

Seems my download is very stable but my upload is still all over the place. I do have a seedbox running which could explain some of this but I'm almost never uploading at more than 1mbps from what I've seen.

That's the only explination I can think of though. I think ill disable seeding for 24hrs or so to see if that's it.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/5715535/ecaeba3c-8165-4cf4-a8af-9cc8c8198c4b)

**Comment by skyeci-draytek** [comment]
I'm seeing  no further issues with my scheduled jobs using the offset. Its been bugging me for ages... I have kept using the same server that was giving me the upload issues.
![Screenshot_20240304_051344_Samsung Internet](https://github.com/alexjustesen/speedtest-tracker/assets/81510309/9831a433-b438-4ee1-b676-25c5660fedf5)

**Comment by GarrettBlackmon** [comment]
> I have kept using the same server that was giving me the upload issues.

I've kept it at the default thus far and let ookla pick for me but my new theory is it's just a shitty server. I'm trying an academic server in Atlanta, GA now to see if that changes anything.

**Comment by skyeci-draytek** [comment]
I gave worked through a bunch of servers and found the one that worked best bar the upload issue - I Would see a drop from 2gb to 100mb..... using the offset (5mins after the hour) has proved to worked so far.

**Comment by MartynKeigher** [comment]
Hey guys! Update from my side over the weekend of testing...

**Setup 1:**
- STT running on a Pi4.
- EEE disabled
- Advertised link modes:  1000baseT/Full
- Running hourly, **8 minutes past** the hour

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/3984570a-2260-44da-a42b-cfd01610bf1e)


**Setup 2:**
- STT running in Ubutnu WSL2 environment on my primary Win11 office PC.
- No custom interface adjustments. (vanilla Win11\WSL, ethernet settings)
- Running hourly, **ON the hour** 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/315ac9f9-fc45-497b-ac46-1f725da00a2b)

Conclusion: While i'm sure disabling EEE & setting the advertised speed on the Pi4 interface (and the switch it's plugged into) helped... I cant help but feel that just by having the speedtest run with a slight offset of the hour did the trick! 

@alexjustesen - Food for thought... In the UI, maybe add a 'randomizer' that sets an hourly cron to  `## * * * *` , where `##` is a randomized number between 0 and 59.

**Comment by GarrettBlackmon** [comment]
Yup, seems like switching to a different server worked.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/5715535/280ce52e-271c-426b-849c-982858c8db2e)


@alexjustesen A few findings for you to share in docs or with anyone having similar issues:

1. It is vital, at least for some servers, to set a minute offset on your scheduled tests to avoid server-side network congestion. This may not be necessary with some servers, however I think it's safe to say it's just good practice and the engineers for these speed test servers will be thankful you are helping distribute the load.

2. If you are still having issues, the server ookla has identified as the best for you (I assume this is purely based on proximity which should only really affect ping) may just not be up to snuff, try manually defining one in the config.

3. There was no noticeable difference seen from disabling eee.

**Comment by sobeservices** [comment]
I have tried all of these and still have the same issue. I tried to see if energy efficiency was the problem. My device wasn't even running it. Tried the offset. I tried everything listed here. Do you have any other suggestions?

**Comment by stich86** [comment]
I'm getting same problem, but just on latest version.. before the migration to the new docker I was able to reach full speed on all scheduled test (currently have a XGSPON 8/2 line). So is the "bug" individued? I don't understand

thanks for any feedback!
