### ISSUE TITLE
Many Issue 0.18.0 immediately downgrade to 0.17.3

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#1275]
No schedule works, no manual test works, no notification work. immediately downgrade to 0.17.3
`x86_64 architecture`
Thanks

**Comment by alexjustesen** [comment]
You know the deal, logs please.

**Comment by corasaniti** [comment]
@alexjustesen 
I'm more precise: the notifications work and also the speedtests with the scheduling work,
Does not work, manual execution is not performed, no information on the log
Thanks in advance

**Comment by alexjustesen** [comment]
> @alexjustesen I'm more precise: the notifications work and also the speedtests with the scheduling work, Does not work, manual execution is not performed, no information on the log Thanks in advance

https://github.com/alexjustesen/speedtest-tracker/pull/1276 will fix manual runs not using the speedtest server list.

**Comment by alexjustesen** [comment]
> Hi Alex Where can I find the log files please. Thank you

If you're getting a "500 server error" in the UI use these [steps](https://docs.speedtest-tracker.dev/help/faqs#im-getting-a-500-or-server-error-error), if its a process failing you can pull them from the container logs in Docker.

**Comment by corasaniti** [comment]
@alexjustesen 
Manual scheduling does not work yet.
I don't want to open another issue. Downgrade to 0.17.2

**Comment by alexjustesen** [comment]
Disable notifications for now and it'll work again.

**Comment by corasaniti** [comment]
@alexjustesen 
all my notifications are disabled and manual scheduling doesn't start :-(
