### ISSUE TITLE
healthchecks.io integration

### ISSUE THREAD

**Issue by karan** [alexjustesen/speedtest-tracker#128]
**Is your feature request related to a problem? Please describe.**
Keep track of service status and get notified when speedtest doesn't run (or fails).

**Describe the solution you'd like**
Ping a specified URL on successful (or failed) speedtest. https://healthchecks.io/ is a popular such monitoring service.

**Additional context**
The original project had this. While not urgent it would bring this project closer to parity.

**Comment by alexdelprete** [comment]
If you check the startup log of the container, you'll notice there's a `/ping` unauthenticated status check endpoint.

```
https://speedtest.domain.io/ping
```

That's what I'm using with Uptime Kuma and Dashy to check if the service is up.

**Comment by alexjustesen** [comment]
@karan thanks for the suggestion, already tracking some monitoring tasks and healthchesks.io is already on the list,

https://docs.speedtest-tracker.dev/getting-started/features
