### ISSUE TITLE
No manually server use anymore

### ISSUE THREAD

**Issue by AleksCee** [alexjustesen/speedtest-tracker#1280]
**Describe the bug**
Manuel runs via dashboard seems to ignore the Manuel server config in general „speedtest server“. It’s seems to use random servers only. I musst wait for the next cron-run to show if it’s also affected here. I will write this in 15 minutes.

**Environment (please complete the following information):**
 - OS: docker
-  Architecture: amd64
 - Version 0.18.0

**Comment by alexjustesen** [comment]
Fixed in #1276

**Comment by AleksCee** [comment]
Ok Scheduled task seems to use the server-list
