### ISSUE TITLE
Notification page in admin panel broken in 0.18.1

### ISSUE THREAD

**Issue by jacotec** [alexjustesen/speedtest-tracker#1282]
**Describe the bug**
The notifocation settings page is not working anymore, returning a 500 server error.

**To Reproduce**
1. Go to Admin panel
2. Click on "Notifications"

**Expected behavior**
Page should work

**Environment (please complete the following information):**
 - OS: Docker
-  Architecture: AMD64
 - Browser: Chrome
 - Version 0.18.1

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by alexjustesen** [comment]
Tying this to #1226
