### ISSUE TITLE
Clicking on "run speed test"

### ISSUE THREAD

**Issue by skyeci-draytek** [alexjustesen/speedtest-tracker#1283]
When clicking on run speed test a further box comes up as shown below which then needs to be clicked. Is this by design now?

Thanks 
![Screenshot_20240301_173637_Samsung Internet](https://github.com/alexjustesen/speedtest-tracker/assets/81510309/4639aced-dd45-4d07-8a00-41ac1fff50a8)

**Comment by AleksCee** [comment]
I think, in future release you can chose another Speedtest-provider. But‘s only an assumption.

**Comment by alexjustesen** [comment]
Short answer, yes.

Long answer, yes because I'm starting to make changes to support additional speedtest services.

**Comment by skyeci-draytek** [comment]
OK thanks for clarifying
