### ISSUE TITLE
Documentation update for php artisan commands

### ISSUE THREAD

**Issue by kmanwar89** [alexjustesen/speedtest-tracker#1285]
**Describe the bug**
Within the docker container, the _php artisan_ command cannot be called from anywhere except the app's _www_ directory (such as /app/www on the linuxserver.io image).

**To Reproduce**
1. Start an existing or create a new container, doesn't matter
2. Open a terminal into the container: _docker exec -it <container name> /bin/bash_
3. Attempt to generate an app key with the provided php artisan command: _php artisan key:generate --show_
4. Error with text _"Could not open input file: artisan"_ should be displayed
5. Navigate to the respective equivalent of `/app/www` within the container and issue the same command. It will now work, as this is where the _artisan_ executable is located

**Expected behavior**
[FAQ Documentation](https://docs.speedtest-tracker.dev/help/faqs) to be updated to reflect these steps/provide clarity

**Environment (please complete the following information):**
 - OS: Ubuntu Server 22.04.2 LTS
-  Architecture: amd64
 - Browser: N/A
 - Version: v0.18.1

**Screenshots**
Single screenshot attached with both failure and success behavior

![image](https://github.com/alexjustesen/speedtest-tracker/assets/11323060/f70e15b4-0c6e-4149-bfef-aecc503fa2e5)

**Logs**
N/A

**Additional context**
Just a small quality-of-life improvement, probably not a huge priority, but also not a huge effort to fix either.

**Comment by mmomjian** [comment]
I wonder if this is something that should instead be changed on the Docker level, by specifying `WORKDIR /app/www`? @thespad @alexjustesen 

Currently the shell enters into the root folder, `/`, but I just tried adding `working_dir: /app/www` to my docker-compose.yaml and it seems to be working as it used to.

**Comment by kmanwar89** [comment]
> I wonder if this is something that should instead be changed on the Docker level, by specifying `WORKDIR /app/www` in the Dockerfile? @thespad @alexjustesen
> 
> Currently the shell enters into the root folder, `/`, but I just tried adding `working_dir: /app/www` to my docker-compose.yaml and it seems to be working as it used to. If we add this to the LSIO Docker image, I think that would fix the issue for others.

The shell enters into `/`, and the home directory is `/config`.  I think the above recommendation makes sense -- I just tried moving the `artisan` executable over to /usr/bin, where `php` is located, but the commands still don't work.

I don't know a ton about Laravel or PHP, but I'm guessing there's other dependencies in that folder that would have to be managed as well.  Might just be easier to update documentation to reference to that `/app/www` folder instead since the commands only apply if you want to manually generate a key and place it in the `.env` file.

**Comment by thespad** [comment]
To be fair, the container readme does cover this:

> APP_KEY= | App key used for encrypting stored data. Generate with `docker exec speedtest-tracker php /app/www/artisan key:generate --show`

**Comment by kmanwar89** [comment]
> To be fair, the container readme does cover this:
> 
> > APP_KEY= | App key used for encrypting stored data. Generate with `docker exec speedtest-tracker php /app/www/artisan key:generate --show`

Oh! Where did you find that? I'm referencing the [FAQ documentation](https://docs.speedtest-tracker.dev/help/faqs) which does not call out the command you mentioned, it just says "Run `php artisan key:generate --show"` within a CLI of the docker container

![image](https://github.com/alexjustesen/speedtest-tracker/assets/11323060/36634a06-f664-4c7d-8f03-a860798e7e19)

**Comment by alexjustesen** [comment]
Doc to run commands can be found here https://docs.speedtest-tracker.dev/other/commands, details out both my image and LSIO's image.
