### ISSUE TITLE
Unable to migrate from existing SQLite DB

### ISSUE THREAD

**Issue by kmanwar89** [alexjustesen/speedtest-tracker#1286]
**Describe the bug**
I previously had an instance of this container running from March until November 2023. I went to start it back up and was met with 500 server errors, not realizing the image had migrated. Upon creating a fresh docker-compose file and copying over either of two existing sqlite databases, no results are present/exportable, but a simple `cat database.sqlite` shows thousands of previous results which I would like to retain.

**To Reproduce**
1. Copy the install steps located on the [docker compose instructions](https://docs.speedtest-tracker.dev/getting-started/installation/installation)
2. On a server, create a docker-compose.yml file, and bring the container up with 'docker compose up'
3. Copy over existing database.sqlite, placing it in the mapped volume for /config
4. Attempt to access the service on it's default URL _(https://serverIP:8443)_
5. Click on results - none are available.

**Expected behavior**
Given import/export behavior is not available, and given the .sqlite database is unaltered, it's expected an existing .sqlite database file to be readable if the only changes are in the docker image, not the database configuration

**Environment (please complete the following information):**
 - OS: Ubuntu Server 22.04.2 LTS
-  Architecture: amd64
 - Browser: Brave (Chrome-based)
 - Version: 0.18.1

**Screenshots**
Failure behavior:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/11323060/6b2c76d4-1608-405a-a41d-b8ef730ece5e)

Example of previous .sqlite files:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/11323060/87839d42-abef-47ea-bd92-7fa221bfb4f5)

Larger databse - the timestamp is slightly adjusted since I tried to spin the container back up, but the last timestamp of a result is November 11th, 2023:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/11323060/982c0d81-412c-48ca-9a01-5d1ce9a4c6ef)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/11323060/301f25fd-2b58-4c9a-a387-37184aa33a93)

**Logs**
N/A

**Additional context**
I know the previous database works at least *partially* because when I copy over my old folder to a new folder and spin up the container, it requires me to login with my previously-created account (i.e. not the default creds). So the data is there...somewhere.  Additionally, since the original ghcr.io image is gone, I can't spin up the old container to at least grab an export/copy down my settings, so I'm a bit stuck with some files that I can't do much with.

**Comment by kmanwar89** [comment]
@alexjustesen would be curious with your thoughts on this one, thank you!

**Comment by alexjustesen** [comment]
There is no easy way to export or migrate from one database system to another at this point. This will come with backup and import/export planned in the future.

Attaching this to #294

**Comment by kmanwar89** [comment]
So would this mean I'm basically SOL in my previous results, such that I can neither recover them (since the previous docker image is gone) and I can't migrate them? That would really suck if it's indeed the answer, but I totally understand if that's the case.

**Comment by alexjustesen** [comment]
Unfortunately unless you're familiar with using a database IDE (like DBeaver) to export the table and import it to your new database.

**Comment by kmanwar89** [comment]
Understood, thank you for the explanation. I may play around with learning the database IDE you mentioned as I've already backed up the database, but it may not present as much of an issue since I switched ISP's last month and the service is so stable, the speedtest doesn't really prove anything :laughing: 

Thanks for the help!
