### ISSUE TITLE
[Feature] Combine time dropdowns on dashboard

### ISSUE THREAD

**Issue by mmomjian** [alexjustesen/speedtest-tracker#1287]
Currently, a drop down appears when results are shown that has the options "last 24h", "last week", and "last month". Especially with the split to separate upload and download, I suggest that it would be more reasonable that all four graphs (upload, download, ping, jitter) are controlled by only one dropdown, instead of each having their own time settings. Currently, if I want to view my last week of results, I have to change the dropdown 4 times. I do understand that they are different graphs but I think it would be more intuitive if they shared an X-axis.

**Comment by alexjustesen** [comment]
#1252 😉
