### ISSUE TITLE
Egress Bandwidth

### ISSUE THREAD

**Issue by kmadaras** [alexjustesen/speedtest-tracker#1288]
Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] I can track my ingress, yet not my egress.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add a function to check ingress as an option.

**Additional context**
Add any other context or screenshots about the feature request here. I'm not sure if speedtest.net provides this function, yet iperf3, which runs against the speedtest servers, does.

**Comment by alexjustesen** [comment]
No sure I follow what you're asking.

**Comment by kmadaras** [comment]
Disregard, I was tired.  There is egress.  Been working on my darn cluster too much :)
