### ISSUE TITLE
Login by Username

### ISSUE THREAD

**Issue by OddMagnet** [alexjustesen/speedtest-tracker#1289]
**Is your feature request related to a problem? Please describe.**
I'm using subdomains for all my services and a password manager which has saved my password for the main domain.
On all my other services I can login with my password manager, just not with speedtest-tracker

**Describe the solution you'd like**
I'd like to be able to login with a Username as well or instead

**Comment by alexjustesen** [comment]
Password managers should work, not sure which you're using but Chrome's PW manager and 1Password both work for me when logging in. Just add your sub-domain to your list of urls the account is valid on and that should be fine.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/30bcd8f8-fd77-4f0b-9a0d-8ef22a7fa64b)

Also regarding username vs. email login I'm going to stick to email based as its the standard for the underlying framework.

**Comment by OddMagnet** [comment]
The problem is more that my password manager can't have both a username and an email (for one domain) and differentiate between when to use which for a given subdomain.
