### ISSUE TITLE
Webhook Notifications sending multiples and blank

### ISSUE THREAD

**Issue by NightHawkATL** [alexjustesen/speedtest-tracker#1290]
**Describe the bug**
I enabled webhook notifications a few days ago. The initial test webhook came through with the test message and it was successfully sent to Gotify through Active Pieces. Almost all subsequent notifications have been blank. I have provided screenshots of what I am seeing in Active Pieces and how I built the messages to be sent. 

**To Reproduce**
1. enable webhooks
2. setup a webhook URL to send to
3. test the webhook
4. set a threshold so that you get an immediate result
5. wait for the notification to come in and see the result as blank
6. most times the test result threshold results will be blank but there will be 3 notifications sent no matter if it is blank or not
7. manual testing will provide full information but scheduled test will be blank.

**Expected behavior**
I expect that the results would be sent on a threshold matched result to the webhook with the data from that test in-tact. I also expect that the notification from that webhook to only be sent once and not multiple times.

**Environment (please complete the following information):**
 - Docker OS: Ubuntu 22.04
-  Architecture:  amd64
 - Browser: Firefox 123.0
 - Version: 0.18.1

**Screenshots**
Automatic hourly testing with threshold met:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/a7710274-0849-4231-87c9-cc7aa2e3908a)

Manual testing with threshold met:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/ff6efb73-1a00-413e-b9d6-186efc90da95)

Each threshold met notification will send 4x (as seen in Active Pieces):
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/6b217e72-5ce5-4197-81cf-decb1d5ef28c)

As seen in Gotify:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/f7776f74-de29-4b89-a322-858186f7a538)

Web UI only shows 1 result for this test:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/74c511d8-13c2-4b6d-a5bc-1efd80bb7d4d)

**Logs**
Logs from around the time of the testing notifications:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/e10f6e36-53d1-4fe8-b44c-87cc05d4173f)

**Additional context**
I have tried a few times after you had told me to open a new ticket and I cannot get the blank results to reproduce as of now. I will let it run overnight and see if it happens again and will provide more info and screenshots. But seeing the ones from yesterday as seen in screenshot#1) and seeing the blank webhook data tells me there is something missing somewhere.

ALSO: I would like to request that the date and time of the test that hit the threshold to be sent as a part of the webhook AND possibly a link to the speedtest result on Ookla's website.

**Comment by NightHawkATL** [comment]
This is not fully completed as the webhook notifications are still being triggered 3x. This was tested with the "Test webhook" button.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/73943a3b-dbc6-4cb2-bfcb-6905c51ff4fb)

**Comment by alexjustesen** [comment]
@NightHawkATL really, you got those messages when hitting test? Those should only be from the threshold pattern.

**Comment by NightHawkATL** [comment]
> @NightHawkATL really, you got those messages when hitting test? Those should only be from the threshold pattern.

That is correct.

**Comment by NightHawkATL** [comment]
Here is a new one that just came in with the download threshold met to trigger an alert notification:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/8c23fb82-416d-4151-b1d2-be694ae3d8ee)

**Comment by alexjustesen** [comment]
@NightHawkATL can you make sure you're running the latest version `v0.18.2`? If not upgrade and test this again, I'm not seeing this locally.

**Comment by NightHawkATL** [comment]
> @NightHawkATL can you make sure you're running the latest version `v0.18.2`? If not upgrade and test this again, I'm not seeing this locally.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/b6fc159e-2189-45ee-a8bb-c3609c745d18)

I just tried another test and went back to the logs in the container and saw this entry right after I triggered the test. not sure if it correlates how I think but just wanted to add this.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/795e1149-bb65-44c0-ba6e-37068acd057b)

**Comment by alexjustesen** [comment]
@NightHawkATL so I'm looking at the webhook issue when it comes to thresholds being breached...

I've tried high thresholds so they fail and low ones so they don't and haven't been able to trigger the 3 notifications. I've also tried testing the webhook and still get one. I'm using pipedream.com to test the webhooks in the screenshot below:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/2ca62986-1ae2-4a51-8bdb-9a3539025959)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/bb879a16-12e5-4509-86d2-4debfc3b5d04)

**Comment by NightHawkATL** [comment]
@alexjustesen i have been doing some testing myself and it seems that the 3x notifications are only with Active Pieces as I am not getting them with n8n. The odd thing is that active pieces actually showed relieving the notification trigger 3x and that is why it sent 3x.

Sorry for all the trouble.

**Comment by alexjustesen** [comment]
That's an odd one for sure. I'm going to close it out and update the title to reflect it's an Active Pieces specific issue.
