### ISSUE TITLE
Clear notifications on threshold recovery

### ISSUE THREAD

**Issue by abelfodil** [alexjustesen/speedtest-tracker#1296]
**Is your feature request related to a problem? Please describe.**

Whenever a threshold is breached, notifications will accumulate which leads to a lot of spam in the notifications tab.

**Describe the solution you'd like**

I want the option to clear notifications on threshold recovery such that only 0 or 1 notifications can exist at time. 

0 when there is no breach anymore.

1 when there is a breach and only for the latest breach.

**Additional context**

**Comment by alexjustesen** [comment]
There currently isn't a way for me to tie notifications to failures and track that history but I'm going to add notification pruning so that any notification > 30 days gets removed.
