### ISSUE TITLE
Provide an APP_PORT env variable to override the default 80 and 443 ports

### ISSUE THREAD

**Issue by SlovakianCanon** [alexjustesen/speedtest-tracker#1302]
**Is your feature request related to a problem? Please describe.**
I want to run this container with `network_mode: service:wireguard`. However if there's already another container on that network listening on port 80 or 443, it fails. Port mapping via `ports:` can't solve this issue, afaik, since it's not supported in "container" network mode.

**Describe the solution you'd like**
Simply support an environment variable either called APP_PORT, or two variables called HTTP_PORT and HTTPS_PORT, or something similar

Unless there's already a way to do this, I think this would be a good setting to expose.

**Comment by alexjustesen** [comment]
`80` (http) and `443` (https) are standard ports from within the container, however you can map these to another port on the host/network like so...

`8080:80`
`8443:443`

Pick any available port on the left of the colon `:`.

**Comment by SlovakianCanon** [comment]
I'm talking a bout something different here - port mapping works great in most use-cases but not if you're using a special type of network like using a wireguard container as the network provider for the speedtest-tracker container.

In such case, providing port mappings is simply not supported (it will error out when running `docker-compose up` if you try). So since the ports can't be changed, I'm stuck with the default ones, and if there's another container on the network that has the same issue where the actual port the server is listening on can't be changed (80 for instance, which is the most common one) then there's a conflict.

**Comment by alexjustesen** [comment]
Can you use a proxy to get around the port issue?

**Comment by SlovakianCanon** [comment]
I don't think so - we end up with the same problem. If I want to run a proxy in front of it I need to point it to the wireguard container, and not speedtest-tracker (since it's running on the wireguard network, it's the only way it's reachable). So it doesn't matter the port I use on the exposed end of the proxy, the underlying port is still 80 and will conflict with any other container listening on port 80 on that same network

**Comment by alexjustesen** [comment]
I'd open an issue on LSIO's [repo](https://github.com/linuxserver/docker-speedtest-tracker) for the image to see if you can map it differently at the container level. Since we're talking application mostly on this repo it's not something I'd be changing.

**Comment by SlovakianCanon** [comment]
I was looking around last night on Github issues about this, trying to gather more info before posting in LSIO's repo, when I stumbled upon [this on the gluetun wiki ](https://github.com/qdm12/gluetun-wiki/blob/main/setup/inter-containers-networking.md)(gluetun is like LSIO's wireguard with some extra bells and whistles):

> Note two containers cannot listen on the same port in this case, there is no workaround. You might have to reach out to the program author to have a configurable listening port to avoid conflicts.

I'm sure I'm not the only one facing this situation, as my use-case is not so out of the ordinary. Basically I want to monitor the speed of my VPN tunnel over time, in addition to my ISP's. So I would run two instances of speedtest-tracker, one with a standard setup and the other routed through the Wireguard container.

I had a quick look in the source code to see how such an option could be implemented but I'm not familiar with the modern PHP ecosystem so I couldn't figure out where it should be configured. Do you think this is something reasonably easy to do?

**Comment by fjeddy** [comment]
Using port 80 as the default port for a simple app like this is without a doubt the wrong way to do it.

I've run into the same issue as the OP, I'm running everything through a VPN using Gluetun (Wireguard), and the containers are routed through the VPN containers. Meaning that the ports are exposed and changed within the VPN container and not the speedtest-tracker container. When you then run speedtest-tracker and Nginx Proxy Manager at the same time through the VPN container, then you get a port conflict as both are using port 80.

This is an edge case scenario that most people don't run into. But looking away from that, then Speedtracker shouldn't use port 80 as the default port, there is absolutely no reason it should, look at most, major, way bigger docker containers then Speedtracker, none of them use port 80, and it's with good reason. Teeny tiny Speedtracker shouldn't either.
