### ISSUE TITLE
Speedtest failing, no error message in results

### ISSUE THREAD

**Issue by hansenc0705** [alexjustesen/speedtest-tracker#1304]
**Describe the bug**
My speed tests started failing a few days ago with no errors within the WebUI. I've tried a clean install and still having issues. Seems to be related to my secondary internet provider (Verizon Wireless 5G Home).

I am able to console into the container and run the speediest cli command and get the following error

```
root@4ae0f89aa2be:/bin#speedtest 

   Speedtest by Ookla

      Server: Verizon - Kissimmee, FL (id: 28884)
         ISP: Verizon Wireless
Idle Latency:    19.68 ms   (jitter: 3.91ms, low: 16.51ms, high: 24.03ms)
    Download:   314.64 Mbps (data used: 546.2 MB)                                                   
                251.96 ms   (jitter: 69.33ms, low: 35.35ms, high: 570.04ms)
      Upload: FAILED                                            cy: 27.75 ms     
[error] Cannot write: 
root@4ae0f89aa2be:/bin#
```

**To Reproduce**
1. Run speedtest
2. View results in results table

**Expected behavior**
speedtest should complete successfully 

**Environment (please complete the following information):**
 - OS linuxserver.io image
-  Architecture: [e.g. arm64, amd64]
 - Browser Safari
 - Version 0.18.2

**Screenshots**
<img width="1264" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/10247644/727be81a-0e1b-4d85-af72-c925af903d93">

**Logs**
See above, happy to provide others if needed

**Additional context**
nothing additional.

**Comment by hansenc0705** [comment]
Wonder if this has something to do with it

https://stackoverflow.com/questions/71564993/why-does-speedtest-cli-upload-fail-for-us-mobile-carriers

**Comment by hansenc0705** [comment]
Going to close this. I was able to fix by disabling pass thru on my cradlepoint and instead NATing the connection. Not ideal but this fixes a couple other problems.

**Comment by ykktrcb7** [comment]
> Going to close this. I was able to fix by disabling pass thru on my cradlepoint and instead NATing the connection. Not ideal but this fixes a couple other problems.

can you provide more information about what you did to fix please?
