### ISSUE TITLE
500 error on general setting

### ISSUE THREAD

**Issue by Kunalb963** [alexjustesen/speedtest-tracker#1305]
**Describe the bug**
500 errror on general setting
**To Reproduce**
in terminal:php artisan app:update-general-settings
Result
Couldn't find open input file: artisan

**Comment by cristoslc** [comment]
also seeing this issue.  

**Repro Steps**
1. Log in to speedtes-tracker.{homeserver}/admin
2. Go to "General" settings page in admin console

**Expected:** Loads settings page
**Actual:** 500 error

**Logs**
PHP error log not terribly informative:
```
[08-Mar-2024 09:15:54] NOTICE: Terminating ...
[08-Mar-2024 09:15:54] NOTICE: exiting, bye-bye!
[08-Mar-2024 09:16:01] NOTICE: fpm is running, pid 254
[08-Mar-2024 09:16:01] NOTICE: ready to handle connections
```

No corresponding entries in Apache error log.

**Environment**
LinuxServer.io docker image (latest @ 8d088774e2ff)

**Additional Steps**
Docker exec'ing into `/app/www` and running `php artisan cache:clear` followed by a container restart had no effect.

**Comment by cristoslc** [comment]
After running that command I continue to get a 500 error, is that expected? Is there a log I can look at to get more detail?
