### ISSUE TITLE
PHP startup error

### ISSUE THREAD

**Issue by jimbo-jones-sys** [alexjustesen/speedtest-tracker#1310]
using the standard compose file for testing 

version: '3.4'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - /path/to/data:/config
            - /path/to-custom-ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: postgres:15
        restart: always
        environment:
            - POSTGRES_DB=speedtest_tracker
            - POSTGRES_USER=speedy
            - POSTGRES_PASSWORD=password
        volumes:
            - speedtest-db:/var/lib/postgresql/data
volumes:
  speedtest-db:

getting the warning of

 speedtest-tracker  | PHP Warning:  PHP Startup: Invalid date.timezone value '', using 'UTC' instead in Unknown on line 0

I have added - TZ=Europe/Berlin to the compose on another test but still no luck

**Comment by alexjustesen** [comment]
These aren't valid paths, to the left of the colon `:` you need to reference a path on your host machine:

```yaml
volumes:
- /path/to/data:/config
- /path/to-custom-ssl-keys:/config/keys
```

If you're not using a custom certificate you can remove `/path/to-custom-ssl-keys:/config/keys`

**Comment by jimbo-jones-sys** [comment]
ok thats all sorted now thank you 

if i change the port to any other number it no longer works please advise

**Comment by alexjustesen** [comment]
Change the port to the left of the `:` as well, right side is internal to the container and needs to be either 80 for http or 443 for https
