### ISSUE TITLE
Massive speed discrepancy

### ISSUE THREAD

**Issue by jimbo-jones-sys** [alexjustesen/speedtest-tracker#1311]
Hello please see attached photo 
![2024-03-14 15_33_43-Window](https://github.com/alexjustesen/speedtest-tracker/assets/62987183/7cf5e4b1-4188-409d-a673-a965cb1b652d)
I'm using windows docker desktop

**Comment by alexjustesen** [comment]
Please take a look at issue history, there are issues for bottlenecks with Docker Desktop on Windows networking. This falls inline with what I see as well when doing development.
