### ISSUE TITLE
A number of tests showing Failed or Started

### ISSUE THREAD

**Issue by lnlyssg** [alexjustesen/speedtest-tracker#1315]
**Describe the bug**
I have a number of tests showing Failed or Started interspersed with successful tests

**To Reproduce**
Unable to reproduce, seems to occur randomly

**Expected behavior**
No Failed or Started tests

**Environment (please complete the following information):**
 - OS: Docker on Synology
-  Architecture: amd64
 - Version: 0.18.3

**Screenshots**
<img width="1211" alt="Screenshot 2024-03-16 at 20 46 37" src="https://github.com/alexjustesen/speedtest-tracker/assets/10902647/74ada647-89e7-4dd2-91a0-446e8f31292e">
<img width="882" alt="Screenshot 2024-03-16 at 20 47 07" src="https://github.com/alexjustesen/speedtest-tracker/assets/10902647/21132281-7f1a-4f2f-a77d-a8160605bb3f">
<img width="875" alt="Screenshot 2024-03-16 at 20 47 17" src="https://github.com/alexjustesen/speedtest-tracker/assets/10902647/41244f70-b25e-4e25-9522-d5167905c39d">

**Additional context**
These started on March 13th but I only just noticed the issue, it looks like one of the servers I had defined is no longer active as it only shows the number in my server list with no name against it (it was 26075) but I'm not sure... I have deleted this server and will see if the issue reoccurs.

**Comment by rairulyle** [comment]
Same
![image](https://github.com/alexjustesen/speedtest-tracker/assets/12708526/01d81ff2-e517-4b5a-bb78-ef32a4448ce5)

It just says `Server Selection - Failed to find a working test server. (NoServers)`
![image](https://github.com/alexjustesen/speedtest-tracker/assets/12708526/41bf4076-1246-4b47-9d9e-d6bc2f1b0a8d)

It was working last month,

**Comment by lnlyssg** [comment]
@rairulyle do you have a server list in your settings?

**Comment by QYG2297248353** [comment]
![image](https://github.com/alexjustesen/speedtest-tracker/assets/56836951/dd8f0f2e-97ed-414f-be80-6d71b206cb49)

There is a server list in the settings, but 500 may appear irregularly. Refreshing will solve this problem

**Comment by alexjustesen** [comment]
@lnlyssg do you have a list of servers or was it only one?

**Comment by alexjustesen** [comment]
Also worth noting these are errors from the Speedtest CLI so its a _good thing_ to see this as it's validating the server the app is passing to the CLI.

**Comment by lnlyssg** [comment]
I have a list, to clarify what I posted originally one of the servers in my list was only showing the numbers and not the longer description. Since removing that server I haven't had any started or failed tests.

**Comment by TheWilli67** [comment]
Hello it seems that i have the same issue....
![image](https://github.com/alexjustesen/speedtest-tracker/assets/92713985/38f6b524-cd6f-44ec-92dd-c6cc292641d6)

the last speedtest seems to be at 8:39 on the admin pannel : 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/92713985/59c3231b-6982-481b-86eb-4bb4ea07f5bb)

theses are the latest try : 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/92713985/91ef08a9-3450-4012-a347-5e81312722c8)

and here is the latest try view results: 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/92713985/09bfb755-1fb5-472b-a158-66f591e0ab8e)

PS : Native french speaker sorry for the gammaticals errors

**Comment by TheWilli67** [comment]
"solved" and speedtest on status completed from 9:48 till now it seems working i don't know where did that came from : 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/92713985/562f47af-b983-4587-a482-756a54ac94ee)

**Comment by alexjustesen** [comment]
Its possible if you run too many tests you could be blocked but I haven't heard of it. Ookla speedtests are pretty data heavy coming in at ~1GB of data so just keep that in mind.
