### ISSUE TITLE
Pages are "very" slow to load

### ISSUE THREAD

**Issue by korishan** [alexjustesen/speedtest-tracker#1316]
When I go to any page, the loading time is easily recorded in the 5+ seconds, especially on the main Dashboard page.  When I'm at the Admin page and click on General, it takes multiple seconds to load. Change to any other page and it's multiple seconds to change. None of my other containers or vms have this slow loading times.

Is there something that I may have configured incorrectly that's causing this issue??

System is a docker inside an LXC container on Proxmox.
Hardware system is an HP380P running with 24 cores and 256GB of ram, and the drive is >10TB in RaidZ2 configuration.
Resources available:
Ram: 2GB
CPU Cores: 2
Swap: 1GB
Version: 0.18.3

According to Proxmox memory usage of the VM is around 1GB used. So I know I'm not running out of resources.

**Comment by alexjustesen** [comment]
Can you share your Docker compose file? LXC containers have had performance issues in the past so make sure you're using LSIO's image and check past issues.

**Comment by korishan** [comment]
Ahh, looks like I'm using the "ghcr.io" image.  Didn't know there was another one I should be using.

`version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8780:80'
            - '8743:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - './config:/config'
            - './ssl/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-app:
  speedtest-db:
`

**Comment by korishan** [comment]
I changed the image to "lscr.io/linuxserver/speedtest-tracker:latest", so will test that one to see how it performs

**Comment by ykktrcb7** [comment]
I have the same issue. Any update on this?

**Comment by korishan** [comment]
Interesting considering that other services that I have inside of LXC's don't have this delay in loading 🤔  I have several different browser based applications running that are quite responsive.

**Comment by gremo** [comment]
Have the same problem running it on Pi 4 (not LXC). Page loads very slow, about 4-5 secs. Ideas? I really like this project, but the lack of responsiveness really ruins it.
