### ISSUE TITLE
Failed tests should be included in the grap generation so that downtime periods are visible

### ISSUE THREAD

**Issue by borj** [alexjustesen/speedtest-tracker#1318]
**Is your feature request related to a problem? Please describe.**
When there is no internet connectivity (i.e. ISP has issues, ...) the speedtests will fail but that will still generate a smooth graph when a test succeeds. The attached sccreenshots represent a situation where internet connectivity was down for 3 hours yet the graph is pristine.

**Describe the solution you'd like**
The failed tests should still be included in the graphs so that downtime periods are visible.

![2024-03-19 16_47_32-Uptime Kuma — Mozilla Firefox](https://github.com/alexjustesen/speedtest-tracker/assets/234882/33b9c159-247a-4356-853d-a4994edb74da)
![2024-03-19 15_44_44-Dashboard - Speedtest Tracker — Mozilla Firefox](https://github.com/alexjustesen/speedtest-tracker/assets/234882/b0f3ed18-f77f-4b58-9ffd-1e4c92b90280)
![2024-03-19 15_44_24-Inbox - Unified Folders - Mozilla Thunderbird](https://github.com/alexjustesen/speedtest-tracker/assets/234882/b068451b-e17a-4465-80d5-87e1c058e9db)

**Comment by alexjustesen** [comment]
Linking to #509 as the parent.
