### ISSUE TITLE
Version 0.18.3 No record of stream data

### ISSUE THREAD

**Issue by FreddieOnly** [alexjustesen/speedtest-tracker#1320]
**Describe the bug**
After updating to version 0.18.3 no record of “download“, “upload“, “ping“ and “jitter“ are written or shown.

**To Reproduce**
1. starting speedtest…
2 error: no results are shown

**Expected behavior**
that the update will show me as before the result from checking every hour

**Environment (please complete the following information):**
 - Synology DSM 7.2.1-69057 Update 3  (Linux)
-  Architecture: ?
 - Browser chrome
 - Version latest

**Screenshots**
![Speedtest o 18 3 screen no results](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/0776b027-a061-4527-98ef-035ea96e418b)

**Logs**
[_speedtest_logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/14694929/_speedtest_logs.txt)

**Comment by alexjustesen** [comment]
What version did you have installed before?

**Comment by shulymn** [comment]
Hi,

I had the same issue, not registering any data since a few days. I checked the log, it's actually a problem from speedtest.net and not speedtest-tracker.
They must have changed their servers list recently because the ones I had selected before aren't in the list anymore.
I reselected a new server and now it works again.

**Comment by FreddieOnly** [comment]
Hi Shulymn,

Thank you for your reply and information! One more question: where did you
reselect the serverlist?
I am looking forward hearing from you


Am So., 24. März 2024 um 15:18 Uhr schrieb shulymn ***@***.***

**Comment by shulymn** [comment]
Hi,

It's in the settings of speedtest-tracker. You don't reselect the serverlist but in my case, i had a server select like this : 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/13053858/50f0dcfa-2c3f-44c0-bbad-b1e65a6e178f)

But seems like the server I had here wasn't available anymore on speedtest.net
So I took another one (or leave it empty) and it made it work again.
