### ISSUE TITLE
Add possibility to delete users

### ISSUE THREAD

**Issue by TheWilli67** [alexjustesen/speedtest-tracker#1323]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**

I believe it would be beneficial to include a delete option, accompanied by a confirmation prompt, within the three-dot menu in the user interface.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/92713985/5a975694-9a59-4b3c-bb6d-cc26fa03d89c)

Perhaps it would be a good idea to add a delete button between the save and cancel buttons within the user edit menu.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/92713985/a81eaa2b-1d15-4b8d-a1d9-b0499ff36240)

**Comment by alexjustesen** [comment]
Looks like you're trying to delete another admin user, first change the role to `User` and then you can delete the account.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/36c07338-b794-48f0-955f-f5f615a9a24d)

Also why not just stick with the first account?
