### ISSUE TITLE
Speedy username to unable to authenticate to database

### ISSUE THREAD

**Issue by vk6xebec** [alexjustesen/speedtest-tracker#1325]
No matter how much I tried using the docker compose file for MariaDB and Postgres as listed, the user Speedy could not connect to the database from reading the docker logs. Source: https://docs.speedtest-tracker.dev/getting-started/installation/installation

Could this please be checked?

This solution worked for me:
https://gist.github.com/luckman212/40ff0a827c12007c8c79ff275d390767

Also the "version  3.4" line is deprecated. Please remove as it throws up errors when running the compose file.

**Comment by alexjustesen** [comment]
If you changed the username or password after starting the containers initially it wont be correct as the username and password for the database user are set on the first startup. 

Delete the database volume, change the password and then start the containers again.
