### ISSUE TITLE
Empty Result List Failed test

### ISSUE THREAD

**Issue by ykktrcb7** [alexjustesen/speedtest-tracker#1328]
**Describe the bug**
Cant run any test results, always displays failed after a few seconds.
Tried even defining the ookla server.

**To Reproduce**
1. Go to dashboard
2. Click on run test

**Expected behavior**

**Environment (please complete the following information):**
 - OS: docker image
-  Architecture: on synology ds218+
 - Browser firefox

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/81748597/89de209e-9e06-47c4-8627-b52955fb54ec)

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by marcosvrs** [comment]
What is the output of the following command?
`sudo docker exec -it [container_name] speedtest -vvv`

**Comment by ykktrcb7** [comment]
`[2024-03-25 18:39:32.148] [info] Resolved address 1: 104.18.202.232
[2024-03-25 18:39:32.148] [info] Resolved address 2: 104.18.203.232
[2024-03-25 18:39:32.340] [info] HTTP request (effective url: https://cli.speedtest.net/api/cli/config?deviceId=f9f3d83a0f338117109ba1d64a3b9ff895b256ea2b74cc9af34086ccef175d95&hid=%2508%2505%2507%2507%2508%255CYZ%2500ZY%255C&sid=09d395079965b01341ce7549cda8f647a04801e3f289a374766296af9afb0351&uname=Linux%204.4.180%2B%20%2342962%20SMP%20Mon%20May%2029%2014%3A38%3A23%20CST%202023%20x86_64) completed with response code 200
[2024-03-25 18:39:32.341] [info] configuration content:
{"suite":{"global":{"engine":{"isUploadFirst":false,"testDurationSeconds":15,"threadCount":4,"packetSizeBytes":32000000},"dynamic":{"stableStop":{"isEnabled":true},"download":{"isScalingEnabled":true,"maxConnections":32}},"loadedLatency":{"enableUdp":true,"enableTcp":true}},"testStage":{"latency":{"pingCount":5},"upload":{"isServerUploadEnabled":true,"isClientPrimaryMeasureMethod":false}}},"app":{"ispName":"Vodafone Portugal","traceLevel":2,"licenseKey":"61d68223660b4a80-Cde5510751664a68f-7b3d75bef52d706e","license":{"message":"You may only use this Speedtest software and information generated\nfrom it for personal, non-commercial use, through a command line\ninterface on a personal computer. Your use of this software is subject\nto the End User License Agreement, Terms of Use and Privacy Policy at\nthese URLs:\n\n\thttps://www.speedtest.net/about/eula\n\thttps://www.speedtest.net/about/terms\n\thttps://www.speedtest.net/about/privacy","version":"aaa8331c62dcaeaf7cbefe8de3952b0240ccae4424412c2e498eeb1beb84b20b"},"gdpr":{"message":"Ookla collects certain data through Speedtest that may be considered\npersonally identifiable, such as your IP address, unique device\nidentifiers or location. Ookla believes it has a legitimate interest\nto share this data with internet providers, hardware manufacturers and\nindustry regulators to help them understand and create a better and\nfaster internet. For further information including how the data may be\nshared, where the data may be transferred and Ookla's contact details,\nplease see our Privacy Policy at:\n\n       http://www.speedtest.net/privacy","acceptTimeout":90},"saveTestResultUrl":"https://results.speedtest.net/reports","resultFormat":"json"},"servers":[{"id":"47363","host":"speedtest-boav.vodafone.pt:8080","name":"Porto","country":"Portugal","sponsor":"Vodafone Portugal","sponsored":true,"host_functional":"1"},{"id":"10363","host":"porto.speedtest.net.zon.pt:8080","name":"Porto","country":"Portugal","sponsor":"NOS","sponsored":false,"host_functional":"1"},{"id":"30945","host":"speedtest-ga1.meo.pt:8080","name":"Gaia","country":"Portugal","sponsor":"MEO","sponsored":false,"host_functional":"1"},{"id":"54454","host":"speedtest.finalspace.pt:8080","name":"Vila Nova de Famalicão","country":"Portugal","sponsor":"Final Space Network","sponsored":false,"host_functional":"1"},{"id":"57379","host":"speedtest.cloudity.net:8080","name":"Vila Nova de Famalicão","country":"Portugal","sponsor":"Cloudity","sponsored":false,"host_functional":"1"},{"id":"57814","host":"speedtest-pt.pq.hosting:8080","name":"Riba de Ave","country":"Portugal","sponsor":"PQ.Hosting","sponsored":false,"host_functional":"1"},{"id":"54303","host":"speedtest-avei.vodafone.pt:8080","name":"Aveiro","country":"Portugal","sponsor":"Vodafone Portugal","sponsored":false,"host_functional":"1"},{"id":"63350","host":"testdevelocidad.aureatelecom.com:8080","name":"Pontecaldelas","country":"Spain","sponsor":"Aureatelecom","sponsored":false,"host_functional":"1"},{"id":"42310","host":"testdevelocidad.itsarria.com:8080","name":"Sarria","country":"Spain","sponsor":"ITSarria","sponsored":false,"host_functional":"1"},{"id":"25118","host":"stvelocimetro.mundo-r.com:8080","name":"La Coruña","country":"Spain","sponsor":"R","sponsored":false,"host_functional":"1"},{"id":"46985","host":"speedtest-alfr.vodafone.pt:8080","name":"Lisboa","country":"Portugal","sponsor":"Vodafone Portugal","sponsored":false,"host_functional":"1"}]}

[info] Configuration expiry date: 1712016000

   Speedtest by Ookla

[info] Server count: 11
[info] app.version: 1.2.0.84 (ea6b6773cf)
[info] Starting stage 1 of type 2
[info] Starting stage 1 of type 2
[info] Resolved address 1: 95.95.252.95
[info] Opening socket to '95.95.252.95'
[info] Starting stage 1 of type 2
[info] Ping 1: 1.90 ms (1.90ms min, 0.00ms jitter)
[info] Ping 2: 1.50 ms (1.50ms min, 0.41ms jitter)
[info] Ping 3: 2.48 ms (1.50ms min, 0.70ms jitter)
[info] Final Ping: 1.50 ms
[info] Stage 1 completed
[info] Starting stage 1 of type 2
[info] Starting stage 1 of type 2
[info] Resolved address 1: 83.174.21.51
[info] Opening socket to '83.174.21.51'
[info] Starting stage 1 of type 2
[info] Ping 1: 2.31 ms (2.31ms min, 0.00ms jitter)
[info] Ping 2: 2.54 ms (2.31ms min, 0.23ms jitter)
[info] Ping 3: 3.22 ms (2.31ms min, 0.46ms jitter)
[info] Final Ping: 2.31 ms
[info] Stage 1 completed
[info] Resolved address 1: 185.83.212.67
[info] Opening socket to '185.83.212.67'
[info] Starting stage 1 of type 2
[info] Resolved address 1: 212.55.137.229
[info] Opening socket to '212.55.137.229'
[info] Ping 1: 2.43 ms (2.43ms min, 0.00ms jitter)
[info] Starting stage 1 of type 2
[info] Ping 2: 2.42 ms (2.42ms min, 0.01ms jitter)
[info] Resolved address 1: 185.83.212.26
[info] Opening socket to '185.83.212.26'
[info] Ping 3: 2.19 ms (2.19ms min, 0.12ms jitter)
[info] Final Ping: 2.19 ms
[info] Resolved address 1: 94.131.10.140
[info] Opening socket to '94.131.10.140'
[info] Stage 1 completed
[info] Ping 1: 5.24 ms (5.24ms min, 0.00ms jitter)
[info] Ping 2: 4.79 ms (4.79ms min, 0.45ms jitter)
[info] Ping 3: 4.81 ms (4.79ms min, 0.23ms jitter)
[info] Final Ping: 4.79 ms
[info] Stage 1 completed
[info] Starting stage 1 of type 2
[info] Ping 1: 4.16 ms (4.16ms min, 0.00ms jitter)
[info] Ping 2: 4.38 ms (4.16ms min, 0.23ms jitter)
[info] Ping 1: 5.34 ms (5.34ms min, 0.00ms jitter)
[info] Starting stage 1 of type 2
[info] Ping 3: 4.64 ms (4.16ms min, 0.24ms jitter)
[info] Final Ping: 4.16 ms
[info] Stage 1 completed
[info] Ping 2: 6.71 ms (5.34ms min, 1.38ms jitter)
[info] Resolved address 1: 185.164.119.180
[info] Opening socket to '185.164.119.180'
[info] Starting stage 1 of type 2
[info] Ping 3: 15.12 ms (5.34ms min, 4.89ms jitter)
[info] Final Ping: 5.34 ms
[info] Stage 1 completed
[info] Resolved address 1: 83.174.22.3
[info] Opening socket to '83.174.22.3'
[info] Resolved address 1: 171.22.84.7
[info] Opening socket to '171.22.84.7'
[info] Ping 1: 2.65 ms (2.65ms min, 0.00ms jitter)
[info] Resolved address 1: 213.60.113.204
[info] Opening socket to '213.60.113.204'
[info] Ping 2: 3.12 ms (2.65ms min, 0.47ms jitter)
[info] Ping 3: 3.37 ms (2.65ms min, 0.36ms jitter)
[info] Final Ping: 2.65 ms
[info] Stage 1 completed
[info] Resolved address 1: 83.174.21.47
[info] Opening socket to '83.174.21.47'
[info] Ping 1: 9.61 ms (9.61ms min, 0.00ms jitter)
[info] Ping 2: 9.65 ms (9.61ms min, 0.04ms jitter)
[info] Ping 3: 9.65 ms (9.61ms min, 0.02ms jitter)
[info] Final Ping: 9.61 ms
[info] Stage 1 completed
[info] Ping 1: 26.29 ms (26.29ms min, 0.00ms jitter)
[info] Ping 2: 26.13 ms (26.13ms min, 0.16ms jitter)
[info] Ping 3: 26.36 ms (26.13ms min, 0.20ms jitter)
[info] Final Ping: 26.13 ms
[info] Stage 1 completed
[info] Ping 1: 32.27 ms (32.27ms min, 0.00ms jitter)
[info] Ping 2: 32.40 ms (32.27ms min, 0.13ms jitter)
[info] Ping 3: 32.45 ms (32.27ms min, 0.09ms jitter)
[info] Final Ping: 32.27 ms
[info] Stage 1 completed
[warning] Timeout occurred in connect.
[error] Error: [0] Cannot open socket
[info] Stage 1 completed
[info] server selected: 10363
[info] Server id: 10363
[info] Name: Porto
[info] Country: Portugal
[info] Sponsor: NOS
      Server: NOS - Porto (id: 10363)
         ISP: Vodafone Portugal
[info] Running TCP test suite
[info] Running Speedtest against host:port porto.speedtest.net.zon.pt:8080
[info] Starting stage 1 of type 2
[info] Resolved address 1: 95.95.252.95
[info] Opening socket to '95.95.252.95'
[info] Ping 1: 2.45 ms (2.45ms min, 0.00ms jitter)
[info] Ping 2: 2.48 ms (2.45ms min, 0.03ms jitter)
[info] Ping 3: 2.41 ms (2.41ms min, 0.05ms jitter)
[info] Ping 4: 2.48 ms (2.41ms min, 0.06ms jitter)
[info] Ping 5: 2.41 ms (2.41ms min, 0.06ms jitter)
[info] Final Ping: 2.41 ms
[info] Stage 1 completed
Idle Latency:     2.45 ms   (jitter: 0.06ms, low: 2.41ms, high: 2.48ms)
[info] Starting stage 2 of type 3
[warning] Receive error: 11 (Resource temporarily unavailable)ency: 3.38 ms    
[warning] Loaded latency: cannot read response.: [11] Resource temporarily unavailable
[warning] Receive error: 11 (Resource temporarily unavailable)
[info] Connection 1 failed. Added connection and continuing test.
[warning] Receive error: 11 (Resource temporarily unavailable)
[info] Connection 2 failed. Added connection and continuing test.
[warning] Receive error: 11 (Resource temporarily unavailable)
[info] Connection 3 failed. Added connection and continuing test.
[warning] Receive error: 11 (Resource temporarily unavailable)
[info] Connection 4 failed. Added connection and continuing test.
[warning] Receive error: 11 (Resource temporarily unavailable)ency: 3.38 ms
    Download: FAILED
[error] Cannot read:`

**Comment by alexjustesen** [comment]
Looks like the server your testing against failed the download test. Try a different server.

**Comment by ykktrcb7** [comment]
I keep getting the same error with different servers in different countries. Can it be caused by double NAT?

**Comment by ykktrcb7** [comment]
is there any way i can test the servers with CLI?

**Comment by ykktrcb7** [comment]
I selected a collection of random servers and set a CRON job during the night to test every hour and got one successful result only
![image](https://github.com/alexjustesen/speedtest-tracker/assets/81748597/09b84144-cf0d-42e3-919a-65e31d8d4ef2)

**Comment by MartynKeigher** [comment]
Yep - I have rerpo here too (both the UI and the API) running **v0.18.3** ... 

```
localadmin@docker-01:~$  curl 192.168.0.18:8081/api/speedtest/latest
{"message":"ok","data":{"id":672,"ping":null,"download":null,"upload":null,"server_id":null,"server_host":null,"server_name":null,"url":null,"scheduled":false,"failed":true,"created_at":"2024-03-29T20:08:07.000000+00:00","updated_at":"2024-03-29T20:08:07.000000+00:00"}}
```

I wondered why my Stream Deck buttons had no data! 😄 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/3298134/14d5a50a-2dac-4adc-9725-176cb944a629)

**Comment by alexjustesen** [comment]
Going to close this out, it's generally the chosen server being the issue. Would suggest picking a different one for sure.
