### ISSUE TITLE
Information about speedtest-tracker-icon.png Usage

### ISSUE THREAD

**Issue by ArthurHuyghe** [alexjustesen/speedtest-tracker#1331]
### Question
I am curious what the plans are for the use of `speedtest-tracker-icon.png` in the future. Additionally, I would like to know if you would be comfortable with the icon being added to the [walkxcode/dashboard-icons](https://github.com/walkxcode/dashboard-icons) repository for use in dashboards and such. 
I already opened a PR-request to change the icon from [henrywhitaker3/Speedtest-Tracker](https://github.com/henrywhitaker3/Speedtest-Tracker) to your icon, but if you do not want to have your icon added, I will close the request immediately.

Thanks in advance!

**Comment by alexjustesen** [comment]
The rabbit is the icon I'm using in the app and in the docs and making no plans on changing it. 

Thanks for adding it to the library!
