### ISSUE TITLE
Allow ability to set default graph time period

### ISSUE THREAD

**Issue by oregonpillow** [alexjustesen/speedtest-tracker#1337]
**Is your feature request related to a problem? Please describe.**

At the moment, the graphs always default to 24hr view. This is annoying when you schedule infrequent speed tests and would be more interested in seeing the results over a longer period. e.g. 1 week.

**Describe the solution you'd like**

Allow ability to set default graph time view. At least for the public dashboard if enabled.

**Additional context**

![image](https://github.com/alexjustesen/speedtest-tracker/assets/53374403/bfb59bac-c5ef-4df6-b827-d0497cf7e436)

**Comment by alexjustesen** [comment]
Attaching to #448
