### ISSUE TITLE
Add way of disabling login for middleware

### ISSUE THREAD

**Issue by Joever9000** [alexjustesen/speedtest-tracker#1343]
**Is your feature request related to a problem? Please describe.**
Login is required for admin panel, so adding any middleware would cause 2 login screens.

**Describe the solution you'd like**
I know it was previously stated that Oauth was not going to be added, but is there any way we could disable the login requirement for the admin panel so that middleware can be added and there wouldn't be 2 login screens?

**Additional context**
I would like to add middleware through nginx and authentik on just the admin paths, but by doing this I would have to first login to authentik and then to the speedtest.

**Comment by Joever9000** [comment]
I should also add that I don't need this as an official feature if I could be provided with some hacky workaround.

**Comment by darylf** [comment]
I was about to create a feature request for this same issue. In my homelab, I use Authelia for authentication, and I also experience the double login issue when accessing the admin panel of Speedtest Tracker.

I understand that authentication is required for authorization within the framework, but I would appreciate reconsidering the authentication flow to allow for more flexibility—perhaps an option to defer authentication to an external provider. This would improve the user experience for those integrating middleware-based authentication solutions.

Would you be open to discussing possible approaches for this?
