### ISSUE TITLE
[Feature] Ability to truncate ALL results in the UI

### ISSUE THREAD

**Issue by MartynKeigher** [alexjustesen/speedtest-tracker#1344]
**Is your feature request related to a problem? Please describe.**
_Not a problem, but a User Story..._ 

As a user with admin rights, 
I would like a way to clear all previous results in the UI,
So that I can start over without having to rebuild the docker containers\instances.

**Describe the solution you'd like**

A button on the 'Results' page with a 'are you sure you want to do this' type confirmation.
Or maybe the button lives in 'General' close to the prune X days option? 
This button would essentially kick off a TRUNCATE to the db table with results, so that the 'next speed test' after deleting the results starts over at speedtest.ID=1.

**Comment by alexjustesen** [comment]
I like 👍

I edited the title to reflect the requirement of truncating the table so the PK is reset which is different than just deleting the records. No idea when I'll get to it but it would be a nice to have.
