### ISSUE TITLE
Add results URL to notifications

### ISSUE THREAD

**Issue by NightHawkATL** [alexjustesen/speedtest-tracker#1370]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
I would like to get the results URL added to the notifications whether it is email or webhooks or whatever.

**Additional context**
It would be nice to click on the speedtest result URL that was performed that triggered the notification or even link to the results from the specific test that is located in the website itself in speedtest-tracker.

**Comment by NightHawkATL** [comment]
It could be either one, whichever is simpler.

**Comment by alexjustesen** [comment]
I "think" I like the idea of driving the traffic back to the application over Ookla directly. This way when I support additional speedtest tools I don't have to account for that in a notification.

**Comment by NightHawkATL** [comment]
That sounds great to me!

**Comment by marcelosoftpack** [comment]
With the image that is current on dockerhub, when a speedtest is made it sents an email.
That email has a "View Results" button that points to http://localhost/admin/results.
Should be an env var to change that.

Another suggestions is that instead button point to the list of all speedtests, should point to the exact test that was made.

**Comment by alexjustesen** [comment]
> Should be an env var to change that.

https://docs.speedtest-tracker.dev/help/faqs#notifications 😉

**Comment by marcelosoftpack** [comment]
So please edit documentation and add it on the env var list

**Comment by alexjustesen** [comment]
PRs welcome to the docs repo: https://github.com/alexjustesen/speedtest-tracker-docs

**Comment by NightHawkATL** [comment]
But I don't use the email notifications, I use webhooks and would like that passed in the webhook information.
