### ISSUE TITLE
InfluxBDv2 error connecting to the API after updated to 0.19.0 version

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#1391]
Using latest Linuxserver version in Unraid. 

After updated to 1.19.0 :  

` production.INFO: InfluxDB2\ApiException: [422] Error connecting to the API (http://192.168.0.199:8086/api/v2/
 failure writing points to database: partial write: field type conflict: input field "upload_latency_low" on measurement "speedtest" is type integer, already exists as type float dropped=1) in /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php:157`

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/599b6069-dedc-4520-8912-d22517162f26)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/f98775a2-7fc8-48d3-8dfc-f322dd366823)

**Comment by alexjustesen** [comment]
I've got an update planned for influx coming, its super cranky about data types and because of changes over time some people it works and some it doesnt. The whole thing needs to be refactored and set to consistent values.

**Comment by masterwishx** [comment]
it coused befor and after cleared cache in 0.19.0, after cleared cache again and reboot container last time , no influxdb error for now but have this : 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/4470d773-de05-4c10-b26e-831c3987eba9)

**Comment by alexjustesen** [comment]
After that error did you restart the image? I get the feeling its the settings package causing it which is why I'll be getting rid of it

**Comment by masterwishx** [comment]
> After that error did you restart the image? I get the feeling its the settings package causing it which is why I'll be getting rid of it

if you mean restart container ?  then yes , sure

**Comment by masterwishx** [comment]
@alexjustesen Also after server reboot on today morning (it was going to be off for the night) have same error for InfluxDBv2 and then same production.WARNING

**Comment by masterwishx** [comment]
![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/105873e8-a303-492b-a5e7-7f06647eadc6)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/c7466168-9727-4e07-978d-70bf3ca6b428)

**Comment by alexjustesen** [comment]
Thanks this is a new one, let me dig in.

To confirm are you on the LSIO image?

**Comment by masterwishx** [comment]
> Thanks this is a new one, let me dig in.
> 
> To confirm are you on the LSIO image?

Yes, Thanks

**Comment by masterwishx** [comment]
@alexjustesen Today after booted server in morning also have this : 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/78e6b552-9032-4b55-8c39-b59d26bff420)


The thing is i have test every 10min , some checks is working (11:30)  others not  :   

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/e0c10dcb-6731-4e37-a0ae-db7baf266ba4)

**Comment by alexjustesen** [comment]
I think it's the debug warning causing confusion, should probably remove those. Nothing wrong actually happening so closing the issue.

Source ref: https://github.com/alexjustesen/speedtest-tracker/blob/4ff86a9eb6d5465c7cc0b84199b7c452c6687b99/app/Listeners/Mail/SendSpeedtestThresholdNotification.php#L59

**Comment by masterwishx** [comment]
> I think it's the debug warning causing confusion, should probably remove those. Nothing wrong actually happening so closing the issue.
> 
> Source ref:
> 
> https://github.com/alexjustesen/speedtest-tracker/blob/4ff86a9eb6d5465c7cc0b84199b7c452c6687b99/app/Listeners/Mail/SendSpeedtestThresholdNotification.php#L59

Sorry, it seems was no need to send notifications becouse was no thresholds reached for these time, just confused wirh utc time.
But mostly opened issue for influxdb error that was also some days befor with thouse warning
