### ISSUE TITLE
Define CRON as environment variable

### ISSUE THREAD

**Issue by thomaschaplin** [alexjustesen/speedtest-tracker#1392]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a nice to have.

**Describe the solution you'd like**
To be able to define an environment variable such as `CRON` which takes a string so that initial creation doesn't require manually setting the cron in the admin panel

**Additional context**
N/A

**Comment by alexjustesen** [comment]
Thanks for the suggestion, I'll be going a different way with scheduling tests to support multiple tests.
