### ISSUE TITLE
run every 6 hours

### ISSUE THREAD

**Issue by Mr-joep** [alexjustesen/speedtest-tracker#1393]
hey this is not really a bugg, but i want it to run every 6 hours. 
https://crontab.guru/#00_0/6_*_*_*
00 0/6 * * *

but when i put this in it gives me this error:
Cron expression is not valid

can this be addid?
i fix it now whit:
00 0,6,12,18 * * *

**Comment by alexjustesen** [comment]
The correct syntax for that would be `* */6 * * *` to get you "every minute past every 6th hour".

**Comment by Mr-joep** [comment]
Omg, I'm sorry for my small brain moment 😅 
Thx

**Comment by alexjustesen** [comment]
> Omg, I'm sorry for my small brain moment 😅 Thx

It happens, coffee is key
