### ISSUE TITLE
NPM cannot expose to internet

### ISSUE THREAD

**Issue by haxoder** [alexjustesen/speedtest-tracker#1394]
**Describe the bug**
Nginx proxy manager displaying 502 error on speedtest.domain.com. Sometimes is working but 95% it is not and I cannot check my speed when im not home...
All my other sites are exposed to internet like this and every single one is working

**To Reproduce**
/

**Expected behavior**
I should see admin panel of speedtest-tracker

**Environment (please complete the following information):**
 - OS: Proxmox
-  Architecture: amd64
 - Browser: any
 - Version: 0.18.6

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/74647926/d9f61756-5f65-4eed-8032-626dbade4445)

**Logs**
/

**Additional context**
/

**Comment by alexjustesen** [comment]
Did you set `APP_URL` to your public domain?

**Comment by haxoder** [comment]
I did not. Thanks

**Comment by alexjustesen** [comment]
If it's all set, please close the issue.
