### ISSUE TITLE
Errors after every update until cache is cleared

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#1395]
Using latest version of LSIO in Unraid

have .env from original image for mail setting telegram bot etc ..

After every update have errors like : Mail , Telegram Bot etc ...    

When cache cleared and restart container the error is gone !

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/bff8b0c8-f3ea-493c-8104-18f5bb597ff3)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/5e236763-0789-4c81-8b7d-f4c1003ace1d)

**Comment by alexjustesen** [comment]
Can you share your `docker-compose.yml` configs?

**Comment by masterwishx** [comment]
> @masterwishx let's try getting rid of your `.env` by just making it's contents empty. Before you do make sure any vars you care about are moved to the Unraid UI.

Do you mean leave empty file or i can remove it?

**Comment by masterwishx** [comment]
@

> @masterwishx let's try getting rid of your `.env` by just making it's contents empty. Before you do make sure any vars you care about are moved to the Unraid UI.

OK i will check it seems we still need .env file :  https://github.com/linuxserver/docker-speedtest-tracker/blob/aebf75e30897d2d2e442a281e83bc8a74dd51025/root/etc/s6-overlay/s6-rc.d/init-speedtest-tracker-config/run#L65

**Comment by masterwishx** [comment]
@alexjustesen I copyed all important vars to unraid, leaved.env as is, it seems the app reading  container vars instead of.env if they both enabled

**Comment by masterwishx** [comment]
Will see on next update.... If will be OK will close issue

**Comment by alexjustesen** [comment]
Good that's what I'd expect. To simplify the stack I'm considering dropping the .env file for `v0.20.0`.
