### ISSUE TITLE
Pushover Webhook - Test -> OK but notify on Speedtest has no results only {}

### ISSUE THREAD

**Issue by haferm** [alexjustesen/speedtest-tracker#1397]
**Describe the bug**
I am using Notification via Webhook to send a message using pushover api.
While the "Test Webhook Channel" works as expected and confirms URL is correct (see also Screenshot) notify on Speedtest has no results. In Message i can see only {} (see 2nd Screenshot)

**To Reproduce**

1.) Test Webhook Channel" sends following message to pushover client:

![1st](https://github.com/alexjustesen/speedtest-tracker/assets/22625877/826f9d2f-a561-4144-b943-585f26437797)

2.) manual or scheduled speedtest sends following message to pushover client:

![2nd](https://github.com/alexjustesen/speedtest-tracker/assets/22625877/f006ce65-9dd5-480d-92c2-684a95b38dc6)

**Environment (please complete the following information):**
 - OS: Docker image
-  Architecture: amd64
 - Browser chrome
 - Version 0.19.0

**Comment by alexjustesen** [comment]
Pushover isn't supported at the moment, the webhook payload happens to be correct when testing but isn't for real payloads. Pushover expects the content in a `message` param.

Attaching to #40.
