### ISSUE TITLE
Fail to install on Container Error code: s6-rc

### ISSUE THREAD

**Issue by WanKa-zone** [alexjustesen/speedtest-tracker#1403]
**Describe the bug**
Fail to install on Container
Error code: s6-rc

**Environment (please complete the following information):**
 - OS: DSM 7.2.1-69057 Update 3
 - Browser: Google Chrome

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/45703375/3b0f3abc-96c8-4976-a07c-e5178cc145f0)

**Comment by alexjustesen** [comment]
Make sure to follow the install docs, I can tell you're not passing in any DB variables if the framework wants to use the default `forge` database.

**Comment by alexjustesen** [comment]
Can you share your `docker-compose.yml` file?
