### ISSUE TITLE
Feature request: switch to easily and temporarily disable scheduled speedtest

### ISSUE THREAD

**Issue by xathon** [alexjustesen/speedtest-tracker#1406]
**Is your feature request related to a problem? Please describe.**
When I want to upload or download a big amount of data, I want to have all the available bandwidth for that operation, without my scheduled speedtest hugging the wire. 

**Describe the solution you'd like**
I'd love a button on the dashboard to quickly toggle on/off the scheduled speedtest. Maybe even a "Turn of scheduled speedtest for 1 hour/day/week/custom" selector.

**Additional context**
It might be helpful to be able to toggle to send out a notification when the schedule is stopped and resumed.

**Comment by alexjustesen** [comment]
Linking to #1351
