### ISSUE TITLE
[Feature Req] Please utilise text based min / max / avg summary, same as HenryWhittaker version

### ISSUE THREAD

**Issue by jaxjexjox** [alexjustesen/speedtest-tracker#1408]
**Is your feature request related to a problem? Please describe.**
Hi Alex, thanks for the hard work.
Wonder if you could copy this from Henrys version
https://i.imgur.com/favOT5T.png

You've got a nice clear group of 3 boxes up the top of yours and I realise you're doing a better job graphing things but the text summary looks an easy win (IMO)

P.S you're welcome to consider adding that fast-cli engine any time ... it would be amazing. ♥

**Comment by craftcm** [comment]
Agreed - this would be a helpful addition. Thank you for all your energy being dedicated to build this project!

**Comment by bckntme** [comment]
I agree. Would like to have this too.
