### ISSUE TITLE
[Feature Req] Please consider anchoring duration so we don't need to change 4 boxes at a time.

### ISSUE THREAD

**Issue by jaxjexjox** [alexjustesen/speedtest-tracker#1409]
Don't like having to change the date / time range, for 4 boxes, would prefer just one control box, changes all graphs. If possible please.
https://i.imgur.com/udx6MAG.png

Suspect I don't need to elaborate more / provide logs etc, should be clear, I hope.  Sorry.

Thank you.

**Comment by alexjustesen** [comment]
Logged in a previous issue.
