### ISSUE TITLE
Gotify webhoook does not trigger when threshold fails

### ISSUE THREAD

**Issue by novaliswolf** [alexjustesen/speedtest-tracker#1415]
**Describe the bug**
Setting up a webhook for Gotify does not trigger for threshold failures

**To Reproduce**
1. Go to Notifications
2. Under Webhooks check "Enable webhook notifications"
3. Under Triggers check "Notify on threshold failures" 
4. Under Recipients in the Url field set the Gotify app url 
5. Click Test webhook channel

The test will send successfully but will not send when the threshold failure is met

**Expected behavior**
Since the test is working correctly, the expected behaviour is that during a threshold failure the notification webhook would be triggered.

**Environment:**
 - OS: Docker (with postgresql backend)
-  Architecture: amd64
 - Browser: Firefox
 - Version: 0.19.0

**Screenshots**
Gotify test notifications - 
![gotify](https://github.com/alexjustesen/speedtest-tracker/assets/71758174/ee59e22f-ebdc-44ac-ab7f-20781cc4b7bc)

Threshold triggered on database
![threshold](https://github.com/alexjustesen/speedtest-tracker/assets/71758174/a9bf9320-d7b5-4e18-ab40-78729954650c)

**Logs**
No info in container logs by default

**Additional context**
N/A. Happy to provide any more info

**Comment by alexjustesen** [comment]
Gotify is not support at this time, dup of #40 and #1383.
