### ISSUE TITLE
The POST method is not supported for route admin/login. Supported methods: GET, HEAD.

### ISSUE THREAD

**Issue by somera** [alexjustesen/speedtest-tracker#1424]
**Describe the bug**
After upgrade to 0.19.0 I see the Exception in Browser when I try to login.

**Expected behavior**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8334250/04b7ce95-6b05-4013-bdc9-214d0b5e01d6)

**Environment (please complete the following information):**
 - OS: Ubuntu
-  Architecture: amd64
 - Browser: FF 125.0.3 run on Windows 11
 - Version 0.19.0 run in docker on Ubuntu

```
docker run -d --name speedtest-tracker \
    --restart=unless-stopped \
    -p 8765:80 \
    -p 8443:443 \
    -e PUID=1000 \
    -e PGID=1000 \
    -e DB_CONNECTION=pgsql \
    -e DB_HOST=xxx \
    -e DB_PORT=5432 \
    -e DB_DATABASE=xxx \
    -e DB_USERNAME=xxx \
    -e DB_PASSWORD=xxx \
    -e APP_URL=http://xxx:8765 \
    -e APP_KEY=xxx \
    -v /root/docker/speedtest-tracker:/config \
    -v /root/docker/speedtest-tracker/web:/etc/ssl/web \
    lscr.io/linuxserver/speedtest-tracker:latest
```

**Comment by alexjustesen** [comment]
That's new, let's enable debug and see if that gives more hints to the issue. https://docs.speedtest-tracker.dev/help/faqs#im-getting-a-500-or-server-error-error

**Comment by somera** [comment]
I can't reproduce it now. I will take a look in the next days on this.

**Comment by alexjustesen** [comment]
🤷‍♂️ I'm going to close it, should you run into it again feel free to open a new issue and reference this one
