### ISSUE TITLE
Teams Webhook

### ISSUE THREAD

**Issue by ctv99** [alexjustesen/speedtest-tracker#1425]
Webhook is added no errors but also test shows nothing.

am i doing something wrong?

**Comment by ctv99** [comment]
https://learn.microsoft.com/en-us/outlook/actionable-messages/message-card-reference

**Comment by alexjustesen** [comment]
Honest question, who uses teams outside of the enterprise?

Also Teams webhook format isn't supported.

**Comment by ctv99** [comment]
I do for msp

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alexjustesen** [comment]
Makes sense, thanks for the use case. I can't promise when that integration will work at the moment.

**Comment by alexjustesen** [comment]
Linking to #40
