### ISSUE TITLE
Default dashboard period

### ISSUE THREAD

**Issue by zkvvoob** [alexjustesen/speedtest-tracker#1429]
**Is your feature request related to a problem? Please describe.**
Right now, when you change the period of a chart on the dashboard, close the browser tab and open it again, the chart shows the last 24 hours.

**Describe the solution you'd like**
If possible, either save the last selected time period on the dashboard, or add an option in Settings for the user to set a default period.

**Additional context**
When performing speed tests only once a day, the "Last 24h" option on the dashboard is not particularly useful. I'd much rather view the trend over time.

Thank you!

**Comment by alexjustesen** [comment]
Dup of #738
