### ISSUE TITLE
Visualisation of failed speed tests

### ISSUE THREAD

**Issue by JKusber** [alexjustesen/speedtest-tracker#143]
**Describe the bug**
My speedtest is scheduled every hour at :55. Today I had problems with my internet provider, my connection was first slower and then completely collapsed. Of course I wanted to have a look at that in the dashboard.

I noticed that failed speed tests (those during the interruption of the connection) are not displayed at all. If you look at several tests in the table, you might not even notice the leap in time (see screenshot). The tests in between are simply missing.

**To Reproduce**
Not sure if it is possible to repoduce it when you stop your network connection and have no idea how to simulate a provider malfunction.

**Expected behavior**
I would expect the failed tests to be displayed with a warning sign in the table and no speed/server. This way you could also evaluate how many tests failed.

**Screenshots**

![image](https://user-images.githubusercontent.com/12516802/201429641-91e20f25-9290-488c-aad9-ef00fbcb4f54.png)

**Comment by alexjustesen** [comment]
I like this, absolutely a good suggestion and something that should be introduced.

**Comment by alexdelprete** [comment]
I thought we already had something like that (with debug on for now):

![image](https://user-images.githubusercontent.com/7027842/201431368-27ea51be-3d62-42d0-bb31-04e84b6bd821.png)

**Comment by JKusber** [comment]
> I thought we already had something like that (with debug on for now):
> 
> ![image](https://user-images.githubusercontent.com/7027842/201431368-27ea51be-3d62-42d0-bb31-04e84b6bd821.png)

Not sure how to activate this?! In my version I can't find this feature.
But anyway I would suggest to combine it in into one results list.

Thank you for the great project!

**Comment by alexjustesen** [comment]
Failed jobs are different from failed speedtests and should only be used for debugging purposes. Jobs are the Speedtest Tracker trying to do something. 

If the speedtest-cli fails I don't currently capture and report that.

**Comment by alexdelprete** [comment]
so jobs=internal tasks. got it. :)

definitely, we need to capture failed speedtests, I didn't know that was missing.

**Comment by alexjustesen** [comment]
Finally getting to this, you can follow the progress in #318. It's really more work than I had initially thought.
