### ISSUE TITLE
Feature request: eliminate need to click "Run Speedtest" and then click "Ookla speedtest"

### ISSUE THREAD

**Issue by craftcm** [alexjustesen/speedtest-tracker#1434]
**Is your feature request related to a problem? Please describe.**
Just a suggestion for ease of use. In order to run a new speed test on demand, the current UI requires a user to first click the "Run Speedtest" button and then click "Ookla speedtest." This extra click seems unnecessary since Ookla is the only provider currently supported. 

**Describe the solution you'd like**
Clicking on "Run Speedtest" will immediately queue a new speed test without needing to also make a second click. 

**Additional context**
Nothing else. Thank you for your work!

**Comment by alexjustesen** [comment]
This UI pattern is in place so that future speedtest providers can be added.
