### ISSUE TITLE
Started / Failed Entries in Results are Empty

### ISSUE THREAD

**Issue by nwh3365** [alexjustesen/speedtest-tracker#1439]
**Describe the bug**
In the Result list, I have a number of Started / Failed entries.

When I open Started entries, the ID, Created, Service, and Scheduled fields are populated.  Everything else is empty, including the Server Name and Server ID fields.

When I open Failed entries, the ID, Created, and Service fields are populated.  Everything else is empty, including the Server Name and Server ID, and Error Message fields.

I understand results not being populated if an error occurs, but having error messages indicating what went wrong would be helpful.  Having the Server Name and Server ID would be helpful as well if they are available (i.e. the failure didn't occur before they were identified).

I'm not sure if this is a bug, or just a lack of information being populated, but these entries are not particularly helpful for troubleshooting as they currently exist.  Are there detailed logs somewhere on the system (even if not in the UI)?

**To Reproduce**
Click on Results, filter for Started or Failed entries.  As there is no useful information listed on the entries, I do not know what the underlying cause is or how to reproduce it, but I have had 16 occurrences total; 8 within the past 24 hours.  Speedtest Tracker has been running for 50 days.  I'm suspecting it may be an issue with a particular server, but I haven't found a way to confirm that.

**Expected behavior**
I would expect the failure entries to include information indicating the reason for the failure.

**Environment (please complete the following information):**
Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-106-generic x86_64)
Docker version 26.1.1, build 4cf5afa
Speedtest Tracker v0.19.0
Browser = Brave Version 1.66.110 Chromium: 125.0.6422.60 (Official Build) (64-bit)

**Screenshots**
Attached.

**Logs**
None found.
![snap400211](https://github.com/alexjustesen/speedtest-tracker/assets/83049351/0cfb5cbf-cd41-4f1b-a497-68e0c82dbbe8)
![snap400212](https://github.com/alexjustesen/speedtest-tracker/assets/83049351/9c8e0cab-b3cc-4434-9b5f-a34adb511dbc)
![snap400213](https://github.com/alexjustesen/speedtest-tracker/assets/83049351/dc299270-d6f1-4d49-bbd8-3041e72abee1)

**Additional context**

**Comment by sandstheman** [comment]
Seeing the same issue as of this morning, additional to this - the dashboard doesn't reflect the failed tests it just shows that the connection has been running.  Would be useful for failed test to be reflected in the graphs.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/11063135/6c04d439-43a9-49c8-8191-3dac61ca8fdd)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/11063135/00a4f98c-408c-4e7a-b224-3ae4eb7105d5)

**Comment by haythamelkhoja** [comment]
I have the same problem and nothing in logs
