### ISSUE TITLE
Webhooks do not fire on threshold violation

### ISSUE THREAD

**Issue by ionyx0** [alexjustesen/speedtest-tracker#1441]
**Describe the bug**
Webhooks are not triggering on threshold violation.  

**To Reproduce**
1. Set up thresholds that will fail on upload, download, or ping
2. Configure a webhook endpoint and test to confirm working
3. Enable "Notify on threshold failures"
4. Run a speedtest
5. Validate at least one threshold was breached
6. Inspect log file to see the WARNING log line explaining that no thresholds were found

**Expected behavior**
Webhook fires on a threshold breach.

**Environment (please complete the following information):**
 - LinuxServer.io Docker image
 - Version 0.19.0

**Screenshots**
Threshold violation database notification at time of log entry listed below for webhook.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/17012367/c9d04658-e269-4ece-b62b-a56e959da927)

**Logs**
2024-05-25T00:00:34.460930193Z [2024-05-25 00:00:34] production.WARNING: Failed webhook thresholds not found, won't send notification.

**Comment by alexjustesen** [comment]
> **Logs** 2024-05-25T00:00:34.460930193Z [2024-05-25 00:00:34] production.WARNING: Failed webhook thresholds not found, won't send notification.

This error is thrown when webhooks are enabled but there are no destinations provided. Make sure you've added at least one webhook url in the notification channels.

**Comment by ionyx0** [comment]
There is a destination listed.  Testing the webhook works as expected.

**Comment by alexjustesen** [comment]
Yeah Gotify is not supported as a destination even thought it "supports" webhooks they need to be in a specific format. The test one just happens to match it.

#40 for supported notification channels.

**Comment by ionyx0** [comment]
> Yeah Gotify is not supported as a destination even thought it "supports" webhooks they need to be in a specific format. The test one just happens to match it.
> 
> #40 for supported notification channels.

Ok.  I will configure my other webhook destination anyway just to confirm.  I didn't check my Gotify logs to see if there were any entries regarding a malformed request.  From reading the code and the log description, it seems like it's not detecting any threshold violations... Hence the issue report.
