### ISSUE TITLE
[Feature] Allow a SpeedTest to be triggered by external call

### ISSUE THREAD

**Issue by c11umw** [alexjustesen/speedtest-tracker#1447]
**Is your feature request related to a problem? Please describe.**
Our cron is set to run a SpeedTest once an hour.

At night I'm often gaming and at different times. Sometimes just for 30mins, sometimes 6hrs.
I usually play online FPS and when the SpeedTest runs it'll disconnect me from the game servers and pause my game for 5+s with a "Network Buffer" message on the screen before resuming. It's not killed me or my team yet, but nearly... ☠️😄 

If I'm streaming the game then OBS _should_ be able to recover, but there's a chance the server side might drop the connection (yet to be tested)

**Describe the solution you'd like**
We have HomeAssistant running here which pulls in data from your SpeedTest API for a visual on the dashboard of the last result.
( https://community.home-assistant.io/t/speedtest-net-integration-alternative/678211 )

Our HomeAssistant knows when our devices are on, so it would be great if, instead of the cron, Trigger the SpeedTest as a schedule from Home Assistant instead. That way I can set it on the same hourly schedule, but exclude the schedule when gaming.

Possibly call the SpeedTest with an HTTP POST command via HomeAssistant RESTful?:
https://www.home-assistant.io/integrations/rest_command/

If it were implemented then we could in theory also add a "Run Now" button on the dashboard to trigger an ad-hoc speed test.

**Additional context**
Would still be useful to have an external trigger method available so it could be integrated into other technologies, not just HomeAssistant

Thanks
CW

**Comment by alexjustesen** [comment]
Externally triggering a speedtest is planned for the API feature releas.

**Comment by c11umw** [comment]
Thanks.
For now I've rate limited the Proxmox LXC where it runs to 110MB/s (880mbps) which should reserve us at least 50mbps of uninterrupted download bandwidth.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/48920056/bd79878d-88c6-4f34-bc2e-7fed057107d1)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/48920056/289553ca-d773-4ea2-81e0-9da51f5d72a9)

**Comment by Nickduino** [comment]
> Thanks. For now I've rate limited the Proxmox LXC where it runs to 110MB/s (880mbps) which should reserve us at least 50mbps of uninterrupted download bandwidth.

It will work...as long as you have over 110 MB/s of available bandwidth
