### ISSUE TITLE
Download and upload values show wrong speed

### ISSUE THREAD

**Issue by gunpowder62** [alexjustesen/speedtest-tracker#1448]
**Describe the bug**
Speedtest results show wrong values compared to the speedtest by ookla directly
Server name: LrdJx, Frankfurt am Main, Germany

Example
ookla (https://www.speedtest.net/de) speedtest result: Download 907.64 Mbps, Upload 41.34 Mbps
speedtest-tracker result: Download 90.76 Mbps, Upload 4.13 Mbps

**Environment (please complete the following information):**
- OS: Docker image
 - Browser: Safari

**Comment by svenvg93** [comment]
Hi @gunpowder62 , 

If you check the results on the ookla speedtest (Results -> View on Speedtest.net) are the values then correct?

**Comment by gunpowder62** [comment]
Hi svenvg93,

I installed speedest-tracker on another server and all looks good. Sorry for inconvenience. Need to check the server I'm running speedtest-tracker.

**Comment by alexjustesen** [comment]
Closing as this looks resolved.
