### ISSUE TITLE
Save Dashboard

### ISSUE THREAD

**Issue by stan0ne** [alexjustesen/speedtest-tracker#1449]
Hello, I have been using the app for a long time for daily reports.

I don't know how to do it, I want help from you:
I want to save the chart reports monthly in the dashboard, every time I re-enter the app, it goes back to the **24h** setting. I want to set the **24h** setting in the screenshot to **last month** and save it. how do I do this?
![resim](https://github.com/alexjustesen/speedtest-tracker/assets/20106071/0488cb49-8dcb-4f00-bb4c-79544ede1d0e)

**Comment by alexjustesen** [comment]
Attaching to #738

**Comment by D4rkm3ch** [comment]
How has this not been implemented yet?
