### ISSUE TITLE
Time-Format since Update to 0.20.1

### ISSUE THREAD

**Issue by AleksCee** [alexjustesen/speedtest-tracker#1478]
Hi,

in the old gui there was an option to set the time format to 24h now the charts and results only 12h format with am/pm. How can I change it now?

thanks, Alex

**Comment by alexjustesen** [comment]
You can use `DATETIME_FORMAT` to change the format of the displayed dates.

**Comment by AleksCee** [comment]
Ok this works for the results but not for the chart-view.

**Comment by alexjustesen** [comment]
Correct, there wasn't a setting for that.

**Comment by Kostecki** [comment]
So how *does* one get 24h format for the charts? Because that's definitely how my charts were showing before v20.

**Comment by alexjustesen** [comment]
😉 https://github.com/alexjustesen/speedtest-tracker/pull/1480

**Comment by Kostecki** [comment]
Hah, beat me to it. I was just about to submit a PR! I appreciate the quick work 👌
