### ISSUE TITLE
Latest update - Application key missing?

### ISSUE THREAD

**Issue by begunfx** [alexjustesen/speedtest-tracker#1479]
I think the latest release broke.  I don't have the application key set as it's supposed to be option and just a little while ago, the container went down and is now in an unhealthy state.

`version: "3.9"
services:
  db:
    image: postgres:16
    container_name: SpeedTest-Tracker-DB
    hostname: speedtestracker-db
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "speedtest", "-U", "speedtestuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/speedtest/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: speedtest
      POSTGRES_USER: xxxxx
      POSTGRES_PASSWORD: xxxxxx
    restart: on-failure:5

  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker:latest
    container_name: SpeedTest-Tracker
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    environment:
       PUID: xxx
       PGID: xxx
       TZ: America/Los_Angeles
       DB_CONNECTION: pgsql
       DB_HOST: speedtestracker-db
       DB_PORT: 5432
       DB_DATABASE: speedtest
       DB_USERNAME: xxxx
       DB_PASSWORD: xxxxx
      # APP_KEY: Not mandatory. docker exec speedtest-tracker php /app/www/artisan key:generate --show
    volumes:
      - /volume1/docker/speedtest/config:/config:rw
    ports:
      - 8999:80
    restart: unless-stopped`

Logs:

`using keys found in /config/keys
Waiting for DB to be available
An application key is missing, halting init!
You can generate a key at https://speedtest-tracker.dev/.`

**Comment by Jiriteach** [comment]
See Discussions or here - https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0. You need to set an APP_KEY now. You can also get one here - https://speedtest-tracker.dev/

**Comment by begunfx** [comment]
Thanks!  Yeah, after some digging just discovered the discussion.  Thanks @Jiriteach
