### ISSUE TITLE
[Feature Request] Allow for a custom Internal Port

### ISSUE THREAD

**Issue by c11umw** [alexjustesen/speedtest-tracker#1485]
**Is your feature request related to a problem? Please describe.**
If the speedtest Tracker is bundled with other containers routing through another container's network, there can be a port conflict if more than one container tries use the same internal ports.

example: Containers routing through a VPN container, the VPN container manages all the ports
in the speedtest_tracker the network is set as:
`--network=container:vpn \`

**Comment by alexjustesen** [comment]
I think this is at the docker level and not application, can you open the same question in the LSIO repo? Let's see what they say.

https://github.com/linuxserver/docker-speedtest-tracker

**Comment by c11umw** [comment]
Done:  https://github.com/linuxserver/docker-speedtest-tracker/issues/20
