### ISSUE TITLE
Email Test works but speedtest results are not.

### ISSUE THREAD

**Issue by edd080** [alexjustesen/speedtest-tracker#1486]
After updating to  20.0, 20.1, and also now on 20.2 ls27 email reports are not being sent, however when I test the email channel the email is received successfully. The rest is working fine and I have no issues with. What can I check please?
The email is set in my docker-compose.yml file as follows:

services:

    speedtest-tracker:

        container_name: speedtest-tracker

        ports:

            - 443:80

        environment:

            - APP_DEBUG=false

            - APP_NAME=Speedtest-Tracker

            - PUBLIC_DASHBOARD=true

            - PUID=1000

            - PGID=1000

            - APP_KEY=base64:

            - MAIL_MAILER=smtp

            - MAIL_HOST=smtp.me.com

            - MAIL_PORT=465

            - MAIL_USERNAME=me@me.com

            - MAIL_PASSWORD=secret

            - MAIL_ENCRYPTION=SSL

            - MAIL_FROM_ADDRESS="me@me.com"

            - MAIL_FROM_NAME="Speedtest Tracker"

            - APP_TIMEZONE=Europe/Malta

            - DISPLAY_TIMEZONE=Europe/Malta

            - DB_CONNECTION=sqlite

            - SPEEDTEST_SCHEDULE=0 1-23/6 * * *

            - SPEEDTEST_SERVERS=1665

            - APP_URL=https://......

        volumes:

            - ./config:/config

        image: lscr.io/linuxserver/speedtest-tracker:latest

        healthcheck:

            test: curl -fSs https://.......

            interval: 10s

            retries: 3

            start_period: 30s

            timeout: 10s

        restart: unless-stopped

Your help would be appreciated.
Thanks.

**Comment by alexjustesen** [comment]
Nice catch, kind of surprised that hasn't been reported earlier.
