### ISSUE TITLE
Setup months lang

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#1489]
With the following environment parameters

```
 -e APP_TIMEZONE=Europe/Rome \
 -e DISPLAY_TIMEZONE=Europe/Rome \
```

I expected to find the name of the months in Italian in the list of results. 
Is it possible to customize the date format of the results and the language of the months?
Thank you

![Cattura](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/bda8d8bf-7667-45d5-bb5a-60d6c6279d65)

**Comment by svenvg93** [comment]
You can use  `DATETIME_FORMAT` to change the format in the results table and `CHART_DATETIME_FORMAT` to change the format in the charts. 

The format is in php timeformat; https://www.php.net/manual/en/datetime.format.php
I use:

```
            - DATETIME_FORMAT="j M Y, G:i:s"
            - CHART_DATETIME_FORMAT="j M, G:i:s"
```
to get 

<img width="231" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/190ae84f-2169-4c79-9100-7f48a03ceda3">

Remove the year for the charts as it got a bit to long ;)

**Comment by corasaniti** [comment]
@svenvg93 
Thank you :-)
