### ISSUE TITLE
Get an 'Application key is missing' error

### ISSUE THREAD

**Issue by rosarch** [alexjustesen/speedtest-tracker#1497]
**Describe the bug**
Get this error in the logs when trying to start the app

'Using keys found in /config/keys
An application key is missing, halting init!
You can generate a key at https://speedtest-tracker.dev/.'

**To Reproduce**
docker compose up -d

**Expected behavior**
I expected the app to start, I am confused by the error as I thought the use of a key was depreciated according to the docs

**Environment (please complete the following information):**
 - OS: Ubuntu
 - x86_64

**Additional context**
I updated to the latest release today

**Comment by livioh** [comment]
Same here

**Comment by alexjustesen** [comment]
Read the `0.20.0` release requirements.
