### ISSUE TITLE
General Settings menu no longer visible 404 Not Found Error

### ISSUE THREAD

**Issue by landiatico** [alexjustesen/speedtest-tracker#1499]
**Describe the bug**

**To Reproduce**
1. Go to 'Admin Pannel'
2. Click on 'Expand Settings'
3. General option is no longer visible.
4. If accesing /admin/general-page a 404 Not Found page is displayed

**Expected behavior**
General settings on linuxserver/speedtest-tracker:0.20.3 or linuxserver/speedtest-tracker:latest (released 4 hours ago) should work. downgrading to tag version-v0.20.2 and version-v0.20.1 and version-v0.20.0 with same problem.

**Environment (please complete the following information):**
 - OS: Ubuntu docker
-  Architecture: amd64
 - Version: 0.20.3 aka latest

**Screenshots**
<img width="360" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/41938073/1b0651f6-2393-478a-8b5c-fcccf70e919d">

**Additional context**

**Comment by svenvg93** [comment]
As of v0.20.x the General admin page is replaced with the environment variables only. The page does not exist anymore. see https://github.com/alexjustesen/speedtest-tracker/discussions/1470 and https://github.com/alexjustesen/speedtest-tracker/pull/1464

**Comment by landiatico** [comment]
Thanks @svenvg93 , so the problem is the documentation and that people like me using :latest tag did not recieve any warning or notification saying that.

Docs (https://docs.speedtest-tracker.dev/getting-started/installation and github) do not show the new env variables thus I had to downgrade to version-v0.19.0 for it to work, only linuxserver site has the env listed but no warning message instructing the user to create those env variables.

**Comment by alexjustesen** [comment]
> Thanks @svenvg93 , so the problem is the documentation and that people like me using :latest tag did not recieve any warning or notification saying that.

It's always my recommendation to not use `:latest` if you don't follow/keep up with changes this way you're not caught out when breaking changes occur. It's always good home lab hygiene is to keep tabs on the services you use.
