### ISSUE TITLE
new install v0.20.3 -> Could not resolve host.

### ISSUE THREAD

**Issue by KGBist2000** [alexjustesen/speedtest-tracker#1501]
**Describe the bug**
New Clean install v0.20.3. A speedtest is failed everytime by following error. "Could not resolve host."
Container is started well without any issues. From container bash i can reach the internet by ping google.com without any issues.

**To Reproduce**
1. Go to 'Admin Page'
2. Click on 'Run Speedtest'
3. See error -> Could not resolve host.

**Expected behavior**
Start speedtest

**Environment (please complete the following information):**
 - OS: Proxmox LXC, Portainer Docker
-  Architecture: [ amd64]
 - Browser [firefox]
 - Version [v0.20.3]

**Docker Compose**

version: '3.4'
services:
    speedtest-tracker:
        container_name: speedtest-tracker-new
        ports:
            - 5443:80
            #- 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:----- replaced ------
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE="9 * * * *"
            - SPEEDTEST_SERVERS="53128,48042,31469"
            - APP_TIMEZONE=Europe/Berlin
            - DISPLAY_TIMEZONE=Europe/Berlin
            - TZ=Europe/Berlin
            - APP_NAME="Speedtest"
            - PUBLIC_DASHBOARD=false
        volumes:
            - /root/speedtest_tracker:/config
            #- /path/to-custom-ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped

**Comment by bigrichwood** [comment]
Same with my container which was upgraded a few hours ago from 0.19.0 to 0.20.3. Connectivity looks fine from within the container, but all tests fail with “could not resolve host”.

I’ve rolled back to 0.19.0 which works perfectly, and I’ll just leave it pinned to that version as it does everything I need.

**Comment by c11umw** [comment]
I wondered why it stopped working today.... that'll be it (watchtower auto-update)
From within the container I could successfully nslookup domains, run the php command to see the closest servers and curl ipinfo to see my WAN IP. 

Forced 0.20.2 and it started working again

**Comment by c11umw** [comment]
Tested. Still failed :(
![image](https://github.com/alexjustesen/speedtest-tracker/assets/48920056/a322b0cf-0155-4e68-be0d-89d7ca6aa1e8)

```
docker run -d \
--name=speedtest_tracker \
-e PUID=1000 \
-e PGID=1000 \
-e SPEEDTEST_SCHEDULE="26 * * * *" \
-e SPEEDTEST_PING_URL=1.1.1.1 \
-e PRUNE_RESULTS_OLDER_THAN=30 \
-e DB_CONNECTION=sqlite \
-e APP_KEY=base64:BxTsckohrV35/sGUhb3UzNwUIJQj/02R8YfD7xyootY= \
-e TZ=Europe/London \
-v /home/docker/config/speedtest_tracker:/config \
--restart=always \
lscr.io/linuxserver/speedtest-tracker:latest
```

**Comment by ckbaxter** [comment]
I can confirm the issue, I tested with vaeious settings and nothing work:
SPEEDTEST_PING_URL=1.1.1.1
SPEEDTEST_PING_URL=heise.de
SPEEDTEST_PING_URL=8.8.8.8

I switch back to v0.20.2…this version works fine for me
