### ISSUE TITLE
Docker Environment Variables for defining thresholds and notifications

### ISSUE THREAD

**Issue by armond-avanes** [alexjustesen/speedtest-tracker#1502]
**Is your feature request related to a problem? Please describe.**
Yes. I have my entire homelab setup automated by Ansible (all docker containers); but one of the things that I need to do manually after the setup, is to launch Speedtest-Tracker web interface and to manually define my thresholds and notifications which is a pain.

**Describe the solution you'd like**
It would be great if the thresholds and notifications could be defined as docker environment variables (at least as initial values which can be later changed in the web UI).

**Comment by armond-avanes** [comment]
@alexjustesen @svenvg93 Thank you so much for adding the support for threshold environment variables. This is a great step ahead toward having a completely automated setup. I appreciate the effort.

Just two quick points here:
- The PR for updating the docs (https://github.com/alexjustesen/speedtest-tracker-docs/pull/55) has been closed without being merged, so the docs are not updated.
- One other aspect of this issue was to have environment variables for setting up notifications, which is still not implemented. I can also create a separate issue only for this part. Just please let me know.

**Comment by alexjustesen** [comment]
> One other aspect of this issue was to have environment variables for setting up notifications, which is still not implemented. I can also create a separate issue only for this part. Just please let me know.

For this we're avoiding it for the time being. I'm trying to assess if I want to split out this project into two implementations. A "UI" version and a "headless" version. Obviously this would have a massive impact to how notifications would be handled and works into the assessment for implementing Apprise discussed in #1961.

**Comment by armond-avanes** [comment]
@alexjustesen Thanks for the update. That's great to see it's still on the roadmap. Yes, I understand the complications. But I'm very happy to learn that you're seriously considering Apprise. I'm a heavy user of that framework/API.

**Comment by svenvg93** [comment]
> * The PR for updating the docs ([Add environment variables for the thresholds speedtest-tracker-docs#55](https://github.com/alexjustesen/speedtest-tracker-docs/pull/55)) has been closed without being merged, so the docs are not updated.
UPDATE: Never mind. I just noticed that there is a new PR for this: [Add environment variables for the thresholds speedtest-tracker-docs#58](https://github.com/alexjustesen/speedtest-tracker-docs/pull/58)

I had to close the first one as there were some conflicts after merging another PR. As the markdown of gitbook makes it hard to solve this in git 😅 So it was easier to close it and make a new one 😄
