### ISSUE TITLE
v0.20.3: Timezone not working as documented

### ISSUE THREAD

**Issue by alexdelprete** [alexjustesen/speedtest-tracker#1503]
**Describe the bug**
Results are UTC based, despite setting TimeZone to local timezone.

**To Reproduce**
1. Set PostgreSQL to local timezone (Europe/Rome in my case)
2. Set env in docker compose like this:
      - APP_TIMEZONE="Europe/Rome"
      - DISPLAY_TIMEZONE="Europe/Rome"
4. Run some tests
5. See this result: as you can see from the screenshot, times are 2h behind (like it was UTC). Furthermore, the "next speedtest" is shown ignoring DISPLAY_TIMEZONE setting and same goes for results page.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/7b311101-fe23-421e-adc2-36bc3054e44a)

**Expected behavior**
I expect times to show in local timezone

**Environment (please complete the following information):**
 - OS: Debian 12
-  Architecture: amd64
 - Browser Edge
 - Version: v0.20.3

**Comment by alexdelprete** [comment]
Update: I just ran a manual test, and the time is correct for this one (time format is still wrong), but for past tests, times are in UTC.

Last test was a few minutes ago, at 11.25pm, now I ran the manual test and it shows 11.47, but previous test shows 9.25pm while it should be 11.25pm.

Display time format is still wrong.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/da2716d4-7beb-4dc8-9696-0aed6d9209df)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/c24e9f6f-3c34-4c81-a5f6-81fa40b78a68)

**Comment by alexjustesen** [comment]
You can change the table timestamp formats using `DATETIME_FORMAT` and chats with `CHART_DATETIME_FORMAT`. Format params can also be found here: https://www.php.net/manual/en/datetime.format.php

Also if you're using `TZ` environment variable in the app container make sure to remove that.

**Comment by alexdelprete** [comment]
Removed TZ: past tests still show with wrong timestamps: 

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/569dcb75-987e-42ea-8725-0b7d53c22098)

**Comment by svenvg93** [comment]
Seem to be the same as I had in https://github.com/alexjustesen/speedtest-tracker/issues/1487

**Comment by alexdelprete** [comment]
> Seem to be the same as I had in https://github.com/alexjustesen/speedtest-tracker/issues/1487 

It will always be a problem, because queries to the db assume the db is in UTC. So all these configuration variables are only workarounds.

It's been discussed a lot in the past, and we're still there.

**Comment by paagundu** [comment]
I don't know if its a fix or workaround, I have these in my `docker-compose.yml` using sqlite db. Now it shows correct scheduled time, and correct time when I run an unscheduled speedtest.

```
- TZ="Asia/Kolkata"
- APP_TIMEZONE="Asia/Kolkata"
- DISPLAY_TIMEZONE="Asia/Kolkata"
```

**Comment by graphixillusion** [comment]
I have the exact same problem: the time is 2h behind the correct time. I have set these two env under the main section:

APP_TIMEZONE="Europe/Rome"
DISPLAY_TIMEZONE="Europe/Rome"

and this one under the mariadb10 section:

TZ="Europe/Rome"

Any way to fix this?

**Comment by mcdoubleyou** [comment]
> You can change the table timestamp formats using `DATETIME_FORMAT` and chats with `CHART_DATETIME_FORMAT`. Format params can also be found here: https://www.php.net/manual/en/datetime.format.php
> 
> Also if you're using `TZ` environment variable in the app container make sure to remove that.

Hey, I'm looking for the same.
I prefer the 24h format.

So I need to set: DATETIME_FORMAT="d.m.Y H"

Thanks!

**Comment by svenvg93** [comment]
> "d.m.Y H"

This one will just show `11.07.2024 18` as date. If thats what you want yess :) 
Might want to add `:i`to get also the minutes `11.07.2024 18:06`

**Comment by bwirt** [comment]
I had some confusion around this as well.  For me, what worked:
- Ensure app and db components are using UTC (sh into containers, "date")
- Do not set TZ or APP_TIMEZONE in your docker compose
- Set DISPLAY_TIMEZONE to your local time zone

Now current and past results show properly in the UI.

**Comment by Maximilian-Pichler** [comment]
> I had some confusion around this as well. For me, what worked:
> 
>     * Ensure app and db components are using UTC (sh into containers, "date")
> 
>     * Do not set TZ or APP_TIMEZONE in your docker compose
> 
>     * Set DISPLAY_TIMEZONE to your local time zone
> 
> 
> Now current and past results show properly in the UI.

This fixed it for me

**Comment by Node815** [comment]
Came here to say @Maximilian-Pichler's solution worked for me.
