### ISSUE TITLE
500 Oops, server error!

### ISSUE THREAD

**Issue by ZoltrixGFC** [alexjustesen/speedtest-tracker#1505]
**Describe the bug**
After upgrading to v0.20.3-ls28, Speedtest Tracker now just shows a 500 error when trying to launch it.

**To Reproduce**
1. Upgrade to v0.20.3-ls28
2. Open website

**Expected behavior**
Website to load.

**Environment (please complete the following information):**
 - OS: Docker
-  Architecture: x86
 - Browser Firefox
 - Version v0.20.3-ls28

**Screenshots**
![Screenshot 2024-06-09 184132](https://github.com/alexjustesen/speedtest-tracker/assets/77313738/a645b804-120f-4aa0-9de4-d4bc41ed9a61)

**Logs**
```
**** The following active confs have different version dates than the samples that are shipped. ****

**** This may be due to user customization or an update to the samples. ****

**** You should compare the following files to the samples in the same folder and update them. ****

**** Use the link at the top of the file to view the changelog. ****

┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐

│  old date  │  new date  │ path                                                                   │

├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤

│ 2023-04-13 │ 2024-05-28 │ /config/nginx/site-confs/default.conf                                  │

│ 2023-04-13 │ 2024-05-27 │ /config/nginx/nginx.conf                                               │

└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘

[custom-init] No custom files found, skipping...

[ls.io-init] done.

nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:7

nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:8
```

**Additional context**
Have looked at the nginx.conf file, but unsure what I am meant to be changing?

**Comment by svenvg93** [comment]
Can you post your `docker-compose` file so we can check the config. 

With 0.20.x some changes are needed to make it work with the new version see https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0

**Comment by ZoltrixGFC** [comment]
I created the container manually in Portainer, so don't have a compose file (that I know of).

But I've added some screenshots to show the config.

![Screenshot 2024-06-09 202357](https://github.com/alexjustesen/speedtest-tracker/assets/77313738/d1a4dfbc-f39f-48f5-98c2-a0ef9bd1428a)
![Screenshot 2024-06-09 202419](https://github.com/alexjustesen/speedtest-tracker/assets/77313738/4ef88421-a7d4-4310-8372-49ac74c15ddc)
![Screenshot 2024-06-09 202442](https://github.com/alexjustesen/speedtest-tracker/assets/77313738/fa980866-4a3f-4d3f-a9a3-2ceb29193a90)

**Comment by alexjustesen** [comment]
First thing let's get rid of the `=` before `base64` in your `APP_KEY` and restart the container after you've updated that.

If that doesn't work follow these steps to enable debug mode to get more verbose logs: https://docs.speedtest-tracker.dev/help/faqs#im-getting-a-500-or-server-error-error

**Comment by ZoltrixGFC** [comment]
@alexjustesen thanks for the help. Removing = fixed the issue. Sorry, what a silly mistake 😮
