### ISSUE TITLE
v0.20.3-ls28 Docker image, SPEEDTEST_SCHEDULE not working

### ISSUE THREAD

**Issue by janreinhardt** [alexjustesen/speedtest-tracker#1506]
**Describe the bug**
Docker run setup of the latest version does not accept the SPEEDTEST_SCHEDULE environment variable. Please see yellow markings in the screenshot below.
Without it, the Docker run command perfectly works and spins up the container. (The error message doesnt match the cause i.e. the environment variable, as it looks to me)

**To Reproduce**

![IMG_1792](https://github.com/alexjustesen/speedtest-tracker/assets/949587/8fe09559-ccdb-4ab4-87b5-447bb45f037d)

**Expected behavior**
Spin up the container, do a speedtest hourly at 15 min past

**Environment (please complete the following information):**
see screenie

**Comment by alexjustesen** [comment]
See if wrapping your cron in double quotes fixes it, `"15 * * * *" \`

**Comment by janreinhardt** [comment]
Yes! 
Works perfectly now. 

Thank you, Alex!
