### ISSUE TITLE
include white bunny logo as favicon in Docker image

### ISSUE THREAD

**Issue by janreinhardt** [alexjustesen/speedtest-tracker#1512]
**Is your feature request related to a problem? Please describe.**
When opening multiple tabs in my Safari browser, I navigate around by the favicons of each tab.
As of now, the Docker image uses a green laser / chart- thingy for speedtest-tracker.

**Describe the solution you'd like**
Same as https://speedtest-tracker.dev/ does: make the Docker container use the white bunny as logo i.e. favicon

**Comment by alexjustesen** [comment]
I think that might be some browser caching as the favicon is set in the application.

Ref: https://github.com/alexjustesen/speedtest-tracker/blob/main/public/favicon.ico

**Comment by janreinhardt** [comment]
yes, youre right. I tried to rule this out before posting here: hit refresh a dozen times. Cleared the browser cache. But Safari on iOS keeps on misbehaving (!).
Tried with Google Chrome now, works as it should.

**Comment by alexjustesen** [comment]
Safari is the new IE
