### ISSUE TITLE
general-page missing

### ISSUE THREAD

**Issue by eBeyond** [alexjustesen/speedtest-tracker#1524]
**Describe the bug**
Under Settings the General page isn't shown. Only Influx, Notifications and Thresholds are shown.

**To Reproduce**
I've changed the default admin-user with my own email. The name is still "Admin" and the role is still "admin".
When I logged in the general isn't visible. I've done the changes a few days ago and it was working then. But now (after an update) it's not shown anymore.
I think it's the only reason, as I haven't changed anything else :D. (Except the update)

**Expected behavior**
I can see the general page and do my settings.

**Environment (please complete the following information):**
 - OS: Ubuntu (docker)
-  Architecture: amd64
 - Browser chrome and firefox
 - Version 0.20.5

**Screenshots**
![Bildschirmfoto 2024-06-12 um 09 12 48](https://github.com/alexjustesen/speedtest-tracker/assets/380468/e57f13e9-4339-427a-8410-f64cc0f52a31)

**Logs**
The logs aren't showing any errors or warnings.

**Comment by svenvg93** [comment]
The General page has been remove and is replaced with env, as of version 0.20. 
See https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0 for more information

**Comment by eBeyond** [comment]
I've got a script which is updating the images automatically. But I had expected that breaking changes would follow the semver specs. Means: breaking changes would cause an update of the major number not just the minor version number.
Ref: point 1 on [semver.org](https://semver.org/)
