### ISSUE TITLE
production.ERROR: Undefined variable $event (Failed Telegram,Mail,Discord thresholds not found)

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#1528]
Using lasted LSIO version in docker in Unraid

moved all env vars to docker vars
have same version with same settings in ubuntu vps (docker compose) portainer  without same issue,also cleared cache but after some time got same error.

After last update 0.20.5 have error:  

`production.ERROR: Undefined variable $event {"exception":"[object] (ErrorException(code: 0): Undefined variable $event at /app/www/app/Mail/SpeedtestThresholdMail.php:51)`

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/75392b96-f09a-4d67-a75f-02acda6fd3ad)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/b72412c2-2f75-4beb-b811-5dd8db8e46ed)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/71f3ca2b-58fa-46db-be39-366f9bb2c1a3)

**Comment by alexjustesen** [comment]
Fixed in #1521 and will be in the next release.

**Comment by masterwishx** [comment]
> Fixed in #1521 and will be in the next release.

Thanks for super speed

**Comment by masterwishx** [comment]
Oh it was already fixed ...

**Comment by alexjustesen** [comment]
Yeah I fixed it, then broke it now it's been re-re-fixed
