### ISSUE TITLE
Discord Notifications failing

### ISSUE THREAD

**Issue by NCVito** [alexjustesen/speedtest-tracker#1529]
**Describe the bug**
After adding discord webhook URL under notifications, no notification is sent to discord.

**To Reproduce**
1. Go to notificaions
2. Enable Discord
3. Add Discord server webhook from discord account
4. click save
5. click test.
6. No notification on discord.
7. Run Speed test
8. No notification on Discord

**Expected behavior**
A message should be sent to my Discord server with the result of the most recently completed speed test.

**Environment (please complete the following information):**
 - OS: Docker on Raspberry PI
-  Architecture: ARM
 - Browser Firefox
 - Version 20.5

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by svenvg93** [comment]
Was there any container logs when triggering the test notifications? 
Just tested on mine running 0.20.5 as well and test notification is delivered as it should be.

**Comment by NCVito** [comment]
Having some trouble locating anything in any logs. Watching the output via portainer shows me nothing out of the ordinary.

**Comment by svenvg93** [comment]
Can you enable debug by adding `APP_DEBUG=true` to the environment  variables. Restart the container. Maybe it will show something more then.

**Comment by NCVito** [comment]
No additional output with that env variable set

**Comment by alexjustesen** [comment]
If you have debug enable make sure you're viewing the console of the container for the log or checkout `/app/www/storage/logs/laravel.log` for additional outputs.

**Comment by NCVito** [comment]
That log is completely empty.

**Comment by alexjustesen** [comment]
Have you tried restarting the container after saving the Discord configs?

**Comment by NCVito** [comment]
Yes, gave that a shot, no luck there. I love this tool you've built so I may just go with another clean install to see if that clears up the issue.

**Comment by svenvg93** [comment]
Does the webhook url work at all? Do you use it for example for other apps as well for example,  If not you can test it here https://toolscord.com/webhook. Just to double check everything ;)

**Comment by NCVito** [comment]
The webhook url looks like it works right using that tool(BTW thanks for showing me that, what a cool site!).

**Comment by NCVito** [comment]
Turns out it was  due to  the container being on its own network. Once it was moved to the bridge network, it was able to send notifications to Discord. 

Thank you all for your help
