### ISSUE TITLE
Maybe a cli or tracker bug

### ISSUE THREAD

**Issue by leufrasiojunior** [alexjustesen/speedtest-tracker#1545]
I don't think it's a bug per se, but rather a problem with the speedtest itself. Some results have a packet loss value with the quantity, for example 1.0204081632653061. According to the documentation of the metrics used, the packet loss value refers to the percentage of packets lost in relation to those sent. If that's really the case, it doesn't make sense that it's 102.04% of the packets sent. Can anyone confirm this value for me?

**Comment by svenvg93** [comment]
Something similar was fixed in the last release for telegram https://github.com/alexjustesen/speedtest-tracker/issues/1488 
Do you see this in a notification or in the results table? 

I think it should be 1.02%  packet loss in your example.

**Comment by alexjustesen** [comment]
Also which notification channel was this in?

**Comment by alexjustesen** [comment]
That view needs some rounding on the value for sure. I _might_ have time tomorrow morning depending how far into the beer fridge I get tonight.
