### ISSUE TITLE
Forgotten Password

### ISSUE THREAD

**Issue by BigJazzz** [alexjustesen/speedtest-tracker#1546]
I can't seem to see any information on this, however any useful links are welcomed.

I have my username and password stored in a password manager, yet when I went to login today, it said my credentials were incorrect. I can't seem to find a way to reset my password/user account (short of trashing the container data and starting again). Is there a way to achieve this without going nuclear?

**Comment by svenvg93** [comment]
Hi! You can reset you password via these steps:

1. Go to container CLI
2. Make sure your in `/app/www`
3. Run command: `php artisan app:reset-user-password myemail@gmail.com`

**Comment by HuckleberryLovesYou** [comment]
To get all email addresses of users you can follow these steps (if you use sqlite3 as a database):
> [!NOTE]
> Execute on host, NOT in Container CLI
1. On your host, navigate into the directory of the  `database.sqlite` file in your container data e.g.
```bash
cd /root/docker-data/speedtesttracker/
```
2. Execute the following command to open the database:
```bash
apt install sqlite3 && sqlite3 database.sqlite
```
3. Now, query all emails:
```sql
SELECT email FROM users;
```
The output should look like the following:
```
admin@example.com
user@example.com
```
