### ISSUE TITLE
After update: Error message Halt init!

### ISSUE THREAD

**Issue by FreddieOnly** [alexjustesen/speedtest-tracker#1547]
After updating to latest version speedtest did not start.
The error message in the logs: An application key is missing, halting init!

**To Reproduce**
update: docker container stepped
docker container recreate pull the latest image
docker container was succesfully installed and is running
cannot reach speedtest see error message

**Expected behavior**
that speedtest is working and can be reached

**Environment (please complete the following information):**
 - OS: synology linux
-  Architecture: ?
 - Browser chrome
 - Version [latest]

**Screenshots**

![Speedtest-logfile](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/f5f475e7-2a93-444d-9d37-47a1cd5eac93)

**Logs**
If applicable, check the logs for any error that might of occurred.

**Comment by svenvg93** [comment]
As the screenshot shows there is no application key set. 
As of the new version you need to set the key in the env of the docker compose. 
See https://github.com/alexjustesen/speedtest-tracker/discussions/1470 for more information.

**Comment by alexjustesen** [comment]
`v0.20.0` require an `APP_KEY`, here's the release notes.

https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0
