### ISSUE TITLE
Time Zone list only showing african countries

### ISSUE THREAD

**Issue by Flyingfufu** [alexjustesen/speedtest-tracker#155]
**Describe the bug**
Time Zone list only shows UTC or African country list. Not possible to select any other country.

**To Reproduce**
1. Go to 'General' / 'Site settings'
2. Click on 'Timezone' drop menu
3. Scroll down ... Not possible to get anything else than UTC or African countries

**Expected behavior**

Get full list of countries

**Environment (please complete the following information):**
 - OS: Docker
-  Architecture: amd64
 - Browser: edge canary / edge / brave
 - Version: latest

**Comment by alexdelprete** [comment]
Did you try typing in the input box?

![image](https://user-images.githubusercontent.com/7027842/201771413-01b65924-84aa-439f-a105-8d3f142d3711.png)

**Comment by Flyingfufu** [comment]
Good catch. I didn't as I saw the list, therefore only tried to scroll without success.

Got the right country by typing, but in my opinion, it is confusing right now getting the african countries straight on the drop down list but not getting the full selection. It should either give the full list or be noticed in the instructions that we should type the needed one (unless I've missed it, I didn't saw this mentionned)

Anyhow, thanks for this prompt feedback.

**Comment by alexdelprete** [comment]
> Good catch. I didn't as I saw the list, therefore only tried to scroll without success.
> 
> Got the right country by typing, but in my opinion, it is confusing right now getting the african countries straight on the drop down list but not getting the full selection. It should either give the full list or be noticed in the instructions that we should type the needed one (unless I've missed it, I didn't saw this mentionned)
> 
> Anyhow, thanks for this prompt feedback.

I think it's done for performance reasons: the javascript pulls up the first X countries in alphabetical order, if it had to pull up all countries you would notice a lag, on slower devices.

I think it's pretty intuitive, maybe the input box could be highlighted just to catch the eye.
