### ISSUE TITLE
Healthcheck.io integration

### ISSUE THREAD

**Issue by TheGroundZero** [alexjustesen/speedtest-tracker#1556]
**Is your feature request related to a problem? Please describe.**

I'd like to use healthcheck.io to monitor both speedtest runs and treshold failures.
Currently the Webhooks integration can only be used for one of both.
You either ping the webhook on any speedtest, which -- by using the period and grace time settings in healthchecks.io -- will warn you of speedtests not being executed; or you ping the fail webhook on treshold failures but then healthchecks.io will complain about not having received pings.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/2406013/5d4a3824-e79e-4f82-8131-8aa0911f3639)

**Describe the solution you'd like**

An extra integration for Healthchecks.io or an adaptation of the Webhooks integration that allows you to enter 2 seperate URLs for (a) speedtest runs and (b) treshold failures.

**Additional context**

Speedtest runs would ping `https://hc-ping.com/<your-slug>` while treshold failures would ping `https://hc-ping.com/<your-slug>/fail`

https://healthchecks.io/docs/signaling_failures/

**Comment by svenvg93** [comment]
Hi @TheGroundZero, 
I have been working on this. For now for the threshold it will add the /fail by default on the set url. No need to set two urls 

<img width="702" alt="Scherm­afbeelding 2024-06-22 om 17 14 02" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/110a73f5-9999-4097-b091-082e2a6485cc">

How it will look in HeathCheck;
Threshold:
<img width="863" alt="Scherm­afbeelding 2024-06-22 om 17 12 20" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/491b7e37-6429-43ce-ac64-36c5712dfd7b">

Normal Complete:
<img width="864" alt="Scherm­afbeelding 2024-06-22 om 17 11 42" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/e3373f0d-41a7-4d45-aa0e-3b6b5ce82528">

Only thing I noticed while testing is that the threshold notification is slightly faster than the completed one, when both are enabled. Which makes it that the mail is not sent to the user by HealthChecks.io. Not sure this is a big deal. 


<img width="1114" alt="Scherm­afbeelding 2024-06-22 om 17 17 54" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/9156a19d-76b0-4adb-801e-733862551897">

**Comment by TheGroundZero** [comment]
Hmmm, ideally the "heartbeet" would be sent at the end of the speedtest. If success -> regular webhook, if there's any error -> `/fail` endpoint.  
This does change the semantics of the webhook as currently it's sent at the launch of the speedtest regardless of what happens during the speedtest.

If you prefer to keep the current order (webhook at start of speedtest, `/fail` on error), it'd be best to add some logic that ensures the fail is always sent _after_ the original webhook.

**Comment by svenvg93** [comment]
Currently there are only two notifications;
- Completed speedtes:t  the results at the end of the test. 
- Threshold breach: the results of the breached test. 

(There is no notification if the speedtest fails for some reason, it is on the wishlist tho https://github.com/alexjustesen/speedtest-tracker/issues/1317)  

I will check if I can have the Threshold  to be sent after the completed speedtest.

**Comment by alexjustesen** [comment]
@svenvg93 if you want to skip the failed notification for now I'll add that separately for `0.21.0`

**Comment by viharm** [comment]
Sorry for posting on a closed item. Does this support the use of self-hosted HC services, which use a self-signed certificate? I mapped my custom CA cert file to /etc/ssl/certs/custom.ca.pem, but I'm not getting a ping. When I try to access the self-hosted HC with curl from inside the container, curl fails cert verification. Is there a way to specify custom CA certs? Or are is there a way to debug? Setting APP_DEBUG=true did not provide any additional detials in the log. I couldn't find any other debug mechanism in the docs.

**Comment by TheGroundZero** [comment]
> Sorry for posting on a closed item. Does this support the use of self-hosted HC services, which use a self-signed certificate? I mapped my custom CA cert file to /etc/ssl/certs/custom.ca.pem, but I'm not getting a ping. When I try to access the self-hosted HC with curl from inside the container, curl fails cert verification. Is there a way to specify custom CA certs? Or are is there a way to debug? Setting APP_DEBUG=true did not provide any additional detials in the log. I couldn't find any other debug mechanism in the docs.

It's best to create a separate Issue/Feature Request for this instead of bumping a closed one
