### ISSUE TITLE
Upload Graph Isssue

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#1562]
I have customized the following pages inside container and mapped this pages in Docker volume
```
/app/www/app/Filament/Widgets/RecentDownloadChartWidget.php
/app/www/app/Filament/Widgets/RecentUploadChartWidget.php
```
by changing the beginAtZero flag as shown below in the `getOptions()` function

`'beginAtZero' => false,`

The Download graph is shown correctly, but the Upload graph remains flat and appears to continue begin from ZERO. See below
Is there anything else I can change?
Thanks in advance

![Cattura](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/5a83feb8-49fe-40bf-a98e-82e2109e11cf)

**Comment by svenvg93** [comment]
I made the same change in my test version and it works there when changing the value to false 

<img width="1076" alt="Scherm­afbeelding 2024-06-22 om 21 38 31" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/0b1ce3d1-2b28-4d54-bd56-5f84bd53524d">

**Comment by corasaniti** [comment]
@svenvg93 
on what architecture? I amd64

**Comment by svenvg93** [comment]
@corasaniti Same here. 
If you look into the container is the adjusted file there as well or just the default one. 

Ps: this might be better to be checked in a Discussions. As it's not really a problem with the application directly  😉

**Comment by corasaniti** [comment]
@svenvg93 

OK I apologize. I understand the error is in the file mapping inside the container. 
The "p" was missing in the RecentUploadChartWidget file name

Before
```
 -v ${PWD}/custom/RecentDownloadChartWidget.php:/app/www/app/Filament/Widgets/RecentDownloadChartWidget.php \
 -v ${PWD}/custom/RecentUploadChartWidget.php:/app/www/app/Filament/Widgets/RecentUploadChartWidget.ph \
```
 
 Now
```
 -v ${PWD}/custom/RecentDownloadChartWidget.php:/app/www/app/Filament/Widgets/RecentDownloadChartWidget.php \
 -v ${PWD}/custom/RecentUploadChartWidget.php:/app/www/app/Filament/Widgets/RecentUploadChartWidget.php \
```

I closed this issue
Thanks

**Comment by svenvg93** [comment]
@corasaniti  Glad you were able to solve it! No worries, happy to help out!
