### ISSUE TITLE
Server ID not working on Kubernetes

### ISSUE THREAD

**Issue by amaurydetremerie** [alexjustesen/speedtest-tracker#1564]
**Describe the bug**
When a test is started, nothing happend. Scheduled or manually triggered. Status always shown as started.
Maybe an error in the configuration

**To Reproduce**
Use this Kubernetes Deployment : 
`apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: speedtest-tracker
  name: speedtest-tracker
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:0.20.7
          ports:
            - containerPort: 80
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: APP_KEY
              value: <api-key>
            - name: APP_URL
              value: <app_url>
            - name: DISPLAY_TIMEZONE
              value: UTC
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: <db_host>
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: <db_name>
            - name: DB_USERNAME
              value: <db_user>
            - name: DB_PASSWORD
              value: <db_password>
            - name: PRUNE_RESULTS_OLDER_THAN
              value: "30"
            - name: SPEEDTEST_SCHEDULE
              value: "0 * * * *"
            - name: SPEEDTEST_SERVERS
              value: "63249,45280,30594,59333,5151,2848,54889"
            - name: APP_DEBUG
              value: "True"

          volumeMounts:
            - name: empty-dir-speedtest-tracker-volume
              mountPath: /config
      volumes:
        - name: empty-dir-speedtest-tracker-volume
          emptyDir:
            sizeLimit: 5Gi`

**Expected behavior**
That it work

**Environment (please complete the following information):**
 - OS: Kubernetes (K3S) in a Debian VM on a Proxmox Host
-  Architecture: amd64
 - Browser chrome
 - Version Tried with 19.0, 20.0, 20.5, 20.6, 20.7

**Screenshots**
![Capture d’écran 2024-06-23 000232](https://github.com/alexjustesen/speedtest-tracker/assets/71339304/d4eb2ce2-7494-4f8b-a18b-df41deb8e898)

**Additional context**
I've tried to remove the SPEEDTEST_SERVERS env, to set it to null, with one server

**Comment by alexjustesen** [comment]
`APP_KEY` is just omitted for security right? Also if you're using an external DB (i.e. not SQLite) you no longer need to mount a volume.

**Comment by amaurydetremerie** [comment]
It's omitted because I use Vault for my secrets and I didn't want to create any confusion. You can find the full yaml [here](https://github.com/amaurydetremerie/HomeLab/blob/main/Kubernetes/K3S/SpeedtestTracker/speedtestTracker.yaml) if you like

**Comment by alexjustesen** [comment]
With debug enabled you should see any errors in the logs at the application level, also do you have any way to extract logs from your k8s cluster?

**Comment by amaurydetremerie** [comment]
Of course, I've checked and nginx error logs are empty, nothing intresting in nginx acces but i can give it to you if you need, PHP error contains only `[22-Jun-2024 22:47:00] NOTICE: fpm is running, pid 266
[22-Jun-2024 22:47:00] NOTICE: ready to handle connections` and here is laravel logs 
[laravel.log](https://github.com/user-attachments/files/15946315/laravel.log)

**Comment by amaurydetremerie** [comment]
As far as I can see, there's a problem when setting the server_id field. Undefined column: 7 ERROR:  column \"server_id\" of relation \"results\" does not exist
Could it be in my config? It's weird because I've tried without the environment variable, with but empty, with a single value, with a list of values. When I look at the environment variable in the pod it has the value `SPEEDTEST_SERVERS=63249,45280,30594,59333,5151,2848,54889`

**Comment by svenvg93** [comment]
I Don't know anything about K3S. The error about the server_id seems the same as in https://github.com/alexjustesen/speedtest-tracker/issues/1554 

Can you try:
- Go to container CLI
- Make sure your in /app/www
- Run command: `php artisan migrate --force
`
For the other user it was sovled after running: `php artisan migrate:clean --force` but it will reset everyhing.

**Comment by amaurydetremerie** [comment]
Thanks for the information. I've tried the migreate:clean (data is not important for the moment, it's a new install) and ther is the result : 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/71339304/1a38bf1b-c483-4b7b-9abf-c84493f20fae)
And for the simple migrate :
![image (1)](https://github.com/alexjustesen/speedtest-tracker/assets/71339304/6d40fee0-6d75-4585-9a6a-913f22583edf)
And the bug is always here

**Comment by svenvg93** [comment]
Can you try `php artisan migrate:fresh --force`

**Comment by amaurydetremerie** [comment]
Everything show Done but the exception is still here

**Comment by amaurydetremerie** [comment]
Thanks for your help. I'm sure it's a pebcak at the end

**Comment by svenvg93** [comment]
In thing i can think of quickly to try is to use sqlite (dont forget to add a volume for it) just to ruleout a problem with postgress.

**Comment by amaurydetremerie** [comment]
You have a really good idea here but the error is exactly the same with sqlite... I think it's not a DB problem

**Comment by alexjustesen** [comment]
@amaurydetremerie what version of pgsql are you using? Just tested it with 15 and didn't get any errors.

**Comment by pmezhuev** [comment]
This error occurs when specifying SPEEDTEST_PING_URL or SPEEDTEST_SERVERS environment and does not depend on the DB.

**Comment by amaurydetremerie** [comment]
> @amaurydetremerie what version of pgsql are you using? Just tested it with 15 and didn't get any errors.

Sorry for the late response but I've been busy at work. The version i use is `PostgreSQL 16.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit` but I don't think it's linked because when I use the sqlite DB the problem is the same.

**Comment by amaurydetremerie** [comment]
@pmezhuev I have the exact same error without using SPEEDTEST_SERVERS or SPEEDTEST_PING_URL environment variable so if you have any idea to try i take it

**Comment by amaurydetremerie** [comment]
Hello, I'm sorry but I started to think about it and I finally found the problem. The idea of @svenvg93 was very good but as the migrate:clean and migrate:fresh didn't work I didn't look any further. This evening I searched my DB and the server_id field was missing from the results table...
I simply added the field and now I have another error but I'm 99% sure it's from my Kubernetes installation.
I don't know why this server_id field isn't present by default but that's what's creating this problem
Thanks for your help and patience

**Comment by alexjustesen** [comment]
@amaurydetremerie if you're all set please feel free to close the issue. If it continues and we need to dig into it a little more feel free to tag me.

**Comment by pmezhuev** [comment]
> @pmezhuev I have the exact same error without using SPEEDTEST_SERVERS or SPEEDTEST_PING_URL environment variable so if you have any idea to try i take it

@alexjustesen Test in the minimum required configuration with only APP_KEY. I had no problems with the installation until I started setting it up.

**Comment by alexjustesen** [comment]
Closing, looks like OP is all set

**Comment by nandi95** [comment]
I'm stumped by what happened here with this data migration. @alexjustesen probably knows better the deal around this.

I just tried to set up the application for the first time and I'm getting the same thing that server_id is not set in the table.
I believe the reason is because, well... it was missed out in the following migration (along with `server_host` and `server_name`). 

https://github.com/alexjustesen/speedtest-tracker/blob/9a0d7dab4e920dadb1827871e478b6c1256d661f/database/migrations/2024_02_18_100000_results_bad_json_table.php#L20-L43

if these are added back in the above file, all will be well again
```php
$table->integer('server_id')->nullable();
$table->string('server_host')->nullable();
$table->string('server_name')->nullable();
```
