### ISSUE TITLE
Docker container CPU spikes

### ISSUE THREAD

**Issue by rusty1281** [alexjustesen/speedtest-tracker#1566]
**Describe the bug**
Not sure if this is a bug or "by design" but was looking at my CPU docker utilization for all my hosts just to glance at how are things, and noticed that the speedtest container has a pattern.

Every 1 min there is a small spike in CPU utilization that lasts exactly 10 seconds. The utilization is 0.1% but I am just curious what this might be. The tests are configured to run once a day only and at midnight.

**To Reproduce**

Deployed the current 0.20.6 version using linuxserver image via docker on RS2423+ (like the rest of 30ish containers on the same host)

**Environment (please complete the following information):**
Synology RS2423+
DSM 7.2.1 (latest)
Docker 20.10.23 build 876964a

**Screenshots**
<img width="1606" alt="Screenshot 2024-06-23 at 19 14 07" src="https://github.com/alexjustesen/speedtest-tracker/assets/5110408/bee84f19-521c-4ba0-8c84-72a12801fd5a">

Today it lasted about 3h:

<img width="1629" alt="Screenshot 2024-06-23 at 19 26 56" src="https://github.com/alexjustesen/speedtest-tracker/assets/5110408/54d8c1f1-ce35-4d18-86b2-38535510f17b">

I haven't touched anything to make it stop or start and by the time I got htop installed inside, the effect stopped so didn't catch it in time, but will keep an eye on it.

**Docker variables**
Apart from the mandatory and needed variables here are a few that might come in useful to describe how the container is configured

```
            - SPEEDTEST_SCHEDULE=0 0 * * *
            - SPEEDTEST_SERVERS="54112"
            - PRUNE_RESULTS_OLDER_THAN=60
```

Again, not sure if this is expected or if it's some sort of bug, but I am just curious.

Thanks in advance!

**Comment by alexjustesen** [comment]
That's the scheduler running in the background. Runs every minute.

**Comment by pucherot** [comment]
Hi, what kind of functions execute the internal scheduler?
Is it possible to reduce the delay to every 15 or 30 minutes?

**Comment by svenvg93** [comment]
> Hi, what kind of functions execute the internal scheduler? Is it possible to reduce the delay to every 15 or 30 minutes?

To check if there is a scheduled test thats need to started based on the cron job schedule defined by the user.
