### ISSUE TITLE
Schedule Missing

### ISSUE THREAD

**Issue by sladester** [alexjustesen/speedtest-tracker#1571]
**Describe the bug**

Had not checked speedtest tracker in a few weeks.  Found it was not running.  Suddenly wanted an APP_KEY, never did before.  No big deal got one, and it started right up ok.  Now I see on the dashboard it says I have no runs scheduled.  OK, guess I need to reschedule... BUT the option to schedule is gone.  My account is set as admin but under settings, the whole General section is not there at all.  The word general is missing.

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
-  Architecture: [e.g. arm64, amd64]
 - Version [e.g. v1]

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by alexjustesen** [comment]
https://github.com/alexjustesen/speedtest-tracker/releases
