### ISSUE TITLE
"General" setting are completely gone...

### ISSUE THREAD

**Issue by Jaxel** [alexjustesen/speedtest-tracker#1572]
**Describe the bug**
The "general" settings page is gone. Seems to be gone since June 8. Because of this, scheduled speedtests are also gone. All settings related to "general" are gone, and have to be set in ENV variables.

**Environment (please complete the following information):**
 - OS: Synology Docker
 - Build-date: 2024-06-21T22:11:20+00:00
 - Linuxserver.io version: v0.20.7-ls31

**Comment by alexjustesen** [comment]
https://github.com/alexjustesen/speedtest-tracker/releases

**Comment by Cinj216** [comment]
And then next month he'll get a wild hair up his butt to change the name of those variables or something and break it all over again for no justifiable reason. This is getting old real fast.

**Comment by alexjustesen** [comment]
> And then next month he'll get a wild hair up his butt to change the name of those variables or something and break it all over again for no justifiable reason. This is getting old real fast.

The beauty of open source is you don't have to use it if you don't like it and can fork it to your liking. 

What I won't tolerate is rude or hostile comments towards myself or anyone else who contributes to this project. Consider this the only warning.

**Comment by Cinj216** [comment]
Boohoo. Keep your project to yourself if you don't want people giving their opinion on it. If I wanted to be rude or hostile, then you'd know it.
