### ISSUE TITLE
CRON Schedule not running hourly. 

### ISSUE THREAD

**Issue by prvsmrtsltppr7** [alexjustesen/speedtest-tracker#1576]
Hi, updated Speedtest Tracker to the latest version and added the environment variable SPEEDTEST_SCHEDULE: to my docker compose file. Docker is ran in a container on a Debian VM running Portainer. 

Set the speedtest schedule in the environment variable
wait until specified time

**Expected behavior**
I expect the speedtest results to show up every hour, on the hour as defined in the environment variable

**Environment (please complete the following information):**
 - OS: Debian 12
 - Version Latest: App: 0.20.6

My docker compose file
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8111:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=APIKEY
            - APP_URL=http://192.168.1.46:8111
            - DB_CONNECTION=sqlite
            - DISPLAY_TIMEZONE=Europe/London
            - SPEEDTEST_SCHEDULE:"0 * * * *"
        volumes:
            - /path/to/data:/config
            - /path/to-custom-ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:0.20.6
        restart: unless-stopped

**Comment by svenvg93** [comment]
Do you see the “next schedule run at” on the dashboard ? 

Also can you try without the quote just =0 * * * *

**Comment by prvsmrtsltppr7** [comment]
I'm really sorry, I didn't even spot that. I think it was because I've been fighting YAML all day. That's a little embarrassing. I did notice that port 8111 is using something called Skynetflow do you know what this is? Seems to be related to speedtest tracker?

**Comment by alexjustesen** [comment]
`8111` is mapped internally to `80` which is just `http` traffic, I'm not running anything called Skynetflow

**Comment by prvsmrtsltppr7** [comment]
Okay thank you, I changed the port to 8112 and ran NMAP again, no skynetflow so not entirely sure whats gone wrong but I'll investigate thanks for the help and sorry!
