### ISSUE TITLE
Add a twitter notification that don't meet the Thresholds

### ISSUE THREAD

**Issue by wakko69** [alexjustesen/speedtest-tracker#158]
Could you add a twitter feature that would report to speed and make it to where you could change the saying. 
Like this " 
`tweet="Hello @CenturyLinkHelp & @CenturyLinkNE my internet speed is " + str(int(eval(d))) + "Mbps down\\" + str(int(eval(u))) + "Mbps up why? I pay for gigabit to the door? #speedtest @AjitPaiFCC this is why we need laws to protect consumers! #NetNeutrality"`
 that don't meet the Thresholds!

**Comment by alexjustesen** [comment]
I like the level of calling out the ISP's here but its a pretty specific request. I'm going to put in my backlog integration with Zapier which might be a better way to go rather than providing a specific integration to a possibly sinking ship.

https://zapier.com/apps

**Comment by hansenc0705** [comment]
Instead of Zapier could it be just webhooks support in general?

**Comment by alexjustesen** [comment]
> Instead of Zapier could it be just webhooks support in general?

Let me think about that implementation, initial reaction is that it's a good idea.

**Comment by alexdelprete** [comment]
> Let me think about that implementation, initial reaction is that it's a good idea.

There's also [apprise](https://github.com/caronc/apprise) that supports every possible service, also webhooks through Custom Notifications service. It's in python, but the dev created a lightweight REST framework that encapsulates apprise library: [apprise API](https://github.com/caronc/apprise-api).

Wiki with all the services and info here: https://github.com/caronc/apprise/wiki

**Comment by wakko69** [comment]
I currently have one sorta of set up already "https://twitter.com/disgruntledt3ch" but it doesn't twit if it goes below a speed. It just twit every 2 hours. based on this post "https://www.reddit.com/r/technology/comments/43fi39/i_set_up_my_raspberry_pi_to_automatically_tweet/"
