### ISSUE TITLE
Add additional data to the Webhooks Payload

### ISSUE THREAD

**Issue by hansenc0705** [alexjustesen/speedtest-tracker#1580]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add more to the webhook notification?

**Describe the solution you'd like**
Add more of the speedtest data to the payload. Adding the SpeedTest.net Results URL to the Webhook might be enough but it would be nice to collect the same data that the table contains in the webhook payload

**Additional context**
Nothing additional besides a thank you.

**Comment by hansenc0705** [comment]
I use SpeedTest Tracker to track my Starlink speeds, there is another site out there that is community maintained that tracks this data. trying to figure out the easiest way to get the data from SpeedTest Tracker over to starlinktrack.com 

https://starlinktrack.com/speedtests/

**Comment by svenvg93** [comment]
Adding only the Speedtest.net result URL is of  course possible, but it will show the mostly the same data as that the payload already does. Is there any data you are looking for specificly? 

The resutls table can show (almost) everything that is returned by the Speedtest CLI. Having all data in the payload might be a bit to much 😅 . Especially has all the notifications are using the same structure for the message. And my geuss is most people.

**Comment by hansenc0705** [comment]
adding just the speedtest url is good for this idea to integrate into starlinktrack.com. 

adding more data to the payload would just give people the ability to pull mort types of data out as needed but without knowing how everything works i dont know the level of effort or how it impacts other notifications.

**Comment by hansenc0705** [comment]
Well I think about it like some of the other products I worked with that have webhooks. You parse the data you need and ignore what you don't.

Thanks for looking at it @svenvg93, appreciate it.

**Comment by svenvg93** [comment]
@alexjustesen FYI I will do this after the open PRs for 0.21.0 are merge into it. So I can do it for all at the same time.

**Comment by AliMickey** [comment]
Just jumping in to add the reason why I (starlinktrack.com) accept the speedtest result URL only:

1. This allows me to check if the speedtest was actually run on Starlink,
2. I pull the speedtest data directly from the trusted source, accepting raw data isn’t ideal as it can be spoofed. 

Thanks for looking into adding this, as it will benefit the community of both of these apps :).

**Comment by eden22ltd** [comment]
would also like the url added to the webhook payload. useful to push all results to a google sheet for data manipulation and show the url for each test alongside

**Comment by svenvg93** [comment]
@alexjustesen This one can be closed as the url is added in the merge with https://github.com/alexjustesen/speedtest-tracker/pull/1615
