### ISSUE TITLE
Speed values differ between test run manually vs. via cron

### ISSUE THREAD

**Issue by italeffect** [alexjustesen/speedtest-tracker#1583]
**Describe the bug**
I have this set to run every hour using only one test server #62981 Sonic. I have a 10g WAN connection. I've been using this container for at least a year and this problem is recent (last month or 2 maybe?) When this runs via cron it reports speeds often in the 1-3 Gbps down and sub 1 -2 Gbps up range. When I run the test manually with the same server by clicking the "Run speedtest" button I get the expected results: ~8 Gbps up / 7 Gbps down.

**To Reproduce**
1. Click "Run Speedtest"
2. Compare results to automated hourly results via cron

**Expected behavior**
Constant results, with variation due to network activity etc. A couple months ago this is how it always performed.

**Environment please complete the following information):**
 - OS: Unraid
-  Architecture: Docker container:  lscr.io/linuxserver/speedtest-tracker:latest with mysql docker container as well
 - Browser: same on chrome and safari
 - Version: 0.20.7

**Screenshots**
![Screenshot 2024-06-27 at 10 28 50 AM](https://github.com/alexjustesen/speedtest-tracker/assets/4203546/d7ca215e-6f53-4d76-ba6a-af4be1f6a1dc)
![Screenshot 2024-06-27 at 10 25 31 AM](https://github.com/alexjustesen/speedtest-tracker/assets/4203546/571bdce7-b758-48c7-902b-09152a9b100e)

The two results with the high speeds were manual, the rest ran automatically on the hour.

**Logs**
Nothing in Logs

**Additional context**

**Comment by svenvg93** [comment]
Hi @italeffect, 

We have seen this in the past that speedtest on the hour mark are lower than at a random moment during the hour. Seems that more and more people are testing their speedtest with tools like this at the hour mark. Which makes the Speedtest Server (or the ISP network) to run out of capacity. 
It might help to set the schedule to run x minutes after the hour to see if that makes an improved. For example mine run 6 minutes after the hour mark.

**Comment by alexjustesen** [comment]
Like @svenvg93 said, I also strongly recommend running tests off-hour and off-half hours as those seem to be the high traffic test times.

**Comment by italeffect** [comment]
Thanks guys! such an obvious answer that I missed.
