### ISSUE TITLE
A Home Assistant add-on?

### ISSUE THREAD

**Issue by Nickduino** [alexjustesen/speedtest-tracker#1586]
Would it be possible to turn this project into a Home Assitant add-on to set it up in one click, rather than having to install it somewhere else and import all data through the API?

That would be a very welcome alternative for people who aren't too tech savy like myself :-)

**Comment by mckooter** [comment]
As a workaround using the unofficial API for now I was able to get the data into home assistant using Node RED (available as an addon if you are using the home assistant os) Below is how simple it looks
![firefox_ROClfIzoui](https://github.com/alexjustesen/speedtest-tracker/assets/6503783/9c6b3964-0a3d-4c26-8cc6-89f6add87aeb)

- The HTTP Request node is simply pulling from http://{{SERVERIP}}:8080/api/speedtest/latest and set to a parsed JSON object
- The sensor node is pulling the data from that JSON and assigning the created/time/server as attributes on that sensor
![firefox_FywxTt2ErI](https://github.com/alexjustesen/speedtest-tracker/assets/6503783/7f229291-2c66-4478-8d08-a09108198dfd)

I apologize if this isnt the appropriate place for this, if it is let me know and I can move it, but figured it would be helpful for others in the mean time.

Thanks,

**Comment by mckooter** [comment]
Additionally, its much easier to just do it in the home assistant configuration.yaml. Here is an example that pulls the same as the above node red (I did add the rest of the values from the json to the attributes of each sensor (could also pull any of those values for its own sensor if desired
```
sensor:
  - platform: rest
    name: Speedtest Ping
    resource: http://{{SERVERIP}}:8080/api/speedtest/latest
    value_template: "{{ value_json.data.ping }}"
    unit_of_measurement: "ms"
    scan_interval: 1800  # 30 minutes in seconds
    json_attributes_path: "$.data"
    json_attributes:
      - id
      - server_id
      - server_host
      - server_name
      - url
      - scheduled
      - failed
      - created_at
      - updated_at

  - platform: rest
    name: Speedtest Download
    resource: http://{{SERVERIP}}:8080/api/speedtest/latest
    value_template: "{{ value_json.data.download }}"
    unit_of_measurement: "Mbps"
    scan_interval: 1800  # 30 minutes in seconds
    json_attributes_path: "$.data"
    json_attributes:
      - id
      - server_id
      - server_host
      - server_name
      - url
      - scheduled
      - failed
      - created_at
      - updated_at

  - platform: rest
    name: Speedtest Upload
    resource: http://{{SERVERIP}}:8080/api/speedtest/latest
    value_template: "{{ value_json.data.upload }}"
    unit_of_measurement: "Mbps"
    scan_interval: 1800  # 30 minutes in seconds
    json_attributes_path: "$.data"
    json_attributes:
      - id
      - server_id
      - server_host
      - server_name
      - url
      - scheduled
      - failed
      - created_at
      - updated_at
```

Thanks again

**Comment by 19ban19** [comment]
I’m running HA in a container same as speedtest tracker. It would be nice if there would be integration in HA or HACS integration available 

thanks

**Comment by soulripper13** [comment]
Has anyone been able to use a script or button to run the test in home assistant?
