### ISSUE TITLE
[Server_ID Fail] - Could not open input file: artisan

### ISSUE THREAD

**Issue by BigFlubba** [alexjustesen/speedtest-tracker#1590]
**Describe the bug**

**To Reproduce**
1. Run `cd app/www/`
2. Run `php artisan app:ookla-list-servers`
4. See error `Could not open input file: artisan`

**Expected behavior**
Show server id's.

**Environment (please complete the following information):**
 - OS: Ubuntu Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-113-generic x86_64)
 - Architecture: amd64
 - Version: 0.20.7

**Comment by alexjustesen** [comment]
This can happen if your PUID and PGID vars aren't correct, while the default is 1000 it could be different for the user that runs Docker on your machine.

To ensure you have the right IDs run `id username`.

**Comment by svenvg93** [comment]
Hi @BigFlubba 

These command only work from inside the container, not from the host directly (looking at your output) 
Can you run `docker exec -it speedtest-tracker /bin/bash` (adjust `speedtest-tracker` if your container as a different name) 

Then you can run 
- cd `/app/www`
- `php artisan app:ookla-list-servers`

This should return the server list.

**Comment by svenvg93** [comment]
Cool! Please close the issue if it is revolved :) 
Will have a look at the docs to improve it :)
