### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by imagenet** [alexjustesen/speedtest-tracker#1593]
There is no general tab to configure cron or is there another way?

I am logged in as administrator

**Comment by imagenet** [comment]
docker run -d --name speedtest-tracker --restart unless-stopped -p 8765:80 -e PUID=1000 -e PGID=1000 -e APP_KEY=base64:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -e APP_URL=http://localhost -e DB_CONNECTION=sqlite -v ${PWD}:/config lscr.io/linuxserver/speedtest-tracker:0.20.7

**Comment by robinhood-code** [comment]
same, and on the dashboard page it now says I don't have any schedule test, which I had scheduled in previous version:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/6055272/3f46ecc3-d709-4c55-b8d6-efd458da59e6)

**Comment by Investigamer** [comment]
Just use: lscr.io/linuxserver/speedtest-tracker:**0.19.0**

Apparently the general tab was removed in favor of environment variables for site name, dashboard public toggle, time zone(s), speed test schedule, results pruning, speedtest servers, etc. Apparently some aspect of maintaining the GUI was proving too time consuming relative to the huge upgrades to the API or... something, but idk. I just never really looked to a speedtest snapshot container for a robust API, I just wanted a nice visual web app to track routine speedtests charts. I just think environment variables where docker apps like this are concerned, should be the very bare metal aspects of the app, it shouldn't be the prime modus for controlling app functionality.

**Comment by robinhood-code** [comment]
ok, saw the changes now:

https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0
