### ISSUE TITLE
SPEEDTEST_SERVERS env variable change has no effect

### ISSUE THREAD

**Issue by rootforbid** [alexjustesen/speedtest-tracker#1594]
**Describe the bug**
Using the docker container, once you start the container for the first time using a specific "SPEEDTEST_SERVERS", it seems speedtest-tracker forever uses that value no matter what value you change it to afterwards.

**To Reproduce**
1. Start a container using a specific server for the environment variable "SPEEDTEST_SERVERS" and make sure you use Sqlite or some kind of database for the data retention.
```
docker run -d \
  --name=speedtest-tracker \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e APP_KEY=123456 \
  -e DB_CONNECTION=sqlite \
  -e SPEEDTEST_SCHEDULE="0 * * * *" \
  -e SPEEDTEST_SERVERS=30252 \
  -p 80:80 \
  -v /home/user/docker_data/speedtest-tracker/data:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/speedtest-tracker:latest
```
3. Do a speed test.
4. Go to the admin/results page and take notice of the server id and name of that speed test (they will match your environment variable value).
5. Stop and delete the container.
6. Relaunch the container with the same docker settings as step 1, but change the "SPEEDTEST_SERVERS" variable to another server.
```
docker run -d \
  --name=speedtest-tracker \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e APP_KEY=123456 \
  -e DB_CONNECTION=sqlite \
  -e SPEEDTEST_SCHEDULE="0 * * * *" \
  -e SPEEDTEST_SERVERS=16331 \
  -p 80:80 \
  -v /home/user/docker_data/speedtest-tracker/data:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/speedtest-tracker:latest
```
8. Do a speed test.
9. Go to the admin/results page and notice that the result of your speed test still has the same server id and name as the first server you used instead of the new one.

**Expected behavior**
The speed test should be using the new server set in "SPEEDTEST_SERVERS".

**Workaround**
Delete the container data (aka losing all your history) and start a fresh new container with the new "SPEEDTEST_SERVERS" value.

**Environment (please complete the following information):**
 - OS: Docker
-  Architecture: amd64
 - Browser chrome
 - Version 125.0

**Additional context**
Not sure if this a simple frontend bug, where the correct speed test does indeed take effect but the frontend just displays the id and name of the original server (with the speed values of the new server).
Or it's a bug in the backend where the speed test does use the original server regardless of any subsequent "SPEEDTEST_SERVERS" changes.

**Comment by svenvg93** [comment]
Hi @rootforbid 
Can you specify how you recreate the container. Im not able to replicate your problem 
As you can see in the screenshots my default server id is `52365` changed it to `52857` run `docker compose down && docker compose up -d` to recreate the container. The new server is used for the last test I run manually.


<img width="770" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/db9d5cd6-62b4-4204-a79c-1cc920fb55b1">


<img width="1291" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/b060ea7d-afe4-4766-89d2-e05d5306eb51">

**Comment by rootforbid** [comment]
The docker commands I use are in the OP.
But I've just tried on my local machine instead of my server and it ran fine.

What I suspect is that the server list you can test on changes at any given time.
Server list via ```docker exec speedtest-tracker php /app/www/artisan app:ookla-list-servers```
If you use a server Id that's not in that list at the time of the test, the test defaults to using the previous Id set?
I guess that's why it's best to maybe not set any specific server at all as it might be part of the server list at time of the test.

**Comment by rootforbid** [comment]
The docker commands I use are in the OP.
But I've just tried on my local machine instead of my server and it ran fine.

What I suspect is that the server list you can test on changes at any given time.
Server list via ```docker exec speedtest-tracker php /app/www/artisan app:ookla-list-servers```
If you use a server Id that's not in that list at the time of the test, the test defaults to using the previous Id set?
I guess that's why it's best to maybe not set any specific server at all as it might not be part of the server list at time of the test.
In any case, this is mostly a Ookla limitation and not really this project's fault.
But maybe a little warning somewhere in the docs could be good to have to warn against using the same single server for the speed tests.

Closing this and thanks for this project :)
