### ISSUE TITLE
After Update missing general settings

### ISSUE THREAD

**Issue by FreddieOnly** [alexjustesen/speedtest-tracker#1596]
Installation of the latest version(0.20.7) has the following issues:

In the dashboard 'No general settings'
Does not schedule any speedtest

**Expected behavior**
An Installation with all features an self schedules speedtests

**Environment (please complete the following information):**
Synology 1821+ (see screenshot)
DSM latest (see screenshot)

**Screenshots**

**Logs**
is attached

**Additional context**
It is a little bit frustrating running in such results after updating, i had this issue several times and no idear how to stop this.,
![Synolog-Hardware](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/be8d4791-a34d-49cc-8aab-119c843fcc93)
![Synology DSM-Version](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/288954eb-639f-4da5-b914-bb6dbe5583fa)
![Speedtest_log](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/4f239c92-0dcb-4238-aeaa-f8462150923c)
![Speedtest_latest](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/a7386380-93e7-4b42-9f06-00d16a258e24)
![Speedtest_no_general_settings](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/b922c2ca-99e9-4eca-92dd-ca0f2eb933d8)
![Speedtest_no_schedule](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/70545c92-4998-4da2-8975-71be41c16a67)

Looking forward hearing from you

**Comment by svenvg93** [comment]
Please read the release notes of the 0.20.x release here https://github.com/alexjustesen/speedtest-tracker/discussions/1470 , action is needed to make it work.
