### ISSUE TITLE
Update to letest version

### ISSUE THREAD

**Issue by FreddieOnly** [alexjustesen/speedtest-tracker#1598]
**Describe the bug**
After  installation I cant see the general settings and still, no runs are scheduled,
after starting a speedtest run i get the following error message ( see screenshots)

[_speedtest_logs.txt](https://github.com/user-attachments/files/16120323/_speedtest_logs.txt)
![Bildschirmfoto 2024-07-07 um 20 22 03](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/0b08dbfe-5bde-47ba-901f-f1cfd430150b)
![speedtest_Error3](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/500656f0-5021-4f60-9e6a-546c5c242d4e)
![speedtest_Error2](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/36464d8c-1608-40db-b377-17ce37943dcc)
![speedtest_Error1](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/072e78d4-6758-4bcd-9a63-5c8be6598fb8)
![Speedtest_nach_Update](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/86b80b24-9ca9-4dcd-9321-2933dce4961f)
![Synolog-Hardware](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/82434c3a-2ac9-4321-9e1e-62f2302f0f57)
![Synology DSM-Version](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/38d9b217-ebe9-442b-a481-1b4f4582fee8)
![Speedtest_latest](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/c1655c7e-6e5d-4bd1-b165-df2d0b5d3779)
![Speedtest_no_general_settings](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/4afc6af1-64c6-4ad8-8fa4-3b6a564bf20a)
![Speedtest_no_schedule](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/bb8d7cbb-de92-49fe-96af-97a07d68cebc)

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by svenvg93** [comment]
Dup of https://github.com/alexjustesen/speedtest-tracker/issues/1596 
@FreddieOnly  Please check the comment in your first issue
