### ISSUE TITLE
After update still error message

### ISSUE THREAD

**Issue by FreddieOnly** [alexjustesen/speedtest-tracker#1600]
I am sorry — still I have issues with speedtracker after the update and following your recommended procedure.

I attach my environmentals and more screenshots
![speedtracker error message](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/22ec4dcd-05a2-48d4-aa43-898394623be2)
![speedtracker errror message_3](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/c530eb6e-3903-45ad-8c3c-8024296af930)
![speedtracker enviromental ](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/8e2dd48b-58de-4510-8fb1-a163e533c010)
![speedtracker error message_2](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/86cd52fb-7d52-4f3d-b4ce-b0101a0bbf0b)
![Speedtest_nach_Update no general settings](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/bfd62701-04f0-4103-9e22-9c36c601fd9d)
![Speedtracker request](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/817abd6d-ca80-48a4-8b6d-727a11225a0f)
![speedtracker application](https://github.com/alexjustesen/speedtest-tracker/assets/102794884/4f312626-208f-4368-b0b4-b119f0c62394)

maybe I had overlooked something

I am looking forward hearing from you

**Comment by svenvg93** [comment]
Hi @FreddieOnly, 
Some quick fixes for in the environment variables to get it fixed

- SPEEDTEST_SERVERS should be the server id(s) you want to test against. Not "ookla-server-list" 

As well when are you getting the errors? By opening a specific page? Running a test?

**Comment by FreddieOnly** [comment]
Here comes another installation and test — sorry with no success

![Error message after changing authentication_1](https://github.com/user-attachments/assets/8c342b53-2b37-4ebc-b05f-fd99ad8ef4a6)
![Speedtest-tracker enviromental settings](https://github.com/user-attachments/assets/b77396a5-379c-439e-b980-4a0835498fc6)
![Speedtest tracker ](https://github.com/user-attachments/assets/8bc2687e-cf98-4b3d-a07b-269de1539e53)
[_speedtest-tracker_logs (1).txt](https://github.com/user-attachments/files/16203413/_speedtest-tracker_logs.1.txt)
![Error message after changing authentication_2](https://github.com/user-attachments/assets/5afeec73-8e91-4235-8c2b-eb72584d228b)
![Error message after changing authentication_3](https://github.com/user-attachments/assets/1f3bc902-ce08-474f-93c5-ba03b517c321)
![Speedtest-tracker not working](https://github.com/user-attachments/assets/cb6cca07-f424-4e34-a29a-16778d482899)
![Speedtest-tracker without general settings](https://github.com/user-attachments/assets/066bfda5-304b-46e2-a22c-6b38b73286f2)

I am looking forward hearing from you
regards

**Comment by svenvg93** [comment]
As I’m on holiday pinging @alexjustesen as he might be able to check why this happens 🙂

**Comment by alexjustesen** [comment]
Closing as the original issue seems to be solved.
