### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gerberanub** [alexjustesen/speedtest-tracker#1607]
**Describe the bug**

i set it to get telegram message notice
but from yesterday it is not working.. no telegram notice.
and  also not working manually speedtest.
i guess there is something wrong with ookla 

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]   docker in synology DSM 7
-  Architecture: [e.g. arm64, amd64]  amd64
 - Version [e.g. v1]  

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by alexjustesen** [comment]
Haven't heard from the OP in a couple weeks so going to close this out, @gerberanub if you circle back around feel free to reply and we can take another look.

**Comment by gerberanub** [comment]
what is OP ???

**Comment by alexjustesen** [comment]
OP is original poster aka you.
