### ISSUE TITLE
problem in table visible and invisible columns

### ISSUE THREAD

**Issue by MrPatate87** [alexjustesen/speedtest-tracker#1609]
**Describe the bug**
I have a problel in configuration in the table columns who are show and ide. I have in both some of the columns and i can't drag and drop this double to hide them.

**To Reproduce**
Don't know how it staer and why

**Expected behavior**
How can i disable some columns in the table with this problem

**Environment (please complete the following information):**
 - OS: docker (synology DSM 7.1.2°
-  Architecture: Intel x64
 - Browser chrom]
 - Version v1.12.0

**Screenshots**
![speed test](https://github.com/user-attachments/assets/04d9085b-8d4e-4c63-94cd-5a2a24d74868)

**Comment by alexjustesen** [comment]
Hey, there looks like your screenshots are from https://github.com/henrywhitaker3/Speedtest-Tracker. This repo is the spiritual successor to that one.

**Comment by MrPatate87** [comment]
Thanks for this quick reply, seems you're right, sorry for this mistake. 
for my problem I decide to delete the docker and recreate it, no more problem after this....
