### ISSUE TITLE
Limit maximum bandwith to use

### ISSUE THREAD

**Issue by phyzical** [alexjustesen/speedtest-tracker#1612]
Just want to limit the maximum upload/download to use to avoid getting packet loss during speed tests.

i tried searching for a generic container solution but all i could find was some k8's solutions and i have not gotten around to migrating my homelab over yet.

**Comment by alexjustesen** [comment]
It doesn't look like Ookla's CLI let's you set the data size unfortunatly.

**Comment by phyzical** [comment]
thanks, yeah i did a 30 minute google and i couldn't find much either, ahwell plan b it is throttle the container/server 😆

**Comment by phyzical** [comment]
https://github.com/alexjustesen/speedtest-tracker/issues/872
