### ISSUE TITLE
Access issue : Forgot email - can't login & can't reset password

### ISSUE THREAD

**Issue by hot22shot** [alexjustesen/speedtest-tracker#1624]
Hello,

Maybe a dumb question but is there a way to list the user(s) email(s) ? 
I can't login because I forgot my email/password and I can't reset the password as I do not know the email.
I tried to guess it but without any luck.

I could make a fresh install but I would loose my past measurements.

Any help appreciated !

**Comment by hot22shot** [comment]
Nevermind, I solved it by opening the database.sqlite with sqlite3 and list users.

**Comment by HuckleberryLovesYou** [comment]
To get all emails, take a look [here](https://github.com/alexjustesen/speedtest-tracker/issues/1546#issuecomment-2599236129)
