### ISSUE TITLE
Show Day of the Week in Results

### ISSUE THREAD

**Issue by Beswald** [alexjustesen/speedtest-tracker#1627]
Been running speedtest tracker for a while. Spun it up when I was having intermittent issues and trying to document my problems for my ISP.

When troubleshooting, the history and trends this program can provide are great. One thing that would be helpful is to show the day of the week as part of the results. Being able to, at a glance, see if it's a weekday, weekend or being able to see if issues happen every Friday for example are useful pieces of information.

In the results:  **Friday,** Jul. 26th, 2024 8:00am

Also consider adding it to the popup that appears when hovering over an individual result in the history charts.

The program has been great for troubleshooting and narrowing down where issues may be occurring.

Thank you.

**Comment by svenvg93** [comment]
Hi @Beswald 

you can use the environment variable `DATETIME_FORMAT` with php date format to add the day as well.
https://www.php.net/manual/en/datetime.format.php 

Adding D will add a Sun,Mon etc

**Comment by Beswald** [comment]
@svenvg93 , perfect. Thank you!

**Comment by svenvg93** [comment]
Your welcome, please close the issue if this solves your problem
