### ISSUE TITLE
Asks me to choose server

### ISSUE THREAD

**Issue by duka10** [alexjustesen/speedtest-tracker#1631]
Hi, after upgrading from version 0.18 to the latest after manually run a speed test im asked to choose a server. In my case its Ookla.
After i revert to version 0.18, when i click the same button it doesn't ask me to choose a server. 

I cant find what changed with this in previous releases. Is there a way to disable that to choose server or to set ookla to be default server?

Im using docker version v0.20.8.

![Screenshot 2024-07-29 084858](https://github.com/user-attachments/assets/72cb91cb-9c99-4998-ba7d-2e0a580abb2c)

**Comment by svenvg93** [comment]
Hi @duka10, 

This was added in a previous release as preparation of adding other tools as well (https://github.com/alexjustesen/speedtest-tracker/milestone/11) . 

For now it is not possible to set a default.

**Comment by duka10** [comment]
Hi @svenvg93,

I understand. Thank you for the info.
