### ISSUE TITLE
Test Telegram Channel

### ISSUE THREAD

**Issue by rolfsorensen** [alexjustesen/speedtest-tracker#1632]
Just upgraded from 0.14.4 to 0.20.8
I noticed that the Test Telegram Channel function is no longer there.
Could this be added back?
It was really helpful when setting up Telegram notification.

**Comment by alexjustesen** [comment]
If your Telegram recipients list is empty or the bot token hasn't been passed into the container the button is hidden. Make sure to save changes first.

**Comment by tismofied** [comment]
I apologize in advance for replying in closed issue, but I having the same issue with no test button showing up.
I added the api token to .env per docs and made sure I entered the chat id under recipient and hit save

**Comment by shomilsaini** [comment]
> If your Telegram recipients list is empty or the bot token hasn't been passed into the container the button is hidden. Make sure to save changes first.

Test button does not show even when I have everything setup. Only way to get notification is to do a test.

Thanks

**Comment by Aristocrat-jt** [comment]
I have a receipiant chat id and TELEGRAM_BOT_TOKEN set up in docker compose, and the button still is missing. Any idea?
