### ISSUE TITLE
Fast backend

### ISSUE THREAD

**Issue by DominicMCN** [alexjustesen/speedtest-tracker#1635]
**Is your feature request related to a problem? Please describe.**

It seems speedtest-cli doesn't support multi connection so it doesn't reflect full bandwidth on multi-wan networks

**Describe the solution you'd like**

Supporting Netflix's fast.com backend. There's already a node cli available at https://github.com/sindresorhus/fast-cli/tree/main

**Additional context**

**Comment by alexjustesen** [comment]
Dup of #976
