### ISSUE TITLE
Configuration - Could not retrieve or read configuration (ConfigurationError) 

### ISSUE THREAD

**Issue by rmcgirr83** [alexjustesen/speedtest-tracker#1636]
**Describe the bug**
Everytime I start a speedtest it is stalled on "started". Looked in the laravel logs and there were some errors, notably server_id doesn't exist in db and it was trying to log this error message Configuration - Could not retrieve or read configuration (ConfigurationError). No speedtest is completing

**Expected behavior**
Show a speedtest result. Prior to using latest from lscr.io everything was working fine

**Environment (please complete the following information):**
Using docker in synology NAS here is compose file

services:
    speedtest:
        container_name: speedtest
        image: lscr.io/linuxserver/speedtest-tracker:latest
        ports:
            - 8999:80
        volumes:
            - /volume1/docker/speedtest:/config
        environment:
            - TZ=America/New_York
            - PGID=100
            - PUID=1032
            - APP_TIMEZONE=America/New_York
            - DISPLAY_TIMEZONE=America/New_York
            - DB_CONNECTION=sqlite
            - APP_KEY=redacted
            - SPEEDTEST_SERVERS=18687
            - SPEEDTEST_SCHEDULE=0 * * * *
        restart: unless-stopped

**Comment by rmcgirr83** [comment]
Clicking on view for the test and it doesn't appear anything is being populated
![Capture](https://github.com/user-attachments/assets/105c07ad-6d94-4f22-919a-452ee172331a)

**Comment by rmcgirr83** [comment]
According to this, that server is listed
[https://c.speedtest.net/speedtest-servers-static.php](url)
![Capture](https://github.com/user-attachments/assets/f0b9523d-f6c9-4d7c-88d9-37882673f549)

**Comment by rmcgirr83** [comment]
Additionally 
My new yml file

> services:
    speedtest:
        container_name: speedtest
        image: lscr.io/linuxserver/speedtest-tracker:latest
        ports:
            - 8999:80
        volumes:
            - /volume1/docker/speedtest:/config
        environment:
            - PGID=100
            - PUID=1032
            - APP_TIMEZONE=America/New_York
            - DISPLAY_TIMEZONE=America/New_York
            - DB_CONNECTION=sqlite
            - APP_KEY=redacted
            - SPEEDTEST_SERVERS=56485
            - SPEEDTEST_SCHEDULE=0 * * * *
        restart: unless-stopped

and that server is accurate
![Untitled](https://github.com/user-attachments/assets/c4aa4876-f198-4893-bf10-6b36f33df2f3)

laravel error logs
[laravel.log](https://github.com/user-attachments/files/16455653/laravel.log)

and I'm still stuck at "started" for the past 10 minutes

**Comment by alexjustesen** [comment]
I'm close to you (CT also) so I'll give `18687` a shot later today.

**Comment by rmcgirr83** [comment]
It seems to be an issue with my firewall  rules on the NAS. Disabling the firewall and the speedtest completed however I'm not sure how to setup the firewall correctly in this instance. I'll keep at it and let you know.

**Comment by rmcgirr83** [comment]
So the issue was the container with docker had joined a some speedtest_default network defined as 172.28.0.x, my bridge network is set as 172.17.0.x and has a firewall rule to allow connections to this network. Changing the docker container  network from the speedtest_default to the bridge network and things are running as normal.
![Capture](https://github.com/user-attachments/assets/fe7ab3b2-c7fc-4a05-8db0-1cba4e10f026)

**Comment by rmcgirr83** [comment]
You may want to include the network_mode in yml instructions for docker containers ;)
> services:
    speedtest:
        container_name: speedtest
        image: lscr.io/linuxserver/speedtest-tracker:latest
        ports:
            - 8999:80
        volumes:
            - /volume1/docker/speedtest:/config
        environment:
            - PGID=100
            - PUID=1032
            - APP_TIMEZONE=America/New_York
            - DISPLAY_TIMEZONE=America/New_York
            - DB_CONNECTION=sqlite
            - APP_KEY=redacted
            - SPEEDTEST_SERVERS=56485
            - SPEEDTEST_SCHEDULE=0 * * * *
        restart: unless-stopped
        network_mode: bridge

**Comment by alexjustesen** [comment]
> You may want to include the network_mode in yml instructions for docker containers ;)

Glad you were able to locate the issue! I'll make a note in the docs as it depends on how people have networking setup in their particular instances.
