### ISSUE TITLE
restore web configuration

### ISSUE THREAD

**Issue by bdistin** [alexjustesen/speedtest-tracker#1637]
**Is your feature request related to a problem? Please describe.**
I updated from 0.16.x->0.20.x and the force to use env variables seems like a step back from a usability standpoint. I understand it makes sense from a deployability standpoint, but the configuration of this project went from "the secretary could do it" to now "we need to get IT involved". 

**Describe the solution you'd like**
ENV variables should continue to be used. However, only in the initial setup/migration and then saved to the database. Further configuration changes should be possible from the web interface again.

**Comment by bdistin** [comment]
That's a rather rude/hostile way to treat a contribution of constructive criticism. Just had a look through the issues and this isn't a duplicate of an OPEN discussion. That paired with the fact that this keeps coming up organically is the definition of an issue, whether you choose to acknowledge that or not.

If you are coding for an audience of 1, that's your prerogative. However, if that's how you view this, you should take communal responsibility by changing the project name and image registration to alexjustesen's-personal-speedtest-tracker. Thus freeing up speedtest-tracker for someone to provide a proper experience for actual users.

![8yzd6z](https://github.com/user-attachments/assets/6313fced-d255-4169-9682-464b5c37e48c)

**Comment by alexjustesen** [comment]
I'd take a look at [past discussions](https://github.com/alexjustesen/speedtest-tracker/discussions/1470#discussioncomment-9701663) for the technical reason why this was done, I've got your feedback noted but posting memes in response aren't a great way for me to take it seriously.
