### ISSUE TITLE
General settings disappeared, scheduled tests stopped running

### ISSUE THREAD

**Issue by bwirt** [alexjustesen/speedtest-tracker#1638]
**Describe the bug**
Haven't logged into speedtest for a while and noticed no tests have been running for two months.  Also, general settings is missing in the web UI so there is no way to check the schedule.  Had been running fine for months.

Updated my image to 0.20.8 (from 0.20.6), no change.

**To Reproduce**
Unknown

**Expected behavior**
Speedtests should run per schedule, general settings should be available.

**Environment (please complete the following information):**
 - OS: Ubuntu / docker
-  Architecture: amd64
 - Browser: Firefox
 - Version: 0.20.8

**Screenshots**
![image](https://github.com/user-attachments/assets/8fdc7535-e97a-42ce-a1f2-721ae21a60b8)

**Logs**
error.log is empty

**Additional context**
N/A

**Comment by zilvernet** [comment]
same for me, i don't have settings general option.

**Comment by Grimlogh** [comment]
Can you post your Compose-File?

Since 20.x the General-Settings Option is not available anymore, you have to define these in your Compose for example. 

Please read the „Breaking Change“
Notice in the releases

**Comment by zilvernet** [comment]
speedtestn:
    container_name: speedtestn
    hostname: speedtestn
    image: lscr.io/linuxserver/speedtest-tracker:latest
    networks:
      master_network:
    ports:
      - 50110:80
      - 50113:443
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - TZ=America/New_York
      - PUBLIC_DASHBOARD=true
      - APP_KEY=********************************* # How to generate an app key: https://speedtest-tracker.dev/      
    volumes:
      - /docker_data/speedtestn/data:/config
      - /docker_data/speedtestn/custom-ssl-keys:/config/keys
    restart: unless-stopped

**Comment by Grimlogh** [comment]
![IMG_3068](https://github.com/user-attachments/assets/f8593cf8-d527-4cdb-83f0-7a1fcfe226e0)

Is that contained like this in your Compose File?
As it says you have to generate an AppKey and replace the string after „APP_KEY=“ with that generated value. 

Furthermore you can add the following to schedule a speedtest every 5 Minutes:

SPEEDTEST_SCHEDULE="*/5 * * * *"

**Comment by zilvernet** [comment]
thanks for the info.
I will add the SPEEDTEST_SCHEDULE
my app_key was masked with *** so it doesn't become public.

**Comment by alexjustesen** [comment]
Thanks @Grimlogh for ref the releases, I'm going to close this out as OP looks all set.
