### ISSUE TITLE
[Feature] Use the OpenSpeedTest Server

### ISSUE THREAD

**Issue by vinii8817** [alexjustesen/speedtest-tracker#1645]
**Is your feature request related to a problem? Please describe.**
No, it is not related to any problem.

**Describe the solution you'd like**
I would like the platform to be able to use OpenSpeedTest as a target server, which would allow scheduled tests within my own infrastructure.

**Additional context**
Nothing more, everything seems fine to me. ;-)
Ref: https://openspeedtest.com/

**Comment by alexjustesen** [comment]
Now tracking in https://github.com/alexjustesen/speedtest-tracker/discussions/976
