### ISSUE TITLE
500 server error when trying to access notification menu (v0.21.0)

### ISSUE THREAD

**Issue by eeeeb** [alexjustesen/speedtest-tracker#1652]
**Describe the bug**
I just updated my docker image from 0.20.9 to 0.21.0 and when I try to open the notifications menu, I get an 500 server error message.

**To Reproduce**
1. Go on the menu item "Notifications" or to .../admin/notification-page
2. See error

**Expected behavior**
The notification settings are being displayed

**Environment (please complete the following information):**
 - Docker-image: Linuxserver.io version: v0.21.0-ls39
-  Architecture: amd64
 - Browser: Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Screenshots**
![image](https://github.com/user-attachments/assets/6a08e180-e72e-45bd-ba27-d07452b18954)

**Logs**
From the laravel.log

> [2024-08-08 20:36:21] production.ERROR: Typed property App\Settings\NotificationSettings::$ntfy_enabled must not be accessed before initialization {"userId":1,"exception":"[object] (Error(code: 0): Typed property App\\Settings\\NotificationSettings::$ntfy_enabled must not be accessed before initialization at /app/www/vendor/spatie/laravel-settings/src/Settings.php:235)
> [stacktrace]
> #0 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(632): Spatie\\LaravelSettings\\Settings->Spatie\\LaravelSettings\\{closure}()
> #1 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(833): Illuminate\\Support\\Arr::mapWithKeys()
> #2 /app/www/vendor/spatie/laravel-settings/src/Settings.php(234): Illuminate\\Support\\Collection->mapWithKeys()
> #3 /app/www/vendor/spatie/laravel-settings/src/Settings.php(241): Spatie\\LaravelSettings\\Settings->toCollection()
> #4 /app/www/vendor/filament/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php(47): Spatie\\LaravelSettings\\Settings->toArray()
> #5 /app/www/vendor/filament/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php(38): Filament\\Pages\\SettingsPage->fillForm()
> #6 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Pages\\SettingsPage->mount()
> #7 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #8 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
> #9 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
> #10 /app/www/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call()
> #11 /app/www/vendor/livewire/livewire/src/Features/SupportLifecycleHooks/SupportLifecycleHooks.php(134): Livewire\\Wrapped->__call()
> #12 /app/www/vendor/livewire/livewire/src/Features/SupportLifecycleHooks/SupportLifecycleHooks.php(20): Livewire\\Features\\SupportLifecycleHooks\\SupportLifecycleHooks->callHook()
> #13 /app/www/vendor/livewire/livewire/src/ComponentHook.php(19): Livewire\\Features\\SupportLifecycleHooks\\SupportLifecycleHooks->mount()
> #14 /app/www/vendor/livewire/livewire/src/ComponentHookRegistry.php(45): Livewire\\ComponentHook->callMount()
> #15 /app/www/vendor/livewire/livewire/src/EventBus.php(60): Livewire\\ComponentHookRegistry::Livewire\\{closure}()
> #16 /app/www/vendor/livewire/livewire/src/helpers.php(98): Livewire\\EventBus->trigger()
> #17 /app/www/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(50): Livewire\\trigger()
> #18 /app/www/vendor/livewire/livewire/src/LivewireManager.php(73): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->mount()
> #19 /app/www/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(17): Livewire\\LivewireManager->mount()
> #20 /app/www/vendor/livewire/livewire/src/Features/SupportPageComponents/SupportPageComponents.php(117): Livewire\\Component->Livewire\\Features\\SupportPageComponents\\{closure}()
> #21 /app/www/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration()
> #22 /app/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Component->__invoke()
> #23 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
> #24 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\\Routing\\Route->runController()
> #25 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
> #26 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
> #27 /app/www/vendor/filament/filament/src/Http/Middleware/DispatchServingFilamentEvent.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #28 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Filament\\Http\\Middleware\\DispatchServingFilamentEvent->handle()
> #29 /app/www/vendor/filament/filament/src/Http/Middleware/DisableBladeIconComponents.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #30 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Filament\\Http\\Middleware\\DisableBladeIconComponents->handle()
> #31 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #32 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
> #33 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #34 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
> #35 /app/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #36 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
> #37 /app/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(64): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #38 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\Authenticate->handle()
> #39 /app/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #40 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
> #41 /app/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #42 /app/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
> #43 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
> #44 /app/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #45 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
> #46 /app/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #47 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
> #48 /app/www/vendor/filament/filament/src/Http/Middleware/SetUpPanel.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #49 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Filament\\Http\\Middleware\\SetUpPanel->handle()
> #50 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #51 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
> #52 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
> #53 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
> #54 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
> #55 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
> #56 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
> #57 /app/www/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #58 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
> #59 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #60 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
> #61 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
> #62 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #63 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
> #64 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
> #65 /app/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #66 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
> #67 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #68 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
> #69 /app/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #70 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
> #71 /app/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #72 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
> #73 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #74 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
> #75 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
> #76 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1188): Illuminate\\Foundation\\Http\\Kernel->handle()
> #77 /app/www/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
> #78 {main}
> "}

**Comment by svenvg93** [comment]
Seem to be related to the database migrations.
If I run `php artisan migrate:fresh` inside the container it works afterwards. 

I will look into this. If @alexjustesen don't beat me to it ;)

**Comment by fvdm** [comment]
@svenvg93 That command emptied my database

**Comment by eeeeb** [comment]
Yes same, I will roll back to a backup from earlier today.

**Comment by alexjustesen** [comment]
> @svenvg93 That command emptied my database

Yeah don't run that command in production, it's a part of testing and the initial install process.

**Comment by hansenc0705** [comment]
more detail in the error
![image](https://github.com/user-attachments/assets/85220d61-0d61-498c-a5b4-9297c0ab37f0)

**Comment by alexjustesen** [comment]
I'll circle back to this tonight, I suggest staying on `0.20.9` for the time being.

**Comment by AleksCee** [comment]
> I'll circle back to this tonight, I suggest staying on `0.20.9` for the time being.

It is save to just use the olde tag after upgrade tomlatest or will this broke something in the DB?

**Comment by alexjustesen** [comment]
> It is save to just use the old tag after upgrade to latest or will this broke something in the DB?

Yes you can roll back

**Comment by alexjustesen** [comment]
@eeeeb or someone else experiencing the issue, if you're familiar with navigating your database can you verify the following records in the `migrations` table?

![image](https://github.com/user-attachments/assets/4394a511-12b4-415e-b32d-c33fcbffb4d3)

**Comment by hansenc0705** [comment]
> @eeeeb or someone else experiencing the issue, if you're familiar with navigating your database can you verify the following records in the `migrations` table?
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/4394a511-12b4-415e-b32d-c33fcbffb4d3)
> 
> 

If you have some steps to get there I can pull that info. I didn't rollback my image.

**Comment by ivangonzalezg** [comment]
> @eeeeb or someone else experiencing the issue, if you're familiar with navigating your database can you verify the following records in the `migrations` table?
> 
> ![image](https://private-user-images.githubusercontent.com/1144087/356431129-4394a511-12b4-415e-b32d-c33fcbffb4d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjc3OTUsIm5iZiI6MTcyMzE2NzQ5NSwicGF0aCI6Ii8xMTQ0MDg3LzM1NjQzMTEyOS00Mzk0YTUxMS0xMmI0LTQxNWUtYjMyZC1jMzNmY2JmZmI0ZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMDEzODE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkzODgyY2E1YmNkYmY0NjM1NjE5ZjRlNmM2NTViYmZmMzlhMTQ1M2Y1ZWY1OGMwZGJmNTE4ZDEzNjk1NjQwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rCoILgPQx0XTPKB94IuFQgO9ySMerK0ytUPv7TbWSQg)

![image](https://github.com/user-attachments/assets/151d1026-ef9b-4181-87ed-2a605b073a60)

**Comment by alexjustesen** [comment]
Thanks, it's just "batch" 2 in the migration series. This number will keep counting up for you depending on when you first deployed the application.

In the `settings` table to you see the default values for the migrated settings? Example below:

![image](https://github.com/user-attachments/assets/b362baac-a9d4-4fbd-b3ac-514f42c72b74)

**Comment by alexjustesen** [comment]
For those having the issue and the `migrations` table and `settings` table looks similar to above can you restart your containers and let me know if the issue persists?

**Comment by hansenc0705** [comment]
Restarted twice and didn't help

**Comment by ivangonzalezg** [comment]
> Thanks, it's just "batch" 2 in the migration series. This number will keep counting up for you depending on when you first deployed the application.
> 
> In the `settings` table do you see the default values for the migrated settings? Example below:
> 
> ![image](https://private-user-images.githubusercontent.com/1144087/356433728-b362baac-a9d4-4fbd-b3ac-514f42c72b74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjgzNTMsIm5iZiI6MTcyMzE2ODA1MywicGF0aCI6Ii8xMTQ0MDg3LzM1NjQzMzcyOC1iMzYyYmFhYy1hOWQ0LTRmYmQtYjNhYy01MTRmNDJjNzJiNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMDE0NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGM0ZTMwMTc1MTNmZDU0ZGMzZWYxZDY4NTg0Y2E1YTQ2N2I0OGZiYjZhZTkwMTUwNWI2ZDc5M2U4OTk0YmMyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gEf91SUHDE1hxWTazb0O5K0QsmtDU7gyp0ScekxBWbk)

Yes, just with different IDs

![image](https://github.com/user-attachments/assets/4b87d62e-3bb8-459b-ac7a-a985000df5fd)

**Comment by alexjustesen** [comment]
Can you add/set the environment variable `SETTINGS_CACHE_ENABLED=false` and restart the container?

**Comment by ivangonzalezg** [comment]
> Can you add/set the environment variable `SETTINGS_CACHE_ENABLED=false` and restart the container?

It works!

**Comment by hansenc0705** [comment]
That worked

**Comment by alexjustesen** [comment]
🤘 fix incoming, thanks all!

**Comment by flopex** [comment]
I had this same issue though I'm on version `v0.24.3-ls61`. Setting `SETTINGS_CACHE_ENABLED=false` and nuking `/config` fixed it.
