### ISSUE TITLE
Email Notification not working again

### ISSUE THREAD

**Issue by edd080** [alexjustesen/speedtest-tracker#1656]
Since the last 2 updates any scheduled Speedtest runs that are processed do not notify me via email, however when I run a test email I receive it successfully. 

**To Reproduce**
1. Run a speedtest and I should receive an email. 

**Environment (please complete the following information):**
 - OS: Raspberry Pi 4 using docker. 

This had happened before, your help would be appreciated.
Thank you.

**Comment by svenvg93** [comment]
Thanks for reporting, should be fixed with the linked PR

**Comment by edd080** [comment]
Thank you so much 👍😊

**Comment by svenvg93** [comment]
@alexjustesen Until the fix is released, might be good to pin this one to prevent double issues

**Comment by alexjustesen** [comment]
Tagging as we speak
