### ISSUE TITLE
incorrect arrow and color of PING on the Dashboard

### ISSUE THREAD

**Issue by Euton2020** [alexjustesen/speedtest-tracker#1664]
**Describe the bug**
incorrect arrow and color of PING on the Dashboard

**To Reproduce**
1. Go to DASHBOARD => PING

**Expected behavior**
A clear 

**Environment (please complete the following information):**
 - OS: SYNOLOGY with Docker-compose
-  Architecture: [e.g. arm64, amd64]
 - Version App 0.21.1

**Screenshots**
![IMG_0361](https://github.com/user-attachments/assets/14cd02b6-1785-4b29-ba8d-7e8b13266621)
![IMG_0362](https://github.com/user-attachments/assets/4a02c4e0-2ec3-4564-a86d-2c5e6dd88c12)

**Logs**

**Additional context**

**Comment by svenvg93** [comment]
It seems correct to me. As for Ping when it's slower the time goes up, when it's faster the time goes down. 
It's the opposite from the download and upload test.

**Comment by alexjustesen** [comment]
Yep that's correct, a higher ping is a bad thing.

**Comment by Euton2020** [comment]
Thank you for your response and your work. now I understand the meaning of this information
