### ISSUE TITLE
Could not retrieve or read configuration (ConfigurationError)

### ISSUE THREAD

**Issue by ehro78** [alexjustesen/speedtest-tracker#1666]
**Describe the bug**
The application is not able to perform tests. In the results table it is showing Started as shown below:

![image](https://github.com/user-attachments/assets/a5170832-9cc4-48c9-90ff-db425d30cbc5)

This happened before, but I couldn't find any causes for that behavior, most of the time I made it work either by restarting the container or the host. None of those actions are working now.

Nevertheless, this time happened something very strange, last Saturday, it was failing, then it worked for a while, and from that point is not working anymore:

![image](https://github.com/user-attachments/assets/0a5cbefb-6283-45d2-8ea1-94a9fe948259)

Last troubleshooting performed:
-Update to the latest version. It didn't work
-Restart the container. It didn't work
-Reboot the host. It didn't work
-I changed the container to use the bridge network as suggested on #1636, but it didn't work 
-Restart the container again. It didn't work
-I tested some pings using URLs to test the DNS resolution and it worked fine:

oot@39378a361f94:/# speedtest -L
[2024-08-13 02:33:13.674] [error] Configuration - Cannot retrieve configuration document (403)
[2024-08-13 02:33:13.680] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
[2024-08-13 02:33:13.680] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
[error] Configuration - Could not retrieve or read configuration (ConfigurationError)
root@39378a361f94:/# speedtest --accept-license --accept-gdpr
[2024-08-13 02:35:45.388] [error] Configuration - Cannot retrieve configuration document (403)
[2024-08-13 02:35:45.393] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
[2024-08-13 02:35:45.394] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
[error] Configuration - Could not retrieve or read configuration (ConfigurationError)
root@39378a361f94:/# ^C
root@39378a361f94:/# 
root@39378a361f94:/# 
root@39378a361f94:/# 
root@39378a361f94:/# 
root@39378a361f94:/# ping www.speedtest.com
PING www.speedtest.com (103.224.182.246): 56 data bytes
64 bytes from 103.224.182.246: seq=0 ttl=51 time=118.170 ms
64 bytes from 103.224.182.246: seq=1 ttl=51 time=115.882 ms
^C
--- www.speedtest.com ping statistics ---
3 packets transmitted, 2 packets received, 33% packet loss
round-trip min/avg/max = 115.882/117.026/118.170 ms
root@39378a361f94:/# ping www.as.com
PING www.as.com (199.232.194.133): 56 data bytes
64 bytes from 199.232.194.133: seq=0 ttl=54 time=59.631 ms
64 bytes from 199.232.194.133: seq=1 ttl=54 time=59.264 ms
^C
--- www.as.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 59.264/59.447/59.631 ms
root@39378a361f94:/# 

**To Reproduce**
Not sure how to reproduce the issue

**Expected behavior**
Show a speedtest result as it happened before

**Environment (please complete the following information):**
-Using docker in a Raspberry Pi 4 with Portainer
 - OS:  Debian GNU/Linux 12 (bookworm)  
-  Architecture: arm64

Stack configuration:

ersion: "3"

services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8087:80
            #- 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=
            - APP_URL=http://brainiac
            - APP_TIMEZONE=America/Bogota
            - DISPLAY_TIMEZONE=America/Bogota 
            - SPEEDTEST_SCHEDULE=45 * * * * 
            - DB_CONNECTION=sqlite
            - TELEGRAM_BOT_TOKEN=
            - PUBLIC_DASHBOARD=true
            - PRUNE_RESULTS_OLDER_THAN=20
            - APP_DEBUG=false 
        volumes:
            - /docker-volume/speedtest-tracker/config:/config
            #- /path/to-custom-ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        network_mode: bridge

**Screenshots**
Shared in the description

**Logs**
Not sure what to collect, but I can provide any information you may need

**Comment by svenvg93** [comment]
The error means that either the specified speedtest server is unavailable,, or there is no connection to the servers. 
Are there any firewall rules that might block traffic from your docker network, and are all ports allowed? 

https://docs.speedtest-tracker.dev/help/error-messages#configuration-could-not-retrieve-or-read-configuration-configurationerror

**Comment by ehro78** [comment]
> The error means that either the specified speedtest server is unavailable,, or there is no connection to the servers. Are there any firewall rules that might block traffic from your docker network, and are all ports allowed?
> 
> https://docs.speedtest-tracker.dev/help/error-messages#configuration-could-not-retrieve-or-read-configuration-configurationerror

No, I haven't configured a FW and as I said before, it was working before, then stopped, it started to work again and finally, it stopped without any intervention from my side

Is there any log I can check to continue with the investigation?

Thanks!

**Comment by alexjustesen** [comment]
It's likely something outside of your network or the target test server being the issue. Start with selecting a different set of servers to test from or let the CLI choose the server for you.

If automatically choosing a server still isn't working try visiting https://c.speedtest.net/speedtest-servers-static.php and manually selecting a different server(s).

**Comment by ehro78** [comment]
Hi, I haven't had the chance to check on this again, but it happened again... today I noticed that tests started again without any intervention from my side:

![image](https://github.com/user-attachments/assets/229fc497-088c-4b1d-b89f-546bad39c7f0)

As you can see in the previous image, it was falling and suddenly, it was fixed

![image](https://github.com/user-attachments/assets/ebc10115-762f-4830-bbc7-03e9b3fa2205)

Is there any log I can check to see what happened last night?

Thanks!

**Comment by alexjustesen** [comment]
Unfortunately it's like the server you're trying to connect to isn't available. 

I would say Speedtest Tracker is "doing its job" letting you know you might have a connection problem but in this case wit might be the destination Ookla server you're having issues with.

**Comment by ehro78** [comment]
It is

**Comment by ehro78** [comment]
It is possible, but I still have some doubts... 

-First, I'm letting the cli choose the server... I'm not specifying one or a list of servers.
- Second, When the speedtest tracker is not working, I tried the test using the GUI from my windows laptop and it did worked. 

I think there is a problem I haven't found yet. I will continue observing this to try to figure it out and I will let you know.
