### ISSUE TITLE
Ping as string on influxdb

### ISSUE THREAD

**Issue by PedroBuffon** [alexjustesen/speedtest-tracker#1670]
So im creating a grafana dashboard getting values from influxdb2, while i was doing some graphs on latency related i see that the ping value from influxdb is retrieved as a string instead of a number and infludb gets the value from the speedtest-tracker too as a string, is this supposed to be this way? i`m using the latest version of speedtest-tracker, influxdb2 and grafana. The values of packet_loss and ping_jitter are in numbers, so thats right only ping is in string.

**Comment by alexjustesen** [comment]
Short answer, no it shouldn't be that way.

The InfluxDB integration needs a complete rewrite, likely with breaking changes to fix authentication and data quality/formats.

**Comment by PedroBuffon** [comment]
Ok, i saw too that you have a milestone for prometheus too, looking forward to it, i just use influxdb for the speedtest-tracker, the rest is all with prometheus, on the ping related matter i`m using a data transformation directly on grafana to convert it to a number as a workaround.
