### ISSUE TITLE
[Feature] Success/failure rate chart

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#1671]
> Let's extract the failed changes to a separate PR, helps me do reviews faster if I'm only testing 1 or a couple things. That being said I think I like the gap in charting more. We could introduce a new chart that's a "failure rate" progress bar chart to show success/failure rates.
>
> I'm happy to work on that one separately.

_Originally posted by @alexjustesen in https://github.com/alexjustesen/speedtest-tracker/issues/1669#issuecomment-2291511595_
            
### 🤔 Ideas
- https://flowbite.com/docs/components/progress/

**Comment by nandi95** [comment]
similar idea: if a threshold is defined, show a horizontal line on the download speed line chart at the point the threshold is defined.

**Comment by svenvg93** [comment]
Quick mockup 

![image](https://github.com/user-attachments/assets/2e49e001-9dd6-49ed-ab09-674efabf9f17)

Could also do a Stacked Bar Chart per month ofc

**Comment by svenvg93** [comment]
Leaving this here for later https://github.com/leandrocfe/filament-apex-charts?tab=readme-ov-file

**Comment by alexjustesen** [comment]
Linking to #509
