### ISSUE TITLE
Low or limited download speed when deployed in Docker in Proxmox LXC

### ISSUE THREAD

**Issue by Dillton** [alexjustesen/speedtest-tracker#1672]
Hello, 
I have deployed speedtest-tracker in Docker running in Synology DS218 plus NAS and it's working absolutely fine for approx. 2 months but it's not my main docker environment so I would like to migrate speedtest-tracker to my main docker running in proxmox lxc.
I have already deployed the app did all configuration which in the end was just a copy paste from the Synology deployment only difference is APP_KEY but for some reason there is a problem with this deployment.

My uplink is 1000/1000Mbps but for some reason the download speed in tests in proxmox is kind of limited to approximate maximum of 200Mbps but upload is always 900Mbps and more.
Synology deployment has both download and upload on high numbers as you can see the results from both Synology and Proxmox below.
Synology:
![image](https://github.com/user-attachments/assets/598ca6d6-a99c-4bec-bb01-f2890813959d)

Proxmox:
![image](https://github.com/user-attachments/assets/fe4e9d24-d325-45c4-aae1-8f2ee1ef8baf)

Can you point me somewhere what I should check or change some setting to make it work exactly as on Synology?
I think I checked everything regarding the network configurations and I am out currently of ideas.

**Comment by svenvg93** [comment]
How are the results when doing a Speedtest directly in the LXC or proxmox host?

**Comment by Dillton** [comment]
It's slow already on proxmox host.
![image](https://github.com/user-attachments/assets/f6fef85f-c5ba-4ee6-82f9-fddb2fb0c316)

**Comment by Dillton** [comment]
In the meantime I tried to replace LAN cable, change port on router, change port to switch.
Nothing of this helped. I am starting to think this would be a proxmox or NIC problem.

**Comment by Dillton** [comment]
Ok so found the solution.
I had to disable ASPM - Active-State Power Management in BIOS. No the speeds are perfect.
