### ISSUE TITLE
Tables interval input always reset to "Last 24h"

### ISSUE THREAD

**Issue by k-matti** [alexjustesen/speedtest-tracker#1682]
**Describe the bug**
I run speed test once a day so default "Last 24h" isn't very help. I want to **permanently** change it to "Last week". 
Is it possible?

**To Reproduce**
1. Change Last 24h to Last week
2. Go somewhere else
3. Go back and see Last 24h

**Expected behavior**
Tables input set to Last week

**Environment (please complete the following information):**
docker on Unraid

**Screenshots**
![obraz](https://github.com/user-attachments/assets/a666b93d-8d7b-4319-8a17-fb8323d37ae2)

**Comment by alexjustesen** [comment]
Closing since we attached this to #738
