### ISSUE TITLE
Scheduled?

### ISSUE THREAD

**Issue by chadgrant** [alexjustesen/speedtest-tracker#1684]
Doesn't seem to schedule anything which seems to defeat the entire purpose of this code

**Comment by svenvg93** [comment]
Hi @chadgrant, 

Can you share your configuration with us so we can help you out 😄.

As of version 0.20.x the schedule need to set in the docker environment files, as are the server etc. See https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0 for more information if you need to set these settings
