### ISSUE TITLE
[Feature Request] ability to use iperf3 over Speedtest-cli

### ISSUE THREAD

**Issue by rhcp011235** [alexjustesen/speedtest-tracker#1688]
First, I wanted to say, I love the work here! I love that you revamped this project! Excellent work!

i wanted to know if it was possible to add ipref3 as a possible speed test tool?

im on a multi gig (10ge and 25ge) and speedtest-cli doesn’t exactly play well with a multi gig connection.

thanks for all the hard work

**Comment by svenvg93** [comment]
Hi @rhcp011235, 

Its been listed in https://github.com/alexjustesen/speedtest-tracker/discussions/976, with sone others as well.
