### ISSUE TITLE
Show thresholds on graphs

### ISSUE THREAD

**Issue by MattIPv4** [alexjustesen/speedtest-tracker#1695]
**Is your feature request related to a problem? Please describe.**

When looking at the dashboard graphs for the tests, it can become hard to see the grid lines underneath to visually see where results fall compared to a threshold.

**Describe the solution you'd like**

It'd be great to visually demarkate the threshold for upload/download on the graphs, either as lines or colored overlays (like Grafana does).

**Additional context**

N/A

**Comment by svenvg93** [comment]
Hi @MattIPv4, 

Thanks for the suggestion 😃 .

In terms of the grapsh hard to read. There is a PR open that will give the ablitity to make reading the graph easier, as you can configure the chart not to chart at 0 anymore. It will show the fluctuation in speeds better.
https://github.com/alexjustesen/speedtest-tracker/pull/1669 

In terms of marking threshold breaches, This is on my list to add as well. It will be possible after merging https://github.com/alexjustesen/speedtest-tracker/pull/1677. Just need to find a good way of showing is 😉 Having some kind of overlay is a good idea!

**Comment by ric-m** [comment]
+1 from me also on this.

**Comment by alexjustesen** [comment]
Coming soon to a graph near you, closing...
