### ISSUE TITLE
Speedtests are not executed

### ISSUE THREAD

**Issue by TheImproof** [alexjustesen/speedtest-tracker#1696]
**Describe the bug**
I have a completely new installation of speedtest tracker running in a docker container on my new truenas system. Speedtests are not executed I think, at least they're staying at status started in the results tab.

Here's my docker compose:

services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=568
            - PGID=568
            - APP_KEY=base64:XXXXXXXXXXXXXXXXXX
            - APP_URL=XXXXXXXXXXXXXXXXX
            - APP_TIMEZONE=Europe/Berlin
            - DISPLAY_TIMEZONE=Europe/Berlin
            - PUBLIC_DASHBOARD=false
            - SPEEDTEST_PING_URL=https://www.google.de
            - SPEEDTEST_SCHEDULE=40 * * * *
            - SPEEDTEST_SERVERS=28818,53558,18613
            - DB_CONNECTION=sqlite
            - APP_DEBUG=true
        volumes:
            - /mnt/vol1/apps/speedtest-tracker:/config
            - /mnt/vol1/apps/speedtest-tracker/keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped

**Screenshots**
![image](https://github.com/user-attachments/assets/f69aa347-c5c7-47b1-be19-11b6e4930667)

**Logs**
I can't find any thing in the logs, but maybe I'm searching at the wrong place? In portainer when showing logs this is the output, even with APP_DEBUG=true:

[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    568
User GID:    568
───────────────────────────────────────
Linuxserver.io version: v0.21.2-ls43
Build-date: 2024-08-24T21:21:31+00:00
───────────────────────────────────────
    
using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.

**Additional context**
I also tried with another set of server ids and removing the variable completely but it didn't change the behavior.

**Comment by svenvg93** [comment]
Hi @TheImproof, 

If you login to the container and just run the `speedtest` command does it start a speedtest then?

**Comment by TheImproof** [comment]
Hi @svenvg93 

I had to accept license agreements and then it worked. But only in the shell, I queued a new speedtest now in the web gui and it stays at started.

**Comment by svenvg93** [comment]
Hi @TheImproof, 

Alright that is a good start. One thing that stands out in your config the ping url 

- SPEEDTEST_PING_URL=https://www.google.de/

can you change it to just `google.de`. https does not work when pinging. As its used to check for an internet connection it wont start the test as the ping fails.

**Comment by TheImproof** [comment]
Hi  @svenvg93 

that was it, thank you very much. I suggest marking the speedtests as failed then, when it ping doesn't work :)
