### ISSUE TITLE
Allow me to set Default timeframe on graphs

### ISSUE THREAD

**Issue by havedill** [alexjustesen/speedtest-tracker#1698]
The charting feature on the homepage defaults to 24 hour views. I would like to be able to change this to default to 7 days, etc. I only run 3 speed tests per day, so the graphic is relatively boring without zooming out.

I dont see this option anywhere in any of the menus

**Comment by svenvg93** [comment]
This will be possible after merging and releasing this pr https://github.com/alexjustesen/speedtest-tracker/pull/1669

**Comment by havedill** [comment]
Awesome, ty
