### ISSUE TITLE
Settings-general has disapeared

### ISSUE THREAD

**Issue by ArthurMitchell42** [alexjustesen/speedtest-tracker#1700]
On the home dashboard the settings-?general option appears to have gone and no schedualed tests are running in the latest version

**To Reproduce**
Simply log in and go to the home page

**Expected behavior**
You should be able to set a schedule

**Environment (please complete the following information):**
 - OS: Docker Ubuntu server
-  Architecture: amd64
 - Browser Firefox
 - Version 0.21.2

**Screenshots**
![image](https://github.com/user-attachments/assets/89241bd1-e7e5-49c1-a9a4-ff3a781f71bf)

**Comment by alexjustesen** [comment]
Please check out the release notes for the 0.20.x series: https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0
