### ISSUE TITLE
Home page wont load: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by gitmotion** [alexjustesen/speedtest-tracker#1702]
**Describe the bug**
Weirdly my instance was up and running just fine this morning and then noticed it went down just now. Looked into it and i was getting a 500 error as soon as I try to hit the page

**To Reproduce**
- load the site

**Expected behavior**
- should show the speedtest-tracker login page or dashboard

**Environment (please complete the following information):**
 - Docker
 - Mariadb

**Screenshots**
![image](https://github.com/user-attachments/assets/27c233c1-31ec-408e-a54e-23f5ba441b52)

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**
I've also tried add the below to the compose file but no help:
- SETTINGS_CACHE_ENABLED=false
- DB_SSLMODE=no-verify

**Comment by svenvg93** [comment]
Hi @gitmotion, 

Looking at the error it seems related to the database.
Did anything change in the database side? Was there a new image pulled or like username or password that changed/expired for example.

https://github.com/alexjustesen/speedtest-tracker/issues/1660 This seems to be the same(ish) problem.

**Comment by gitmotion** [comment]
thanks for the response @svenvg93! it's definitely a db issue, not sure what though. I haven't changed any of my environment variables and it broke while untouched. i've tried redeploying with as a container for both the speedtest-tracker and mariadb (both v10 and latest) but still ran into the same issue on a fresh install. seems to be related to authentication? decided to switch over to sqlite db and it works just fine but with a loss of history. but in either case it's fine, may look back on deploying with mariadb later

**Comment by svenvg93** [comment]
Either is authentication or somethings else why it's refusing the connection. 
In this case I would check if the user still has access to the DB. and if needed make a new user with access to test.

**Comment by gitmotion** [comment]
oh wow i figured it out, i deployed something different and accidentally added that database to the reverse proxy and it was mixing up the database connections based on the network -_- so my fault on this and all is good!
