### ISSUE TITLE
Container speedtest-tracker won't start

### ISSUE THREAD

**Issue by odurand75** [alexjustesen/speedtest-tracker#1703]
**Describe the bug**
The application won't start

**To Reproduce**
1. Installed the container on a Synology NAS 920+ using the provided instructions on  https://docs.speedtest-tracker.dev/getting-started/installation/synology
2. Started the container
3. Container did not start

**Expected behavior**
Container starts

**Environment (please complete the following information):**
 - OS: Synology NAS 920+ (DSM 7.2.1-69057 Update 5)
-  Architecture: INTEL Celeron J4125
 - Browser: N.A.
 - Version: v0.21.2

**Screenshots**
N.A.

**Logs**
See Attached for complete log
[speedtest-tracker.csv](https://github.com/user-attachments/files/16959432/speedtest-tracker.csv)

**Additional context**
N.A.

**Comment by svenvg93** [comment]
Hi @odurand75, 

The instructions for Synology are outdated. The best is to follow the steps for docker 

https://docs.speedtest-tracker.dev/getting-started/installation/installation

This line indicated there is come problem connection to the mysql database. 

`2024/09/11 14:54:08,stdout,"[2024-09-11 06:54:08] production.ERROR: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'forge' and table_type in 
`


If you could share some screenshots of the setup we can help you get up and running :)
