### ISSUE TITLE
APP_TIMEZONE list

### ISSUE THREAD

**Issue by mantaalex** [alexjustesen/speedtest-tracker#1717]
is there a list of APP_TIMEZONE= timezones ?
i'm here in belgium and i cannot select CEST only CET but the time is wrong

**Comment by svenvg93** [comment]
Hi @mantaalex, 

`APP_TIMEZONE` uses the normal timezone formats, As you are in belgium it will be `Europe/Brussels`
Additionally you need to set `DISPLAY_TIMEZONE` to the same timezone as well to have the interface show the correct time. 

You can as well use `CHART_DATETIME_FORMAT` and `DATETIME_FORMAT` to change the format of how the date and time are shown to your liking.  Check out https://docs.speedtest-tracker.dev/getting-started/environment-variables for all the needed information :)

**Comment by alexjustesen** [comment]
Additionally a full list can be found here: https://www.php.net/manual/en/timezones.php

**Comment by tushgaurav** [comment]
Thanks
