### ISSUE TITLE
Support nettest.com also

### ISSUE THREAD

**Issue by bogdanr** [alexjustesen/speedtest-tracker#1722]
[Open Nettest](https://nettest.com) provides an open-source platform for measuring speed. With it, we can measure the speed using servers independent of Ookla or ISPs and there are servers on all continents.

There is a nodejs client that could be used to implement Open Nettest as an alternative to Ookla: https://github.com/specure/open-rmbt-node

**Comment by alexjustesen** [comment]
Attaching to #976
