### ISSUE TITLE
500 error unsupported cypher

### ISSUE THREAD

**Issue by mikeyjjb** [alexjustesen/speedtest-tracker#1728]
Hi, I'm getting the following error;

Unsupported cipher or incorrect key length. Supported ciphers are:

aes-128-cbc, aes-256-cbc
aes-128-gcm, aes-256-gcm

This is my docker run;

docker run -d --name speedtest-tracker --restart always \
    -p 8093:80 \
    -p 8493:443 \
    -e PUID=1000 \
    -e PGID=1000 \
    -e APP_KEY=base64:pHUJgc4K8q3L9m0Qpe0RYFknG9tGjjIRBo \
    -e APP_DEBUG=true \
    -e DB_CONNECTION=sqlite \
    -e SPEEDTEST_SCHEDULE=@hourly \
    -e SPEEDTEST_SERVERS=12492 \
    -e PRUNE_RESULTS_OLDER_THAN= \
    -e CHART_DATETIME_FORMAT= \
    -e DATETIME_FORMAT= \
    -e APP_TIMEZONE= \
    -v /var/docker/speedtest/data:/config \
    -v /var/docker/speedtest/custom-ssl-keys:/config/keys \
    lscr.io/linuxserver/speedtest-tracker:latest

I'm a bit lost, can anyone give some advice¿

**Comment by svenvg93** [comment]
Hi @mikeyjjb, 

Can you share a screenshot of where you get the error? Is it from the application itself or your browser?

**Comment by mikeyjjb** [comment]
![Uploading Screenshot_20240925_190326_Firefox.jpg…]()

**Comment by mikeyjjb** [comment]
Thanks that worked perfectly, thanks for the help!
