### ISSUE TITLE
Cron not working

### ISSUE THREAD

**Issue by N47H4N** [alexjustesen/speedtest-tracker#1729]
**Describe the bug**
Cron schedule not working

**To Reproduce**
1. set SPEEDTEST_SCHEDULE to */5 * * * *
2. Wait but nothing happens

**Expected behavior**
Result in the dashboard every 5 minutes

**Environment (please complete the following information):**
 - OS: Unraid 6.12.13 + Docker from LinuxServer
-  Architecture: x64
 - Browser Edge
 - Version: App: 0.21.2

**Screenshots**
No screenshots needed, interface is empty without result

**Logs**
No logs, no error:
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: v0.21.2-ls46
Build-date: 2024-09-21T21:22:27+00:00
───────────────────────────────────────
    
Setting resolver to  10.2.0.1
Setting worker_processes to 16
generating self-signed keys in /config/keys, you can replace these with your own keys if required
[custom-init] No custom files found, skipping...
[ls.io-init] done.

**Additional context**
My docker config:
DB_CONNECTION:sqlite
APP_KEY:****
SPEEDTEST _SERVERS: 43030
SPEEDTEST _SCHEDULE:*/5 * * * *
APP_TIMEZONE:Europe/Zurich
DISPLAY_TIMEZONE:Europe/Zurich
APP_URL:https://192.168.20.103:9444/
APP_DEBUG:true

**Comment by alexjustesen** [comment]
Did you restart your container after changing your env variable?

**Comment by N47H4N** [comment]
yes

**Comment by svenvg93** [comment]
Do you see this in the webgui; 
<img width="470" alt="Scherm­afbeelding 2024-09-25 om 21 31 25" src="https://github.com/user-attachments/assets/41e141bd-cf47-4eba-ab26-6f00f5ff0751">

Does the speedtest work when you do a manual one?

**Comment by N47H4N** [comment]
I don't :(

![image](https://github.com/user-attachments/assets/ee3c3024-1cd2-45d8-ba55-b083998e8731)

**Comment by svenvg93** [comment]
Not sure if its a copying error but there is an space between SPEEDTEST and _SCHEDULE (same for the server btw)

**Comment by N47H4N** [comment]
I can't belive it was that easy. Nice catch.. sorry for the mistake

**Comment by svenvg93** [comment]
No worries man, happy it all works now :) Enjoy! 
Please close the issue if its all working good now :)

**Comment by stevehurcombe** [comment]
> Not sure if its a copying error but there is an space between SPEEDTEST and _SCHEDULE (same for the server btw)

That happened to me too. I copied it from here:
https://docs.speedtest-tracker.dev/getting-started/environment-variables

**Comment by alexjustesen** [comment]
Fixed, thanks!

**Comment by stevehurcombe** [comment]
It's still "odd":
![image](https://github.com/user-attachments/assets/a7b9ead1-1f0b-4b3f-9bd8-7167b6278fc6)
