### ISSUE TITLE
bash: app:result-fix-statuses: command not found

### ISSUE THREAD

**Issue by k-matti** [alexjustesen/speedtest-tracker#1736]
I want to run "app:result-fix-statuses:" to fix statuses in the results table as mentioned here https://docs.speedtest-tracker.dev/other/commands
But got this error "bash: app:result-fix-statuses: command not found" I run command in /app/www
I am using linuxserver docker image

**Comment by svenvg93** [comment]
Hi @k-matti, 

The full needed command is `php artisan app:result-fix-statuses`. That one should work when you are in the /app/www folder.
