### ISSUE TITLE
When running a scheduled test I get a low download result but if I run a manual test right after I get the correct result

### ISSUE THREAD

**Issue by rafapirotto** [alexjustesen/speedtest-tracker#1737]
**Describe the bug**
Scheduled results are inacurate (download speed is lower than what they are supposed to). When I run a manual test immediately after it shows the correct result

**To Reproduce**
1. Schedule a test
2. Wait for scheduled test
3. Run a manual test
4. Compare the manual vs scheduled download speed result

**Expected behavior**
Scheduled download speed result should be same as manual one

**Environment (please complete the following information):**
 - OS: docker inside ubuntu desktop
-  Architecture: amd64
 - Browser chrome
 - Version v0.21.2-ls45

**Screenshots**
![image](https://github.com/user-attachments/assets/4ad61c99-53e7-41ac-bccb-15acc63f3b24)

**Logs**
No errors in the logs

**Additional context**

**Comment by svenvg93** [comment]
We have seen this in the past, due to congestion on the network or server test run on hour mark might get lower results. We advise to run the test a couple of minutes after the hour make like 3 minutes for example. To get a more representative result's.

**Comment by rafapirotto** [comment]
I can confirm that your suggestion works!
