### ISSUE TITLE
Wrong Time

### ISSUE THREAD

**Issue by splitti** [alexjustesen/speedtest-tracker#1739]
**Describe the bug**
I always have a time difference of 2 hours. That means the time measurement takes place at 12 o'clock, but it is displayed as 10 o'clock.
I live in Germany, so I have tried various ways to provide the correct time. The Docker host has the correct time setting.
I have tried these parameters, all alternating with each other, but I have not come to a solution.
environment:
TZ=Europe/Berlin
APP_TIMEZONE=Europe/Berlin
volumes:
/etc/localtime:/etc/localtime:ro

**Expected behavior**
I would like to see the correct time displayed on the dashboard and the results page.

**Comment by svenvg93** [comment]
Hi, check out the other time environment options here https://docs.speedtest-tracker.dev/getting-started/environment-variables. Especially the display time zone one.

**Comment by ptcarino** [comment]
> Hi, check out the other time environment options here https://docs.speedtest-tracker.dev/getting-started/environment-variables. Especially the display time zone one.

what's the syntax for **DISPLAY_TIMEZONE**? is it a boolean or does it accept UTC timezone format like America/Chicago?

i tried setting TZ=America/Chicago too but to no effect.

**Comment by svenvg93** [comment]
It needs the timezone format like America/Chicago
Setting the `APP_TIMEZONE` as well will do the trick. I have set both.

**Comment by splitti** [comment]
Wow, so simple and i searched hours for a solution. Thx!

**Comment by ptcarino** [comment]
> It needs the timezone format like America/Chicago Setting the `APP_TIMEZONE` as well will do the trick. I have set both.

this worked. thanks! the docs may need to reference the syntax for DISPLAY_TIMEZONE though.
