### ISSUE TITLE
Help Forum

### ISSUE THREAD

**Issue by ric-m** [alexjustesen/speedtest-tracker#1740]
Afternoon,
Is there a help forum?
Ric

**Comment by svenvg93** [comment]
Hi, 

No there is no help forum, feel free to ask for help here or in the discussions

**Comment by alexjustesen** [comment]
If you have general questions please use the discussions, opening an issue should be used for bugs or feature requests.

https://github.com/alexjustesen/speedtest-tracker/discussions
