### ISSUE TITLE
Showing correct status for the speed tests going to run on servers which do not exist anymore

### ISSUE THREAD

**Issue by armond-avanes** [alexjustesen/speedtest-tracker#1743]
The issue of "Started but not completed" speed tests has been discussed in a couple of other tickets including the following:
https://github.com/alexjustesen/speedtest-tracker/issues/1591

My request is that SpeedTest-Tracker shows the correct status for such failed tests, instead of just showing "Started" with no further data or error message for that record. Something like "Server not exist/available" and the Server ID should also be included on the record. Or the status could be "Error" with some description/comment on that test record explaining the actual failure reason (no such server ID exists).

Currently the only thing you see are the timestamp and the test ID. By seeing the Server ID and the correct status, admins will be able to quickly identify the servers which do not exist anymore. And if it happens all the time for the same server(s), they'll know that they need to remove those servers from the servers list.

**Comment by svenvg93** [comment]
This will be fixed with the merge of https://github.com/alexjustesen/speedtest-tracker/pull/1679 
It will show the correct status, server id and the error message returned by the Ookla client.

**Comment by armond-avanes** [comment]
Thank you! The PR is exactly what I need!

Is there any ETA on when you're planning to merge it? Looks like you've been going back and forth on this PR for the past two months.

**Comment by armond-avanes** [comment]
@alexjustesen Is there any ETA for the PR discussed above?
