### ISSUE TITLE
Run a speedtest with ookla cause a 500 error

### ISSUE THREAD

**Issue by SiriosDev** [alexjustesen/speedtest-tracker#1744]
**Describe the bug**
Run a speedtest with ookla cause a 500 error

**To Reproduce**
1. Open `speed tracker`
2. Click on `Run Speedtest`
3.  Click on `Ookla Speedtest`

**Environment (please complete the following information):**
 - OS: Debian 12 (Docker)
-  Architecture: amd64
 - Browser chrome
 - Version 0.21.2

**Screenshots**
![image](https://github.com/user-attachments/assets/659b99c3-977f-4418-8b20-c8f223b038b3)
![image](https://github.com/user-attachments/assets/47dd7b0c-ff3a-4739-8ddb-36e4c44f8176)

**Logs**
```log
TypeError
App\Actions\Speedtests\RunOoklaSpeedtest::handle(): Argument #1 ($serverId) must be of type ?int, string given, called in /app/www/vendor/lorisleiva/laravel-actions/src/Concerns/AsObject.php on line 24
```

**Comment by svenvg93** [comment]
How did you defined the server id's in the env variables?

They shoud be defined like below when using multiple servers.
`SPEEDTEST_SERVERS=3242,21509,61186`

For a single server its like this 
`SPEEDTEST_SERVERS=3242`

**Comment by SiriosDev** [comment]
my bad I forgot to post the compose, I can't post it now, but this is certainly the fix, my brain skipped `id divided by commas` and so I entered `domains divided by commas`. I feel stupid for not noticing this after reading it so many times 🤦🤣 Thanks You Very Much

**Comment by svenvg93** [comment]
No worries 😄  let us know if there are any problems after changing it to the ID's. Otherwise please close the issue if all works :)

**Comment by SiriosDev** [comment]
yep, worked thx 🙏
