### ISSUE TITLE
How to schedule a rountine speedtests?

### ISSUE THREAD

**Issue by WanKa-zone** [alexjustesen/speedtest-tracker#1745]
I tried looking in dev, but could not find any page had mentioned about how to create routine speedtests.
![image](https://github.com/user-attachments/assets/9ff0a4be-c8b6-4ea5-a2c4-3d9509ba25eb)

**Comment by svenvg93** [comment]
Hi! 

As part of your docker compose you will have a environment section that contains the schedule.
For example like this;
```
environment:
  SPEEDTEST_SCHEDULE="6 */2 * * *"
```
This example is At minute 6 past every 2nd hour.
On https://crontab.guru/ you can make your own schedule, you can change it, only chante the part that is between the ""  and restart the container to apply them.
