### ISSUE TITLE
[CR] New Features Custom columns in test results list

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#175]
It would be nice to be able to customize the columns and reduce the font size in the test results table. 
For example I would like to hide the "View On Speedtest.net" column

![Cattura](https://user-images.githubusercontent.com/5001932/203823749-e0a5fd77-2ad0-42cd-8a93-e682e0e91515.PNG)

Thank you and congratulations, the project is very beautiful
:-)

**Comment by alexjustesen** [comment]
Thanks for the suggestion, going to close this and track it in #48
