### ISSUE TITLE
No Speedtest result 

### ISSUE THREAD

**Issue by Tchet33** [alexjustesen/speedtest-tracker#1750]
Hello, 
I just install speedtest-tracker with docker compose and I can’t see any result.

The Speedtest stay in started status. 

```python
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1026
            - PGID=100
            - APP_KEY=base64:Wf6ZVrVBQtgxan6u94rJej44uTXPZl/Ci7lfQI1kdcc=
            - DB_CONNECTION=sqlite
            - DB_HOST=/config/database.sqlite
            - SPEEDTEST_SCHEDULE=16 */3 * * *
            - SPEEDTEST_SERVERS=62028,32438,58159
            - PRUNE_RESULTS_OLDER_THAN=7
            - CHART_DATETIME_FORMAT=j.M.Y
            - DATETIME_FORMAT=j.M.Y
            - APP_TIMEZONE=Europe/Paris
            - DISPLAY_TIMEZONE=Europe/Paris
            - TZ=Europe/Paris
            - APP_DEBUG=true
        volumes:
            - /volume1/docker/speedtest/config
            - /volume1/docker/speedtest/config/key
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
``` 
![IMG_7760](https://github.com/user-attachments/assets/8b9a44d1-03ea-4e69-89b1-8e558adde89a)
![IMG_7761](https://github.com/user-attachments/assets/7eb54fa4-42ca-42b7-94a8-d3f68240c500)

**Comment by svenvg93** [comment]
Hi @Tchet33, 

Looking at your compose it all looks fine. 
The `- DB_HOST=/config/database.sqlite`. This not needed when using sqlite. 

That is stays in status Started means the somewhere the test is failing. 
When you login the container can you run a speedtest directly?

**Comment by svenvg93** [comment]
Depending on the error it returns it might be that the container does not have internet access. Speedtest CLI will connect to the server on port 8080.

**Comment by Tchet33** [comment]
Sorry I don't know the CLI comand tu run a speed test in to the CLI.
I think your right from CLI I can't ping 8.8.8.8,but in the firewall of the Synology NAS I open 8080 and 8443 ports

**Comment by svenvg93** [comment]
If you can't ping 8.8.8.8 that means that the container has no internet connection al all. 
The command to run the speedtest from the CLI is `speedtest`.

**Comment by Tchet33** [comment]
![Capture2](https://github.com/user-attachments/assets/6e47e57d-7a8e-49d9-b25b-a47bafa2f6d3)

Thanks, its the same issue like the other post, when i turn off my firewall its ok.

I must find the rule who block it

**Comment by alexjustesen** [comment]
Closing as this seems to be narrowed down to the devices firewall.
