### ISSUE TITLE
Update Docker Hub Image

### ISSUE THREAD

**Issue by war59312** [alexjustesen/speedtest-tracker#1757]
Hi,

First off, thank you for this.

Could we please get the Docker Hub Image at https://hub.docker.com/r/ajustesen/speedtest-tracker updated?

Seems been 6 months since last update.

Best,

Will

PS: Recommend updating the overview page as well.

**Comment by svenvg93** [comment]
That image is no longer maintained, check out  https://github.com/alexjustesen/speedtest-tracker/issues/1117. Docker image is now maintained by LinuxServer.io 😊

**Comment by war59312** [comment]
Got it, thanks. Yea totally missed that. Should update that page to mark as such then..

Anyhow, knocking out new setup via https://mariushosting.com/synology-install-speedtest-tracker-with-portainer/

**Comment by alexjustesen** [comment]
> PS: Recommend updating the overview page as well.

Can you drop a URL to the page?

**Comment by svenvg93** [comment]
@alexjustesen This is the link to the old docker hub image https://hub.docker.com/r/ajustesen/speedtest-tracker

**Comment by alexjustesen** [comment]
There isn't a way to mark the image as deprecated but I'll update the overview description so it's clear on docker hub.
