### ISSUE TITLE
500 Oops, server error!

### ISSUE THREAD

**Issue by Roycinger** [alexjustesen/speedtest-tracker#1758]
**Describe the bug**
After deploying the container, the page shows an error 500

**To Reproduce**
1. load the website

**Expected behavior**
not a 500 error :)

**Environment (please complete the following information):**
 - OS: debian
-  Architecture: amd64
 - Browser: Chrome, Firefox

**Screenshots**
![image](https://github.com/user-attachments/assets/a49fc6fc-3d05-4837-be26-207e2422575d)

**Logs**
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: v0.21.4-ls49
Build-date: 2024-10-10T00:44:21+00:00
───────────────────────────────────────    

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.

**Additional context**
I set APP_DEBUG=true but it won't show any usable issue.

Thanks for assistance!

**Comment by FearNaBoinne** [comment]
Same here, deploying in a container on Synology (x86) NAS:

My log keeps repeating (Cannot change the log sort direction on the NAS!):
```
2024/10/13 11:46:22	stdout	  Context: {"exception":{"errorInfo":null,"connectionName":"sqlite"}}          
2024/10/13 11:46:22	stdout	  "key" in (laravel_cache_illuminate:queue:restart))                           
2024/10/13 11:46:22	stdout	  ath to the database. (Connection: sqlite, SQL: select * from "cache" where   
2024/10/13 11:46:22	stdout	  /www/database/database.sqlite] does not exist. Ensure this is an absolute p  
2024/10/13 11:46:22	stdout	  The exception occurred while attempting to log: Database file at path [/app  
2024/10/13 11:46:22	stdout	  in append mode: Failed to open stream: Permission denied                     
2024/10/13 11:46:22	stdout	  The stream or file "/app/www/storage/logs/laravel.log" could not be opened   
2024/10/13 11:46:22	stdout	                                                                               
2024/10/13 11:46:22	stdout	In StreamHandler.php line 140:
```

**Comment by svenvg93** [comment]
Hi @Roycinger 

Which error is shown on the webpage when you turn on `APP_DEBUG` and restart the container? 

-- 

Hi @FearNaBoinne 

How does your compose looks? Seems that some path are not existing. Sqlite DB should be made automatically when starting the container for the first time.

**Comment by FearNaBoinne** [comment]
Compose.yml:
```services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 6080:80
            - 6443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:BxSP5IAXtG2EY0XiwxYh2g6kh5U0L11Z97E7A5tu5og=
            - APP_URL=https://10.50.164.9:6443/
            - APP_DEBUG=1
            - DB_CONNECTION=sqlite
        volumes:
            - /volume2/SSD-Share/Speedtest/config:/config
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped```

From CLI:
```[FNB-user]@SynoNAS:/volume2/SSD-Share/Speedtest/config$ pwd
/volume2/SSD-Share/Speedtest/config
[FNB-user]@SynoNAS:/volume2/SSD-Share/Speedtest/config$ ll
total 4
drwxrwxrwx+ 1     1000  1000  88 Oct 13 12:19 .
drwxrwxrwx+ 1 [FNB-user] users  36 Oct 13 11:41 ..
-rwxrwxrwx+ 1     1000  1000   0 Oct 13 12:16 database.sqlite
drwxrwxrwx+ 1     1000  1000  32 Oct 13 11:46 keys
drwxrwxrwx+ 1     1000  1000  38 Oct 13 11:46 log
-rwxrwxrwx+ 1     1000  1000  28 Oct 13 11:46 .migrations
d----w----  1     1000  1000 212 Oct 13 12:16 nginx
drwxrwxrwx+ 1     1000  1000  44 Oct 13 11:46 php
drwxrwxrwx+ 1     1000  1000  36 Oct 13 11:57 www```

**Comment by Roycinger** [comment]
> Hi @Roycinger
> 
> Which error is shown on the webpage when you turn on `APP_DEBUG` and restart the container?
> 
> --
> 
> Hi @FearNaBoinne
> 
> How does your compose looks? Seems that some path are not existing. Sqlite DB should be made automatically when starting the container for the first time.

Basically the same as before I added APP_DEBUG=true:
![image](https://github.com/user-attachments/assets/55c1a2d9-bbcf-4f96-a8ab-0145027ed056)

**Comment by FearNaBoinne** [comment]
> Basically the same as before I added APP_DEBUG=true: 

Try 'APP_DEBUG=1'

**Comment by Roycinger** [comment]
> > Basically the same as before I added APP_DEBUG=true:
> 
> Try 'APP_DEBUG=1'

same result

**Comment by FearNaBoinne** [comment]
Fixed it for *my* situation by adding 'everyone' to the config folder with +RW in filemanager on Synology... May be a bit too much, but I'll work on finding the correct user to 'allow' eventually!

**Comment by svenvg93** [comment]
> > Hi @Roycinger
> > Which error is shown on the webpage when you turn on `APP_DEBUG` and restart the container?
> > --
> > Hi @FearNaBoinne
> > How does your compose looks? Seems that some path are not existing. Sqlite DB should be made automatically when starting the container for the first time.
> 
> Basically the same as before I added APP_DEBUG=true: ![image](https://private-user-images.githubusercontent.com/7791335/376026294-55c1a2d9-bbcf-4f96-a8ab-0145027ed056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDE5ODgsIm5iZiI6MTcyODg0MTY4OCwicGF0aCI6Ii83NzkxMzM1LzM3NjAyNjI5NC01NWMxYTJkOS1iYmNmLTRmOTYtYThhYi0wMTQ1MDI3ZWQwNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTNUMTc0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MThiNmJiYmU4NTY0YzUxYjI1MTNiNmZjMGViMjYzNmY0MTFmZDY5MTg4Yjg2NzYwZDFhMDA4ZGYzYjM2Yjc5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ca7ViRphikkDzlpqKSv8waPcrs9hk0CG_vHFMzj6UoQ)

Did you restart / redeploy the container there should be something in blue page showing up with the more details error.

**Comment by Roycinger** [comment]
> > > ## Hi @Roycinger
> > > Which error is shown on the webpage when you turn on `APP_DEBUG` and restart the container?
> > > Hi @FearNaBoinne
> > > How does your compose looks? Seems that some path are not existing. Sqlite DB should be made automatically when starting the container for the first time.
> > 
> > 
> > Basically the same as before I added APP_DEBUG=true: ![image](https://private-user-images.githubusercontent.com/7791335/376026294-55c1a2d9-bbcf-4f96-a8ab-0145027ed056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDE5ODgsIm5iZiI6MTcyODg0MTY4OCwicGF0aCI6Ii83NzkxMzM1LzM3NjAyNjI5NC01NWMxYTJkOS1iYmNmLTRmOTYtYThhYi0wMTQ1MDI3ZWQwNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTNUMTc0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MThiNmJiYmU4NTY0YzUxYjI1MTNiNmZjMGViMjYzNmY0MTFmZDY5MTg4Yjg2NzYwZDFhMDA4ZGYzYjM2Yjc5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ca7ViRphikkDzlpqKSv8waPcrs9hk0CG_vHFMzj6UoQ)
> 
> Did you restart / redeploy the container there should be something in blue page showing up with the more details error.

Yes, several times. 
I put the APP_DEBUG=true here, I hope that's the right place:
![image](https://github.com/user-attachments/assets/9284de90-2b2c-4578-ad8d-b528ea3a33c2)

**Comment by svenvg93** [comment]
Do you have the full app key set in environment value?
Make sure it contains the base64 at the start and the = at the end.

**Comment by Roycinger** [comment]
> Do you have the full app key set in environment value? Make sure it contains the base64 at the start and the = at the end. And no additional spaces etc.

Yes sir:
https://github.com/alexjustesen/speedtest-tracker/issues/1758#issuecomment-2409121022

**Comment by Roycinger** [comment]
issue solved
