### ISSUE TITLE
InfluxDB error: partial write: field type conflict

### ISSUE THREAD

**Issue by bvarick** [alexjustesen/speedtest-tracker#1762]
I am running speedtest-tracker in a docker container (from the latest lsio image), that sends the data to influxdb (also a docker container). It's been working great for months. A few days ago (with no configuration changes), the data stopped flowing from speedtest-tracker. 

Here is the error log:
```
speedtest-tracker  | [2024-10-16 13:37:12] production.INFO: InfluxDB2\ApiException: [422] Error connecting to the API (https://influxdb.domain.com/api/v2/write?org=xxxxxxxxxxxxx&bucket=speedtest&precision=s)(failure writing points to database: partial write: field type conflict: input field "download_latency_avg" on measurement "speedtest" is type float, already exists as type integer dropped=1) in /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php:164

```

any suggestions how to resolve this?

**Comment by Ja50n-Kru** [comment]
I have just suddenly got this after my container updated to 

- Linuxserver.io version: v0.21.6-ls56
- Build-date: 2024-11-14T12:21:20+00:00

My error:

`[2024-11-16 13:18:12] production.INFO: InfluxDB2\ApiException: [422] Error connecting to the API (http://xxx.xxx.xxx.xxx/api/v2/write?org=Home&bucket=speedtest-tracker&precision=s)(failure writing points to database: partial write: field type conflict: input field "download_jitter" on measurement "speedtest" is type float, already exists as type integer dropped=1) in /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php:164`

How to fix? This now happens every time it tries to log - worked perfectly well before the update to the latest container. Thanks.
