### ISSUE TITLE
General Settings section missing.

### ISSUE THREAD

**Issue by chayde** [alexjustesen/speedtest-tracker#1766]
**Describe the bug**

When loading speedtest tracker for the first time, after initial login the General section under setting is missing. I see the section in screenshots for the documentation but my instance does not have a General section to click on. 

**To Reproduce**
I log into the application using the default credentials and the General section is missing from the settings area. 

**Expected behavior**
I would expect a general settings section so I could schedule speedtests, etc. 

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
-  Architecture: [e.g. arm64, amd64]
 - Version [e.g. v1]
 
OS: Ubuntu 22.04 LTS (server)
Docker: Docker version 27.3.1, build ce12230
Docker Compose: Docker Compose version v2.29.7
Docker Image: Linuxserver.io version: v0.21.4-ls50 | Build-date: 2024-10-15T13:29:18+00:00
Client OS: Windows 11
Browser: multiple tested Chrome, Edge, Arc

**Screenshots**
![speedtesttracker](https://github.com/user-attachments/assets/c1a24b80-e175-45e2-8200-6ae4992e5543)

**Logs**
If applicable, check the logs for any error that might of occurred.
I'm not sure how to check for errors in the logs for a missing menu item but if someone provides commands or a log file to check I can do so. 

**Additional context**

**Comment by svenvg93** [comment]
Hi @chayde, 
The General Settings have been removed in an earlier release see  https://github.com/alexjustesen/speedtest-tracker/discussions/1470 for more information. 

The screenhost have not been updated yet,
