### ISSUE TITLE
HASS Integration

### ISSUE THREAD

**Issue by albeedelacruz** [alexjustesen/speedtest-tracker#1769]
Is there a way to integrate this with Home Assistant. I'd like to be able to add automations when I don't get the desired speed from my ISP.--such as switching to back up, notifications, or something else. Would be fun to have this feature, I love your work!

**Comment by svenvg93** [comment]
There is no integration at the moment. Check out https://github.com/alexjustesen/speedtest-tracker/issues/1586 as there are some workarounds shown by others for now.

**Comment by albeedelacruz** [comment]
Solved
