### ISSUE TITLE
Custom Server in Results

### ISSUE THREAD

**Issue by gnwoodward** [alexjustesen/speedtest-tracker#1773]
I am extremely appreciative of the work that's been done on this, and I use it to hold my ISP accountable for subscribed speeds and daily speed tests from other sources.

**Is your feature request related to a problem? Please describe.**
Not a problem - this is a feature request to add more server detail/location

**Describe the solution you'd like**
In the environment section in my YAML I have added 5 servers. It would be beneficial to add a custom description since the provider has the same name, but they are in different locations and, unfortunately, are other services (Cable, Fiber, Wireless)

An example of what I currently see in Results is:
ID - Server ID - Download - Upload - Ping - Status - Created
AP&T - 10367 -  900 Mbps - 55 Mbps - 18ms - Completed - Oct 31

Ideally, if we were able to customize the server, it would change the first ID field:
AP&T (DSL - Juneau, AK) - 10367 - 900 Mbps - 55 Mbps - 18ms - Completed - Oct 31

Adding a separate Location field would also be helpful.

ID - Location - Server ID - Download - Upload - Ping - Status - Created

**Additional context**
If there is a way to customize the output to display the above request and I missed the documentation on that, I apologize.
Please keep up the great work!

**Comment by svenvg93** [comment]
Hi @gnwoodward, 

The server location is already present in the results table, just not enabled by default. You can enable it by clicking on the three columns in the top right corner of the table.

**Comment by gnwoodward** [comment]
Amazing. Thank you. I'll be donating to further support your awesome wrok.

**Comment by gnwoodward** [comment]
Is there a way to modify the width of the results page to remove the scrollbar, by chance?
