### ISSUE TITLE
ATT Speedtest Server no longer working

### ISSUE THREAD

**Issue by andrewjmoser** [alexjustesen/speedtest-tracker#1774]
I noticed my speedtest results started to be very erratic around 10/25/24.  I run a test every hour, and I had not specified a specific server ID to use for my tests, but it seemed to always default to ATT, Server ID 47749, my ISP is ATT.    Every test before 10/25/24, was hitting that ATT server ID.    After that, it was just hitting any of the random servers in my area.   Did something happen to the ATT Server ID 47749?   I tried to force it in my container with the - SPEEDTEST_SERVERS= 47749 setting, but every test using it fails.  When I go to https://c.speedtest.net/speedtest-servers-static.php I do not see the ATT server as an option.    Running a direct test from my ATT Modem, I get basically line speeds as expected.   Is there a way I can figure out what server is needed for ATT or what happened to it?   

I'm using Docker, with the latest release of speedtest-tracker.

<img width="1006" alt="Screenshot 2024-11-01 at 9 36 27 AM" src="https://github.com/user-attachments/assets/ffa9eece-b802-47dc-a5f0-87e5110412cf">

**Comment by svenvg93** [comment]
HI @andrewjmoser, 

It seems that server id 47749 no longer exists as it returns an error when testen on it, and like you said it does not show up on the speedtest.net website anymore. The only one how can tell you what happend to the server is AT&T themself 😅 .

```
speedtest -s 47749
[error] Configuration - No servers defined (NoServersException)
```

If you want to specify a server in your config make sure there is no space between the = and the server id 😉 .
