### ISSUE TITLE
Only able to show speeds for the last month, am I missing something, or would it be a feature request

### ISSUE THREAD

**Issue by PlasmaSoftUK** [alexjustesen/speedtest-tracker#1776]
Been running this since September but the graph only has the option for speeds over the last month, is it possible to make it save/show more of the readings. I would ideally like to be able to look at the speeds over the last 6 months or a year?

When I look at the results page they are there all the way back to Sept, but the graph only offer 24hrs, Last Week, Last Month

**Comment by alexjustesen** [comment]
Expanded timeframes for charts are planned for a future release, if you want to look at more history I suggest exporting the results and charting them in Excel for now.
