### ISSUE TITLE
Telegram Notifikation on Test missing since Update to 0.23.0

### ISSUE THREAD

**Issue by AleksCee** [alexjustesen/speedtest-tracker#1808]
**Describe the bug**
I get no telegram notifications any more.

**To Reproduce**
run a test or wait for scheduled test

**Logs**
The only logs I found after a test run:

2024-11-22 18:35:16] production.ERROR: mb_convert_case(): Argument #1 ($string) must be of type string, App\Enums\ResultService given {"exception":"[object] (TypeError(code: 0): mb_convert_case(): Argument #1 ($string) must be of type string, App\\Enums\\ResultService given at /app/www/vendor/laravel/framework/src/Illuminate/Support/Str.php:1366)
[stacktrace]
#0 /app/www/vendor/laravel/framework/src/Illuminate/Support/Str.php(1366): mb_convert_case()
#1 /app/www/app/Listeners/Telegram/SendSpeedtestCompletedNotification.php(38): Illuminate\\Support\\Str::title()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): App\\Listeners\\Telegram\\SendSpeedtestCompletedNotification->handle()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(473): Illuminate\\Events\\Dispatcher->dispatch()
#6 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php(14): event()
#7 /app/www/app/Jobs/Ookla/RunSpeedtestJob.php(79): App\\Events\\SpeedtestCompleted::dispatch()

**Comment by AleksCee** [comment]
I temporarily fix it local in my docker container by editing the line 38 in the exception line 2 like this:
    'service' => Str::title($event->result->service->getLabel()),   
    
And restart the container. But I don‘t know is this a problem in every notification class, umhabet only show for this exception.

**Comment by Aristocrat-jt** [comment]
Has this been fixed? I'm on 0.23.1, and I don't see a Telegram test button.

**Comment by socekin** [comment]
Has this been fixed? I'm on 1.0.2 and  don't see a Telegram test button.
