### ISSUE TITLE
[CR] New Feature Request: date and time of the last test performed

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#182]
It would be nice if, like in henrywhitaker3's project, the Dashboard showed the date and time of the last test performed
Thanks

![Cattura1](https://user-images.githubusercontent.com/5001932/204145859-bd18a154-925f-4482-b805-6e66ecf192b1.PNG)
![Cattura2](https://user-images.githubusercontent.com/5001932/204145960-a5123e5a-ce37-42b9-bc11-0f9322cf8560.PNG)

**Comment by alexjustesen** [comment]
Good coverage point, I'll add it to the next release

**Comment by corasaniti** [comment]
Hi, this feature was added in version 0.50? I can't see it. 
Thank you

**Comment by alexdelprete** [comment]
> this feature was added in version 0.5.0? I can't see it.

you can see the changelog here: https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.5.0

It hasn't been added. Is it urgent?

**Comment by alexjustesen** [comment]
Yeah didn't have time in this release, hit the low hanging fruit instead.

**Comment by corasaniti** [comment]
@alexjustesen Thanks
