### ISSUE TITLE
High values are not shown on download latency chart 📊.

### ISSUE THREAD

**Issue by gorucci** [alexjustesen/speedtest-tracker#1825]
**Describe the bug**
High values are not shown on download latency chart. Some of my test results have high (pardon the repetition) "high download latency". To be specific, the 2 that are missing on a graph are 1006ms and 1102ms. This makes chart discontinuous.

**To Reproduce**
1. Somehow get a result with more than 1000ms (not sure for the exact value) high download latency.
2. Go to `/admin` aka Dashboard.
3. Scroll down to "Download Latency" chart.
4. See error.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: linuxserver/speedtest-tracker:0.23.1 container inside an ubuntu-server 24.04.
-  Architecture: amd64
 - Browser: macOS safari, iOS safari, macOS chrome, Windows chrome
 - Version 0.23.1

**Screenshots**
![image](https://github.com/user-attachments/assets/2566ae1b-27ac-4e9f-a4d9-6cbc6532450a)

**Logs**
Results have no error messages.

**Additional context**
None.

**Comment by gorucci** [comment]
Wow! That was crazy fast! Like, you know, off the charts fast (pun intended). Thank you.

TBH, I've tried to find a bug myself, like searching for the `1000` constant or analysing RecentDownloadLatencyChartWidget. But my lack of experience in PHP made this too tough 🥲. I had hope that your charts were made with some kind of JS lib.

**Comment by alexjustesen** [comment]
`number_format()` function is what got us because it added a comma to the int which made it a string which the charts didn't like.
