### ISSUE TITLE
Make IP lookup service configureable

### ISSUE THREAD

**Issue by pkirsche** [alexjustesen/speedtest-tracker#1838]
**Is your feature request related to a problem? Please describe.**
After upgrading the docker image to an image above 0.21.6, no speedtests are performed anymore, they all results in an error immediately. Changing back to image 0.21.6 makes the speedtest work again. It's just switching the container image, no configuration changes.

So I digged a bit deeper and examined the container itself as well as the error message shown in webinterface.
The error reported within the failed speedtest run is:

`Failed to fetch external IP address, server is likely unable to connect to the internet.`

Inside the container, connectivity to the internet is fine. I can ping, curl and lookup dns names with v0.22.0 and above (even tested 0.24.1 today)
Also nothing than the image itself has changed on my docker host, so even here, the new image seems to be the problem.

Finally I checked the laravel.log and I think I found the reason:

`[2024-11-25 20:04:37] production.ERROR: Failed to fetch external IP address. ["cURL error 60: SSL certificate problem: self-signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://icanhazip.com/"]`

I only see this error message with images since 0.20.0 and above, not with the working 0.21.6 and below versions.
This hinted me to an issue with https://icanhazip.com/, which seems to be used to get the external IP address within the newer containers.
But unfortunately, I am using nextdns as my private dns server which blocks unwanted and malicious sites. And for what reason ever, https://icanhazip.com/ is on one of the blacklists too.

Problem was solved (hopefully only for some time) by whitelisting within nextdns service.

**Describe the solution you'd like**
Can you please consider to implement an option (either via gui or env) to configure the IP detection service? There are some other services, I even host one myself.
I really don't know if https://icanhazip.com/ is really any harmful, but it seems to add an unneccessary dependency for such a great tool your speedtest-tracker is. Making it configureable also indicates to this behavior if set as default value within the documentation.

Please keep up the phenomenal work and thanks for all your effords until this point. I really love your speed-tracker.

**Comment by alexjustesen** [comment]
So canihazip.com is a Cloudflare tool which simply returns the external IP of the request, pretty harmless in my opinion. 

I suggest adding it to an allow list if possible in Nextdns, I made a note here in the docs for AdGuard and Pi-hole as well: https://docs.speedtest-tracker.dev/help/faqs#adguard-and-pi-hole-allow-domains.

I'm going to leave this issue open for the time being so I can evaluate other services/patterns.

**Comment by aaronspruit** [comment]
I was running into the same issue after upgrading from 0.20.7.  I would highly recommend updating the documentation that this be added to the error message documentation.

**Comment by svenvg93** [comment]
> I was running into the same issue after upgrading from 0.20.7. I would highly recommend updating the documentation that this be added to the error message documentation.

Got it covered in https://github.com/alexjustesen/speedtest-tracker-docs/pull/48

**Comment by alexjustesen** [comment]
Closing as checking for an internet connection is baked into the "health" checking when running the speedtest process.
