### ISSUE TITLE
 Daylight Saving Time is not switching back to Standard Time

### ISSUE THREAD

**Issue by leuchtrakete666** [alexjustesen/speedtest-tracker#1840]
**Describe the bug**
 Daylight Saving Time is not switching back to Standard Time

**To Reproduce**
1. Enter a timezone like Europe/Vienna in the environment variables.
2. Wait until the switch date.
3. The time is not changed.
4. I am using the variables TZ, APP_TIMEZONE and DISPLAY_TIMEZONE

**Expected behavior**
A shift of 1 hour.

**Comment by alexjustesen** [comment]
Try dropping `TZ`, you don't need this variable and in the past it's caused some issues at the container level.
