### ISSUE TITLE
Add armv7 support

### ISSUE THREAD

**Issue by hydezhao** [alexjustesen/speedtest-tracker#1848]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to the docker image on armv7 devices.

**Describe the solution you'd like**
Build and release armv7 docker images

**Comment by svenvg93** [comment]
The docker image is being build and maintained by [LinuxServer.io ](https://github.com/linuxserver/docker-speedtest-tracker). Unfortunately they [dropped support](https://www.linuxserver.io/blog/a-farewell-to-arm-hf) for armv7 a while ago.
