### ISSUE TITLE
Mail body content include details

### ISSUE THREAD

**Issue by garanda21** [alexjustesen/speedtest-tracker#185]
When you setup a mail notification channel and receive that email, there's no details on its content. it just a link to `http://localhost/admin/results`.

It would be nice if the mail could have the Speed test details, like ping, download and upload or even better that you can setup the body parameters that you wanna receive.

This is the actual body that I get:
![IMG_F214C5E42EBC-1](https://user-images.githubusercontent.com/9530250/204505178-23710f33-4fff-44d9-bafb-57b270df2852.jpeg)

PS. Also, if you can check, the mail send links to localhost, maybe add the chance to enter your actual IP Server. 

Thanks

**Comment by alexjustesen** [comment]
> When you setup a mail notification channel and receive that email, there's no details on its content. it just a link to `http://localhost/admin/results`.
> 
> It would be nice if the mail could have the Speed test details, like ping, download and upload or even better that you can setup the body parameters that you wanna receive.
> 
> This is the actual body that I get: ![IMG_F214C5E42EBC-1](https://user-images.githubusercontent.com/9530250/204505178-23710f33-4fff-44d9-bafb-57b270df2852.jpeg)
> 
> PS. Also, if you can check, the mail send links to localhost, maybe add the chance to enter your actual IP Server.
> 
> Thanks

Good suggestion on the more content, also the url is based off `APP_URL` in the `.env` file. So you can always change your IP address there.

**Comment by alexjustesen** [comment]
Added content suggestion to the backlog, closing the issue
