### ISSUE TITLE
ServerIDs getting ignored (using servers that are not in list)

### ISSUE THREAD

**Issue by Estradamis** [alexjustesen/speedtest-tracker#187]
**Describe the bug**
I setup a list of serverIDs to be used for Speedtests (list of comma separated values) but the speedtest used servers even though there weren't in my list so I had servers picked that provided just 1/20 of my speed which resulted in bad and useless results

**To Reproduce**
1. Go to Settings and set ServerIDs
2. Wait for Pentests to take place and check if only those IDs have been used

**Expected behavior**
Only the IDs I define get used for PenTests

**Environment (please complete the following information):**
 - OS: Docker Container

**Screenshots**
Setting:
![image](https://user-images.githubusercontent.com/72608455/205177670-20199e61-decf-45fd-8a70-748d5fef7144.png)

Server used:
![image](https://user-images.githubusercontent.com/72608455/205177748-836431a0-f5ba-42a6-be12-a101e34b22ec.png)

**Comment by alexdelprete** [comment]
Right now only 1 server ID is supported. Multiple IDs is on the roadmap.

**Comment by alexjustesen** [comment]
^ other Alex isn't wrong. I'm tied up with client work at the moment but hopefully have time to work on features again next week.

**Comment by alexdelprete** [comment]
I'll change my tagname on github to **TheOtherAlex** 😆

**Comment by alexjustesen** [comment]
Closing as this is being tracked in the features list already. https://docs.speedtest-tracker.dev/getting-started/features
