### ISSUE TITLE
Selecting a single server in env isn't working

### ISSUE THREAD

**Issue by sunnycloudy1337** [alexjustesen/speedtest-tracker#1875]
**Describe the bug**
When selecting a single server in the `.env` file because I don't run it under docker (I just installed it like I normally install laravel applications) it doesn't actually do anything and the results are all from random servers and thus my average is way way lower than it should be.

**To Reproduce**

1. Have this in the `.env` file (tried it with and without quotes)
```
SPEEDTEST_SERVERS="11494"
SPEEDTEST_SCHEDULE="0 * * * *"
```

2. Run `php /app/www/artisan queue:work` as a system service
```
root@ookla-speedtest:/app/www# systemctl status queue.service 
* queue.service - Queue
     Loaded: loaded (/etc/systemd/system/queue.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-12-02 00:48:30 UTC; 1 day 12h ago
   Main PID: 103 (sudo)
      Tasks: 2 (limit: 76790)
     Memory: 70.8M
        CPU: 2min 10.063s
     CGroup: /system.slice/queue.service
             |-103 sudo /app/www/artisan queue:work
             `-106 php /app/www/artisan queue:work

Dec 03 13:00:04 ookla-speedtest sudo[106]:   2024-12-03 15:00:04 App\Jobs\Ookla\SkipSpeedtestJob ................ RUNNING
Dec 03 13:00:04 ookla-speedtest sudo[106]:   2024-12-03 15:00:04 App\Jobs\Ookla\SkipSpeedtestJob .......... 121.72ms DONE
Dec 03 13:00:04 ookla-speedtest sudo[106]:   2024-12-03 15:00:04 App\Jobs\Ookla\SelectSpeedtestServerJob ........ RUNNING
Dec 03 13:00:04 ookla-speedtest sudo[106]:   2024-12-03 15:00:04 App\Jobs\Ookla\SelectSpeedtestServerJob ... 18.23ms DONE
Dec 03 13:00:04 ookla-speedtest sudo[106]:   2024-12-03 15:00:04 App\Jobs\Ookla\RunSpeedtestJob ................. RUNNING
Dec 03 13:00:24 ookla-speedtest sudo[106]:   2024-12-03 15:00:24 App\Jobs\Ookla\RunSpeedtestJob ................ 19s DONE
Dec 03 13:00:24 ookla-speedtest sudo[106]:   2024-12-03 15:00:24 App\Jobs\Ookla\BenchmarkSpeedtestJob ........... RUNNING
Dec 03 13:00:24 ookla-speedtest sudo[106]:   2024-12-03 15:00:24 App\Jobs\Ookla\BenchmarkSpeedtestJob ...... 21.90ms DONE
Dec 03 13:00:24 ookla-speedtest sudo[106]:   2024-12-03 15:00:24 App\Jobs\Ookla\CompleteSpeedtestJob ............ RUNNING
Dec 03 13:00:24 ookla-speedtest sudo[106]:   2024-12-03 15:00:24 App\Jobs\Ookla\CompleteSpeedtestJob ...... 183.65ms DONE
```

3. Run `/app/www/artisan schedule:run` in crontab every minute
```
* * * * * /usr/bin/php /app/www/artisan schedule:run > /dev/null
```

4. Results look like this:

![image](https://github.com/user-attachments/assets/927e9711-22bc-4e23-932f-8d46c10a015e)

**Expected behavior**
I should see results only from `Digi (RCS & RDS)` because that's the only server I've chosen (the id for it is `11494`)

**Environment (please complete the following information):**
```
root@ookla-speedtest:/app/www# uname -a
Linux ookla-speedtest 6.8.12-4-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-4 (2024-11-06T15:04Z) x86_64 x86_64 x86_64 GNU/Linux
root@ookla-speedtest:/app/www# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
root@ookla-speedtest:/app/www# 
```
 - I'm running the latest version as of now of your project [v0.24.3](https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.24.3)
```
root@ookla-speedtest:/app/www# cat config/speedtest.php 
<?php

use Carbon\Carbon;

return [

    'build_date' => Carbon::parse('2024-11-27'),

    'build_version' => 'v0.24.3',
```

**Screenshots**
please see above

**Logs**
no logs to report

**Additional context**
I'll try to select it twice something like this `SPEEDTEST_SERVERS="11494,11494"` but I have to wait a few hours and see the results, I'll report back

Thanks!

**Comment by alexjustesen** [comment]
If you change your environment variables are you restarting your queue worker and/or dumping and rebuilding the cache?

**Comment by sunnycloudy1337** [comment]
honestly I don't know what fixed it

1. restarting the container (LXC)
2. or putting `SPEEDTEST_SERVERS="11494,11494"` in `.env`

because now it works (tweaked the cron to minute 16 every hour, another tip I've read on the discussions here, hehe)

![image](https://github.com/user-attachments/assets/7ed4e833-3e74-44a5-bf97-0c5e435962d8)

**Comment by sunnycloudy1337** [comment]
> If you change your environment variables are you restarting your queue worker and/or dumping and rebuilding the cache?

I don't think it's a cache issue, because changing the minute from 00 to 16 in .env was without rebuilding any chance, just saving the `.env` file, that's all I did

**Comment by sunnycloudy1337** [comment]
> 1. restarting the linux container (which inherently restarted the web server, queue worker and scheduler)

because I did restart it out of frustration 7 hours ago, after I opened the issue here

```
root@ookla-speedtest:/app/www# uptime
 21:26:20 up  6:52,  1 user,  load average: 0.27, 0.32, 0.32
```

**Comment by sunnycloudy1337** [comment]
I'll just leave `SPEEDTEST_SERVERS="11494"` in `.env`... restart the LXC again and check in the morning

Thanks!

**Comment by sunnycloudy1337** [comment]
```
SPEEDTEST_SERVERS="11494"
SPEEDTEST_SCHEDULE="17 * * * *"
DISPLAY_TIMEZONE=Europe/Bucharest
TELESCOPE_ENABLED=false
```

done, and updated the minute to 17 to keep track of it :)
also restarted the LXC, will check in the morning!

**Comment by sunnycloudy1337** [comment]
Yes, it works and the graph is much more consistent now, it's perfect! Thank you!

![image](https://github.com/user-attachments/assets/dd5aa6f3-4dfe-4f9c-971a-cb86cd30a21d)

![image](https://github.com/user-attachments/assets/e2c31dca-baab-4a9c-a421-83f0f96cf5b4)
