### ISSUE TITLE
[REQUEST] Add Instance Name to Discord notifications

### ISSUE THREAD

**Issue by SawkeeReemo** [alexjustesen/speedtest-tracker#1879]
Due to some limitations with other services like GlueTUN, I have multiple instances of Speed-Tester running. But there’s no way (that I’ve noticed) to discern which instance of Speed-Tester the alert is for. With email notifications, I can add the instance name to the email subject in the env vars, which is helpful. But I don’t see a way to do that for Discord, for example.

**Comment by svenvg93** [comment]
In the meantime until we add it to the notification a quick solution might be to make diffrent webhooks per instance in Discord and give theses the needed names. 

![image](https://github.com/user-attachments/assets/f06c0b66-0bc4-4740-813b-5d32ee7b835b)

**Comment by SawkeeReemo** [comment]
Thanks for that! Thats a great tip for folks who pay for Discord. I actually tried that before posting here and learned that they only allow one webhook per free account. 

Frankly speaking, I’d rather support you than them. I’m happy to wait for any potential addition for this. I just thought I’d make the request here so it was hopefully “on the books.” Really appreciate all the work you independent devs do. It’s inspired me to start learning how to code as well.

**Comment by svenvg93** [comment]
Really? Im able to make multiple webhooks on a channel and I'm on a free account as well. 
![image](https://github.com/user-attachments/assets/a6b054d5-9677-437c-b29c-8e3506cb52c8)

![image](https://github.com/user-attachments/assets/42366b89-2679-45ae-a01a-439cc16e2acd)

Still thought it won't be difficult to add the App name to the notification. Just need to find a good place to add it into the message 😄

**Comment by SawkeeReemo** [comment]
So… I’m not entirely sure my note was understood, because now all instance of Speedtest Tracker just have that exact text… so I still can’t tell which one the notification is for. I have 4 docker containers of Speedtest Tracker running on a NAS for four separate GlueTUN containers. In the email notifications, with the MAIL_FROM_NAME env car, I can type something like “SP1” so that when I get the email notification for threshold breech, I know which one it is. 

Unfortunately, I haven’t seen a way to do that with the Discord notifications. So other than me remembering in which order I’ve scheduled them and if I even have all four running at the time… see what I mean?

**Comment by svenvg93** [comment]
You can change the "Speedtest Tracker"  in the notification by setting the `APP_NAME` Env. With this is can be like 

`A new speedtest on SP1 was completed using Ookla.`

**Comment by SawkeeReemo** [comment]
Oh! Thanks! I totally missed that env var. My mistake, and thank you. Love this program. Seriously nice work with it. …makes me want to figure out a way to automatically relaunch gluetun when my threshold limits hit.

**Comment by svenvg93** [comment]
Hmm, do you see the change of the App_name in the webgui? Like in the top left corner?
