### ISSUE TITLE
Failed Speedtests are not shown on Results List

### ISSUE THREAD

**Issue by Estradamis** [alexjustesen/speedtest-tracker#188]
**Describe the bug**
When a scheduled speedtest cannot be executed, it will just not show up in the results page

**To Reproduce**
1. Set Schedule to run speedtest
2. Turn your device offline for next run

**Expected behavior**
The Results page shows failed executions as well

**Environment (please complete the following information):**
 - OS: Docker container

**Screenshots**
![image](https://user-images.githubusercontent.com/72608455/205178148-6f630373-627c-4716-add3-68c9c254d94e.png)

**Comment by alexjustesen** [comment]
For now the "results" are only successfully run speedtests. I suggest enabling notifications if you want to see failed speedtest attempts.
