### ISSUE TITLE
Have individual speedtest status ?

### ISSUE THREAD

**Issue by boddedo** [alexjustesen/speedtest-tracker#1883]
Hello !

**Is your feature request related to a problem? Please describe.**
I added multiple speedtest server in the SPEEDTEST_SERVERS line
I also added a cron to check every 6 hours
the server will execute randomly only one of them every 6 hours, making some big difference in the graph (depending about the distance)

**Describe the solution you'd like**
I looking for a way to have Dashboard by tested server and maybe a graph, something like that:
![image](https://github.com/user-attachments/assets/45a0e2bb-73b6-4c27-aabc-8489927810b9)

**Comment by alexjustesen** [comment]
👍 planned for when we rebuild the dashboard post-v1.

**Comment by svenvg93** [comment]
Link to https://github.com/alexjustesen/speedtest-tracker/issues/1452 as well for later :)
