### ISSUE TITLE
Grafana Dashboard broke

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#1891]
With the 0.25 release and the refactor of the InfluxDB2 integration, my Grafana Dashboard broke.
I am no longer able to display the graph correctly and see the connected values. Each sample is displayed as a single value

**Screenshots**
How I see them
![1](https://github.com/user-attachments/assets/8426350e-457a-4940-9ecd-3f1c5423438e)
How I would like to get them
![1 - Copia](https://github.com/user-attachments/assets/a3c92df7-b54d-4c26-be00-91710b1d8408)

Thanks in advance

**Comment by masterwishx** [comment]
do you have `Merge series/tables` ?

**Comment by corasaniti** [comment]
@masterwishx 
No, and I created a new bucket. Same problem with the Influx native Dashboard, I see the values ​​disconnected
See screenshoot

1value
![1](https://github.com/user-attachments/assets/6feb11bd-2f09-460c-ae4a-3fcaff3b1c53)

2value
![2](https://github.com/user-attachments/assets/3e0d9395-cd33-4ce7-b1ca-171298de2c56)

3value
![3](https://github.com/user-attachments/assets/2641396e-a163-4432-a018-0ad31f786491)

**Comment by masterwishx** [comment]
try to add Merge series/tables in grafana

**Comment by corasaniti** [comment]
@masterwishx 
Thank you very much, it worked
![1](https://github.com/user-attachments/assets/632e4879-c24d-444f-866f-faa61a937a9a)

**Comment by masterwishx** [comment]
Please check https://github.com/masterwishx/Speedtest-Tracker-v2-InfluxDBv2
