### ISSUE TITLE
wget error connecting to install.speedtest.net (151.101.130.219:443)

### ISSUE THREAD

**Issue by stevehurcombe** [alexjustesen/speedtest-tracker#1897]
**Describe the bug**
During startup it tries to download speedtest cli, but it's failing.

**To Reproduce**
Start the docker container

**Expected behavior**
speedtest cli will appear in /app/Bin etc.

**Environment (please complete the following information):**
Synology Docker

**Screenshots**
![image](https://github.com/user-attachments/assets/5c2d2bb4-2be4-4733-9a0b-3ad1a1bddc86)

**Logs**
Ookla GDPR and EULA accepted. Downloading Speedtest CLI.                                                                                                   
Connecting to install.speedtest.net (151.101.130.219:443)                                                                                                  
wget: error getting response: Connection reset by peer                                                                                                     
tar: can't open 'speedtest.tgz': No such file or directory                                                                                                 
cp: cannot stat 'speedtest': No such file or directory                                                                                                     
s6-applyuidgid: fatal: unable to exec /site/app/Bin/speedtest: No such file or directory

**Comment by svenvg93** [comment]
Which image are you using? 
The Ookla CLI client is installed during the build of the container image, its not downloaded during the start of the container.

**Comment by stevehurcombe** [comment]
Hi,
Thanks for your prompt reply. 

I've just deleted everything, including the folders and the downloaded image, and the same thing happens. 

I think I've located the downloaded image in docker and that folder is empty:
![image](https://github.com/user-attachments/assets/1676b020-0dcd-45c6-9ef4-40e4a60ef6e0)

When it starts up the log file implies it's downloading things:
![image](https://github.com/user-attachments/assets/d05e6e57-3c55-438b-82f3-f6b9478d5096)

The image is coming from here:
https://registry.hub.docker.com/r/henrywhitaker3/speedtest-tracker/

![Screenshot 2024-12-06 123547](https://github.com/user-attachments/assets/5d04fbe6-c2c4-490f-aaac-eee0e1fbc9f1)

**Comment by alexjustesen** [comment]
> The image is coming from here: https://registry.hub.docker.com/r/henrywhitaker3/speedtest-tracker/

Ah that's the problem, that's the application this once replaces. Install instructions for this Speedtest Tracker is located here: https://docs.speedtest-tracker.dev/getting-started/installation.

Also as a note, Synology NAS are supported but directions are written with the new UI in mind using Container Manager application.
