### ISSUE TITLE
Improve Dockerfile for Faster Development Builds

### ISSUE THREAD

**Issue by rubencosta13** [alexjustesen/speedtest-tracker#1899]
## Is your feature request related to a problem? Please describe.  
The Docker build time is quite long due to the use of a large base image and a high number of dependencies. This leads to slower iteration times and increased overhead when rebuilding the image.

## Describe the solution you'd like  
Optimize the Dockerfile to improve build efficiency by:
- Using a smaller base image, such as `debian:bookworm-slim`, instead of `ubuntu:22.04`.
- Combining `RUN` commands to reduce layers and unnecessary steps.
- Removing any non-essential dependencies, focusing on only the required ones.

## Additional context  
This optimization would significantly reduce build time, improve performance, and streamline the development workflow.  

**I can work on this optimization if given the proper "green light" to proceed.**

**Comment by alexjustesen** [comment]
The dev image is published using https://laravel.com/docs/11.x/sail, its not meant for speedy builds but to be a flexible development environment.
