### ISSUE TITLE
Composer production install

### ISSUE THREAD

**Issue by sunnycloudy1337** [alexjustesen/speedtest-tracker#1913]
**Describe the bug**
When trying to install the laravel app with `composer install --no-dev` there is an error while generating the optimized autoload files, it is complaining about the `TelescopeServiceProvider` which is only found in the dev packages. (see screenshot)

**To Reproduce**
1. Put app on an ubuntu server
2. Have `.env` file with `APP_DEBUG=false` in it (not that it should matter anyway for the next step)
3. Run  `composer install --no-dev`

**Expected behavior**
The app should work without the dev package dependencies.

**Environment (please complete the following information):**
```
root@ookla-speedtest:~# uname -a 
Linux ookla-speedtest 6.8.12-4-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-4 (2024-11-06T15:04Z) x86_64 x86_64 x86_64 GNU/Linux
root@ookla-speedtest:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```
```
root@ookla-speedtest:~# cat /app/www/config/speedtest.php 
<?php

use Carbon\Carbon;

return [

    'build_date' => Carbon::parse('2024-12-11'),

    'build_version' => 'v0.26.0',

    /**
     * General settings.
```

**Screenshots**
![image](https://github.com/user-attachments/assets/4086f96c-a1d9-4a64-9ebb-0dda1b44091e)

**Logs**
N/A

**Additional context**
Composer should allow for production environments just like npm does with `npm run build` :)

**Comment by alexjustesen** [comment]
You'll want to specify your `APP_ENV=production` so Laravel doesn't go looking for dev dependencies when booting.

Telescope ref in the `AppServiceProvider`: https://github.com/alexjustesen/speedtest-tracker/blob/8ea81f9b84c09a1bc732dbbf34587827b7b8d20e/app/Providers/AppServiceProvider.php#L24-L33

**Comment by sunnycloudy1337** [comment]
you're right, forgot about the `APP_ENV` flag, silly me.

it works now, thanks!
