### ISSUE TITLE
[BUG] V1.0.0 impossible to edit the default admin user after the first installation

### ISSUE THREAD

**Issue by mariushosting** [alexjustesen/speedtest-tracker#1919]
Version 1.0.1 can't edit the default admin user after first installation. There is no 3 dots point anymore to edit it.

**Comment by svenvg93** [comment]
This has changed in [v0.26.0](https://github.com/alexjustesen/speedtest-tracker/pull/1908). Changing the authenticated user via the user panel caused an issue after changing it. You can change the details of the used user in the profile in the top right corner. 

Docs link: https://docs.speedtest-tracker.dev/security/authentication#change-user-account 
_Note to self; update the wording in the docs to make it more clear_

**Comment by mariushosting** [comment]
> This has changed in [v0.26.0](https://github.com/alexjustesen/speedtest-tracker/pull/1908). Changing the authenticated user via the user panel caused an issue after changing it. You can change the details of the used user in the profile in the top right corner.
> 
> Docs link: https://docs.speedtest-tracker.dev/security/authentication#change-user-account _Note to self; update the wording in the docs to make it more clear_

I woke up recently but I swear it's not intuitive. I can't find how to do it even in the updated documentation. It should be simple.

**Comment by mariushosting** [comment]
A user will thing to go to Users to change the default admin user. It's not intuitive to put it somewhere else entirely.

**Comment by alexjustesen** [comment]
> It's not intuitive to put it somewhere else entirely.

Clicking the profile is a pretty standard pattern for changing _your_ account information in my opinion.

If you create another admin account you can edit the default account when you're signed into the second account. This was done to prevent accidently changing your own role and getting locked out as the "only" admin.
