### ISSUE TITLE
Failed run has no log or information

### ISSUE THREAD

**Issue by aaronspruit** [alexjustesen/speedtest-tracker#1928]
**Describe the bug**
When attempting to run against a specific server (8864) the speedtest fails.  However, there are no details about why it failed anywhere that I can find.  I'm attempting to troubleshoot why this server no longer works for me, as it is the closest and on the same network.  Other servers seem to work fine (seen in second screenshot), so I'm not sure where it is failing.

**To Reproduce**
Unsure if these will work for others, as this server was working for me yesterday.  
1. run a speedtest against server 8864

**Expected behavior**
There is an error message logged to the logs and ideally put in the message field for the specific result.  

**Environment (please complete the following information):**
 - OS: linuxserver.io container on Ubuntu 24.04 node of k3s
-  Architecture: amd64
 - Browser: FF 133.0.3
 - Version: v1.0.0

**Screenshots**
![image](https://github.com/user-attachments/assets/e914a34f-f460-4c93-9a51-28974ff3ce80)

![image](https://github.com/user-attachments/assets/054f67d7-dff6-4b53-9e59-b9d6ce947f3b)

**Logs**
There is nothing in the laravel.log.  Unsure where else to look.

**Comment by svenvg93** [comment]
What happens if you run `speedtest -s 8864 -f json-pretty` inside of the container.

**Comment by aaronspruit** [comment]
For 8864
```
root@speedtest-deployment-8586c88dbf-n6d4m:/# speedtest -s 8864 -f json-pretty 
{
    "error": "Cannot read: "
}
```

for 10162
```
root@speedtest-deployment-8586c88dbf-n6d4m:/# speedtest -s 10162 -f json-pretty 
{
    "type": "result",
    "timestamp": "2024-12-14T23:52:32Z",
    "ping": {
        "jitter": 0.478,
        "latency": 6.853,
        "low": 6.246,
        "high": 7.299
    },
    "download": {
        "bandwidth": 107740650,
        "bytes": 919387488,
        "elapsed": 8608,
        "latency": {
            "iqm": 6.674,
            "low": 5.170,
            "high": 226.040,
```

**Comment by aaronspruit** [comment]
Ok, adding the verbose flag...

```
root@speedtest-deployment-8586c88dbf-n6d4m:/# speedtest -s 8864 -f json-pretty -v
{
    "type": "log",
    "timestamp": "2024-12-14T23:54:51Z",
    "message": "Receive error: 11 (Resource temporarily unavailable)",
    "level": "warning"
}
{
    "type": "log",
    "timestamp": "2024-12-14T23:54:51Z",
    "message": "Receive error: 11 (Resource temporarily unavailable)",
    "level": "warning"
}
{
    "type": "log",
    "timestamp": "2024-12-14T23:54:51Z",
    "message": "Receive error: 11 (Resource temporarily unavailable)",
    "level": "warning"
}
{
    "type": "log",
    "timestamp": "2024-12-14T23:54:51Z",
    "message": "Receive error: 11 (Resource temporarily unavailable)",
    "level": "warning"
}
{
    "type": "log",
    "timestamp": "2024-12-14T23:54:54Z",
    "message": "Receive error: 11 (Resource temporarily unavailable)",
    "level": "warning"
}
{
    "type": "log",
    "timestamp": "2024-12-14T23:54:54Z",
    "message": "Receive error: 11 (Resource temporarily unavailable)",
    "level": "warning"
}
{
    "error": "Cannot read: "
}
```

**Comment by aaronspruit** [comment]
Is there a way to enable verbose logging or something more for what the UI is executing?  I'd love to be able to view a log and see what command it ran.  

Also, it may be needed to use the verbose json return in the future to capture these so they aren't just blank.  Looking at the working one with verbose logging on, the results json looks the same - so you can still easily parse it.

**Comment by aaronspruit** [comment]
> What happens if you run `speedtest -s 8864 -f json-pretty` inside of the container. Also are both test run as an manual test or scheduled?

For the scheduled vs. manual - check out my other bug #1927.  However, it was failing on both scheduled or manual, assuming I didn't have anything set as the default server.

**Comment by svenvg93** [comment]
The error message is not in the same format is normally is, thats why it's shown in the UI. 

Current logic
https://github.com/alexjustesen/speedtest-tracker/blob/ae0bf56b314df0edebefdcf5f7782cba1ee0f0f9/app/Jobs/Ookla/RunSpeedtestJob.php#L61-L70

https://github.com/alexjustesen/speedtest-tracker/blob/ae0bf56b314df0edebefdcf5f7782cba1ee0f0f9/app/Helpers/Ookla.php#L12-L30

Using verbose might work, but need to check if there are no other implications.

Like for example I got some additional output on an successful test

```
{
    "type": "log",
    "timestamp": "2024-12-15T00:11:50Z",
    "message": "Loaded latency: cannot read response.: [11] Resource temporarily unavailable",
    "level": "warning"
}
{
    "type": "log",
    "timestamp": "2024-12-15T00:11:51Z",
    "message": "No libz support available, not compressing data.",
    "level": "warning"
}
```

Another way might be to just have a placeholder like "Ookla CLI failed for unknown reason without a error message"

**Comment by alexjustesen** [comment]
So my guess is that particular server isn't up to date and that you might be getting throttled. I was able to successfully run a test against it but I noticed some key data is missing like `packed_loss`.

While it might be your closest server you might want to select a different one that is being updated and maintained. Example below with one of my preferred servers.

### Server: `8864`

```
Speedtest by Ookla

      Server: CenturyLink - Seattle, WA (id: 8864)
         ISP: Frontier Communications
Idle Latency:    79.38 ms   (jitter: 0.60ms, low: 78.73ms, high: 80.42ms)
    Download:   322.78 Mbps (data used: 543.9 MB)                                                   
                200.16 ms   (jitter: 58.64ms, low: 79.73ms, high: 915.17ms)
      Upload:   206.79 Mbps (data used: 265.0 MB)                                                   
                 78.62 ms   (jitter: 4.12ms, low: 76.22ms, high: 222.56ms)
 Packet Loss: Not available.
```

```json
{
  "type": "result",
  "timestamp": "2024-12-16T00:52:18Z",
  "ping": {
    "jitter": 0.829,
    "latency": 78.662,
    "low": 77.983,
    "high": 79.361
  },
  "download": {
    "bandwidth": 33664374,
    "bytes": 332488596,
    "elapsed": 10914,
    "latency": {
      "iqm": 239.571,
      "low": 82.03,
      "high": 1350.234,
      "jitter": 66.09
    }
  },
  "upload": {
    "bandwidth": 32772160,
    "bytes": 435652682,
    "elapsed": 13903,
    "latency": {
      "iqm": 82.941,
      "low": 79.946,
      "high": 216.505,
      "jitter": 4.136
    }
  },
  "isp": "Frontier Communications",
  "interface": {
    "internalIp": "removed",
    "name": "eth0",
    "macAddr": "removed",
    "isVpn": false,
    "externalIp": "removed"
  },
  "server": {
    "id": 8864,
    "host": "seattle.speedtest.centurylink.net",
    "port": 8080,
    "name": "CenturyLink",
    "location": "Seattle, WA",
    "country": "United States",
    "ip": "63.224.243.194"
  },
  "result": {
    "id": "removed",
    "url": "removed",
    "persisted": true
  }
}
```

### Server: `56485`

```
Speedtest by Ookla

      Server: Frontier - Secaucus, NJ (id: 56485)
         ISP: Frontier Communications
Idle Latency:    10.67 ms   (jitter: 0.91ms, low: 10.23ms, high: 11.60ms)
    Download:   327.01 Mbps (data used: 387.0 MB)                                                   
                 26.53 ms   (jitter: 7.52ms, low: 12.35ms, high: 111.02ms)
      Upload:   322.23 Mbps (data used: 253.5 MB)                                                   
                 73.37 ms   (jitter: 6.50ms, low: 14.05ms, high: 98.21ms)
 Packet Loss:     1.1%
```

```json
{
  "type": "result",
  "timestamp": "2024-12-16T00:57:05Z",
  "ping": {
    "jitter": 0.439,
    "latency": 11.16,
    "low": 10.409,
    "high": 11.717
  },
  "download": {
    "bandwidth": 41582777,
    "bytes": 394428432,
    "elapsed": 9413,
    "latency": {
      "iqm": 24.812,
      "low": 10.68,
      "high": 116.3,
      "jitter": 8.495
    }
  },
  "upload": {
    "bandwidth": 46080948,
    "bytes": 641118677,
    "elapsed": 14612,
    "latency": {
      "iqm": 25.085,
      "low": 10.779,
      "high": 62.134,
      "jitter": 3.904
    }
  },
  "packetLoss": 0.5347593582887701,
  "isp": "Frontier Communications",
  "interface": {
    "internalIp": "removed",
    "name": "eth0",
    "macAddr": "removed",
    "isVpn": false,
    "externalIp": "removed"
  },
  "server": {
    "id": 56485,
    "host": "secaucus.nj.speedtest.frontier.com",
    "port": 8080,
    "name": "Frontier",
    "location": "Secaucus, NJ",
    "country": "United States",
    "ip": "74.42.170.3"
  },
  "result": {
    "id": "removed",
    "url": "removed",
    "persisted": true
  }
}
```

**Comment by holocronology** [comment]
Just noticed that I've been having this same issue since Nov 17th...

**Comment by svenvg93** [comment]
@holocronology Can you run the same command in your container. `speedtest -f json-pretty`.

**Comment by holocronology** [comment]
> speedtest -f json-pretty

`
speedtest =f json-pretty

   Speedtest by Ookla

      Server: Verizon - New York, NY (id: 30411)
         ISP: Verizon Fios
Idle Latency:     7.75 ms   (jitter: 0.27ms, low: 7.44ms, high: 8.15ms)
    Download:   872.95 Mbps (data used: 933.4 MB)                                                   
                 11.05 ms   (jitter: 1.30ms, low: 8.43ms, high: 22.80ms)
      Upload:   946.32 Mbps (data used: 1.2 GB)                                                   
                155.38 ms   (jitter: 47.37ms, low: 4.07ms, high: 392.26ms)
 Packet Loss:     0.0%
  Result URL: <redacted> 
`
