### ISSUE TITLE
Iperf3  tests

### ISSUE THREAD

**Issue by Skyeci73** [alexjustesen/speedtest-tracker#1948]
Upon testing an 8gb/8gb connection and finding the cli does not report the upload correctly, would it be possible to use iperf3 to gather test results from known working Internet based iperf servers and have the results graphed as they are currently. 

I have found iperf3 is the only way to get an accurate result 

Thanks

**Comment by alexjustesen** [comment]
Planned at "some point": https://github.com/alexjustesen/speedtest-tracker/discussions/976
