### ISSUE TITLE
How to set the default chart time?

### ISSUE THREAD

**Issue by mwckr** [alexjustesen/speedtest-tracker#1953]
Hi,

there were many requests to implement a default timerange for the charts. 
https://github.com/alexjustesen/speedtest-tracker/issues/1855
https://github.com/alexjustesen/speedtest-tracker/issues/1858
https://github.com/alexjustesen/speedtest-tracker/issues/1449

It seems you implemented this:
https://github.com/alexjustesen/speedtest-tracker/pull/1669

For the life of me, I cannot figure out how to get this to work. It's not explained anywhere, do I add something to my environment variables, if yes, what?

Sorry if this is written down somewhere, but I cannot find it. It's not in the docs, as far as I'm aware.

Thanks.

**Comment by svenvg93** [comment]
That one was closed and not merged. As we needed to get some other things out of the way first to make it easier and more flexible with other parts of the application. 

It will come in the future, no eta yet

**Comment by alexjustesen** [comment]
I close things that might be duplicates or similar just to keep the issues manageable. That's why we also reference issues to keep that lineage.
