### ISSUE TITLE
Issue running under HTTPS - Need Relative Links

### ISSUE THREAD

**Issue by deweycd** [alexjustesen/speedtest-tracker#196]
**Describe the bug**
When running speedtest-tracker behind traefik using HTTPS I am unable to get the css or js to load due to absolute linking.  Can the links be converted to relative paths so that the HTTPS will overwrite the HTTP portion of the links?

**Comment by alexdelprete** [comment]
Did you search issues before opening a new one? It's always recommended.

The Traefik insecure-secure issue has been discussed for a long time, and solved, please check #34 #54 #56 and #95 issues.

You should be able to solve the problem (hint: check SSL_MODE), if not, post your docker-compose and traefik dynamic config and we'll take a look at it.
