### ISSUE TITLE
Feature missing ?

### ISSUE THREAD

**Issue by hoangnamitc** [alexjustesen/speedtest-tracker#211]
I see that this feature is not available?

[the demo repository here](https://github.com/LaravelDaily/Laravel-Filament-Plugins-Demo/tree/filament-breezy)

Thank !

**Comment by alexdelprete** [comment]
Specify which feature in the subject at least. :)

**Comment by alexjustesen** [comment]
> I see that this feature is not available?
> 
> [the demo repository here](https://github.com/LaravelDaily/Laravel-Filament-Plugins-Demo/tree/filament-breezy)
> 
> Thank !

Yeah more context and specifics would be great
