### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by stepanov1975** [alexjustesen/speedtest-tracker#217]
Just updated (docker) and getting 500 server error
[speedtest.log](https://github.com/alexjustesen/speedtest-tracker/files/10247971/speedtest.log)

**Comment by alexjustesen** [comment]
Urg

**Comment by alexjustesen** [comment]
@stepanov1975 bugfix incoming mind testing when it's published shortly?

**Comment by alexjustesen** [comment]
Nope, that didn't fix it. Opening the issue again for me to tackle again later tonight.

**Comment by stepanov1975** [comment]
With the latest version works fine

**Comment by sschneider** [comment]
Had the same issue. Also works for me in the latest version. Thanks for your work and the quick fix.

**Comment by kaerbr** [comment]
For me the 500 error only appears if I have no entries in the result table. And only on the "dashboard" site.

**Comment by alexjustesen** [comment]
> For me the 500 error only appears if I have no entries in the result table. And only on the "dashboard" site.

Likely a different issue can you open another issue and paste in the error logs?
