### ISSUE TITLE
First Chart Issue....

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#220]
1. It would be nice to redraw and refresh the scale when download or upload is hidden and show more details in graphs. (see screen)
 
![Cattura1](https://user-images.githubusercontent.com/5001932/208201318-feb00163-fe54-4afa-a7a2-6b6d812da7d0.PNG)
![Cattura2](https://user-images.githubusercontent.com/5001932/208201439-a81cb7c8-5835-4ad8-9ff6-874cd463b375.PNG)

As happens in the project by henrywhitaker3

![Cattura4](https://user-images.githubusercontent.com/5001932/208201935-c5764f02-e456-4937-b2be-618cb47417e7.PNG)
![Cattura5](https://user-images.githubusercontent.com/5001932/208201944-03dd7017-8858-460d-93b7-f2c27021794c.PNG)

2. When the page loads, "today" is selected by default as the time range but all the data is shown instead... The problem occurs for all download/upload, ping, and jitter graphs
![Cattura3](https://user-images.githubusercontent.com/5001932/208201394-7886a0ba-4ba3-45c6-bc56-cc3e9c80e84b.PNG)

Thank you for the excellent work you are doing.
Thanks

**Comment by alexjustesen** [comment]
Well 💩, guess I need a margarita and to open VS Code again.
