### ISSUE TITLE
Not really a bug: Jitter graph

### ISSUE THREAD

**Issue by alexdelprete** [alexjustesen/speedtest-tracker#229]
I think Jitter should only apply to Ping values. It's true that it's a variability measure, so it could in principle be applied to DL/UL, but in networking it's generally always referred to latency measurements.

![image](https://user-images.githubusercontent.com/7027842/208225396-04bb4625-315c-4cdb-9ab5-48e25c8761bd.png)

If it was a deliberate choice, no problems, we can live with that. :)

BTW: you made a great job, latest version looks amazing. :)

**Comment by alexjustesen** [comment]
Yeah so the CLI actually returns download/upload latency ping which is what this is. I'm including it because my ISP in the past has had poor ping performance in a direction usually

**Comment by alexdelprete** [comment]
I'm sorry, I misinterpreted the values, I thought the DL/UL jitter was related to speed, not latency per direction. The high DL jitter tricked me. Shouldn't have opened the issue. :)

**Comment by alexjustesen** [comment]
NP, I've got on my future list to define all the metrics in the docs but not something I have capacity for ATM
