### ISSUE TITLE
European time zones lost in 0.8.0

### ISSUE THREAD

**Issue by jacotec** [alexjustesen/speedtest-tracker#231]
**Describe the bug**
After updating to 0.8.0 my time zone was reset from "Europe/Berlin" to "UTC".

I can't reselect Europe/Berlin as the drop-down ends with "Africa/Tripoli"

**To Reproduce**
1. Go to Settings
2. Try to find "Europe/Berlin" as time zone

**Expected behavior**
Timezones outside Africa should be available

**Environment (please complete the following information):**
 - OS: Docker on Ubuntu 20.04 Server
-  Architecture: amd64
 - Browser: Don't care
 - Version: 0.8.0

**Comment by alexjustesen** [comment]
Just start typing as it's a searchable dropdown 😉

![image](https://user-images.githubusercontent.com/1144087/208245172-e081812d-c14a-4c5b-b48c-41a89bc714af.png)
