### ISSUE TITLE
Kbps represented as Mbps

### ISSUE THREAD

**Issue by 06Games** [alexjustesen/speedtest-tracker#232]
**Describe the bug**
On the graph, kbps are displayed as if they were mbps.

**To Reproduce**
1. Have a speed test result with mixed units
2. Go to the dashboard
3. Look at the speed graph

**Expected behavior**
Should be 0.xxx not xxx mbps on the graph

**Environment:**
 - OS: DSM 7.1.1-42962 Update 3
-  Architecture: amd64
 - Browser: Firefox
 - Version v0.8.0

**Screenshots**
![image](https://user-images.githubusercontent.com/24252743/208238780-1192f2ee-93b0-46b3-97be-7ac79ac085e6.png)

**Comment by alexjustesen** [comment]
Good catch, the charts don't maintain scale well

**Comment by hackermondev** [comment]
Same issue

**Comment by AML225** [comment]
I have the same issue with Gbps showing as Mbps:

<img width="952" alt="Capture" src="https://user-images.githubusercontent.com/37520295/208310445-12d25b22-2cf1-4739-842a-aa3e7e622098.PNG">

**Comment by alexjustesen** [comment]
> I have the same issue with Gbps showing as Mbps:
> 
> <img width="952" alt="Capture" src="https://user-images.githubusercontent.com/37520295/208310445-12d25b22-2cf1-4739-842a-aa3e7e622098.PNG">
> 

Aaaaaah it's not dark mode. Issue not valid 🤣
