### ISSUE TITLE
error on the dashboard if no test are made

### ISSUE THREAD

**Issue by Tiagoez** [alexjustesen/speedtest-tracker#235]
error on the dashboard if no test are made

 - OS: Ubuntu 20.04 server
-  Architecture: dell poweredge r720 

**Screenshots**
![image](https://user-images.githubusercontent.com/85638873/208256624-f8043b00-3747-46cc-89e7-0bea706bf803.png)

[speedtest-tracker_logs1 (1).txt](https://github.com/alexjustesen/speedtest-tracker/files/10252466/speedtest-tracker_logs1.1.txt)

**Comment by mzeecedric** [comment]
Same here after getting your latest release last night...

**Comment by alexjustesen** [comment]
Go to /results and then you should be able to access the settings page. Manually set your timezone there and that should resolve the issue

**Comment by alexjustesen** [comment]
#234 is the original issue
