### ISSUE TITLE
Time Zone Issue

### ISSUE THREAD

**Issue by bam7** [alexjustesen/speedtest-tracker#242]
I am seeing some weird issues with the scheduler that looks like maybe a time zone issue.   My scheduled cron entry is [ 0 8,20 * * * ] which should trigger at 8 AM and 8 PM.   My time zone is  America/New_York, so 5 hours off UTC.  The jobs are running at 3 am and 3 PM which correlates to the 5 hours off the scheduled time.   I can adjust around this but is it a config issue somewhere?

**Comment by bam7** [comment]
I see a similar open issue.   My version is Speedtest Tracker v0.8.1
I will go thru some of those steps outlined in issue #194 and see if I get anywhere.

**Comment by alexjustesen** [comment]
I *think* this is related to #194 as well. I think I'm going to remove the timezone from the UI and make it a Docker env instead this way the container, cron and app can all read one env var.
