### ISSUE TITLE
Displaying averages + deltas

### ISSUE THREAD

**Issue by MattIPv4** [alexjustesen/speedtest-tracker#243]
**Is your feature request related to a problem? Please describe.**

👋 Loving this project! My internet speed is pretty consistent, but I'd like to be able to more easily view discrepancies in each run.

**Describe the solution you'd like**

It'd be really cool to be able to view averages over time for all the charts and key stats. Building on that, it'd also be nice I think to then have a view where you can see each run's delta compared to the average, or compared to the previous run.

**Additional context**

N/A

**Comment by alexjustesen** [comment]
So, I'm thinking aloud here but about showing the following metrics on the dashboard...

1. % increase/decrease for download/upload/ping vs. the last test
2. 24h and 1 week averages for download/upload/ping
3. adding a filter to the dashboard to show results by server, these stats are pretty useless if the user has a list of servers they run tests against (soon) which could change the results significantly IMO

**Comment by MattIPv4** [comment]
Those sound like a solid set of initial items -- it'd be cool to be able to plot the averages as dotted lines on the graphs, so you can visually see how far from the average each test is.

(It'd also be cool to be able to plot a dotted line of tests offset by say a week, so you can visually see how the tests compare to a week ago.)

**Comment by alexjustesen** [comment]
I'm not planning to go too crazy on charting but I do want to provide quick insights and value for the bulk of the users. When getting into complex charting I think this is where making sure I have an API and integrations for timeseries DBs so more advanced charting can be done outside of the app.

**Comment by alexjustesen** [comment]
> 1. % increase/decrease for download/upload/ping vs. the last test

added in #247

**Comment by alexdelprete** [comment]
> I'm not planning to go too crazy on charting

Alex, if you go to that road, you'll receive hundreds of request, and I don't think the dashboard can or should become a Grafana. I've built a Grafana dashboard using Influxdb data as you know, I've provided installation instructions as you requested, I would suggest to put those in official documentation and direct users to that for "Advanced Stats/Graphs".

**Comment by PapaBearDoes** [comment]
I agree that this should not become a Grafana dashboard type of thing, but ... having recently used this data to get a break on my internet provider cost due to them not providing the proper speeds I'm paying for, I can say that having a quick display of the averages (monthly, weekly) for at least the DL/UL speeds would be helpful.  As it is I had to manually export and crunch the numbers to get the averages which I then used to argue my case with Comcast.

**Comment by MattIPv4** [comment]
Thank you for shipping this <3

**Comment by rm-hull** [comment]
@alexjustesen great feature - thankyou ... is there any appetite / how much effort would it be to change it so that it has a moving average?
