### ISSUE TITLE
Docker install Laravel cache

### ISSUE THREAD

**Issue by zvarg** [alexjustesen/speedtest-tracker#246]
**Describe the bug**
Docker container failed to start.

**To Reproduce**
1. Create stack with portainer (standard docker sqlLite from [docs](https://docs.speedtest-tracker.dev/getting-started/installation))
2. Update the stack
3. See error

**Expected behavior**
Speedtest-tracker started. Navigating to https port will display login page.

**Environment (please complete the following information):**
 - OS: Docker Container (Open media vault, with portainer on Raspberry Pi4)
-  Architecture: arm64
 - Browser Firefox
 - Version v0.8.1

**Logs**
🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
In PackageManifest.php line 178:
The /var/www/html/bootstrap/cache directory must be present and writable.  
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

**Additional context**
Container start failed with some log filter issue, but a restart resolved it. Issue above hurts more.

**Comment by zvarg** [comment]
> Are you changing the docker-compose file or are you just pulling the latest image?

Minor changes was made in docker compose file: I added a http port (before that I was used only https). All copied from docs.

It worked before, and yesterday I was recreate container with re-pull image (latest) and redeploy. And now I am facing the problem mentioned.  Sady i dont know which version was the image, but I can see an unused image with creaded date:  `2022-11-26 14:51:20`.

**Comment by alexjustesen** [comment]
So it was likely `v0.4.2` you were last running if the last pull was on 11/26.

In the repo's root check out `.env.example` and compare it to the one you mounted in your `/config` location. Make sure it's set to `file` for now.

**Comment by zvarg** [comment]
I compared it, and my config is the same as `.env.example`. The driver was set to `file`: `CACHE_DRIVER=file`.

More info: 
1. I deleted the existing container, deleted config folder I used. (for fresh install)
2. Create the stack with re-pull latest image
3. Container started as it should.
4. Update stack with anything (I added restart policy to unless-stopped)
5. Re-create container
6. Container failed to start with the error mention above.

**Comment by alexjustesen** [comment]
@zvarg a new release was tagged today `v0.9.2`, I didn't tackle this specifically but it's worth testing again.

**Comment by zvarg** [comment]
Unfortunatelly the same error is still present. No changes were made on configuration, just update the image to the latest.

**Comment by alexjustesen** [comment]
I got a spare pi kicking around, I've never used omv but I'll try and reproduce this over the next few days.

I've got this running on an rpi with Ubuntu 22.04 and portainer and I'm not having any issues

**Comment by alexdelprete** [comment]
> Unfortunatelly the same error is still present. No changes were made on configuration, just update the image to the latest.

are you using Open Media Vault on RPi? Can you try from shell, using a normal docker-compose.yml file?

**Comment by zvarg** [comment]
This issue is occuring while re-pull image and redeploy container. I can workaround these steps:
1. Manually delete container
2. Remove configuration folder manually
3. Deploy stack with latest image.

@alexdelprete Yes I am using OMV with Portainer. I can try some other time using shell but I focus mainly on omv-portainer stacks to be fully recoverable. Using shell will be equal with the workaround mentoin above, in order to get things work. 

Anyway, this should be a low-prior bug - or preferably closed bug - becuase the workaround.

**Comment by alexdelprete** [comment]
I don't think this is a bug in the image/container, that's why I asked if you could test with docker-compose from shell, just to validate my hypothesis: I think it's something related to your specific environment (OMV/Portainer/RPi).

This error is related to the environment, not specific to the image:
```
The /var/www/html/bootstrap/cache directory must be present and writable.
```

One of my friends has tested ST on an RPi with a docker-compose file I prepared for him, and it's working, so I would point more to an OMV/Portainer/RPi specific issue.

Let us know once you test it with docker-compose, thanks.

**Comment by alexjustesen** [comment]
Yeah I'm thinking it's ovm related too but need to really get in and play with it

**Comment by alexdelprete** [comment]
> Yeah I'm thinking it's ovm related too but need to really get in and play with it

let's wait for his test with docker-compose...I have an RPi too but I use it as my homelab time source (GPS hat, PPS disciplined, Stratum 1 precision) and secondary DNS server, I tend to not use it for tests, but if needed I can quickly install docker+docker-compose and test ST.

**Comment by zvarg** [comment]
I have good new. I updated my existing container and now it is working. I don't know what you did and in what version, but now all good. However, I have some permission issues, but that is another story:

`{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Failed to save settings: boost::filesystem::create_directories: Permission denied [system:13]: \\\"/root/.config/ookla\\\", \\\"/root/.config/ookla\\\"\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Path used: /root/.config/ookla/speedtest-cli.json\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Error: [0] Cannot open socket\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Error: [113] Host is unreachable\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Error: [0] Cannot open socket\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Error: [113] Host is unreachable\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Error: [113] Host is unreachable\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Error: [113] Host is unreachable\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Error: [113] Host is unreachable\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Error: [113] Host is unreachable\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:09Z\",\"message\":\"Error: [113] Host is unreachable\",\"level\":\"error\"}
{\"type\":\"log\",\"timestamp\":\"2023-01-08T11:00:10Z\",\"message\":\"Error: [113] Host is unreachable\",\"level\":\"error\"}
 at /var/www/html/app/Jobs/ExecSpeedtest.php:55)`

I can live with that for now.

**Comment by alexjustesen** [comment]
@zarg That almost looks like the speedtest failed, can you try a different server? If the issue continues open another issue as I'm going to mark this solved.
