### ISSUE TITLE
Results over 1.0 Gigabit

### ISSUE THREAD

**Issue by theunicellular** [alexjustesen/speedtest-tracker#250]
Speedtest results that go above 1 gigabit are being shown as 1 Mbps on the dashboard graph rather than 1,000+ Mbps. Thought my internet connection was dropping out until I looked up each entry in results to see what happened. 

I didn't see this reported in issues so I hope this is not a repeat of something already known. Thanks!

![Screenshot 2022-12-19 152116](https://user-images.githubusercontent.com/5010119/208514067-6bd252b0-6959-41b7-a18b-792102ccfde6.png)

**Comment by alexjustesen** [comment]
Someone had the opposite problem with Kbps but it's all the same route cause so going to track this issue in #232

**Comment by theunicellular** [comment]
Oh sorry about that. Thank you for the quick response and the work you do!
