### ISSUE TITLE
[Feature Request] API

### ISSUE THREAD

**Issue by klercke** [alexjustesen/speedtest-tracker#253]
**Is your feature request related to a problem? Please describe.**
It would be great if this was a drop-in replacement for https://github.com/henrywhitaker3/Speedtest-Tracker/ for API integrations so that those of us using them can do a full migration.

**Describe the solution you'd like**
Users can continue using old API integrations

**Additional context**
I love this project so far!

**Comment by alexjustesen** [comment]
😉 already got you #81, going to close this but follow that issue as it's a `v1.0.0` requirement

**Comment by klercke** [comment]
Great, thanks! I searched for "API" but didn't think to search for "homepage" or "dashboard".

**Comment by alexjustesen** [comment]
Yeah I don't mention it there specifically (and probably should) but I use [benphelps/homepage](https://github.com/benphelps/homepage) in my homelab so I selfishly want coverage there too.
