### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by aobh** [alexjustesen/speedtest-tracker#255]
**Describe the bug**
When opening the application/website it shows:

500 |  Server Error

**To Reproduce**
Open website

**Expected behavior**
Working application

**Environment (please complete the following information):**
- OS: Debian 11/Docker
-  Architecture: amd64
 - Browser: Firefox 108
 - Version: 0.90

**Logs**

[Explore-logs-2022-12-21 14 47 31.txt](https://github.com/alexjustesen/speedtest-tracker/files/10278173/Explore-logs-2022-12-21.14.47.31.txt)

**Comment by dkdhanda8** [comment]
Also facing the same issue. Website was loading before but after my latest cron job it's giving 500 error.
Environment (please complete the following information):

OS: Debian 11/Docker
Architecture: arm64
Browser: Brave
Version: 0.90
Logs

**Comment by zvarg** [comment]
Analyzing the log shows that if you have at least 2 speedtest result then a comparison for the last 2 of them will calculated. Therefore if you navigate to results page (`http://baseUrl:8080/admin/results`) and delete all of the results but one, the dashboard page will work.

`[...] percentChange(): Return value must be of type float, string returned [...]`

**Comment by alexjustesen** [comment]
This one is going to take a little more debugging, I have multiple results (800+) in my database and I'm not seeing this error

**Comment by zvarg** [comment]
Bug will came in in commit #247. Somehow a string returned instead of a float. I assume not a big ass bug 😄

**Comment by alexjustesen** [comment]
> I assume not a big ass bug 😄

I'm hoping for knat, small and annoying vs. june bug, large and hurts.

**Comment by alexjustesen** [comment]
I "think" I narrowed it down, #256 the function now expects a string instead of a float per the php docs.
