### ISSUE TITLE
Separate charts for download / upload (or mixed axis chart)

### ISSUE THREAD

**Issue by zvarg** [alexjustesen/speedtest-tracker#258]
**Is your feature request related to a problem? Please describe.**
Speedtest results on an asymetric connection can be visually frustrating. I have 1000/40 Mbps down/up speed the nearly representing two horisontal lines. Impossible to see drops.

![image](https://user-images.githubusercontent.com/18576529/209004454-0eefe4b9-443d-4a5e-83af-b2b61b244d9e.png)

**Describe the solution you'd like**
The chart could have a second axis. One for download and one for upload speed. Displaying would be more representating because of the smaller thresholds.

**Additional context**
If the implementation of the the axis chart is problematic, maybe an option for a separate chart would be welcome for down/up speed.

**Comment by alexjustesen** [comment]
For later Alex to reference https://www.chartjs.org/docs/latest/samples/line/multi-axis.html

**Comment by alexjustesen** [comment]
I did also take a little stab at this while I had 5min and at first pass the lines overlap perfectly which is less than ideal... 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/1144087/209009410-f7503ae7-cbac-4b9f-adbe-6adb30c7b52d.png">

Might have to enforce starting the chart from zero again?
<img width="836" alt="image" src="https://user-images.githubusercontent.com/1144087/209009845-e9635fe6-58e5-435d-8f16-bd5ede07cb6b.png">

Open to feedback on this one...

**Comment by zvarg** [comment]
I was looking for something like the last one. Different min and max for each axis is a must have. 

Just thinking...

Starting from zero? Maybe determine min and max dynamically? E.g.: on 1000/40: Download speed would be between 800 and 1100 most of the time, while up speed would be between 0 and 50.

Determine min and max for down speed axis 
Min: `min(of all data of down speed tests) - 20 or 0 if negative`
Max: `max(of all data of down speed tests) + 20
`
Same for up speed.

Something like that.

**Comment by alexjustesen** [comment]
Maybe instead of hard coding these constraints they're prime to configure in the settings. For some (my real connection) I'm 1000/1000 so the dynamic charts are better.

**Comment by zvarg** [comment]
Yes, avoid constants from example (1100, 800, 50,0) Also 20 can be comes from settings. I am not a UX expert, but that can be calculated dynamically too. For example x% of the min and same for max. But that's another profession.

**Comment by alexjustesen** [comment]
So the charts on the dash are powered by Chartjs so it can be extended to anything that lib supports. I'll keep thinking about it.

**Comment by alexdelprete** [comment]
Dynamic limits and single/double Y axis in the options would adapt the graphs to many use-cases.

For more advanced stuff, I'd suggest users to use influx data + grafana, much more flexible and powerful.

**Comment by alexjustesen** [comment]
> For more advanced stuff, I'd suggest users to use influx data + grafana (a dashboard is already available), much more flexible and powerful.

I think it was in a discussion but this is my recommendation as well. In this case I think cleaning up the UI is a good idea but for advanced charting and anything custom I would recommend an external solution.

**Comment by zvarg** [comment]
Since Chartjs is supporting our discussion. Your opinion with starting the grid with zero would be perfect as resolve the feature request. I wait for more feature request about the charts before starting to think big and starting to use another 3rd party packages and libraries.

@alexjustesen What do you think? Are you seeing the example #2 you provided as an easily implementable solution and can we wait for it in relatively short time? In any way, thanks in advance.

**Comment by alexjustesen** [comment]
I'm not going to set a date on when more chat enhancements will be out especially with the holidays coming up.

I've had a bunch of small enhancements and issues over the last couple weeks that have prevented me from starting on backup/import/export which I see as more important than tweaking the UI at this time.

**Comment by zvarg** [comment]
Of course. Enjoy your holiday. As always, feature request should be priorized and more important issues and features comes first.

**Comment by luckman212** [comment]
Not sure if this FR is still being considered, but for example, on my 1G connection, I would prefer if those big purple dips weren't so severe looking. A y axis that was anchored (0-based) would be my preference...

<img width="1008" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/1992842/4956cc27-896c-4d51-87e0-89fd46da9fe6">
