### ISSUE TITLE
Unable keep toggle columns in result table

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#262]
**Describe the bug**
The toggled columns and customizzation of fields in result table, does not kept after logout. 
I am forced to customize at each login ...

**Expected behavior**
The customization of the columns in the results table is kept until a new modification.

Thanks

**Comment by alexjustesen** [comment]
So the columns are tied to the session so if you logout it nukes the session data. I'd either not logout or change the session lifetime in your .env to something longer. It's in minutes fyi.

**Comment by corasaniti** [comment]
@alexjustesen 
SESSION_LIFETIME=120 is it in minutes?
Is there a way to have the session duration infinite?
Thank you

**Comment by alexjustesen** [comment]
To my knowledge there is no way to set it as infinite but you could just put a big number in there

**Comment by corasaniti** [comment]
@alexjustesen 
is the value in minutes? Right?

**Comment by alexjustesen** [comment]
Yeah it is

**Comment by corasaniti** [comment]
i set
-e SESSION_LIFETIME=525600 \
it's been a year, let's hope it's enough... :-)

**Comment by alexdelprete** [comment]
> To my knowledge there is no way to set it as infinite but you could just put a big number in there

could the DB be used to save session data? does filament support this?

**Comment by alexjustesen** [comment]
> > To my knowledge there is no way to set it as infinite but you could just put a big number in there
> 
> could the DB be used to save session data? does filament support this?

already does, session driver default is `database`

**Comment by alexdelprete** [comment]
I remember in the movie War Games that to force Joshua to play by himself the number of players had to be set to zero. Does that work with session to make it infinite? :)

**Comment by alexjustesen** [comment]
Unfortunately no, but you can set it to a year and if you login from time to time it'll reset the time.
