### ISSUE TITLE
Separate Graph for Upload Bandwidth

### ISSUE THREAD

**Issue by adriancossu** [alexjustesen/speedtest-tracker#267]
**Is your feature request related to a problem? Please describe.**
My ISP provides me with a much lower upload bandwidth (30 mbps) than download bandwidth (1gbps). When I view the graph on the dashboard, because the download speeds are much higher the scale of the Y axis does not allow me to perceive differences in the upload speed. 

**Describe the solution you'd like**
I would like the option to have the upload displayed on a separate graph from the download. Or an alternative would be to have a secondary Y axis on the right hand side for upload which scales separately.  

**Additional context**

**Comment by alexjustesen** [comment]
#258
