### ISSUE TITLE
Email notification sent from MAIL_USERNAME instead of MAIL_FROM_ADDRESS 

### ISSUE THREAD

**Issue by SOUPrayer** [alexjustesen/speedtest-tracker#275]
**Describe the bug**
Email notification sent from MAIL_USERNAME instead of MAIL_FROM_ADDRESS 

**To Reproduce**
1. Save email address on notification
2. Click `Test mail channel` or wait until notification is sent
3. Check email to see it is sent from email used to log in(`MAIL_USERNAME`), not from value set to `MAIL_FROM_ADDRESS` variable

**Expected behavior**
Email notification is sent from value set to `MAIL_FROM_ADDRESS` variable

**Environment (please complete the following information):**
Docker running on Unraid

**Screenshots**
![image](https://user-images.githubusercontent.com/26297909/209557613-37180ac3-fe6b-4939-ab0d-b99ffab1ca4d.png)

**Comment by alexjustesen** [comment]
@SOUPrayer can you do me a favor and instead try modifying the mounted `.env` file using the example smtp config here: https://docs.speedtest-tracker.dev/settings/notifications/mail

**Comment by zvarg** [comment]
I tried to set `MAIL_FROM_ADDRESS` variable to custom value. Test email still works like a charm.

@alexjustesen I modified the `.env` file but it is somehow not used at all. I am editing it and nothing changed. But when I am editing my stack and updating it, then it works. After this, when I am watching `.env` file, the old edited values persist. I assume environment variable stored somwhere else.

**Info**: Make sure `MAIL_USERNAME `variable is the full email like username@gmail.com, not just the username, or authenticatin will fail. Also if your password contains `$` you should escape it with anothet `$` character. Personally I recommend using [Google App passwords](https://support.google.com/accounts/answer/185833?hl=en).
