### ISSUE TITLE
Not Working on Raspberry Pi 4

### ISSUE THREAD

**Issue by WaizenErnter** [alexjustesen/speedtest-tracker#276]
I installed it as a stack via portainer on my Pi 4. It runs on Pi OS lite 64Bit and the newest updates. When I queue a Test, nothing is happening. I attached a log File.
[_speedtest-tracker_logs (1).txt](https://github.com/alexjustesen/speedtest-tracker/files/10311127/_speedtest-tracker_logs.1.txt)

My Stack Code:
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '1080:80'
            - '1443:443'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - '/home/docker/speedtest:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:v0.9.1@sha256:bef96eebdd14139fa547000ac304b25bc39f04f211e23efccaeb4e355f4bde4d'
        restart: unless-stopped

**Comment by alexjustesen** [comment]
@WaizenErnter try pulling the latest image, I've got this running on an rpi 4b+ and having no issues. Same OS too

**Comment by WaizenErnter** [comment]
@alexjustesen Did you use docker compose in the terminal, docker compose in portainer or docker run?

**Comment by alexjustesen** [comment]
portainer w/ a stack which is docker-compose from the docs

**Comment by WaizenErnter** [comment]
Which DB version do you use?

**Comment by alexjustesen** [comment]
> @alexjustesen Which DB version do you use?

I'm connecting to a mysql instance on another server in my stack.
