### ISSUE TITLE
Discord Notification and many other by Apprise Notification Library

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#277]
First of all a Big Thank you for continuing the cool old but the New speedtest-tracker.

I hope we will see more new cool futures ...
I'm interested in discord Notification and I saw you have its on list to do ...
You can simply add many notifications by adding to your Docker the Apprise https://github.com/caronc/apprise-api
Thanks

**Comment by alexjustesen** [comment]
Thanks! Just so I'm clear, Apprise is like an notification router where I could create one integration with Apprise and configure it to send out to various services?

**Comment by masterwishx** [comment]
> Thanks! Just so I'm clear, Apprise is like an notification router where I could create one integration with Apprise and configure it to send out to various services?

Yes , you right , just for example how to use it , please check more on https://github.com/caronc/apprise-api

if you need example how easy to integrate it in your project you can check https://github.com/xavier-hernandez/docker-external-ip

from this repo:

1. add 'RUN pip install apprise' in dockerfile
2. and run in script:

 elif [[ "${NOTIFICATION_TYPE}" == "APPRISE" ]]; then
        if [[ -z ${APPRISE_TITLE} ]]
        then
            APPRISE_TITLE="EXTERNAL IP"
        fi
        echo -e "\nSending notification via Apprise..."

        for i in {1..10}
        do
            combo_notify="${NOTIFICATION_TYPE}_${i}"
            if [[ -n ${!combo_notify} ]]
            then
                apprise -vv -t "${APPRISE_TITLE}" -b "${1}" "${!combo_notify}"
            fi
        done
    fi

**Comment by alexjustesen** [comment]
@masterwishx is it just me or does the API not support CURL and is python library based?

**Comment by masterwishx** [comment]
> Scratch that, maybe the stateless solution is what I'm looking for

Are you checked https://github.com/xavier-hernandez/docker-external-ip for how integrated apprise, or you don't want to use pip installed?

**Comment by alexjustesen** [comment]
This project isn't python based which is why I'm asking, instead of relying on a 3rd party service/container I'm probably going to stick close to the eco system and use the notification channels https://laravel-notification-channels.com/about/#suggesting-a-new-channel

**Comment by masterwishx** [comment]
> I'm probably going to stick close to the eco system and use the notification channels

Sure , make it like you think will be better , i only suggested the option that i know .

**Comment by alexdelprete** [comment]
> This project isn't python based which is why I'm asking

I already mentioned you apprise some time ago in another discussion, and you gave me the same answer.

**Comment by alexdelprete** [comment]
I have 4, I know what you're talking about. :)

Problem is sleep deprivation...you'll get used to it...:D

**Comment by alexdelprete** [comment]
@alexjustesen I was thinking about how uptime-kuma (node.js project) used apprise for the notifications, from what I understood, it's including apprise as a docker image, and then it interfaces with it through an app URL: https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/apprise.js

Might be an idea...
