### ISSUE TITLE
Manage our need

### ISSUE THREAD

**Issue by tutur1004** [alexjustesen/speedtest-tracker#283]
**Is your feature request related to a problem? Please describe.**
Hello, I have some network limitation with my host, I need to add limits to the bandwidth, I did with docker-tc for download speed but I can't for upload one

**Describe the solution you'd like**
- [ ] Add a setting to disable/enable separatly Ping/Download/Upload
- [ ] Add a bandwidth limlitation

**Comment by alexjustesen** [comment]
Thanks for the input but at this time it's not technically possible with the cli. Should it in the future please open a new issue.
