### ISSUE TITLE
So I remember to keep my eyes peeled at cloudflare 

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#284]
https://twitter.com/tubes__/status/1610374841517101056?t=NcMlNNlhZ0eGsewNUBdKag&s=19

**Comment by alexdelprete** [comment]
Their speedtest is my favorite, unfortunately there's never been a CLI nor an API.

**Comment by alexjustesen** [comment]
> Their speedtest is my favorite, unfortunately there's never been a CLI nor an API.

I asked this question to a dev working on it, "keep my eyes peeled" was the answer which isn't a "no"

**Comment by alexdelprete** [comment]
Yes I read it on Twitter. :)

**Comment by agneevX** [comment]
Cloudflare has published their nodejs package: https://github.com/cloudflare/speedtest

**Comment by alexdelprete** [comment]
> Cloudflare has published their nodejs package: https://github.com/cloudflare/speedtest

Great news, was waiting for this. It's great to have an alternative benchmark. Hope @alexjustesen will get well soon.

**Comment by alexjustesen** [comment]
Feature is more important than bug fixing right?

**Comment by janisslsm** [comment]
> Feature is more important than bug fixing right?

Nobody mentioned anything about having to add it right away, just notified of the package's release so not sure where you're getting that from.

**Comment by alexjustesen** [comment]
> > Feature is more important than bug fixing right?
> 
> Nobody mentioned anything about having to add it right away, just notified of the package's release since this issue seems to have been meant as a way to keep track of that so not sure where you're getting that from.
> 
> Apologies if this came off as rude, not what I intended.

I was more so joking and referencing the known issues right now with the container and scheduler stability

**Comment by alexdelprete** [comment]
> Apologies if this came off as rude, not what I intended

you haven't been rude at all. and thanks for the heads-up.

> Feature is more important than bug fixing right?

yes, if you don't suffer from bugs. :D (joking)

Take your time Alex, there's no rush, health is more important than anything else.

**Comment by janisslsm** [comment]
> > > Feature is more important than bug fixing right?
> > 
> > 
> > Nobody mentioned anything about having to add it right away, just notified of the package's release since this issue seems to have been meant as a way to keep track of that so not sure where you're getting that from.
> > Apologies if this came off as rude, not what I intended.
> 
> I was more so joking and referencing the known issues right now with the container and scheduler stability

Ah, my bad. I haven't paid much attention to this repo lately so didn't know, just got email notifications from it so I replied.

**Comment by alexjustesen** [comment]
Idea for implementing Cloudflare's Speedtest package. Headless Chrome & Puppeteer as the package relies on a browser and it's intended to be run in the cli.

https://www.howtogeek.com/devops/how-to-run-puppeteer-and-headless-chrome-in-a-docker-container/
