### ISSUE TITLE
Backup / restore data

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#294]
Provide functionality to easily backup and restore the database and any environment variables.

**Comment by HRA42** [comment]
@alexjustesen Where do you stand on this and what are the road block ahead? Would love to start working on a prototype. I started using the app around 6 month ago with version v0.11.17 and I want to migrate my sql-lite database over to postgresql. 

Just want to know where I need to pick up on this :)

**Comment by alexjustesen** [comment]
@HRA42 in the queue to be started on soon... Time zone jank should be fixed this week then I need to circle back around to the CORS issue then it's backup / restore.
