### ISSUE TITLE
Import data from henrywhitaker3/Speedtest-Tracker

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#295]
## 🚀 Planned features
- [ ] At time of import provide the option to "append" results or "overwrite" results

## 🤔 Other tasks / considerations
- [ ] Update the docs to include directions on how to export data from henrywhitaker3/Speedtest-Tracker and how to import it

**Comment by alexjustesen** [comment]
Moved to planned `v0.14.0` as `v0.13.0` has some critical data fixes that'll need to be made and it'll be easier to handle the import after that is done.

**Comment by PJGitHub9** [comment]
Hey! So I migrated to your app from the older project! :) This interface is a lot nicer, got it nicely integrated with MariaDB all running on UnRaid :) 

Is there any progress on the import? It looks like the older version has stopped working for me within the last week for no reason, so you might have more people migrate to this version :)

**Comment by alexjustesen** [comment]
> Hey! So I migrated to your app from the older project! :) This interface is a lot nicer, got it nicely integrated with MariaDB all running on UnRaid :) 
> 
> Is there any progress on the import? It looks like the older version has stopped working for me within the last week for no reason, so you might have more people migrate to this version :) 

Important is planned after some backup / restoration work that needs to occur and then I need to fix some data jank.

Basically don't want to import data if I don't have a good process for backing up and restoring the previous state.

**Comment by flammable** [comment]
Hello! I've been holding off from switching to this version, as I don't want to lose my stats from the old version (which somehow still works for me). If I switch, but keep the data from the old version in a separate folder, can I import it later? Or should I stick with the old version and wait for the import feature?

Thanks for adding so many improvements! I'm really excited to use this!

**Comment by alexjustesen** [comment]
A significant period of time has gone by without this being implemented, if you're still following this feature proposal give a 👍 or 👎 if you'd use it.

**Comment by alexjustesen** [comment]
Since we're 2+ years out at this point, we're going to move on. Unless you're hording data (I get it) there is no benefit to keeping history this far back.
