### ISSUE TITLE
Adding Speedtest Server ID doesn't always work correctly

### ISSUE THREAD

**Issue by alexdelprete** [alexjustesen/speedtest-tracker#314]
I'd like to be able to specify a speedtest id manually in the config, but it seems like you can only select from the lookup list. And it doesn't always find the server you need. (I tried adding 3667, TIM Milano).

The server is working and it's also reliable, so I'd like to add it but I can't. I know I could fiddle with the db and insert it manually, but I think it's something to be fixed nonetheless.

**Comment by alexjustesen** [comment]
Did you try searching just by name?

**Comment by alexdelprete** [comment]
Yes...I find TIM for other cities, not the one I need though. Is it possible to search also for ID?
