### ISSUE TITLE
Ubuntu 22.04 and multi-arch support

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#32]
The base image used for this project is testing Ubuntu 22.04 along with a complete refactor so I'm going to bump the base image to their beta and start testing shortly.

In addition to upgrading the base OS multi-arch support should also be provided so that devices like Raspberry Pi's can run Speedtest Tracker.

https://github.com/serversideup/docker-php/pull/59

**Comment by benjamin-feron** [comment]
Hi,
Does it means your image will be compatible with arm64 ?

**Comment by alexjustesen** [comment]
Reopening this, while the base has support for other architecture I haven't done it or tested anything as of yet.

**Comment by Jiriteach** [comment]
Awesome work on the multi-arch support. Any chance of a armv7l build? Thanks

**Comment by alexjustesen** [comment]
> Awesome work on the multi-arch support. Any chance of a armv7l build? Thanks

Running some old raspberry pi's are we?
