### ISSUE TITLE
Missing Database Notification

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#323]
**Describe the bug**
I have created a new user and although notifications are enabled from the settings, I am not receiving notifications from the database. They appear to only come for the default user admin@example.com

**To Reproduce**
1. Create new user
2. verify that database notifications are active
3. perform new speedtest
4. verify that notifications are not displayed

**Expected behavior**
Database notifications must be received by all users

**Environment (please complete the following information):**
 - OS: RaspianOS bullseye
-  Architecture: armv7
 - Browser Chrome and Opera

**Comment by alexjustesen** [comment]
Oooo ya know what, I need to get that updated as notifications were only designed for the 1 user model. Will be in a future patch.

**Comment by alexjustesen** [comment]
So on this one... I really need to change how notifications are handled now that there are multiple users possible in the app. Adding that feature added more complexity than initially thought.

I don't want to just blanket send everything to each user so a future update will be moving notification settings from the app level to be set at the user level.

Closing for now but got it in my notes.
