### ISSUE TITLE
Test Telegram channel receive 'Error 500'

### ISSUE THREAD

**Issue by garanda21** [alexjustesen/speedtest-tracker#325]
**Describe the bug**
On click 'Test Telegram channel', receive 'Error 500'

**To Reproduce**
1. Go to 'Notifications'
2. Click on 'Enable telegram notifications'
2. Click on 'Test Telegram channel'

**Expected behavior**
No error and warning about the missing information

**Logs**
`production.ERROR: count(): Argument https://github.com/alexjustesen/speedtest-tracker/pull/1 ($value) must be of type Countable|array, null given {"userId":1,"exception":"[object] (TypeError(code: 0): count(): Argument https://github.com/alexjustesen/speedtest-tracker/pull/1 ($value) must be of type Countable|array, null given`

**Additional context**
On first time click is evaluating against a `null` object, of course `count` fails... 

A new pull request #324 is open fixing this behaviour and with a bonus validation.

**Comment by corasaniti** [comment]
I confirm this Issue. I also have a question: In the Telegram notification settings I am only asked "ChatID" for the recipient. 
No Telegram bot token request??!?! It's correct?
Thanks

**Comment by garanda21** [comment]
> I confirm this Issue. I also have a question: In the Telegram notification settings I am only asked "ChatID" for the recipient.
> No Telegram bot token request??!?! It's correct?
> Thanks

Yes on UI you only setup your personal `ChatID`, for bot token you have to setup on `.env` file in your mounted data directory. 

Please refer to a documentation: [https://docs.speedtest-tracker.dev/settings/notifications/telegram](https://docs.speedtest-tracker.dev/settings/notifications/telegram)

**Comment by corasaniti** [comment]
@garanda21 

Since i don't use the .env file,  can I pass an environment variable to my docker run?

`-e TELEGRAM_BOT_TOKEN=putyourtokenhere`

Thanks

**Comment by garanda21** [comment]
> @garanda21
> 
> Since i don't use the .env file, can I pass an environment variable to my docker run?
> 
> `-e TELEGRAM_BOT_TOKEN=putyourtokenhere`
> 
> Thanks

Absolutely, it should work. I have mine on my docker-compose variable and works perfect!

**Comment by corasaniti** [comment]
> I confirm this Issue. I also have a question: In the Telegram notification settings I am only asked "ChatID" for the recipient. No Telegram bot token request??!?! It's correct? Thanks

I correct myself. The "Test telegram Channel" button works perfectly. The `TELEGRAM_BOT_TOKEN `in the .env file was probably missing

**Comment by jiimint** [comment]
Hi 
I just have the same "error 500"
I add the TELEGRAM_BOT_TOKEN in the .env file and I put the chat id in settings.
After testing receive the error 500.

**Comment by jiimint** [comment]
> Hi I just have the same "error 500" I add the TELEGRAM_BOT_TOKEN in the .env file and I put the chat id in settings. After testing receive the error 500. My log: `192.168.100.200 - - [17/Jan/2023:10:40:05 +0000] "POST /livewire/message/app.filament.pages.settings.notification-page HTTP/1.1" 500 6628 "http://192.168.100.40:8080/admin/notifications" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"`

Just find error!!!
Please change your [documatation ](documentation: https://docs.speedtest-tracker.dev/settings/notifications/telegram)
here and in` telegram Chat ID` must be `-1234567890`

**Comment by garanda21** [comment]
> > Hi I just have the same "error 500" I add the TELEGRAM_BOT_TOKEN in the .env file and I put the chat id in settings. After testing receive the error 500. My log: `192.168.100.200 - - [17/Jan/2023:10:40:05 +0000] "POST /livewire/message/app.filament.pages.settings.notification-page HTTP/1.1" 500 6628 "http://192.168.100.40:8080/admin/notifications" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"`
> 
> Just find error!!! Please change your (documentation: https://docs.speedtest-tracker.dev/settings/notifications/telegram) here and in` telegram Chat ID` **must** be `-1234567890`

That pretty much depends on your chat, If the chat is a group, the chat id is negative. If it is a single person, then positive.

Right now mine is configured without dash and works perfect, my Chat ID is for single person.

**Comment by alexdelprete** [comment]
> Right now mine is configured without dash and works perfect, my Chat ID is for single person.

Same for me, my chat ID is a positive number, not negative. Works perfectly.

**Comment by jiimint** [comment]
> > > Hi I just have the same "error 500" I add the TELEGRAM_BOT_TOKEN in the .env file and I put the chat id in settings. After testing receive the error 500. My log: `192.168.100.200 - - [17/Jan/2023:10:40:05 +0000] "POST /livewire/message/app.filament.pages.settings.notification-page HTTP/1.1" 500 6628 "http://192.168.100.40:8080/admin/notifications" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"`
> > 
> > 
> > Just find error!!! Please change your (documentation: https://docs.speedtest-tracker.dev/settings/notifications/telegram) here and in` telegram Chat ID` **must** be `-1234567890`
> 
> That pretty much depends on your chat, If the chat is a group, the chat id is negative. If it is a single person, then positive.
> 
> Right now mine is configured without dash and works perfect, my Chat ID is for single person.

Yes its a group id, so they have to add it this difference in their documentation.

**Comment by superfunk2000** [comment]
I can confirm that it only works for Individual Users, not Groups (with a negative sign).
I would appreciate it if it worked for groups too.

Tip: It is important to always save first and then request the test message.

**Comment by garanda21** [comment]
@alexjustesen This should be closed, due to new 11.1 version fixes it!

**Comment by alexjustesen** [comment]
Consider it done
