### ISSUE TITLE
Docker image version tagging

### ISSUE THREAD

**Issue by eltionb** [alexjustesen/speedtest-tracker#326]
Instead of only using latest tag, can you also tag the image with the release version?

Example: ghcr.io/alexjustesen/speedtest-tracker:v0.11.0

**Comment by alexdelprete** [comment]
it's already like this: https://github.com/alexjustesen/speedtest-tracker/tags

**Comment by eltionb** [comment]
Thanks for quick reply.
I actually based my issue on tags not showing up in docker hub: https://hub.docker.com/r/ajustesen/speedtest-tracker/tags

Just validated that tags are ok in ghcr.

great project btw

**Comment by alexjustesen** [comment]
> it's already like this: https://github.com/alexjustesen/speedtest-tracker/tags

Yeah they're right, noticed this last night while on DH. This should def be addressed. @UnAfraid in the past you've helped with getting the Docker workflow polished, any chance you'd be able to help here too?

**Comment by UnAfraid** [comment]
> > it's already like this: https://github.com/alexjustesen/speedtest-tracker/tags
> 
> Yeah they're right, noticed this last night while on DH. This should def be addressed. @UnAfraid in the past you've helped with getting the Docker workflow polished, any chance you'd be able to help here too?

Sure thing, i'll open up a PR soon.

**Comment by alexdelprete** [comment]
> Just validated that tags are ok in ghcr.

sorry, I tend not to use docker hub when possible, ghcr.io is much better, so I never tested it on DH. :)

**Comment by alexdelprete** [comment]
> Sure thing, i'll open up a PR soon.

The power of open-source and the spirit of collaboration never ceases to surprise me, even after all these years. Thank you guys. :)

**Comment by alexjustesen** [comment]
> Sure thing, i'll open up a PR soon.

Really appreciate it, thank you!
