### ISSUE TITLE
Unable to update above 0.6.2

### ISSUE THREAD

**Issue by EVOTk** [alexjustesen/speedtest-tracker#332]
**Describe the bug**
I am currently in version 0.6.2, and I can't update to a higher version (I have an error 500)

**To Reproduce**
1. Update image docker to 0.7.0
2. Open speedtest-tracker
3. See error

**Expected behavior**
No 500 error after update to >0.6.2

**Environment (please complete the following information):**
 - OS: OMV6 - Docker
-  Architecture: amd64
 - Browser : Firefox
 - Version 0.6.2 to 0.7.0 ( same result to update to 0.7.1 or 0.8.0, or latest 0.11.0 )

**Screenshots**
Before update : 
![image](https://user-images.githubusercontent.com/45015615/212464443-a98ac5a1-4d90-4ca2-b574-fecf9205430e.png)

After Update : 
![image](https://user-images.githubusercontent.com/45015615/212464454-c62a55b6-6c32-415a-a14c-a06562d683db.png)

**Logs**
After update 0.6.2 to 0.7.0 : 
 [_speedtest-tracker_logs(2).txt](https://github.com/alexjustesen/speedtest-tracker/files/10416982/_speedtest-tracker_logs.2.txt)

**Additional context**

**Comment by EVOTk** [comment]
Oh, I realize that if I click on "Results" I also get an error 500, even with version 0.6.2

**Comment by alexjustesen** [comment]
Have you tried forcing a pull of the `:latest` image? If that hasn't worked stop the container, delete the image from storage and pull latest again.

**Comment by EVOTk** [comment]
Hello
Thank you for the answer.
As long as I want to use a version higher than 0.6.2, it breaks the functioning of speedtest tracker. 
I was in version 0.3.0 
I restored a backup of this morning, I can upgrade to 0.6.2 without any problem, after some version I have 500 errors.

**Comment by alexjustesen** [comment]
You should be able to migrate all the way to the latest version `0.11.0`, but it looks like the error is missing settings data which I believe existing in an old version until patched.

Can you try going straight to `v0.11.0` and if it doesn't work post the logs again?

**Comment by EVOTk** [comment]
I deleted the container, and modified my compose to use image 0.11.0, then create the container.
![image](https://user-images.githubusercontent.com/45015615/212500943-8108db2c-905a-4eff-8aff-cc1facd228bb.png)

When I access the WebUI, I accept the self-signed certificate, and I get a 500 error directly:
![image](https://user-images.githubusercontent.com/45015615/212500978-629b5fcb-50f8-44ce-a445-3904bb36d1e2.png)

Here are the logs:
[logs_after_0.6.2_to_0.11.0.txt](https://github.com/alexjustesen/speedtest-tracker/files/10419068/logs_after_0.6.2_to_0.11.0.txt)

**Comment by EVOTk** [comment]
Hello,
I have retried the migration to 0.11.0. 
I told myself that in case of failure I would start again from scratch, but the migration worked on the 1st try...

I have now the last version, and no 500 error.

It's solved :D, even if I don't understand how :(
