### ISSUE TITLE
Description how to use InfluxDB

### ISSUE THREAD

**Issue by zackmuc** [alexjustesen/speedtest-tracker#334]
**Is your feature request related to a problem? Please describe.**
Do not know how to get influxdb with speedtest tracker to work

**Describe the solution you'd like**
Could there be a manual?

**Comment by nhasian** [comment]
detailed instructions are here:
https://docs.speedtest-tracker.dev/settings/data-platforms/influxdb2

**Comment by alexjustesen** [comment]
As far as setting up influxdb and using it to house data for graphana I'd search around on youtube as there are many tutorials out there for that patterns.
