### ISSUE TITLE
Unable to access after update 

### ISSUE THREAD

**Issue by theRealBassist** [alexjustesen/speedtest-tracker#335]
**Describe the bug**
Following updating my stack, I am unable to access speedtest tracker. Previously I was able to. Now I am not.

**To Reproduce**
1. Stop my container
2. Pull the latest image
3. Start the container

**Expected behavior**
When I go to the IP:PORT of the container, I should access the instance

**Environment (please complete the following information):**
 - OS: Linux Mint
-  Architecture: amd64
 - Browser: Firefox
 - Version: 0.11.0

**Screenshots**
![image](https://user-images.githubusercontent.com/18382263/212544232-9210a3a6-67ca-43a9-b0c8-bf81dec0cf8f.png)

**Logs**
Unknown which are applicable

**Additional context**
I have port 80 forwarded to 8110. However, I have also tried it with 443 and it does not work there either. I setup my container through Portainer using docker-compose. I will include a copy of it below

[docker-compose.txt](https://github.com/alexjustesen/speedtest-tracker/files/10420332/docker-compose.txt)

**Comment by garanda21** [comment]
You have to share your container log, otherwise is imposible to know the causes!

Check this for reference: [https://docs.docker.com/engine/reference/commandline/logs/](https://docs.docker.com/engine/reference/commandline/logs/)

**Comment by theRealBassist** [comment]
> 

Apologies! They will be attached below.
[Logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/10421481/Logs.txt)

**Comment by alexjustesen** [comment]
I wonder if this is similar to the issue in #332...

**Comment by theRealBassist** [comment]
@alexjustesen So that was actually one of the issues that I looked through before I posted here myself. The major difference that I saw was that, from what I could tell he seems to be displayed an error code from within speedtest tracker whereas mine is just flat out not connecting.

I might be misunderstanding the other issue, of course, but I can definitely see them being at least somewhat related issues.

**Comment by alexjustesen** [comment]
Have you tried the insecure port and mapping to `:80`?

**Comment by garanda21** [comment]
Maybe try `ssl_mode` ?

This issue help me in the past:

[https://github.com/alexjustesen/speedtest-tracker/issues/280#issuecomment-1368988522](https://github.com/alexjustesen/speedtest-tracker/issues/280#issuecomment-1368988522)

**Comment by theRealBassist** [comment]
@alexjustesen 

I just tried mapping 8110:80, but to no avail.

@garanda21 

I tried setting SSL_MODE=off (in conjunction with mapping 8110"80) in the environment section of my docker-compose, but also to no avail.

**Comment by alexjustesen** [comment]
Yeah ssl mode is now "mixed" by default so you have the flexibility to map to either `80` or `443` so I don't think it's that.

Can you attach your logs?

**Comment by alexjustesen** [comment]
@theRealBassist `v0.11.1` was just released that removes the trusted proxy restrictions. This should improve ease of use when working with different proxy services. If you continue to have issues please post in this discussion.

https://github.com/alexjustesen/speedtest-tracker/discussions/364
