### ISSUE TITLE
Option to disable authentication

### ISSUE THREAD

**Issue by MattIPv4** [alexjustesen/speedtest-tracker#336]
**Is your feature request related to a problem? Please describe.**

As a user of the tracker on a private network where I am the only one with access, I'd like to disable authentication for ease-of-use.

**Describe the solution you'd like**

Allow the disabling of authentication for the tracker. The UI notes that this is on the roadmap, but I didn't see an existing issue actually tracking this.

**Additional context**

N/A

**Comment by alexjustesen** [comment]
At this time I'm not planning on removing authentication as it's core to the admin panel framework and would take a bit of effort.

**Comment by MattIPv4** [comment]
Fair enough, would it make sense to remove the note in the panel itself that says you've got it on the roadmap to support disabling?

**Comment by alexjustesen** [comment]
Oooo good catch. Forgot about that

**Comment by ajayt6** [comment]
i ran into the same problem. Worked around it by setting env variable PUBLIC_DASHBOARD to true.
