### ISSUE TITLE
Configuration - Could not retrieve or read configuration (ConfigurationError)

### ISSUE THREAD

**Issue by Bag72** [alexjustesen/speedtest-tracker#343]
Just checking my speeds, system has been running since early november 22 with no issues.  On the 13-Jan, last Friday it stopped working and is returning a error.
This was the first error raised.  The hour before it worked fine.
{"type":"log","timestamp":"2023-01-13T20:00:13Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}
Except for the date/time the same error was generated every hour since then.   
Interestingly the system reports the container was updated 7 days ago, on the 13th.   I've changed nothing, the .env file is readable both on the NAS and inside the container.  The Containers are running OK and the Internet is working fine.
I've restart the containers.  I even remove the volume link to config so it used the container one only.  I wiped the containers and reloaded the images. No difference.
Any ideas?

**Comment by alexjustesen** [comment]
@Bag72 you ran into the new reporting on failures feature, try changing the server you speedtest against.

**Comment by Bag72** [comment]
I've not chosen a server.  I leave the field blank to let it select the best server as it says in the field.

I click the drop down and there is nothing there and if I type something in the field, like google.com, it fails with a Server 500.

**Comment by alexjustesen** [comment]
Yeah that's because `google.com` wouldn't be an accurate server ID. From the container make sure it has access to the internet but pinging google with `ping google.com` and making sure there is no packetloss and/or the connection is successful. 

In the server field the IDs should only be valid Speedtest Server id's from the search feature or that you've manually entered in integer form.

**Comment by Bag72** [comment]
Alex,  Thanks for the quick responses.
I can access the internet fine from the host.   Not sure what to do from inside the container to test it has a link though.

As I said I don't have anything in the dropdown for the server list and so I typed in the IP and server id for the last successful link.
Funnily enough I noticed that I had one successful connection yesterday at 1400.  Just the one since it stopped working.
So how do I enter server ids,  what are valid server ids that I could use and why is is not picking up some as before when I don't enter anything as in 'Leave empty to let the system pick the best server.'   It is clearly picking invalid servers.

**Comment by Bag72** [comment]
Update : Although inside the container I couldn't ping or wget, curl worked fine so I was able to pull something down from within the container.  It also has internet access.

**Comment by Flyingfufu** [comment]
Hello,

First, many thanks for this project.

Then, exact same issue here. There is no way to add a server Id in the field. I only get a "500 | Server Error" message, whatever the id number or server address I put in the field. The problem started after I've upgraded to the last version... Any further test idea is welcome

**Comment by Flyingfufu** [comment]
Hello,

First, many thanks for this project.

Then, exact same issue here. There is no way to add a server Id in the field. I only get a "500 | Server Error" message, what ever the id number or server address I put in the field.

**Comment by Bag72** [comment]
Clearly not everyone is hitting this.  I've rebuilt the docker again but not wiped the DB.   The config area has the .env in it.   Should I just delete the lot and lose all my data or is there a way I can reset the server ids and move on.

Is there anything I can try?

**Comment by alexjustesen** [comment]
If you use something like dbeaver you can open the SQLite DB or others. You can then go into the settings table and modify the server listing.

Obviously make sure to take a backup before doing so. 

If dbeaver gives you issues for sqlite there are other ide's you can use

**Comment by Bag72** [comment]
Alex, I have no idea what to change in the DB so that doesn't help me.  Do you have more detailed instructions?

It looks to me that I may as well wipe all my data and start again.   I can do this if necessary but would prefer not to lose my data.   Do you know what happened so it won't happen again?

**Comment by Bag72** [comment]
Alex, I'm going to reinstall from scratch wiping all my data.  I'm actually already using Maria DB as I used your docker-compose file to get it going and I've several Maria and MySQL instances and none of those have been corrupted.

I am convinced it is something in the last build you released.  It died immediately after that was applied.  Funny it only happened to a few people.  Maybe I'll skip the upgrades unless there are major changes.

**Comment by Bag72** [comment]
Well that didn't go well.   I stopped the containers, wiped everything, after making a backup, and even deleted the images so it would have to download.   Brought it all back up.  Same situation.  No ids in the dropdown and the system complains about the configuration file again.

I'm now going to try a previous version, although never done this before, to take me back to the previous working version.  Let you know how that goes.

**Comment by alexjustesen** [comment]
If you go into the container's terminal try running `php artisan migrate --force` and see if anything happens. Hint: nothing should. It should say "no migrations" or something to that effect.

If that doesn't work and you want a fresh install at the DB layer try `php artisan app:install --force`, WARNING: it will reset everything!

**Comment by Bag72** [comment]
The first cli line said 'Nothing to Migrate' as you suspected.  The second one went through an initialisation script which wiped the DB but it still did not work.   Same configuration error.

I also tried previous versions of the docker containers and none of them worked.  I even tried it without the data being mapped to a volume outside the container.  Nothing got exactly the same configuration error.  I'm guessing that there are several failures at the start that show up as configuration errors as I am now beginning to suspect that it is reading the file fine but hitting an error with a DNS resolution or something and it simply displays that as an error. 

Anything else I can run to identify the issue?

**Comment by alexjustesen** [comment]
Can you get the logs from when the docker container starts?

**Comment by CAuguston** [comment]
[speedtest-tracker.log](https://github.com/alexjustesen/speedtest-tracker/files/10494761/speedtest-tracker.log)

Im getting similar issues. I have pasted my log from docker-compose
[_speedtest-tracker_logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/10494788/_speedtest-tracker_logs.txt)

**Comment by Bag72** [comment]
My log files.
DC Up.txt is the logs generated on the console at startup then it sits and waits
[DC Up.txt](https://github.com/alexjustesen/speedtest-tracker/files/10498185/DC.Up.txt)

DC_Log_Test.txt is where I connect to the GUI and trigger a queued job
[DC Log Test.txt](https://github.com/alexjustesen/speedtest-tracker/files/10498186/DC.Log.Test.txt)

**Comment by Bag72** [comment]
Alex,   Brian @AwesomeOpenSource on YouTube has just released a video on this software.  Watching it I realised that I had not seen that version before.   So it appears that I have been running the same version since early November.   Which made me think my config file might be missing some key changes that the latest version needs.  Hence the config issue.

So I wiped everything in the shared directories, the .env file, the Maria DB files and wiped the docker images I had downloaded.  Funnily enough deleting the latest version of the image crashed my NAS and it took a bit of fiddling, and a few crashes, to remove the image.  Eventually, it was a clean system with no speedtest data at all and no old container images.   I then performed docker-compose up and it downloaded the latest image and it came up working.   I then brought it down, reloaded the MariaDB databases and tried again and it stayed working so I have my data as well.   Fantastic, Win Win.

So mine is fixed.   Not sure what I did as I had already rebuilt without the .env.  Perhaps my downloaded version was corrupt.  It did start when it was upgraded and brought my system down removing it and now it is gone it worked when I downloaded the latest version.  I'm not sure tbh.

However, love the new version. you have made so many improvements.  I'm impressed.  Thank you for your help on this.

**Comment by alexdelprete** [comment]
> I realised that I had not seen that version before.

so you were using the old ST project with instructions taken from this new project? Didn't you see the screenshots in the documentation?

This could explain why other users are having issues, they're mixing projects. :)

**Comment by Bag72** [comment]
No, I was not mixing projects.  I meant an older version of the 'alexjustesen/speedtest-tracker' docker image which is now 0.11.   I loaded it up with docker compose in November and think I was on 0.6.1 or something close having looked through them all.   Now I have 0.11 installed and working.

**Comment by alexdelprete** [comment]
You wrote yesterday:

![image](https://user-images.githubusercontent.com/7027842/214587069-fc01dcca-5bc0-467c-81d0-356208d69b0c.png)

So what did you mean by "latest"?

**Comment by Bag72** [comment]
I meant build v0.11 being the latest build.

**Comment by alexdelprete** [comment]
So you were not using the old version...

**Comment by Bag72** [comment]
Just because another product is available that you mistakenly thought I was using doesn't change the fact that v0.6 is an older version of this product. That is what the v in front of the numbers mean.  You understand what I meant by old version after I clarified it.  Who cares?  It's not a big deal.

For the record I've not even tried the other guys version.  This is the first and only one I tried and it does everything I want and he hasn't even finished his plans yet..

**Comment by alexdelprete** [comment]
You said you updated to latest version and it didn't work. After a while you said everything was fixed, because you were simply using a very old version (0.6). I see some contradictions. :)

But you're correct on one thing: who cares...let's not waste more time on a non-existent issue. 

Good luck. And please close the issue if you're ok now.

**Comment by Bag72** [comment]
Agree and I'll let you have the last word there because I'm such a nice guy.  :) 
I was leaving it open because others were having similar issues and although I now believe my issue was my own system being corrupt somehow others may have different view.
 I'm happy to close it.    Thanks again for the help.

**Comment by alexjustesen** [comment]
Glad the video helped! I saw it too because I noticed a big jump in stars over the last couple of days
