### ISSUE TITLE
Clarify thresholds in docs

### ISSUE THREAD

**Issue by Wyrrrd** [alexjustesen/speedtest-tracker#345]
I am a bit confused by the naming of "absolute thresholds".

If these are the only thresholds available, the name is weirdly specific. Maybe move to just "thresholds".

If there are such things as "relative thresholds", the docs are just devoid of info about them. If these are not yet implemented, but planned, there could be a placeholder in the feature list for them.

**Comment by alexjustesen** [comment]
Soon(tm), well at least they're planned so in prep for that it was better to get the naming right from the get go.

Plus it's always better to be overly specific especially with OSS
