### ISSUE TITLE
Low speed values with selected server in config.yml

### ISSUE THREAD

**Issue by alexdelprete** [alexjustesen/speedtest-tracker#35]
I noticed really low speed values reported in the admin panel, I just did a manual test with the server 4302 I configured in `config.yml`:

```yaml
speedtest:
  enabled: true
  schedule: '*/40 * * * *' # every hour
  ookla_server_id: 4302 # specify a server ID to use a sepecific server
tz: 'Europe/Rome'
```

```shell
   Speedtest by Ookla

      Server: Vodafone IT - Milan (id: 4302)
         ISP: Tecno General S.r.l
Idle Latency:     8.64 ms   (jitter: 0.31ms, low: 8.36ms, high: 9.29ms)
    Download:   813.10 Mbps (data used: 874.1 MB)
                 42.38 ms   (jitter: 38.70ms, low: 9.66ms, high: 941.40ms)
      Upload:   261.07 Mbps (data used: 150.7 MB)
                  9.76 ms   (jitter: 0.77ms, low: 8.44ms, high: 12.24ms)
 Packet Loss:     0.0%
  Result URL: https://www.speedtest.net/result/c/158c6f1d-3278-4606-b24a-fbd142c6deec
```

Is alpha.6 still using config.yml? If that's the case, I'm worried about the performance within docker, but the old speedtest-tracker worked fine in that regard. How do I check detailed info of a single test (server used, etc.)?

**Comment by alexjustesen** [comment]
This might be related to docker networking, can you try running the container on the host network? Looks like an issue was opened on the original repo too https://github.com/henrywhitaker3/Speedtest-Tracker/issues/919#issuecomment-1262319044

**Comment by Kostecki** [comment]
I'm experiencing this as well. Messing with docker networking doesn't seem to improve anything.

**Comment by alexdelprete** [comment]
> This might be related to docker networking, can you try running the container on the host network? Looks like an issue was opened on the original repo too

Tried with host network, made no difference. My suspicion is that it's not using the server I configured, or something related to the version of speedtest-cli.

**Comment by alexdelprete** [comment]
> I have a container with the original repo running alongside - here i don't have any problems maxing my connection.

Yup, same for me. But I remember I had this issue with the old project too, and fixed it upgrading speedtest-cli. Since then, everything was ok.

**Comment by alexjustesen** [comment]
I've got family in town for a couple of days but I'll look into this ASAP. It's happening for me as well

**Comment by alexdelprete** [comment]
> It's happening for me as well

Glad you have the same issue, so you can trace it. No worries about timing, no emergency.

**Comment by Kostecki** [comment]
I get the expected results when i run the speedtest directly inside the container. Same server for both tests and the test themselves are run pretty much back to back.

The current version of the speedtest binary (1.2.0.84) also seems to be the latest version available from Ookla, so probably no issues there.

**Comment by alexdelprete** [comment]
> I get the expected results when i run the speedtest directly inside the container. Same server for both tests and the test themselves are run pretty much back to back.

My suspect is that the scheduled tests are not run against the configured server. From the UI there's no column indicating which server ID has been used for each test.

> The current version of the speedtest binary (1.2.0.84) also seems to be the latest version available from Ookla, so probably no issues there.

Yes 1.2.0.84 is the latest. Thanks for reporting this, at least we can exclude that problem.

**Comment by Kostecki** [comment]
> My suspect is that the scheduled tests are not run against the configured server. From the UI there's no column indicating which server ID has been used for each test.

There is in the database though (i use MariaDB) and the server_id/server_name columns do match with the value i provided in the config.yml - at least for me.

**Comment by alexdelprete** [comment]
Thanks. So that's weird...I hope Alex finds the issue.

**Comment by alexjustesen** [comment]
Next release will contain the server info in the results table https://github.com/alexjustesen/speedtest-tracker/pull/38.

Still working on the speed issue

**Comment by alexjustesen** [comment]
I've also confirmed speed tests are running slow from within the container, not a clue why just yet but documenting results below...

Internet plan  `1gbps/1gbps`

### CLI from WSL
```bash
   Speedtest by Ookla

      Server: Frontier - Wallingford, CT (id: 14235)
         ISP: Frontier Communications
Idle Latency:     5.66 ms   (jitter: 0.54ms, low: 5.03ms, high: 6.41ms)
    Download:   937.26 Mbps (data used: 1.3 GB)
                 11.83 ms   (jitter: 1.23ms, low: 4.36ms, high: 19.07ms)
      Upload:   922.49 Mbps (data used: 497.1 MB)
                  6.97 ms   (jitter: 1.05ms, low: 4.67ms, high: 10.50ms)
 Packet Loss:     0.0%
```

### CLI from within the container
```bash
Speedtest by Ookla

      Server: Frontier - Wallingford, CT (id: 14235)
         ISP: Frontier Communications
Idle Latency:     5.77 ms   (jitter: 0.21ms, low: 5.67ms, high: 5.99ms)
    Download:   238.27 Mbps (data used: 212.5 MB)                                                   
                  6.25 ms   (jitter: 1.49ms, low: 4.34ms, high: 15.75ms)
      Upload:   237.21 Mbps (data used: 390.4 MB)                                                   
                  6.26 ms   (jitter: 1.94ms, low: 4.25ms, high: 33.07ms)
 Packet Loss:     0.0%
```

**Comment by michealespinola** [comment]
Although we are all referring to docker, it may be valuable to know which OS people are having issues with. I believe there are inherent performance issues with docker on Windows that this may involve. It could be useful to distinguish and/or isolate the issue with.

**Comment by bverkron** [comment]
I have really inconsistent results in the container, but the host is very consistent.

Container results (easier to show a history of results from the web UI than the CLI output, but they're basically the same)
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/19174503/193332013-61bc3b8f-31bb-4f17-a534-2a1f45151a81.png">

Host results (get very close to this every single time)
```
Idle Latency:     2.47 ms   (jitter: 0.41ms, low: 1.80ms, high: 2.93ms)
    Download:   919.62 Mbps (data used: 1.4 GB)                                                   
                  8.75 ms   (jitter: 5.43ms, low: 3.45ms, high: 464.80ms)
      Upload:   759.28 Mbps (data used: 1.4 GB)                                                   
                  4.96 ms   (jitter: 1.95ms, low: 1.30ms, high: 18.65ms)
 Packet Loss:     0.0%
```

I'm running with the following configuration (switched to host networking during troubleshooting in this issue )

```dockerfile
version: '3.6'
services:   
  speedtest:
      container_name: speedtest
      image: henrywhitaker3/speedtest-tracker
      # required to get full speed
      network_mode: host
      # not required when running in host mode as the ports are defined by the built in nginx instance in nginx/site-confs/default
      # ports:
      #  - 8765:80
      volumes:
          - /home/master/speedtest/mount_config:/config
      environment:
           - TZ=America/Vancouver
           - OOKLA_EULA_GDPR=true
      logging:
          driver: "json-file"
          options:
              max-file: "10"
              max-size: "200k"
      restart: unless-stopped   
```

nginx/site-confs/default
```
server {
        listen 8888 default_server;
... rest of file is defaults...
}
```
FYI one of the first things I checked was whether it was using the correct Ookla server and it was. It's within the same city as me and the same one that gets used in the Ookla web UI and on the host where I get the consistent fast speeds.

**Comment by alexdelprete** [comment]
> Although we are all referring to docker, it may be valuable to know which OS people are having issues with. I believe there are inherent performance issues with docker on Windows that this may involve. It could be useful to distinguish and/or isolate the issue with.

Ubuntu. In the past I used the old project container also on a docker for windows, no performance issues.

**Comment by alexdelprete** [comment]
> I have really inconsistent results in the container, but the host is very consistent.

from what I see, you're using the old project container. We're discussing about the new one in this repo.

**Comment by alexjustesen** [comment]
> > I have really inconsistent results in the container, but the host is very consistent.
> 
> from what I see in the docker-compose, you're using the old project container. We're discussing about the new one in this repo.

Old repo is having the same issue it looks like so I directed @bverkron here so they can follow along with the new stuffs.

**Comment by alexjustesen** [comment]
> Although we are all referring to docker, it may be valuable to know which OS people are having issues with. I believe there are inherent performance issues with docker on Windows that this may involve. It could be useful to distinguish and/or isolate the issue with.

Worth a shot... I am currently running this on Windows 11 version `22H2`, -> WSL -> Docker. I'll try running the container on my lab machine Ubuntu 22.04 and see if it has the same issues.

**Comment by bverkron** [comment]
> > > I have really inconsistent results in the container, but the host is very consistent.
> > 
> > 
> > from what I see in the docker-compose, you're using the old project container. We're discussing about the new one in this repo.
> 
> Old repo is having the same issue it looks like so I directed @bverkron here so they can follow along with the new stuffs.

Ah, you're correct! I started this setup / journey with the original repo (as that's referenced in most places online) and didn't think to convert to migrate one when I found out about it. 😅.

I did a fresh setup with the following but get `500 | SERVER ERROR` in the UI :(

```
services:   
  speedtest:
      container_name: speedtest-tracker
      image: ghcr.io/alexjustesen/speedtest-tracker:latest
      ports:
        - 8888:80
      volumes:
          - /home/master/speedtest/mount_app:/app
      environment:
           - HP_POOL_NAME=speedtest-tracker_php
           - DB_CONNECTION=sqlite
           - DB_DATABASE=/app/database.sqlite
      restart: unless-stopped 
```

I'll do some troubleshooting and open a separate issues if necessary.

**Comment by bverkron** [comment]
> Although we are all referring to docker, it may be valuable to know which OS people are having issues with. I believe there are inherent performance issues with docker on Windows that this may involve. It could be useful to distinguish and/or isolate the issue with.

OS:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

Docker:
```
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.40
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:34 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
...
```

**Comment by alexdelprete** [comment]
> I did a fresh setup with the following but get `500 | SERVER ERROR` in the UI

There's already an issue open for that: #33

Since that blocking issue is only relevant to sqlite, if you want to test it, switch to mysql instead.

```yaml
    environment:
      TZ: Europe/Rome
      PHP_POOL_NAME: speedtest-tracker_php
      DB_CONNECTION: mysql
      DB_HOST: mariadb.axel.dom
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: *******
      DB_PASSWORD: *******
```

**Comment by alexdelprete** [comment]
> Old repo is having the same issue it looks like so I directed @bverkron here so they can follow along with the new stuffs.

I know, but I guess he wanted to test this new project. :)

**Comment by alexjustesen** [comment]
So I've spent on and off a couple weeks now trying to figure out why it seems like networking is slow. If anyone has any ideas that would be great, especially for a #hacktoberfest PR

**Comment by michealespinola** [comment]
@alexjustesen did you confirm you are having this issue with Windows and Ubuntu? Are we tracking any demographics about this?  Such as ISP, bandwidth limits, etc? 

I don't see any issues on my end (running on a Synology NAS) My bandwidth cap (w/Cox) is 500 Mbps, and speedtest-tracker measures it accurately.

Maybe this issue only affecting people test higher-end bandwidths? Certain ISPs? Por que no los dos, etc.

**Comment by alexdelprete** [comment]
> So I've spent on and off a couple weeks now trying to figure out why it seems like networking is slow

The only time I saw this with the old project, I upgraded speedtest-cli inside the container manually and since then I never experienced it anymore. Since your project already uses latest version, I don't know what else could cause it. Maybe something related to php performance in the container with highspeed connections?

**Comment by bverkron** [comment]
I started performing some tests to see if I could narrow down where the issue is coming from. So I built a container straight from the parent Ubuntu 20.04 that the ____ image that this project uses is based on

```Dockerfile
FROM ubuntu:20.04

3RUN apt-get update && apt-get install -y curl && \
    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash && \
    apt-get install speedtest
```

I was only getting around 500 Mbps average (I have gigabit internet and get close to that on my other devices) so I though it was the base Ubuntu container that had the speed issue. However, it turns out my host machine is now only getting about 500 Mbps for reasons I haven't figured out yet. It was previously getting close to 1000 Mbps when I was troubleshooting with the original speedtest-tracker project image.

Maybe others can play around with the Ubuntu base image and see if they get expected speeds there. If we can full speeds there then the issues is somewhere in between that image and this projects image, perhaps in some tools or config that's done along the way. One could even try the direct parent image of `serversideup/php:beta-8.1-fpm-nginx`

**Comment by bverkron** [comment]
Fixed my host speed issue by... rebooting my network equipment... which is weird considering all other devices on the network were pulling 1 Gbps consistently... hmmm

Interestingly I'm now getting close to 1Gbps on the host, in the base Ubuntu container, AND the latest image from this project.

```
ghcr.io/alexjustesen/speedtest-tracker   latest               dd41c92e9986   2 weeks ago     314MB
```

```
root@2206f928445f:/var/www/html# speedtest 
   Speedtest by Ookla
      Server: *********
         ISP: TELUS
Idle Latency:     2.32 ms   (jitter: 0.65ms, low: 1.68ms, high: 2.86ms)
    Download:   919.71 Mbps (data used: 1.4 GB)                                                   
                  4.04 ms   (jitter: 0.78ms, low: 1.59ms, high: 8.26ms)
      Upload:   628.51 Mbps (data used: 721.3 MB)                                                   
                  7.78 ms   (jitter: 2.92ms, low: 2.00ms, high: 18.69ms)
 Packet Loss:     0.0%
```

The upload is a little on the slow side but it varies on the host right now too so I don't think that's the fault of the container.

Colour me confused. Not sure if I can help anymore since I'm no longer getting the issue? Well, at least not when running the speedtest command on the command line. I have not tried the web interface (still blocked by https://github.com/alexjustesen/speedtest-tracker/issues/33) but I imagine it should be the same since it's just running the cli command in the background?

**Comment by michealespinola** [comment]
I previously incorrectly stated my bandwidth as ~~500 Mbps~~ on cable internet - It's actually 600 Mbps. My speedtest average is ~568 Mbps and is quite consistent.  My ping, not so much.

**Comment by michealespinola** [comment]
If I go back and forth between using a docker container version of Speedtest Tracker and the speedtest.net website, performing tests against the same local server, my speed test results are very consistent between the two.

My docker container is on the default system bridge network. Its the only one of my containers that are on it. All of my other containers are running on host.

**Comment by Kostecki** [comment]
Something i noticed when going through the database is that the speed reported by the dashboard and what's in the database is wildly different from what the speedtest.net image (that's also saved in the database) shows.

I setup a clean Ubuntu VM on my unRaid server, so the same hardware as my "main" speedtest-instance.

This is the database entries:
![Skærmbillede 2022-10-19 kl  13 36 46](https://user-images.githubusercontent.com/9408523/196680291-e6b6e8fb-8263-48c9-8a6f-f35a25006e89.png)

And these are the speedtest.net images:
https://www.speedtest.net/result/c/d792dc23-05e0-47f6-bfdd-39ab921b4658
https://www.speedtest.net/result/c/045a039e-ca4b-441e-aeaa-f19abdac3198

My connection is 1000/60 but I'm limited by my Unifi UDR to about 600 down, so the first image is spot on and the second is at least much better than what's reported in the dashboard.

Could it simply be a matter of erroneous being introduced at some point between test and the dashboard?

**Comment by alexdelprete** [comment]
@alexjustesen I can confirm the findings of @Kostecki (I didn't think of checking the speedtest url results, shame on me).

I picked some entries in the db, and the results never match the ones of speedtest.net url:

Entry in the db highlighted:

![image](https://user-images.githubusercontent.com/7027842/196711495-85cde1a4-9ee6-4065-97a7-b5de0c204225.png)

Relevant speedtest.net url result:
![image](https://user-images.githubusercontent.com/7027842/196711196-1d9969b5-5bc8-47d8-a53f-9dc041f856f6.png)

So there's some bug somewhere. :)

**Comment by alexjustesen** [comment]
Oooo I get the feeling this might be a bytes/bits issue...

**Comment by alexdelprete** [comment]
> Oooo I get the feeling this might be a bytes/bits issue...

But the strange thing is that someone above says it got it working by rebooting the switch or something like that...:)

**Comment by alexjustesen** [comment]
Because math is hard, I'm going to probably write it bits on create... 

https://github.com/alexjustesen/speedtest-tracker/blob/3a836a03f24299fb12d7afba8b71e06aa7278d2e/app/Jobs/ExecSpeedtest.php#L64

**Comment by alexjustesen** [comment]
> Are you using the -u flag when calling speedtest?

My understanding was this is only for `user output` and didn't effect what was returned as `json`

**Comment by alexdelprete** [comment]
You're right, machine-readable formats use bytes:

```
Machine readable formats (csv, tsv, json, jsonl, json-pretty) use bytes as the unit of measure with max precision
```

**Comment by alexdelprete** [comment]
> My connection is currently 600/30

Michael, are you sure you're using Alex's speedtest-tracker image? Because my UI is different vs the one of your screenshot:

![image](https://user-images.githubusercontent.com/7027842/196730573-e52abce0-61f1-4cb7-9c79-04df7c7c8837.png)

**Comment by alexjustesen** [comment]
> Question, how is it possible that @michealespinola reports correct values?

They're using the one that seems to be abandoned right now

**Comment by alexdelprete** [comment]
> They're using the one that seems to be abandoned right now

That's what I thought. You should've changed the project name...it will create confusion for a while. :)

**Comment by alexjustesen** [comment]
Issue resolved, just a note Docker on wsl run slow so make sure you're not evaluating tests from there.
