### ISSUE TITLE
Setting up InfluxDB via enviromentals

### ISSUE THREAD

**Issue by PovilasID** [alexjustesen/speedtest-tracker#352]
**Is your feature request related to a problem? Please describe.**
I have all my settings on server while setting up the instance  

**Describe the solution you'd like**
Env variables that could be passed to have them send data to influx

**Additional context**
Docker compose file

**Comment by alexjustesen** [comment]
You can setup Influxdb and other integrations though the admin panel. I'm going to keep settings there as they're easier to maintain
