### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by PovilasID** [alexjustesen/speedtest-tracker#353]
**Is your feature request related to a problem? Please describe.**
Then sharing details about network issues I have to copy each measurement's data individually.  

**Describe the solution you'd like**
In results panel an 'Export as CSV' option next to 'View' and 'Delete'. If any results are selected to export only selected.

**Additional context**
It may be a part of #294 

Bonus: It would be cool if a report or a PNG could be generated for a period. Something similar to what speedtest does. It would be something easily sharable to compare with other user's in neighbouring networks to figure out if it's a local problem only.

**Comment by alexjustesen** [comment]
I like the distinction for only exporting selected records. Export is what I'm currently working on so it'll be coming soon.
