### ISSUE TITLE
Docker image fails to start or produce logs.

### ISSUE THREAD

**Issue by MegaShinySnivy** [alexjustesen/speedtest-tracker#354]
**Describe the bug**
Container fails to start and outputs no logs via docker logs speedtest-tracker. 

**To Reproduce**
1. Pull the latest image using the SQLite example for docker-compose
2. Bring the project up

**Expected behavior**
The container starts normally and provides logs

**Environment (please complete the following information):**
 - OS: Ubuntu Server 20.04.5
-  Architecture: amd64
 - Browser: Firefox
 - Version: latest, digest: sha256:4529407f5b1c06ccba36761fc11208f4cbe13e4463d146cd953f6b1676ae20fc 

**Logs**
No logs are outputted, which is the main issue. It also is impossible to connect to the speed test server over 80 or 443

**Additional context**
The only possible thing to mention is that this is on a bare-metal node running docker. All else should be normal.

**Comment by alexjustesen** [comment]
@MegaShinySnivy can you look at the Docker logs as well? You should see a bunch of tasks happening during startup.

**Comment by MegaShinySnivy** [comment]
To be clear, you mean the logs from the docker engine itself?

**Comment by MegaShinySnivy** [comment]
I'm gonna go ahead and close this, as it seems to just be an issue on my machine.
