### ISSUE TITLE
Configuration - Could not retrieve or read configuration Synology NAS

### ISSUE THREAD

**Issue by mark-763** [alexjustesen/speedtest-tracker#355]
I've installed speedtest-tracker in docker on my Synology 918+. (I've used this tutorial: https://mariushosting.com/how-to-install-speedtest-tracker-on-your-synology-nas/)

Installation went well and looked good.

Unfortunately the speedtest is not working, If I view the results I get the following message:

{"type":"log","timestamp":"2023-01-25T09:00:36Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}

I tried also to use a specific server id near me, but it does not work at the moment. The webinterface is running fine.

Any ideas?

**Comment by Amraki** [comment]
I had the same problem and eventually resolved it by starting over with these steps: https://docs.speedtest-tracker.dev/getting-started/installation#install-on-synology

The only difference I noticed is it's using the 'bridge' network in the last screenshot.

And if you haven't already, be sure to configure the bridge firewall settings. The lower half of this should help: https://drfrankenstein.co.uk/step-3-setting-up-a-docker-bridge-network/

**Comment by Amraki** [comment]
Please also follow #343 for other possible solutions.

**Comment by mark-763** [comment]
I tried now everything. I dont get it to work. I dont know what to do else. I still get this error:

{"type":"log","timestamp":"2023-02-01T11:24:31Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}

But if I look at the docker container log, this error isn't there. I've installed it many times new, but nothing worked so far.
