### ISSUE TITLE
Speed Test is showing incorrect speeds

### ISSUE THREAD

**Issue by thechesu** [alexjustesen/speedtest-tracker#359]
I'm using the same server id as the one on speedtest.net

![Screenshot 2023-01-25 at 20-50-14 Dashboard - Speedtest Tracker](https://user-images.githubusercontent.com/123273000/214688470-e37d714f-0714-4418-ad5c-50f0d107d808.png)
![Screenshot 2023-01-25 at 20-58-50 Speedtest by Ookla - The Global Broadband Speed Test](https://user-images.githubusercontent.com/123273000/214689327-e5cae281-fbf7-4d10-8d7b-7767ca4d8e1c.png)

Mariadb/MSQL Docker-Compose was used  with default configuration.

**Comment by alexdelprete** [comment]
test with speedtest-cli not with the web app.

where is the server_id on that results page? maybe hovering the mouse on the name of the server gives you the URL with the server_id, just to make sure it's the same. anyway, to compare accurately, you need to use speedtest-cli from shell.

**Comment by alexjustesen** [comment]
What speeds do you expect to see?

**Comment by thechesu** [comment]
> What speeds do you expect to see?

Around 300mb download.  

Does the app test my internet speed or is it the speed of the host of my VPS?   The latter makes sense for the higher speeds the the app is giving me.

**Comment by alexjustesen** [comment]
It's going to test from where you're hosting it ---> Ookla service.

So if you're hosting it externally to your house and on a VPS service like Digital Ocean or Linode it's going to test that connection.

**Comment by thechesu** [comment]
> It's going to test from where you're hosting it ---> Ookla service.
> 
> So if you're hosting it externally to your house and on a VPS service like Digital Ocean or Linode it's going to test that connection.

I'm hosting with IONOS.   Thanks for your quick response, the different speeds make sense now.
