### ISSUE TITLE
SSO / OpenID

### ISSUE THREAD

**Issue by superfunk2000** [alexjustesen/speedtest-tracker#361]
**Is your feature request related to an issue? Please describe.**
It's difficult to log in.

**Describe the solution you want**
I would like authentication via OpenID

**Additional context**
If the above solution is too complex, would it be possible to switch off the internal authentication?

**Comment by alexjustesen** [comment]
Thanks for the suggestion, at this time I don't plan on adding SSO options but will keep this in mind for post `v1`

**Comment by phyzical** [comment]
@alexjustesen just a friendly nudge now that v1 is oh so very close 👍

**Comment by tomerh2001** [comment]
Any update?
