### ISSUE TITLE
Docs - Install with Docker Compose (PostgreSQL)

### ISSUE THREAD

**Issue by zvarg** [alexjustesen/speedtest-tracker#362]
**Describe the bug**
There is an invalid environment variable you used - probably - at [Install with Docker Compose (MariaDB/MySQL)](https://docs.speedtest-tracker.dev/getting-started/installation#install-with-docker-compose)
```
environment:
  - MARIADB_RANDOM_ROOT_PASSWORD
```

**To Reproduce**
1. Go to [Install with Docker Compose (MariaDB/MySQL)](https://docs.speedtest-tracker.dev/getting-started/installation#install-with-docker-compose)
2. Click on Docker (PostgreSQL)
3. See environment variable on `DB` service

**Expected behavior**
Invalid environment variable should be removed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18576529/215171564-015c64b6-3b54-4527-b537-c33d5a48315c.png)

**Comment by alexjustesen** [comment]
Thanks, fixed in docs.
