### ISSUE TITLE
multi-wan gateway

### ISSUE THREAD

**Issue by somedevreally** [alexjustesen/speedtest-tracker#365]
Hello,

great app, i have a feature request.
i have multi WAN gateway in loadbalance group. so when the speedtest runs it goes through one of the gateway.

can there be a feature to print WAN IP in the result? so its easy to know which gateway was used for speedtest.
it can also be good option if there is dynamic IP too.

thanks

**Comment by alexdelprete** [comment]
If you click on the 3 dots to the right of a record of the results table, you can click view and it will show you raw data of the test result. There's the `externalip` field.

![image](https://user-images.githubusercontent.com/7027842/215282089-7714cedd-2722-45ea-8c9a-f2632520a1ce.png)

**Comment by somedevreally** [comment]
oh i totally missed that, too much info tucked away. maybe toggle columns can have show external IP. but i can live with this.
