### ISSUE TITLE
Lazy load widgets to improve Dashboard performance

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#368]
**Is your feature request related to a problem? Please describe.**
More faster, more better(er)

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.
](https://rias.be/blog/keep-your-filament-admin-dashboard-fast-by-lazy-loading-widgets)

**Comment by AleksCee** [comment]
Is the issue perhaps the same I observe: the dashboard trigger 4 requests every second from every browser which has a active view on the page. Is there a way to inform the browser if a reload should start via event or stream from steh server to minimize the requests?
