### ISSUE TITLE
dashboard showing wrong result (by factor 1000) if speed is near 1000MBit

### ISSUE THREAD

**Issue by unnameduser2** [alexjustesen/speedtest-tracker#372]
It seems that the dashboard view shows results near 1000 Mbps with Kbps instead.
The results-page still shows correct value in Mbps.

![speedtest](https://user-images.githubusercontent.com/55552173/215344819-1c5ede9a-b63c-4ce3-91cc-76f2c096ff43.PNG)

current version: v0.11.1

**Comment by unnameduser2** [comment]
I just noticed that the speedtest.net resultpage really shows only 0.93Mbps as result for this run, so it seems that the results-page shows wrong value...
![speedtest1](https://user-images.githubusercontent.com/55552173/215345461-92889790-60f3-43ad-b5a0-12da5fdc30eb.PNG)

**Comment by alexdelprete** [comment]
> It seems that the dashboard view shows results near 1000 Mbps with Kbps instead.

Works fine.

![image](https://user-images.githubusercontent.com/7027842/215345919-7bd95726-2e8e-4071-aa6d-0cd3497bb50f.png)
![image](https://user-images.githubusercontent.com/7027842/215345928-bb2c74cf-0856-4294-a30d-cda817022ade.png)

**Comment by unnameduser2** [comment]
> > It seems that the dashboard view shows results near 1000 Mbps with Kbps instead.
> 
> Works fine.
> 
Thanks for reply,
See my own reply, dashboard view is correct but not the results-page.
It seems that the server which was used for my last test had high load and so the results were really bad...

**Comment by alexdelprete** [comment]
> See my own reply, dashboard view is correct but not the results-page.

I see now. The result is not converted to Mbps in the results table.

cc @alexjustesen

**Comment by alexjustesen** [comment]
> > See my own reply, dashboard view is correct but not the results-page.
> 
> I see now. The result is not converted to Mbps in the results table.
> 
> cc @alexjustesen

Yeah it's the right numbers but the label is wrong. I'll have that fixed in the next release already got it on my whiteboard. Going to close this issue out.
