### ISSUE TITLE
Location data in Influxdb

### ISSUE THREAD

**Issue by PovilasID** [alexjustesen/speedtest-tracker#374]
**Is your feature request related to a problem? Please describe.**
I can not group servers by location in dashboards. It looks like InfluxDB does not get the location parameter passed to it.

**Describe the solution you'd like**
A location pram passed to InfluxDB, so I could group performance per location not just per server.

**Additional context**
I manually listed a bunch of server in Geneal Settings. They are in different geographical locations. It is normal that Speeds from EU to US will be slower than to my neighbor but does it drop over time compared to that location.
Bonus: It would be nice to manually launch tests or launch one test from each location/group.

**Comment by alexjustesen** [comment]
So influx should be getting the server ID, what about grouping off of that? 

https://github.com/alexjustesen/speedtest-tracker/blob/main/app/Models/Result.php#L74-L94

**Comment by PovilasID** [comment]
I am getting the ID that is fine. What I am looking for is `location`:
```json
"server":{"id":31120,"host":"speedtest-fkt-eqx.retn.net","port":8080,"name":"RETN","location":"Frankfurt","country":"Germany","ip":"94.158.241.17"}
```
See next to server it says: `"location":"Frankfurt"` and `"country":"Germany"` I have tagged 3 servers in Germany to be tested against and 2 in Netherlands. What I am looking to compare is averages between those two countries. 
Here is what code might look like:

```php
....
            'server_id' => (int) $this->server_id,
            'server_host' => $this->server_host,
            'server_name' => $this->server_name,
            'server_location' => $this->server_location,
            'server_country' => $this->server_country,
            'scheduled' => $this->scheduled,
            'packet_loss' => (float) $data['packetLoss'] ?? null, // optional, because apparently the cli doesn't always have this metric
        ];
    }

```
Have not tested it but if `$this` context is just decoded result JSON should just work.

**Comment by alexjustesen** [comment]
I opened up #375, no eta yet but once this is built you'll be able to customize the fields InfluxDB receives.
