### ISSUE TITLE
Missing File in Image?

### ISSUE THREAD

**Issue by jonjmills** [alexjustesen/speedtest-tracker#376]
Fresh install of Unbuntu 22.4.1 and of Debian 11.5. Container starts, then terminates

Error:
/run/s6/basedir/scripts/rc.init: 67: restart:: not found

Run Command:
docker run -d --name Speedtest-Tracker \
    -p 8090:80 \
    -p 10443:443 \
    -e PUID=1000 \
    -e PGID=1000 \
    -v /var/lib/docker/volumes/speedtest_tracker:/config \
    ghcr.io/alexjustesen/speedtest-tracker:latest \
    restart: unless-stopped

**Comment by alexdelprete** [comment]
1. Logs of the container to check startup phase.
2. Check permissions of PUID 1000 PGID 1000 for folder /var/lib/docker/volumes/speedtest_tracker

**Comment by jonjmills** [comment]
id me
uid=1000(me) gid=1000(me) groups=1000(me)

ls -l
drwxr-xr-x 2 me me   4096 Jan 30 16:33 speedtest_tracker

🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
   ERROR  The [public/storage] link already exists.  
🐇  Configuring Speedtest Tracker...
✅  Database exists
🔗  Creating database symlink
✅  Environment file exists
🔗  Creating symlinks to config and log files
✅  App key exists
🔒  Fixing app path file permissions
💰  Building the cache...
[30-Jan-2023 22:35:08] NOTICE: fpm is running, pid 96
[30-Jan-2023 22:35:08] NOTICE: ready to handle connections
[30-Jan-2023 22:35:08] NOTICE: systemd monitor interval set to 10000ms
🚛  Migrating the database...
✅  All set, starting Speedtest Tracker container...
⏰  Starting the cron service...
💪  Starting the queue worker...
/run/s6/basedir/scripts/rc.init: 67: restart:: not found
[30-Jan-2023 22:35:09] NOTICE: Terminating ...
[30-Jan-2023 22:35:09] NOTICE: exiting, bye-bye!

**Comment by alexdelprete** [comment]
Some users with similar issues simply deleted and reinstalled from scratch, something wrong with the image maybe? https://github.com/alexjustesen/speedtest-tracker/discussions/364

**Comment by jonjmills** [comment]
VM on Proxmox. Hardware is a bit older (Intel Pentium G3220), but not enough that it should be an issue I would think.

**Comment by alexdelprete** [comment]
I don't think so, but you never know with these old cpus on these new sw stacks. :)

Did you try recreating everything from scratch? Also: can you try it on another system?

**Comment by neongrau81** [comment]
Same issue here. I am as well running a Docker VM on Proxmox on some older Hardware (Fujitsu Futro S740)

**Comment by jonjmills** [comment]
Installed xcp-ng on same hardware but changed to another SSD drive as xcp-ng didnt recognize the drivers for the original m.2 ssd. Fresh install of Debian and still same issue.

Friday I will be reinstalling Proxmox on my main VM host and will test again with much more up to date hardware and report back, but this is starting to point to the old hardware CPU being the issue some how.

**Comment by alexdelprete** [comment]
Try using docker user group as PGID. An RPi user solved a similar issue with that.

**Comment by jwaugh** [comment]
Having same exact issue. Both on M1 MacBook Pro and on ProxMox Debian VM like other users here.

**Comment by feferd** [comment]
i changed PGID=999 (docker group) -> result is the same

**Comment by feferd** [comment]
runnig in docker-compose works

  speed:
    hostname: speed
    container_name: speed
    image: ajustesen/speedtest-tracker
    restart: unless-stopped
    ports:
      - 9080:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1003
    volumes:
      - ${DATA_DIRECTORY}/speedtest/config:/config
    networks:
      my-net:
        ipv4_address: 172.20.10.18
    dns:
      - 192.168.1.9

**Comment by alexdelprete** [comment]
can you try with docker-compose and PGID=999 (docker group id).

**Comment by jonjmills** [comment]
All new hardware today and still same issue. I will test with docker compose tomorrow.

**Comment by jonjmills** [comment]
Docker compose does indeed work correctly.

version: '3.3'
services:
    speedtest-tracker:
        container_name: Speedtest-Tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - '/var/lib/docker/volumes/speedtest_tracker:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped

**Comment by alexdelprete** [comment]
> Docker compose does indeed work correctly.

thanks for the feedback. what PUID/PGID values did you use? can you close the issue if it's ok? Thanks.

@alexjustesen I would suggest to change the installation instructions to use docker compose. It would avoid a lot of users opening issues.
