### ISSUE TITLE
Ability to run a Script on an event.

### ISSUE THREAD

**Issue by Bag72** [alexjustesen/speedtest-tracker#378]
I'd like the addition a script for some events. Every now and again my link goes down and I get 0 for the data items.   I'd like to have a script executed under those events so I can restart the link.

**Comment by MartynKeigher** [comment]
It's not elegant but... Setup a notification into Telegram (when a threshold has not been met) and then... 

Have something that monitors Telegram for that message (you could use something like Zapier, [n8n](https://n8n.io/), or [make](https://www.make.com/en) for this), which would then trigger your custom script.

**Comment by alexjustesen** [comment]
I've got webhooks on the roadmap would this get you there?

**Comment by Bag72** [comment]
@MartynKeigher Thanks for that.   I don't use Telegram and I don't really want to set something up just for this.    Although, I'll have a look at Telegram as that may be useful for something else.  So many tools.  I suspect would be more likely to use email for this as I already have that in place.

@alexjustesen Not sure what webhooks are as I've never used them but the look like they will execute a HTTP page,   Would that allow the execution of a script?   Would I also need to put a browser in place or could it tap into yours?

**Comment by MartynKeigher** [comment]
> I've got webhooks on the roadmap would this get you there?

Yes. That works. Also... Another thing you could do is (when its available) is send a notification to slack.. WITH BUTTONS!! Then, you can take an action based on the event that is messaged into Slack! ;p 

_(From my perspective!)_ ...Once this app gets Slack & webhooks... possibilities are endless! :)

**Comment by Bag72** [comment]
Had a look at the Telegram App.   Solves a different problem I have and I'll be looking at installing it soon.   Not sure it will solve this problem though as it looks like I need to send it through Telegrams website and when the link is down that is a no go.   I'll add it to my ever growing list now and do a bit more digging when I get round to installing it on my NAS.
Thanks for the pointers guys.

**Comment by alexjustesen** [comment]
Going to close this as I don't want to introduce a level of complexity at the moment in-app to handle custom scripts. At this time I suggest @MartynKeigher suggestion to use Telegram and extending that through Zapier, n8n or make.
