### ISSUE TITLE
I'd like the addition a comment field for the entries.

### ISSUE THREAD

**Issue by Bag72** [alexjustesen/speedtest-tracker#379]
I'd like the addition a comment field for the entries. Every now and again my link goes down and I get 0 for the stats. I'd like to be able to add in a comment for those entries and possibly have that comment, or a link, displayed on the chart so you can hover over it and see the comment.

**Comment by alexjustesen** [comment]
Just a heads up this does not include comments in charts, overhauling chats at a later date.
