### ISSUE TITLE
Possibility of "Pause" queue worker

### ISSUE THREAD

**Issue by garanda21** [alexjustesen/speedtest-tracker#381]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would be nice a button for pause or snooze the queue (Pi-hole or AdGuard style)

**Additional context**
For example, I'm on a meeting and I wanna to stop/pause the worker for 2 hours so my connection is not affected for the test.

**Comment by alexjustesen** [comment]
Linking this to #341 as this will be a part of a larger overhaul of how "scheduled" tests are handled.
