### ISSUE TITLE
Running a test on specific server

### ISSUE THREAD

**Issue by PovilasID** [alexjustesen/speedtest-tracker#382]
**Is your feature request related to a problem? Please describe.**
I have a number of servers listed in settings but I can not control on which one a test is run so if I want to compare changes on specific server I can not do that.  

**Describe the solution you'd like**
Turning a manual test button into a split button with a list of servers to trigger a test on that specific server:
![image](https://user-images.githubusercontent.com/396243/215996830-3c068e9b-dae4-4858-92b7-f9605d7d1f4a.png)

**Additional context**
It also could be triggered from the settings page next to the list of servers.

**Comment by PovilasID** [comment]
I looked into UI elements available for that stack you are using, maybe instead of a split button there could be a multi select drop down with default being "Any" and the rest of options manually listed servers.

**Comment by alexjustesen** [comment]
Linking this to #341 as these will both be a part of a larger change to how "scheduled" tests are handled.
