### ISSUE TITLE
Restart missing in rc.init script

### ISSUE THREAD

**Issue by feferd** [alexjustesen/speedtest-tracker#386]
### Error
/run/s6/basedir/scripts/rc.init: 67: restart:: not found

### i run this command
docker run -d --name speedtest-tracker \
  -p 9080:80 \
  -p 8443:443 \
  -e PUID=1000 \
  -e PGID=1003 \
  -v /xxx/config:/config \
  ghcr.io/alexjustesen/speedtest-tracker \
  restart: unless-stopped

### Expected behavior
Container started

- OS: Ubuntu Arm server on rpi4 , 4GB
-  Architecture: arm64

**Logs**
[_speedtest-tracker_logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/10570107/_speedtest-tracker_logs.txt)

**Comment by feferd** [comment]
it is duplicate of "Missing File in Image? #376"

**Comment by feferd** [comment]
running in docker-compose works

  speed:
    hostname: speed
    container_name: speed
    image: ajustesen/speedtest-tracker
    restart: unless-stopped
    ports:
      - 9080:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1003
    volumes:
      - ${DATA_DIRECTORY}/speedtest/config:/config
    networks:
      my-net:
        ipv4_address: 172.20.10.18
    dns:
      - 192.168.1.1

**Comment by zyystudio** [comment]
same issue here with proxmox7.3 native docker


root@pve:/home# id admin
uid=1000(admin) gid=997(docker) groups=997(docker)

docker run -d --name speedtest-tracker -p 9080:80 -e PUID=1000 -e PGID=997 -e TZ="Asia/Shanghai" -v /var/run/docker.sock:/var/run/docker.sock -v /pvedata/docker/speedtest-tracker/config:/config ajustesen/speedtest-tracker:latest restart: unless-stopped

the log is 
GID/UID
-------------------------------------
User uid:    1000
User gid:    997
-------------------------------------
🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
🏃‍♂️ An SSL key was not detected, so I'll generate a self-signed SSL certificate pair for you...
..+...+..+.+...........+...+......+.+.....+.........+......+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.........+........+.......+.....+.............+...+...+..+.......+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+......+.....+....+..+.+............+........+.......+...+...+..+.......+..+...............+.+............+...+............+...+...+..+...+......+.+............+.....+.+......+........+............+...............+.+.....+...+.+........+......+....+..+....+..+.......+..+....+...........+....+..+.............+..........................+...+.+......+...+...........+......+....+..+..........+...+..+..................+.+...........+...+......+..........+.....+....+......+.....+.+.....+...+.......+...+.....+....+...+..+............+...+.+......+...+...+.....+.......+..+..........+...........+.........+.+..+......+.+......+.....+.........+.+..+.+........................+......+..+.........+...+......+.+......+...+...........+.+..+..........+...+.....+...+....+......+...........+......+.......+...+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   INFO  The [public/storage] link has been connected to [storage/app/public].  
🐇  Configuring Speedtest Tracker...
✅  Database exists
🔗  Creating database symlink
✅  Environment file exists
🔗  Creating symlinks to config and log files
✅  App key exists
🔒  Fixing app path file permissions
💰  Building the cache...
.+..+...+.+......+......+..+.............+..+......+......+...+.+..+....+......+.........+.....+.+...+...........+.+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+....+..+..........+......+...............+..+..........+..+..........+...+.....+......+...............+.+........+......+.+...........+....+.....+.+...............+..+...+............+.+.....+.+...........+...+.+........................+......+...+..+.........+..........+..+.......+..+......+.............+.....+.+...+.....+......+.+.....+.+...+............+..+++++++++++++++++++++++++++++++++++++++++++++++++++[06-Mar-2023 22:05:21] NOTICE: fpm is running, pid 101
[06-Mar-2023 22:05:21] NOTICE: ready to handle connections
[06-Mar-2023 22:05:21] NOTICE: systemd monitor interval set to 10000ms
++++++++++++++
-----
🚛  Migrating the database...
✅  All set, starting Speedtest Tracker container...
⏰  Starting the cron service...
💪  Starting the queue worker...
/run/s6/basedir/scripts/rc.init: 67: restart:: not found
[06-Mar-2023 22:05:22] NOTICE: Terminating ...
[06-Mar-2023 22:05:22] NOTICE: exiting, bye-bye!



any hint?
Thanks
