### ISSUE TITLE
Thresholds trigger bug

### ISSUE THREAD

**Issue by JFPCreations** [alexjustesen/speedtest-tracker#388]
Thresholds triggered and notification mail send when speedtest is over it. 

![Screenshot_20230203-204717](https://user-images.githubusercontent.com/10256543/216767326-42534074-61f4-468e-abef-8b41a5230757.png)
![croppedImage](https://user-images.githubusercontent.com/10256543/216767328-a98ec69c-e96b-44d6-aab8-82562ee863d2.png)
![Screenshot_20230204-045916](https://user-images.githubusercontent.com/10256543/216767330-5b705a07-2d06-4271-aa8e-e850da1986dd.png)

**Comment by foux** [comment]
Globally I think there's an issue with Gbps on other parts of the app. For example in this screenshot : 
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/246550/218677617-d78c70e3-a148-4aa0-af18-8ebab5ea7be1.png">

The result is marked as 2.547 mbps when it is in fact 2.547 gbps.

@alexjustesen do you want me to create a seperate issue for this, or are they linked?

Thanks!

**Comment by JFPCreations** [comment]
It's ok if I put my thresholds in Gbps like this: 

![image](https://user-images.githubusercontent.com/10256543/219516522-724aac1d-0b88-4abb-8664-ee09e5d86ff4.png)

So you can only change the Mbps to Gbps in the thresholds part.

Thank you.

**Comment by alexjustesen** [comment]
Rolling this into a parent issue.
