### ISSUE TITLE
Configuration - Could not retrieve or read configuration (ConfigurationError) - Back again.

### ISSUE THREAD

**Issue by Bag72** [alexjustesen/speedtest-tracker#389]
Alex,

I'm back with my problem from a few days ago.   Container has been running OK.  I had problems before, Issue 355, but fixed by wiping and reinstalling if you remember.

At 0130GMT today the system stopped working again with the same error.
{"type":"log","timestamp":"2023-02-04T01:30:15Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}

Now nothing changed on the container and it has been using the same one for 4 days.   Interestingly 4 days ago I had several hours of the same message at around 0700GMT which fixed itself and until I looked through the logs today I hadn't noticed.

At 0130GMT I was fast asleep and have not made any changes to the system.  Last time I put it down to something I had done and there was a bit of a mix up with updates.   I hadn't been doing them and I thought I was.

So I have a few questions and hopefully it can lead to a fix for me.

What error generates the above message?  Unable to read, file doesn't exist, certain parameters not there?
Where is the configuration file stored?   I have config/.env and that is w:rwe and still accessible.
When does it read the file?  It looks like during every time speedtest is queued.
In the code after reading the config file does the error handling move on?   If the next command errors will it use this error instead of one of its own?
Grasping at straws here and as it isn't just me it seems a particularly strange error.

What can I do to help diagnose this?

**Comment by alexjustesen** [comment]
You're getting this error in your results right?

**Comment by Bag72** [comment]
When the test is ran, either through the timer or by clicking the run now button it fails and the following is down as the error when you click on the red icon in the GUI.

{"type":"log","timestamp":"2023-02-04T01:30:15Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}

This is the same error I got last time and then I fixed it by deleting everything and reloading.   This time that isn't working.  I'm now convinced it is something on my system triggering an obscure bug, not something unique to me because others are getting it but definitely present on my system. 

I've reloaded the brand new .env from Github, Loaded the new DC and started it up as new.  Still no joy.  See attachments.

It can clearly see and read the .env file as it filled in the App Key environment variable.  So it is clearly in the right place and RW.   It is clearly something simple but finding it will be an issue.   How can I set it up to step through the code to find exactly where it goes wrong?

  
![Screenshot from 2023-02-05 21-06-30](https://user-images.githubusercontent.com/114260783/216846137-87d2c2a8-123c-4b85-aae7-0b4b672003fa.png)
[docker-compose.txt](https://github.com/alexjustesen/speedtest-tracker/files/10613807/docker-compose.txt)
[env.txt](https://github.com/alexjustesen/speedtest-tracker/files/10613808/env.txt)

**Comment by cinderblockgames** [comment]
Having the same issue.  Just started up the container for the first time.

**Comment by alexjustesen** [comment]
So this error occurs when the `speedtest-cli` can't reach the server it's trying to test against. Try setting another server under General settings (if you have one set) and if you don't have one set try specifying one.

**Comment by cinderblockgames** [comment]
I don't have any options in the General list at all.

**Comment by alexjustesen** [comment]
Thanks I'll look into this, might be a bug on the initial installs.

**Comment by Bag72** [comment]
I don't have any items in my drop down list to choose as a target.  However it was getting some to target originally so they must have come from somewhere.   Is there an environment setting you can use if there is none on the list and you can't type one in or alternatively a db setting?  Where does it get these from?

**Comment by Bag72** [comment]
Perhaps a more relevant error would be better as well.  I spent hours playing with the configuration files.

**Comment by MarcusSi2023** [comment]
Just wanted to confirm that I have this exact same issue. [
<img width="1512" alt="Screenshot 2023-02-09 at 2 55 18 PM" src="https://user-images.githubusercontent.com/84341023/217923219-c50d3268-f3c5-4bb3-a62e-072c4887f681.png">

**Comment by kode54** [comment]
Same error here too. And the previous deprecated speed test tracker I was using, stopped passing any tests around 4am today.

**Comment by cinderblockgames** [comment]
@kode54 Thank you - you made me realize that, while I made a network for speedtest to hit the internet, I forgot to add it to the container.  This is working for me now.

**Comment by Bag72** [comment]
@kode54.    I tried editing the file /etc/resolv.conf but it wouldn't let me as it was in use.  I stopped the container and again no joy.  How did you replace yours?   It was pointing to 127.0.0.11 for some reason and that isn't anything like my DNS servers so have no idea where that came from so I tried to edit by copying out and got this;.
So in container resolv.conf
nameserver 127.0.0.11
options ndots:0

docker cp speedtest:/etc/resolv.conf .
edited resolv.conf to point to my DNS server

docker cp resolv.conf speedtest:/etc/resolv.conf
Error response from daemon: Error processing tar file(exit status 1): unlinkat /etc/resolv.conf: device or resource busy

Any ideas?

**Comment by kode54** [comment]
I didn't replace the resolv.conf inside the container. I had originally changed the one on the host machine. Apparently my actual problem was with DNS services on my router.

**Comment by Bag72** [comment]
Mmmmmmm.  That can't be my problem or it would be intermittent as my DNS server is fine.  I may get occasional drop outs when it is heavily used but certainly not continuously for weeks.

Alex,
Still not working.  Even after rebuilds.  Is there anything I can do to help diagnose this?

**Comment by Bag72** [comment]
LOL.  You aren't going to believe this.   I installed a new LXD container and I needed to reboot the system.  It started working and has been doing so for a couple of hours now.  I'll keep my eye on it but it is clearly going to be frustrating to debug.

**Comment by Bag72** [comment]
and stopped again 0800 this morning.   Something very strange here.  Checked logs on host.  Nothing strange happened at that time.  Why just this app as well?

**Comment by kode54** [comment]
Happened with the unmaintained app this one replaced, too. I swapped it for this one because I thought it was the app, not Docker or the Speedtest-CLI app.

**Comment by cinderblockgames** [comment]
Same - 0700 and 0800 (EST) have failed with the configuration error.

**Comment by alexjustesen** [comment]
Sorry for the delay, had to catch up on client work.

Going to look into this later this morning after I get some ☕ in the system and a feature branch merged I'm currently working on.

**Comment by alexjustesen** [comment]
Btw... this error message is from the Speedtest CLI failing.

**Comment by Bag72** [comment]
Alex,

Any progress here.  It's still not pulling any data down.  Is there anything that I can help you with for testing?

**Comment by schech1** [comment]
I have the same issue.
Raspberry Pi on docker.

**Comment by alexjustesen** [comment]
`v0.11.3` has been released with dependency updates which will also rebuild the Ookla CLI, can someone let me know if they're still getting this error?

**Comment by cinderblockgames** [comment]
So far so good, though the last error I had was 27 hours ago.

**Comment by alexjustesen** [comment]
@Bag72 still having problems? If not can you close the issue once you've verified it?

**Comment by MarcusSi2023** [comment]
I continue to have issues, using latest version in UnRaid. Maybe it is a settings thing for me though, should I have the network to bridge or host?

**Comment by alexjustesen** [comment]
I'll spin it up on my unraid machine later this week, rebuilding some disks atm

**Comment by Bag72** [comment]
@alexjustesen Just noticed your email.    Thanks for looking at this.    I've just spun up Docker and ran the application.   It worked OK.   I'll run it for a few days and see if there are any further issues.   It frequently runs and is OK before it fails again.  First run 1800GMT 8-Mar.   It runs every 30 mins.

**Comment by Bag72** [comment]
@alexjustesen   Well that didn't last long.   It performed OK till 2100GMT where it failed again with exactly the same error as before.   It has failed since then.  I took down the docker and reset it but still no joy.  It is now as before.

**Comment by alexjustesen** [comment]
Are you specifying a server?

**Comment by Bag72** [comment]
No.  It has never allowed me to.
I go to General.....Speedtest Settings and then when I select the drop down option in Speedtest server ID  it is blank.  It always has been as well.   Therefore I have always allowed it to select it's own.  How can I force a server?

At 1000GMT it restarted working.  At this point it has had 2 successful tests.

**Comment by alexjustesen** [comment]
@Bag72 #458 incoming which will show a list of local servers (to you) by default in the search box. The error your getting is the Speedtest CLI not being able to run a test against the server it's try to so it's failing.

Think you found some janky server in the wild.

**Comment by MarcusSi2023** [comment]
Still not working. My server is running behind CGNAT, could that present any issues?

**Comment by alexjustesen** [comment]
> Still not working. My server is running behind CGNAT, could that present any issues?

Maybe? I don't have any experience with carrier grade NAT (never been an issue for me). You can always verify the container can reach Ookla's speedtest service by using `curl` to get a list of servers.

```
curl https://www.speedtest.net/api/js/servers?limit=1
```

This should return a json object with one record if it works correctly.

**Comment by MarcusSi2023** [comment]
Just tested, able to reach Ookla's service. Plus I can use the Unraid CLI tool for Ookla speedtest.

**Comment by alexjustesen** [comment]
@Bag72 and @MarcusSi2023 are you both running this on Unraid?

**Comment by Bag72** [comment]
I have a QNAP NAS.   The container is set up in bridge mode which means the NAS IP is the container IP and I use the port to get in to the container.

I've just gone through the data from all the previous tests and it appears that there is about 4 or 5 servers that show when it is working, and they are working now.  Perhaps I have an issue with my location that causes timeouts?

However, as you know I can't set preferred servers via the GUI.  Is there environment settings I can set instead?  Having some servers that are an issue would fit the inconsistency of the errors especially as I don't define any.

Perhaps if the speedcheck failed then if it tried a different server straight away and logged the failures we could keep track of the good servers and remove the bad ones.   I'm UK based perhaps that makes a difference.

@MarcusSi2023 CGNAT does cause issues for some We don't have it here in the UK but there is a good YT article on it under ScottiByte.  He does some obscure articles and CGNAT is one where he explains issues and workarounds.  It may help it may not.  No harm in looking.

**Comment by Bag72** [comment]
OK. Had some time to play yesterdayday so found out how to input the servers.  Not quite as I expected but I managed to get in the few regular successful ones.

Interestingly it has worked since then, 9-Mar-0130GMT, but today it uses servers I've not seen before so it doesn't stick to the ones I listed.   Maybe something was corrupt and entering some servers reset it.  Fingers crossed.

**Comment by MarvvanPal** [comment]
After some successful speedtests, the error is now also displayed...

Basis: Raspian OS @Pi4 and Docker (rootless) managed via Portainer.

`curl https://www.speedtest.net/api/js/servers?limit=1` is successful from container:

> [{"url":"http:\/\/speedtest01.dns-net.de:8080\/speedtest\/upload.php","lat":"52.5167","lon":"13. 3833", "distance":0, "name": "Berlin", "country": "Germany", "cc": "DE", "sponsor": "DNS:NET Internet Service GmbH", "id": "20507", "preferred":0, "https_functional":1, "host": "speedtest01.dns-net.de.prod.hosts.ooklaserver.net:8080"}]

How can I start the speedtest-cli manually from the container? Command is not found...

**Comment by alexjustesen** [comment]
> How can I start the speedtest-cli manually from the container? Command is not found...

If you wanted to run a speedtest manually from the terminal you can run `speedtest`, additional basic flags are `--server-id=12345` to specify a server and `--output=json` if you don't want the default human-readable format.

For a list of all commands and flags run `speedtest --help`.

**Comment by MarvvanPal** [comment]
Alright, I was able to do a manual test:

> root@71d1c8162c09:/var/www/html# speedtest
> Retrieving speedtest.net configuration...
> Testing from Vodafone Germany Cable (xx.xx.xxx.xx)...
> Retrieving speedtest.net server list...
> Selecting best server based on ping...
> Hosted by IWB Telekom (Basel) [215.13 km]: 155.119 ms
> Testing download speed................................................................................
> Download: 82.17 Mbit/s
> Testing upload speed......................................................................................................
> Upload: 3.27 Mbit/s

After recreating the container (with keeping the /config volume) I'm still not able to do any (also not manually) test. I also get no "failed result" in the overview. The only response is the popup that the test is queued. 

Btw... these terrible bandwidth values are the reason that I like to see this project.

**Comment by Bag72** [comment]
I found out how to input the servers, I think.  Not quite as I expected but I managed to get in the few regular successful ones.

It has now been running since 9-Mar-0130GMT successfully.

Interestingly although it has worked since then it uses servers I've not seen before so it doesn't stick to the ones I input.   Maybe something was corrupt and entering some servers reset it.  Fingers crossed.   I have deleted the container and recreated it at 1345GMT today.   I connected up OK at the last test.

I'll leave it running now and let you know how it goes.

**Comment by Bag72** [comment]
Well, that didn't work well.   Rebuilt and restart worked the once while I was watching.  Failed every time after that and what was worse is that I could get into the config section, server error 500, to enter a server id.   I remember the server 500 error.  Did you adjust it in all relevant areas?

Is there a way to enter a server id, or set, as a config variable in docker compose?

Seems to me that the docker system is not initialising for some reason in my setup.  Perhaps it defaults to one that is flaky and thus is intermittent.

**Comment by alexjustesen** [comment]
In this discussion I put how to reset the app database and/or update the settings table. lmk if that helps

https://github.com/alexjustesen/speedtest-tracker/discussions/493

**Comment by MarvvanPal** [comment]
Short update: As mentioned I used a new container with new .sqlite db / config without success.

After updating to image v0.11.11  and recreating the container the speedtest tracking works since saturday, 18.3.23. I only changed the cronjob in settings, which is functional (with one 1h shift, but that's another topic and I'm using UTC instead a proper TZ - tried to reduce multiple changes).

I will observe and report here.

**Comment by MarvvanPal** [comment]
Since my last post on the 21st of March and using v0.11.11, I have not had any 'ConfigurationError' errors. I also experienced a lost connection last weekend that was logged correctly.  
![grafik](https://user-images.githubusercontent.com/79196690/233831931-7c8793df-ba1e-4842-9503-b6840060de3f.png)
![grafik](https://user-images.githubusercontent.com/79196690/233832024-cef5c988-a367-445d-97ca-7589e6c82aa7.png)
