### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR, SSL_MODE in .env possibly overruled

### ISSUE THREAD

**Issue by Fribb** [alexjustesen/speedtest-tracker#390]
**Describe the bug**
WebUI Is Inaccessible because of the ERR_SSL_PROTOCOL_ERROR

**To Reproduce**
1. Start the Container
2. open WebUI

**Expected behavior**
The WebUI is accessible

**Environment (please complete the following information):**
 - OS: Unraid 6.11.5 with Docker
-  Architecture: AMD64
 - Browser Chrome & Firefox
 - Version ghcr.io/alexjustesen/speedtest-tracker:latest

**Screenshots**

**Logs**
```
To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...

   ERROR  The [public/storage] link already exists.  

🐇  Configuring Speedtest Tracker...
✅  Database exists
🔗  Creating database symlink
✅  Environment file exists
🔗  Creating symlinks to config and log files
✅  App key exists
🔒  Fixing app path file permissions
💰  Building the cache...
🚛  Migrating the database...
✅  All set, starting Speedtest Tracker container...
⏰  Starting the cron service...
💪  Starting the queue worker...
192.168.178.13 - - [04/Feb/2023:14:07:32 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xA0\xF8\xB4?\x9Aq\xC3\xA2`\xD8\xE6S\xFF\xA68p\xFC\x19\xA0\xF9g+\x8Aop\xF2\xFD\xF0e\x9F)+ b-o\xCAI\xD8_~[\x19d\xAB\xB6\x8E\x14sI\x96\x1B\x11\x9FIG\xDA?\xADD\x84()%J\x00 ZZ\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x01\x00\x01\x93\x8A\x8A\x00\x00\x003\x00+\x00)**\x00\x01\x00\x00\x1D\x00 \x01\xAEL\xCC\xAE\x1C\xBDq \xA4g\x91\xF7,\x11vd\x7FFpg\x9C\x925\xD0\x8C\xA2\xEE\xA92\xAE}\x00\x0B\x00\x02\x01\x00\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00" 400 150 "-" "-"
192.168.178.13 - - [04/Feb/2023:14:07:32 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03v!C\xDF\x80\x93" 400 150 "-" "-"
192.168.178.13 - - [04/Feb/2023:14:07:32 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xDA*%\x14\x03\xEA\x9B\xBD\xAE\xEE\xAD\xA6\x91#\xD1X`:\xD3\xD7\x86\xF8u\xD9\x12\xA3\xC7\x0B\x19\xF9\x97\xF1 \x03\x7F!\xF4\x95X\x06)W\xCF;\x5C\xA4\x99\xC6\xDF@\xB3\xCE\x14\xAD^\xC3\x91\x11Q\x14\x18ml\x9E\x08\x00 ::\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x01\x00\x01\x93\x1A\x1A\x00\x00\x00\x10\x00\x0E\x00\x0C\x02h2\x08http/1.1\x00#\x00\x00Di\x00\x05\x00\x03\x02h2\x00\x12\x00\x00\x00-\x00\x02\x01\x01\x00\x17\x00\x00\x00\x0B\x00\x02\x01\x00\x00" 400 150 "-" "-"
192.168.178.13 - - [04/Feb/2023:14:07:32 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xAD\xFCt\x01\xAB\xEDP|X\xEA=\xF8\x82\xB7X\xF1\x1A\xD0\xE2M\xF1\x8D\x0F\xC7\xAF\xD92\xCD\xFFG\xF7h ]$\xD0\x8C*n\x09\x98wd\xD2" 400 150 "-" "-"
```

**Additional context**
So I found #54 which basically described the issue. 
I could gain access to the WebUI by adding an HTTPS port to the container. But since I only run it locally I thought that this was unnecessary for my use case, I mean it worked before with just HTTP.

I found that you can disable this with `SSL_MODE=off` in the `.env` file which I added. it still worked.

Then I removed the HTTPS port from the container and it took almost a minute for the container to do anything. But now the problem still resulted in the PROTOCOL_ERROR message in the browser.

Looking at the log above it says:

> 🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...

But my `.env` file clearly has it set to off. I would understand that the default is mixed if there is nothing defined in my `.env` file but since it is, why is it still mixed?

**Comment by alexdelprete** [comment]
> But my `.env` file clearly has it set to off. I would understand that the default is mixed if there is nothing defined in my `.env` file but since it is, why is it still mixed?

Because it's not reading your .env file is the only explanation.

Use docker-compose and put the env variables in there.

Mixed is the appropriate configuration, so the container can be accessed both in HTTP and HTTPS. If you can't access it in https, you are doing something wrong.

> I could gain access to the WebUI by adding an HTTPS port to the container.

What does this mean? Did you follow the installation instructions? Please explain in detail how you setup the container.

**Comment by Fribb** [comment]
I use Unraid to host my docker containers which will construct the docker run command based on a template and the values added to it. It is the ZappyZap Template that is linked in the documentation. That run command looks like this:

```
docker run
  -d
  --name='speedtest-tracker'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Fribb-Tower"
  -e HOST_CONTAINERNAME="speedtest-tracker"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='https://[IP]:[PORT:8083]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/devzwf/unraid-docker-templates/main/images/speedtest-tracker-icon.png'
  -p '8083:80/tcp'
  -v '/mnt/user/appdata/speedtest-tracker':'/config':'rw' 'ghcr.io/alexjustesen/speedtest-tracker:latest'
```
> Mixed is the appropriate configuration, so the container can be accessed both in HTTP and HTTPS. If you can't access it in https, you are doing something wrong.

That would make sense if I would access the container in any environment that required the traffic to be encrypted. Since I only use it locally it is completely unnecessary and not needed for me to access it through HTTPS and let my browser always warn me that I don't have a valid certificate.

> What does this mean? Did you follow the installation instructions? Please explain in detail how you setup the container.

while browsing the linked issue number #54 I saw that this might have something to do with the container somehow requiring an HTTPS connection so I added the Port mapping 8084:443 to it and after a restart, I could access the container over that port.

The `.env` file Is in the config folder next to the database.sqlite.

```
-rwxr-xr-x  1 nobody users     779 Feb  4 14:01 .env*
-rwxr-xr-x  1 nobody users 1544192 Feb  4 19:06 database.sqlite*
```

Just to make sure, I renamed the `.env` file after stopping the container, started the container again and the `.env` was created. So unless the container somehow puts the file into the wrong place or the app is using a different file, the location and permissions are all fine.

I then stopped the container again, added the `SSL_MODE=off` to the just created `.env` file, started the container and...

```
 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...

   ERROR  The [public/storage] link already exists.  

🐇  Configuring Speedtest Tracker...
```

From the dockerfile it seems that SSL_MODE is explicitly set as environment with `ENV SSL_MODE="mixed"`.

Based on that I figured that it isn't the environment of the APP which the `.env` probably refers to but rather the environment of the container itself.

So, I added a new environmental variable to the container called `SSL_MODE` with the value `off` and led the container be created.

NOW it works.

So maybe I misunderstood and the `.env` file everyone was talking about in the #54 issue was for docker/docker-compose and not the `.env of the app?! That was not really clear.

ON the other hand, isn't that being setup by the app itself? So adding that value to the app `.env` file should have some impact right?

**Comment by alexdelprete** [comment]
I don't know how unraid works, sorry.

In general, .env is where environment variables should be picked up by the container, but you need to verify if this is the case with the unraid environment, might be working differently. Both .env and variables in docker-compose are processed, docker-compose has precedence over .env file.

It's clear that .env file is not read in your case, maybe it's a permission problem. Check PUID and PGID, those are the user/group the container is impersonating.

Regarding SSL_MODE="mixed": this tells the container to accept http AND https. So if it works for you with SSL_MODE="off" and http, it should also work with SSL_MODE="mixed" and http. Doesn't make sense that it only works when SSL_MODE="off".

Unfortunately, I think it's due to the specifics of unraid, maybe the docker environment works in a different way.

**Comment by Fribb** [comment]
I think we are not talking about the same thing here. I did a bit of research about the `.env` file just to understand it better.

So according to the docker-compose documentation when you have a `.env` file next to the `docker-compose.yml` then you can define the environmental variables there that are then passed to the container (so like the PUID or PGID). this can be done with either the `env_file` attribute in the compose file directly or even as `--file` or `--env-file` in the CLI tool, This seems to be what you are talking about.

I was talking about the `.env` file in the `/config/` folder that is automatically created when the container is starting and contains things like the database that should be used.

That is where I put the `SSL_MODE=off` which had no effect.

This might then also be the mistake on my part because in issue #54, everyone was talking about the `.env` file and I never used this in such a way to define environment variables for the container itself. I only found the already mentioned `/config/.env` and maybe mistakenly assumed that was what everyone meant.

This would also explain why the addition of `SSL_MODE=off` in `/config/.env` didn't do anything but adding a new environmental variable to the container itself worked.

And since the `/config/.env` was created when the container there is no incorrect permission or ownership.

But that still doesn't answer the question of why it doesn't work with `/config/.env` or why the web UI isn't accessible even with `SSL_MODE=mixed`.

I mean, I am not familiar with PHP anymore but from my knowledge, it needs some form of a webserver to serve the files. That webserver would need to be configured which seems to happen through the container environmental variables but not through the `/config/.env` but the App itself seems to be or else it wouldn't be able to know what database it should use, correct?

I would assume that when I have a config folder and an environment file in that config folder I can configure the environment inside of the container so if I set `SSL_MODE=off` it should also be off.

Now, this could all be intended or just the way it is supposed to be but this isn't made clear anywhere. I checked the documentation on https://docs.speedtest-tracker.dev/ but I cannot find anything in regard to `SSL_MODE` or where to put it. So part of the confusion also stems from that.

But even if this is intended and the documentation is updated to reflect that, the question about why there is an error accessing the HTTP exposed Port of the container when the `SSL_MODE` is set to mixed?

**Comment by alexdelprete** [comment]
1. `.env file`: I confirm it is automatically created under `/config`, but if you edit that one adding or modifying a value in there, it's not being picked up. I would point this to @alexjustesen to be looked at. I never used the .env file, I only use env vars in compose file, so I never noticed it. I tried setting SSL_MODE in there, but it didn't have any effect.

2. the real issue here is that you're saying that in mixed mode, while both 80 and 443 are active inside the container, you can't access it on port 80, that is mapped to port 8083 in your template. If you check the log of the container, at startup you can see that it says it's listening on both ports (80 and 443), and NGINX is used inside the container as web server. This is the first time I hear something like this. Can you please show a full container log with SSL_MODE=mixed and SSL_MODE=off? Does Unraid use a sort of reverse proxy to reach the containers services?

**Comment by Fribb** [comment]
> Can you please show a full container log with SSL_MODE=mixed and SSL_MODE=off?

Just for completion's sake, since I already posted the `SSL_MODE=mixed` log ´putput initially:

```
To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...

   ERROR  The [public/storage] link already exists.  

🐇  Configuring Speedtest Tracker...
✅  Database exists
🔗  Creating database symlink
✅  Environment file exists
🔗  Creating symlinks to config and log files
✅  App key exists
🔒  Fixing app path file permissions
💰  Building the cache...
🚛  Migrating the database...
✅  All set, starting Speedtest Tracker container...
⏰  Starting the cron service...
💪  Starting the queue worker...
192.168.178.13 - - [04/Feb/2023:14:07:32 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xA0\xF8\xB4?\x9Aq\xC3\xA2`\xD8\xE6S\xFF\xA68p\xFC\x19\xA0\xF9g+\x8Aop\xF2\xFD\xF0e\x9F)+ b-o\xCAI\xD8_~[\x19d\xAB\xB6\x8E\x14sI\x96\x1B\x11\x9FIG\xDA?\xADD\x84()%J\x00 ZZ\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x01\x00\x01\x93\x8A\x8A\x00\x00\x003\x00+\x00)**\x00\x01\x00\x00\x1D\x00 \x01\xAEL\xCC\xAE\x1C\xBDq \xA4g\x91\xF7,\x11vd\x7FFpg\x9C\x925\xD0\x8C\xA2\xEE\xA92\xAE}\x00\x0B\x00\x02\x01\x00\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00" 400 150 "-" "-"
192.168.178.13 - - [04/Feb/2023:14:07:32 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03v!C\xDF\x80\x93" 400 150 "-" "-"
192.168.178.13 - - [04/Feb/2023:14:07:32 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xDA*%\x14\x03\xEA\x9B\xBD\xAE\xEE\xAD\xA6\x91#\xD1X`:\xD3\xD7\x86\xF8u\xD9\x12\xA3\xC7\x0B\x19\xF9\x97\xF1 \x03\x7F!\xF4\x95X\x06)W\xCF;\x5C\xA4\x99\xC6\xDF@\xB3\xCE\x14\xAD^\xC3\x91\x11Q\x14\x18ml\x9E\x08\x00 ::\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x01\x00\x01\x93\x1A\x1A\x00\x00\x00\x10\x00\x0E\x00\x0C\x02h2\x08http/1.1\x00#\x00\x00Di\x00\x05\x00\x03\x02h2\x00\x12\x00\x00\x00-\x00\x02\x01\x01\x00\x17\x00\x00\x00\x0B\x00\x02\x01\x00\x00" 400 150 "-" "-"
192.168.178.13 - - [04/Feb/2023:14:07:32 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xAD\xFCt\x01\xAB\xEDP|X\xEA=\xF8\x82\xB7X\xF1\x1A\xD0\xE2M\xF1\x8D\x0F\xC7\xAF\xD92\xCD\xFFG\xF7h ]$\xD0\x8C*n\x09\x98wd\xD2" 400 150 "-" "-"
```

Accessing the WebUI over the exposed HTTP port resulted in ERR_SSL_PROTOCOL_ERROR.

Accessing the WebUI over the exposed HTTPS port works.

`SSL_MODE=off`

```
To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔓 SSL_MODE has been DISABLED, setting the web server to work in HTTP only...

   ERROR  The [public/storage] link already exists.  

🐇  Configuring Speedtest Tracker...
✅  Database exists
🔗  Creating database symlink
✅  Environment file exists
🔗  Creating symlinks to config and log files
✅  App key exists
🔒  Fixing app path file permissions
💰  Building the cache...
🚛  Migrating the database...
✅  All set, starting Speedtest Tracker container...
⏰  Starting the cron service...
💪  Starting the queue worker...
192.168.178.13 - - [05/Feb/2023:06:09:30 +0100] "GET / HTTP/1.1" 302 382 "http://192.168.178.3:9983/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
192.168.178.13 - - [05/Feb/2023:06:09:30 +0100] "GET /admin HTTP/1.1" 302 406 "http://192.168.178.3:9983/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
192.168.178.13 - - [05/Feb/2023:06:09:30 +0100] "GET /admin/login HTTP/1.1" 200 3703 "http://192.168.178.3:9983/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
```

Accessing the WebUI over the exposed HTTP port works.

> Does Unraid use a sort of reverse proxy to reach the containers services?

not that I know of and I use it for a while now. It should behave just like a normal docker instance.

**Comment by alexdelprete** [comment]
> Accessing the WebUI over the exposed HTTP port resulted in ERR_SSL_PROTOCOL_ERROR.

this is not possible, unless there's a redirect from HTTP to HTTPS. In another issue the user was using https:// in the browser URL. Make sure the url is correct there.

Can you please set this env variable please? `FORCE_HTTPS=false`

Thank you.

**Comment by Fribb** [comment]
You are completely right I was constantly trying to access the HTTP Port through the Browser URL with HTTPS...

Why? Well, there are two reasons.

1. A template in Unraid has a WebUI field in which you can add the, well, WebUI address that the container can be accessed with. This seems to have been set to HTTPS by default (this field is also hidden unless you inspect the "advanced" view). But then the container itself only provides the HTTP port to port 80 from what I know (it has been a while since I used this container). Funny thing is, you can also see that in the docker run command, I posted earlier....
2. Chrome, which I used to test this with, constantly hides the protocol in the URL. Instead of displaying `https://192.168.178.3:8083/admin` it just displays `192.168.178.3:8083/admin`

This is quite annoying to figure out now especially since it worked for literally months without any issues in that regard.

On the other hand, I have added a link to Speedtest-tracker WebUI in my Organizrr for easier access and it has `http://192.168.178.3:8083/` set. So whenever I would have used THAT link I should have accessed the HTTP WebUI.

But that shouldn't really matter anymore since at least that problem is solved or at least has an explanation on why I stumbled over the `ERR_SSL_PROTOCOL_ERROR` error.

Many thanks.

I think this would also resolve the whole issue because with just using the HTTP URL the issue isn't happening anymore and doesn't require `SSL_MODE` anymore.

**Comment by alexdelprete** [comment]
Great to know it was the browser, again. :)

Now the only thing to check is the .env file under config, created by the container, not being read at startup.

Thanks for closing this.
