### ISSUE TITLE
[Feature Request] Have data on the index.html page

### ISSUE THREAD

**Issue by cinderblockgames** [alexjustesen/speedtest-tracker#397]
**Is your feature request related to a problem? Please describe.**
When I start up the container and go to /, I just get a 404.  I had to track down an image someone posted and guess that going to /admin would be right, then track down the login info in the docs.

**Describe the solution you'd like**
Since logging into the admin side is required, ideally index.html would have a link to there and show the default username/password.

**Comment by alexjustesen** [comment]
`/` uri redirects to `/admin` routes currently and no `404 Not Found` error is displayed. At this time I'm not planning to add anything outside of the auth middleware.

https://github.com/alexjustesen/speedtest-tracker/blob/84759a2cd7a92befaff45dfce740c62999d8d312/routes/web.php#L16-L18
