### ISSUE TITLE
The --single mode in the settings in general section

### ISSUE THREAD

**Issue by malordin** [alexjustesen/speedtest-tracker#398]
**Is your feature request related to a problem? Please describe.**
I would like the application to run two tests in between, or to run a single test (multi or single mode).

**Describe the solution you'd like**
In the global settings, select the mode of operation - single or multi connection. Another solution is to add another cron schedule for the test in single mode

**Additional context**
To understand the picture, speedtest.net has a single mode, both on the site and in the console:
`speedtest-cli --single`

As mentioned in my last [post](https://github.com/alexjustesen/speedtest-tracker/issues/385)

A similar command can be run with `speedtest-cli --single` , or in the web version if you select the switch at the bottom.

This is what it looks like in the console:

```
➜  ~ speedtest-cli --single 
Retrieving speedtest.net configuration...
Testing from Telecom (1.1.1.1)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Operator(City) [2.36 km]: 26.36 ms
Testing download speed................................................................................
Download: 206.46 Mbit/s
Testing upload speed......................................................................................................
Upload: 136.04 Mbit/s
➜  ~ speedtest-cli --version
speedtest-cli 2.1.3
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
```

This is what it looks like on speedtest.net

![image](https://user-images.githubusercontent.com/20083687/217055171-6adc501b-39e1-4ce6-b942-953fd2a463c7.png)

-----

Please look again and tell me how feasible it is. Single communication test modes are also useful for diagnosing network problems and identifying bottlenecks

**Comment by bleomycin** [comment]
+1 for this. There are many applications that rely exclusively on single threaded connections and the performance variance between a single and many connections can be drastic. VPN, IP security cameras, remote desktop, rsync, scp all rely on single connections. Right now there doesn't be a way to keep track of this performance easily to hand over to my ISP. My single thread speeds on average only achieve 10% of the rated upload speed from my ISP but if you look at the history from speedtest-tracker things look much better than they are.

**Comment by svenvg93** [comment]
I quickly looked at this. As it stands now this is not possible as the Ookla Speedtest CLI client does not have the option to switch between Single and Multi connections. 

```
sven@srv01:~$ speedtest --help
Speedtest by Ookla is the official command line client for testing the speed and performance of your internet connection.

Version: speedtest 1.2.0.84

Usage: speedtest [<options>]
  -h, --help                        Print usage information
  -V, --version                     Print version number
  -L, --servers                     List nearest servers
  -s, --server-id=#                 Specify a server from the server list using its id
  -I, --interface=ARG               Attempt to bind to the specified interface when connecting to servers
  -i, --ip=ARG                      Attempt to bind to the specified IP address when connecting to servers
  -o, --host=ARG                    Specify a server, from the server list, using its host's fully qualified domain name
  -p, --progress=yes|no             Enable or disable progress bar (Note: only available for 'human-readable'
                                    or 'json' and defaults to yes when interactive)
  -P, --precision=#                 Number of decimals to use (0-8, default=2)
  -f, --format=ARG                  Output format (see below for valid formats)
      --progress-update-interval=#  Progress update interval (100-1000 milliseconds)
  -u, --unit[=ARG]                  Output unit for displaying speeds (Note: this is only applicable
                                    for ‘human-readable’ output format and the default unit is Mbps)
  -a                                Shortcut for [-u auto-decimal-bits]
  -A                                Shortcut for [-u auto-decimal-bytes]
  -b                                Shortcut for [-u auto-binary-bits]
  -B                                Shortcut for [-u auto-binary-bytes]
      --selection-details           Show server selection details
      --ca-certificate=ARG          CA Certificate bundle path
  -v                                Logging verbosity. Specify multiple times for higher verbosity
      --output-header               Show output header for CSV and TSV formats

 Valid output formats: human-readable (default), csv, tsv, json, jsonl, json-pretty

 Machine readable formats (csv, tsv, json, jsonl, json-pretty) use bytes as the unit of measure with max precision

 Valid units for [-u] flag:
   Decimal prefix, bits per second:  bps, kbps, Mbps, Gbps
   Decimal prefix, bytes per second: B/s, kB/s, MB/s, GB/s
   Binary prefix, bits per second:   kibps, Mibps, Gibps
   Binary prefix, bytes per second:  kiB/s, MiB/s, GiB/s
   Auto-scaled prefix: auto-binary-bits, auto-binary-bytes, auto-decimal-bits, auto-decimal-bytes
```

**Comment by malordin** [comment]
@svenvg93 

Apparently you have some old version of the CLI, I just checked on an Ubuntu 22.04 system and it's still there even after 2 years.

`➜  ~ speedtest-cli
Retrieving speedtest.net configuration...
Testing from Operator (xxx.xxx.xxx.xxx)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Operator (City) [123.123 km]: 123.123 ms
Testing download speed................................................................................
Download: 123.123 Mbit/s
Testing upload speed......................................................................................................
Upload: 123.123 Mbit/s
➜  ~ speedtest-cli --single
Retrieving speedtest.net configuration...
Testing from Operator (xxx.xxx.xxx.xxx)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Operator (City) [123.123 km]: 123.123 ms
Testing download speed................................................................................
Download: 123.123 Mbit/s
Testing upload speed......................................................................................................
Upload: 123.123 Mbit/s
➜  ~ speedtest-cli --version
speedtest-cli 2.1.3
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
➜  ~ speedtest-cli --help
usage: speedtest-cli [-h] [--no-download] [--no-upload] [--single] [--bytes] [--share]
                     [--simple] [--csv] [--csv-delimiter CSV_DELIMITER] [--csv-header]
                     [--json] [--list] [--server SERVER] [--exclude EXCLUDE] [--mini MINI]
                     [--source SOURCE] [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
                     [--version]

Command line interface for testing internet bandwidth using speedtest.net.
--------------------------------------------------------------------------
https://github.com/sivel/speedtest-cli

options:
  -h, --help            show this help message and exit
  --no-download         Do not perform download test
  --no-upload           Do not perform upload test
  --single              Only use a single connection instead of multiple. This simulates a
                        typical file transfer.
  --bytes               Display values in bytes instead of bits. Does not affect the image
                        generated by --share, nor output from --json or --csv
  --share               Generate and provide a URL to the speedtest.net share results image,
                        not displayed with --csv
  --simple              Suppress verbose output, only show basic information
  --csv                 Suppress verbose output, only show basic information in CSV format.
                        Speeds listed in bit/s and not affected by --bytes
  --csv-delimiter CSV_DELIMITER
                        Single character delimiter to use in CSV output. Default ","
  --csv-header          Print CSV headers
  --json                Suppress verbose output, only show basic information in JSON format.
                        Speeds listed in bit/s and not affected by --bytes
  --list                Display a list of speedtest.net servers sorted by distance
  --server SERVER       Specify a server ID to test against. Can be supplied multiple times
  --exclude EXCLUDE     Exclude a server from selection. Can be supplied multiple times
  --mini MINI           URL of the Speedtest Mini server
  --source SOURCE       Source IP address to bind to
  --timeout TIMEOUT     HTTP timeout in seconds. Default 10
  --secure              Use HTTPS instead of HTTP when communicating with speedtest.net
                        operated servers
  --no-pre-allocate     Do not pre allocate upload data. Pre allocation is enabled by default
                        to improve upload performance. To support systems with insufficient
                        memory, use this option to avoid a MemoryError
  --version             Show the version number and exit`

**Comment by svenvg93** [comment]
@malordin I use the Ookla CLI, which is the same as used by the application. 
https://www.speedtest.net/apps/cli 

I think you are using the unofficial version that was made before Ookla made their own, looking at the output;

```
Command line interface for testing internet bandwidth using speedtest.net.
--------------------------------------------------------------------------
https://github.com/sivel/speedtest-cli
```

**Comment by alexjustesen** [comment]
> I think you are using the unofficial version that was made before Ookla made their own, looking at the output;

This is correct, we're using Ookla's official CLI which is executed using the `speedtest` command while the unofficial is run using `speedtest-cli`.
