### ISSUE TITLE
Error Undefined array key "ping"

### ISSUE THREAD

**Issue by Veezzy** [alexjustesen/speedtest-tracker#399]
Most times I get this Error like 1 out 10 times i get a result.

Results Data:

{"type":"log","timestamp":"2023-02-06T22:00:03Z","message":"Path used: /root/.config/ookla/speedtest-cli.json","level":"error"}

Error in log:
production.ERROR: Undefined array key "ping" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"ping\" at /var/www/html/app/Models/Result.php:85)
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()

**Comment by alexjustesen** [comment]
This is related to #301, changes coming soon to how data is handled.
