### ISSUE TITLE
Notification channels

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#40]
When a notification is triggered it should be sent to a channel so that the user is notified of the thing.

Supported channels ~~should~~ will include:
- [x] Database notification channel
- [x] #141
- [x] #1196 
- [x] #1522
- [x] #265 
- [x] #1561 
- [x] #1579
- [ ] #1651
- [x] #1567
- [x] #1574 
- [x] #869 
- [x] ~#1578~, cancelled because MS is dropping Teams webhook support

**Comment by jpslv** [comment]
This app is really awesome and a nice "upgrade" over others that are available but outdated on unRAID. Would love to have discord notifications. Is it possible?

**Comment by alexjustesen** [comment]
> This app is really awesome and a nice "upgrade" over others that are available but outdated on unRAID. Would love to have discord notifications. Is it possible?

Discord is already on the list 😉, also this reminds me I'll need to get this onto the unRAID Community App Store

**Comment by jpslv** [comment]
I've installed today this one on my unRAID server.

![image](https://user-images.githubusercontent.com/95918883/198841324-e12e6191-bcef-4317-b844-d684b52db20f.png)

**Comment by jpslv** [comment]
And thank you so much for the Discord feature!

**Comment by alexjustesen** [comment]
> I've installed today this one on my unRAID server.
> 

Right after I posted that I saw someone created the app, nice to see the unRAID community here!

**Comment by mztiq** [comment]
Thanks for reviving this project, I'm happy to see all this progress!
Any chance for [Ntfy](https://github.com/binwiederhier/ntfy) notification implementation? It works pretty similar to Gotify, alternatively some kind of curl notifications would be great too.

**Comment by alexjustesen** [comment]
> Thanks for reviving this project, I'm happy to see all this progress!
> Any chance for [Ntfy](https://github.com/binwiederhier/ntfy) notification implementation? It works pretty similar to Gotify, alternatively some kind of curl notifications would be great too.

Ntfy sounds good so can do, also what do you mean about a curl notification?

**Comment by mztiq** [comment]
That'd be awesome!
Ntfy also supports notifications via curl as described [here](https://docs.ntfy.sh/publish/), that's what I meant.

**Comment by gf78** [comment]
Proposal: add generic webhook notification. users can add get urls, these are requested in case of a notification. values are added as query.

this gives users more flexibility to trigger actions in their own systems

**Comment by alexjustesen** [comment]
> Proposal: add generic webhook notification. users can add get urls, these are requested in case of a notification. values are added as query.
> 
> this gives users more flexibility to trigger actions in their own systems

Added to the list

**Comment by hctrr** [comment]
proposal: add support for [apprise](https://github.com/caronc/apprise)
_Apprise allows you to send a notification to almost all of the most popular notification services available to us today such as: Telegram, Discord, Slack, Amazon SNS, Gotify, etc._

**Comment by shiftylilbastrd** [comment]
Pushover would be a great addition as well

**Comment by ilsaul** [comment]
@alexjustesen I appreciate your idea to integrate many notification systems but aprise with one REST call realizes several notification systems. In a short time you can integrate it compared to the time it takes to integrate any of the other systems. You can also think that by integrating an external system when someone ask you to add a new system you can always reply to see if Aprise supports it while you integrate other things.

**Comment by alexjustesen** [comment]
> @alexjustesen I appreciate your idea to integrate many notification systems but apprise with one REST call realizes several notification systems. In a short time you can integrate it compared to the time it takes to integrate any of the other systems. You can also think that by integrating an external system when someone ask you to add a new system you can always reply to see if Apprise supports it while you integrate other things.

https://github.com/alexjustesen/speedtest-tracker/issues/277#issuecomment-1370839098

**Comment by masterwishx** [comment]
@alexjustesen Sorry , cant find if notifications (mostly interested Discord) is added to milestones ?

**Comment by alexjustesen** [comment]
> @alexjustesen Sorry , cant find if notifications (mostly interested Discord) is added to milestones ?

Not yet, list at the top is accurate.

**Comment by masterwishx** [comment]
OK, Thanks will wait ... :)

**Comment by blusls79** [comment]
Hi! Great work. Wondering if you can help me with an issue I am experiencing. When I setup the mail notification, I never receive the email. I have checked all spam filters/folders I have and I don't see the email I am expecting when I click the test button in the Mail sections of the notifications page.

**Comment by alexjustesen** [comment]
> Hi! Great work. Wondering if you can help me with an issue I am experiencing. When I setup the mail notification, I never receive the email. I have checked all spam filters/folders I have and I don't see the email I am expecting when I click the test button in the Mail sections of the notifications page. I am using a known good email configuration via Sendgrid. Which I have setup on other tools and apps I have running in my environment.

Can you do me a favor and start a discussion on your issue? This issue I'm using to track progress on features and don't want to have multiple topics.

**Comment by blusls79** [comment]
Sorry about that, and done.

**Comment by viriatusX** [comment]
Good evening.
Any ETA to implement notifications with Discord? Thank you very much 🙏

**Comment by grosejon** [comment]
I used to use Notifiarr with the old speedtest tracker, and that worked really well. The notifications ended up in Discord which made it very easy.

**Comment by crispybegs** [comment]
+1 for slack notifications if poss!

**Comment by Wamy-Dev** [comment]
+1 For Discord!

**Comment by abelfodil** [comment]
+1 for Gotify

**Comment by schorschebob** [comment]
+1 for slack notification. Would be awesome!

**Comment by Melotron** [comment]
+1 for ntfy

**Comment by rairulyle** [comment]
For Discord, you can use [shoutrrr](https://containrrr.dev/shoutrrr/v0.8/), this is what I use for [watchtower ](https://containrrr.dev/watchtower/notifications/#shoutrrr_notifications)and it is very much easy to setup.

It looks likes this:

```
    environment:
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "discord://${DISCORD_TOKEN}@${DISCORD_ID}"
      WATCHTOWER_SCHEDULE: "0 0 * * *" # every 12:00 AM every day
```

**Comment by tiritibambix** [comment]
+1 for discord notification

**Comment by MDeLuise** [comment]
+1 for Ntfy notification

**Comment by jonezy35** [comment]
Has there been much interest in the Slack notification channel? Now that I figured out Discord (assuming that's good to be merged) I could pivot to Slack now that I have an understanding of the notification functionality.

**Comment by crispybegs** [comment]
> Has there been much interest in the Slack notification channel? Now that I figured out Discord (assuming that's good to be merged) I could pivot to Slack now that I have an understanding of the notification functionality.

i used to have my speed results delivered to slack every day on one of the old versions and was quite sad when it vanished, so yes I'd love it back

**Comment by jonezy35** [comment]
> > Has there been much interest in the Slack notification channel? Now that I figured out Discord (assuming that's good to be merged) I could pivot to Slack now that I have an understanding of the notification functionality.
> 
> i used to have my speed results delivered to slack every day on one of the old versions and was quite sad when it vanished, so yes I'd love it back

Sweet assuming my PR for Discord gets merged I can see about getting Slack notifications up and running once I confirm everything is good with the current PR

**Comment by crispybegs** [comment]
> > > Has there been much interest in the Slack notification channel? Now that I figured out Discord (assuming that's good to be merged) I could pivot to Slack now that I have an understanding of the notification functionality.
> > 
> > 
> > i used to have my speed results delivered to slack every day on one of the old versions and was quite sad when it vanished, so yes I'd love it back
> 
> Sweet assuming my PR for Discord gets merged I can see about getting Slack notifications up and running once I confirm everything is good with the current PR

thank you for your service

**Comment by Magelo** [comment]
> > Thanks for reviving this project, I'm happy to see all this progress!
> > Any chance for [Ntfy](https://github.com/binwiederhier/ntfy) notification implementation? It works pretty similar to Gotify, alternatively some kind of curl notifications would be great too.
> 
> Ntfy sounds good so can do, also what do you mean about a curl notification?

![image](https://github.com/alexjustesen/speedtest-tracker/assets/10362303/bf383698-3241-4b98-b0f1-f63e8fc8f46b)

Hi, working with Ntfy, replacing {user}, {password} and {url} with valid info works when using button "Test webhook channel" but save changes refuse to save with message "The url field must be a valid URL."

**Comment by alexjustesen** [comment]
I'm willing to bet this happens because validation doesn't trigger when testing a url but does in save.

**Comment by Magelo** [comment]
> I'm willing to bet this happens because validation doesn't trigger when testing a url but does in save.

Absolutely, my point is, why the validation triggers when saving, a not valid URL? The URL is working with "Test webhook channel", in Ntfy I received the test notification.

**Comment by alexjustesen** [comment]
Ntfy support is planned (at some point), I would say the initial webhook scope is more intended for a simple payload and like Discord isn't meant for that.

**Comment by alexjustesen** [comment]
@jonezy35 when you go to do Slack (if you're still interested) I'm bring in a new pattern for notifications that hooks into the new event driven architecture.

https://github.com/alexjustesen/speedtest-tracker/pull/1264 has the new events and https://github.com/alexjustesen/speedtest-tracker/pull/1267 shows how to do this with webhooks.

**Comment by jonezy35** [comment]
I'm interested! Just been real busy with work this week

**Comment by alexjustesen** [comment]
> I'm interested! Just been real busy with work this week

No rush at all, just wanted to give you a heads up because you've been in those files.

**Comment by NightHawkATL** [comment]
I have just enabled webhooks yesterday to send to activepieces to then send to gotify. I am getting multiples of 4 each time and they alternate as blank and correctly filled. 1x set of 4 will have data and the next set of 4 on trigger will be blank.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/538f75d2-fcda-4078-9de3-b4af5dbe57a6)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/171c18e9-0faa-4d56-9a3b-5429a183c6f8)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/8395658/5204d37a-32c5-4426-a39b-101a653dac0c)

**Comment by alexjustesen** [comment]
@NightHawkATL this PR is for the "Feature" of notification channels. If you're having a problem please open an issue to detail it out.

**Comment by abelfodil** [comment]
There's a lib to implement gotify https://github.com/VerifiedJoseph/gotify-api-php

Are we allowed to use it?
