### ISSUE TITLE
Option to disable the Login Page

### ISSUE THREAD

**Issue by afriedl79** [alexjustesen/speedtest-tracker#401]
would be very convenient to have an option to disable the login page or at least set a timeout value for a new login request.

**Comment by alexjustesen** [comment]
At this point there is no plan to disable auth

**Comment by dphildebrandt** [comment]
Any chance you'd reconsider? I think it's a fairly common pattern to simply self-host the docker container behind another oauth (google, authelia, etc) and so to have a double login is less than optimal. Would be nice to give people the choice to disable.

**Comment by alexjustesen** [comment]
I'll keep it in mind but at this time it's not a priority as it would result in a major rewrite and the core functionality for v1 isn't done.
