### ISSUE TITLE
Results page column label incorrect

### ISSUE THREAD

**Issue by KrunchMuffin** [alexjustesen/speedtest-tracker#402]
In the Download column it says Mbps when in reality it is Gbps. Maybe just remove that part of the label and put it in the  data itself.

![image](https://user-images.githubusercontent.com/1037197/218287412-93005182-6e17-4713-8502-333543c4be43.png)

**Comment by alexdelprete** [comment]
Click the 3 dots at the end of the results row, then click "View".

From the **View Result** window, please copy the contents of the Data section and paste it here.

![image](https://user-images.githubusercontent.com/7027842/218289587-0f3b39c1-2b6e-4083-866d-bfae8c094b38.png)

**Comment by KrunchMuffin** [comment]
here you go

```JSON
{
    "download": {
        "bandwidth": 237832887,
        "bytes": 2169547572,
        "elapsed": 9312,
        "latency": {
            "high": 150.506,
            "iqm": 82.048,
            "jitter": 15.827,
            "low": 10.284
        }
    },
    "interface": {
        "externalIp": "174.112.116.240",
        "internalIp": "172.17.0.5",
        "isVpn": false,
        "macAddr": "02:42:AC:11:00:05",
        "name": "eth0"
    },
    "isp": "Rogers Cable",
    "packetLoss": 0,
    "ping": {
        "high": 15.025,
        "jitter": 1.056,
        "latency": 11.501,
        "low": 10.802
    },
    "result": {
        "id": "6f23cbfb-be79-49d2-9548-eac23d473890",
        "persisted": true,
        "url": "https://www.speedtest.net/result/c/6f23cbfb-be79-49d2-9548-eac23d473890"
    },
    "server": {
        "country": "Canada",
        "host": "stottawa.rogers.com",
        "id": 46151,
        "ip": "72.136.172.138",
        "location": "Ottawa, ON",
        "name": "Rogers",
        "port": 8080
    },
    "timestamp": "2023-02-12T01:00:19Z",
    "type": "result",
    "upload": {
        "bandwidth": 6749587,
        "bytes": 27010992,
        "elapsed": 4002,
        "latency": {
            "high": 19.444,
            "iqm": 4.399,
            "jitter": 0.785,
            "low": 3.763
        }
    }
}
```

**Comment by KrunchMuffin** [comment]
The dashboard is correct

![image](https://user-images.githubusercontent.com/1037197/218290550-b4411e56-853f-4838-b138-5626144b8a0b.png)

**Comment by alexdelprete** [comment]
Download Bandwidth: 237832887 bytes per second

237832887 * 0,000008 = 1902.66 Mbps = 1.9 Gbps

And you can check yourself using the speedtest url that is in the json data: https://www.speedtest.net/result/c/6f23cbfb-be79-49d2-9548-eac23d473890

The value you see in the column is 1896 Mbps, but it should be 1902 Mbps. Maybe @alexjustesen can explain the small difference.

**Comment by KrunchMuffin** [comment]
Maybe I wasn't clear enough. If it has to be Mbps, move the . over 3 places to the right

![image](https://user-images.githubusercontent.com/1037197/218291377-81536f8f-37e6-4c61-a08d-c75b72896aaa.png)

**Comment by alexdelprete** [comment]
The dot seems to be the thousands separator in that case, but on the upload is the decimals separator. That's what misled you. In any case, it has to be checked by @alexjustesen.

**Comment by Magelo** [comment]
Using threshold notification is not working because of this problem. If I set a notification for anything under 500 Mbps, my 1.087 Gbps is tested as 1.087 Mbps and triggers the threshold notification.

![image](https://user-images.githubusercontent.com/10362303/219817461-f03ea37f-fa86-482a-a70a-92717a81be2a.png)

**Comment by alexjustesen** [comment]
There are known inconsistencies in the UI currently regarding correctly labeling data speeds when rounding up. Will be fixed in the next release.
