### ISSUE TITLE
Add option to disable authentication

### ISSUE THREAD

**Issue by foux** [alexjustesen/speedtest-tracker#407]
**Is your feature request related to a problem? Please describe.**
It's not an issue per say, but more of an inconvenience. I'm using a centralized auth for all my services. With Speedtest I'm forced to login again with speedtest second auth.

**Describe the solution you'd like**
It would be nice to be able to completely disable Speedtest Tracker authentication, which would come handy in some cases : 

- People not exposing their services over the internet
- Services jailed behind a VPN
- Other auth services in places.

Thanks!

**Comment by alexjustesen** [comment]
Duplicate #401
