### ISSUE TITLE
Email notification link is broken

### ISSUE THREAD

**Issue by zvarg** [alexjustesen/speedtest-tracker#408]
**Describe the bug**
The link to `View Results` is broken as it is pointing to `http://localhost/admin/results`. 

**To Reproduce**
1. Receive an notification from absolute threshold failed
2. Click on 'View Results'
3. See error

**Expected behavior**
Link should be pointing to `{baseUrl}/admin/results`

**Screenshots**
![image](https://user-images.githubusercontent.com/18576529/218785301-f467df16-1bae-497c-a33f-1d4c09807706.png)

**Additional context**
May be set somehow I missing, but could not find any mention on [docs](https://docs.speedtest-tracker.dev/settings/notifications/mail).

**Comment by alexjustesen** [comment]
@zvarg the url is going to be based on your `APP_URL` environment variable, make sure that's what you'd expect to see.

**Comment by zvarg** [comment]
Sorry for the delay. It works for sure when I set the environment variable as follows: `APP_URL="http://pi:9020/"`

@alexjustesen may I suggest a doc improvement for this variable. Thanks in advance.

**Comment by alexjustesen** [comment]
I been meaning to start a list of FAQs in the docs so added this as the first https://docs.speedtest-tracker.dev/faqs
