### ISSUE TITLE
Speed test results are off

### ISSUE THREAD

**Issue by Serph91P** [alexjustesen/speedtest-tracker#410]
**Describe the bug*
If I test it on the ookla page itself the speed are way more believeable. See Screenshots.
Via the docker they are way below what is believable.

**To Reproduce**
Start a Speedtest and See Results

**Expected behavior**
The Same results on the test

**Environment (please complete the following information):**
 - OS: Unraid
-  Architecture: amd64
 - Browser: Firefox
 - Version 0.11.1

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8904984/219011246-d67e105e-610c-40f5-a70c-46ee21b0a388.png)
![grafik](https://user-images.githubusercontent.com/8904984/219011479-598a3604-764f-4679-8dfa-9eaaf6a4e399.png)

**Logs**
`{"type":"result","timestamp":"2023-02-15T11:00:15Z","ping":{"jitter":4.339,"latency":18.814,"low":16.450,"high":26.173},"download":{"bandwidth":10113258,"bytes":45037392,"elapsed":4408,"latency":{"iqm":22.069,"low":16.713,"high":28.192,"jitter":3.264}},"upload":{"bandwidth":6136194,"bytes":43541360,"elapsed":7108,"latency":{"iqm":17.284,"low":15.891,"high":495.784,"jitter":10.935}},"isp":"Vodafone Germany","interface":{"internalIp":"172.17.0.2","name":"eth0","macAddr":"02:42:AC:11:00:02","isVpn":false,"externalIp":"redacted"},"server":{"id":7961,"host":"speedtest01.tk-bodensee.net","port":8080,"name":"Stadtwerke Konstanz GmbH","location":"Konstanz","country":"Germany","ip":"redacted"},"result":{"id":"f7406ffd-53b9-47c8-bd94-3e048c4d8b5d","url":"https://www.speedtest.net/result/c/f7406ffd-53b9-47c8-bd94-3e048c4d8b5d","persisted":true}}`

**Additional context**

**Comment by alexjustesen** [comment]
There are known inconsistencies in the UI currently regarding correctly labeling data speeds when rounding up. Will be fixed in the next release.
