### ISSUE TITLE
Homeassistant ifame

### ISSUE THREAD

**Issue by Lillifee** [alexjustesen/speedtest-tracker#411]
First of all - great project, with a nice user interface, and perfect documentation.

**Is your feature request related to a problem? Please describe.**
Homeassistant allows the creation of custom menu entries to embed sites like adguard, grafana, etc.

configuration.yaml
```
panel_iframe:
  speedtest:
    title: Speedtest
    icon: mdi:speedometer
    url: "http://192.168.3.5:8080"
```

Speedtest refuses the connection in an iframe
Refused to display 'http://192.168.3.5:8080/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

![image](https://user-images.githubusercontent.com/23337626/219455684-b624d815-b9a4-4d3d-a247-0a58b5d758c7.png)

console output
![image](https://user-images.githubusercontent.com/23337626/219455827-287cd469-8050-4a30-a34c-11e11fef290d.png)

**Describe the solution you'd like**
It would be nice to set an environment variable like grafana to allow the same origin and embedding of the site.

example of grafana docker compose:
```
  environment:
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_SECURITY_COOKIE_SAMESITE: none
```

**Additional context**

Homeassistant 
https://community.home-assistant.io/t/solved-panel-iframe-grafana-docker-doesnt-work/143445/12

Please rate this feature with a low priority.
Thanks a lot

**Comment by clemone210** [comment]
The same applies for iFrame feature in [Organizr](https://github.com/causefx/Organizr)

**Comment by Nortrix0** [comment]
While I'm sure this is not recommended from a security point of view, I was able to get it working by using this in my CaddyFile

```
reverse_proxy speedtest:80 {
             header_down -X-Frame-Options
}
```

**Comment by alexjustesen** [comment]
@Lillifee this might now be possible in the lates `v0.13.0-beta.x` build, if it's still requested can you double check?

**Comment by alexjustesen** [comment]
Also leaving this here should it still not be possible I'll test further to modify the CORS middleware.

https://voutzinos.com/blog/cross-origin-iframe-laravel/
