### ISSUE TITLE
Exclude server(s)

### ISSUE THREAD

**Issue by phistook** [alexjustesen/speedtest-tracker#412]
**Issue**
I have one server that misbehaves and I'm getting consistently significantly lower readings from it that are not representative of the speed I'm getting. I've compared that server to others at the same time and confirmed it.
At the moment I can list all of the other servers to exclude that one but as server availability changes I need to update the list.

**Solution suggestion**
Because the CLI doesn't support this, my suggestion is to use the -L to retrieve available servers, remove from that list those that are listed for exclusion and then pick a random one from the remaining as the test server.
This is effectively creating a dynamic server list by removing certain servers rather than listing all desired ones.

**Comment by alexjustesen** [comment]
Linking this to #341 as this will be a part of a larger change to how "scheduled" tests are run.
