### ISSUE TITLE
Settings not accepting all valid cron formats

### ISSUE THREAD

**Issue by mnul** [alexjustesen/speedtest-tracker#413]
**Describe the bug**
I went into the settings to change the cron schedule, but it says "cron expression not valid" 

**To Reproduce**
1. Go to Settings, General
2. Into the cron field enter "7/30 * * * *"
3. Click Save, see error "cron expression not valid"
4. Check the cron expression on crontab.cronhub.io, there is says it is valid.

**Expected behavior**
accept the vallid cron schedule

**Environment:**
 - OS: Ubuntu
-  Architecture: amd64
 - Docker:  23.0.1
 - Version V0.11.1

**Comment by alexjustesen** [comment]
It [looks](https://crontab.guru/#7/30_*_*_*_*) like that format is non-standard which is why its failing validation. If you want to run at half-past every hour why not just do `30 * * * *`?

**Comment by mnul** [comment]
I see. 
the basic idea is to not have all cron schedules at * o'clock and half past *, but to offset the jobs by a few minutes to avoid the most "crowded" times. In terms of data traffic everyone will test at *:00 and *:30, but there is less traffic at *:07 and *:37
