### ISSUE TITLE
absolute thresholds over 1 Gbps get notifications

### ISSUE THREAD

**Issue by bharrisii** [alexjustesen/speedtest-tracker#419]
When setting absolute threshold for download to 1000 Mbps it will trigger even when speeds are greater.

Running on Synology Docker
Laravel v9.48.0
PHP v8.1.14
Filament v2.16.66
Speedtest Tracker v0.11.1

Attached screenshots:
![absolute thresholds settings](https://user-images.githubusercontent.com/125853031/220019061-1fcc6df7-d539-456f-a21d-8ea1feb30ce7.jpg)
![email notification](https://user-images.githubusercontent.com/125853031/220019063-8de706e6-c67c-404a-932c-447ab573bc16.jpg)

**Comment by alexjustesen** [comment]
This is related to the issue I'm tracking with #418
