### ISSUE TITLE
Results table to occupied all the available width

### ISSUE THREAD

**Issue by hdkars** [alexjustesen/speedtest-tracker#431]
**Describe the solution you'd like**
Really just an aesthetic change.. Let the result table stretch to the available width space, so all the columns are visible without scrolling

Right now its set to 80rem (max-w-7xl). Maybe better to be 80%? dunno

**Comment by alexjustesen** [comment]
For later Alex to circle back around on this, will add it as a setting in the UI.

https://filamentphp.com/docs/2.x/admin/appearance#changing-the-maximum-content-width
