### ISSUE TITLE
REST API to retrieve tests and history

### ISSUE THREAD

**Issue by agneevX** [alexjustesen/speedtest-tracker#435]
**Is your feature request related to a problem? Please describe.**

I use Home Assistant and I'd like to use data from this app to display it over there as well.

On `henrywhitaker3/speedtest-tracker`, an unoffical API exists...

```sh
~ ❱ curl -s http://10.0.0.10:8700/api/speedtest/latest | jq .
{
  "data": {
    "id": 11876,
    "ping": "1.824",
    "download": "148.146616",
    "upload": "146.133368",
    "created_at": "2023-02-28T12:30:31.000000Z",
    "updated_at": "2023-02-28T12:30:31.000000Z",
    "server_id": "xxx",
    "server_name": "xxx",
    "server_host": "xxx",
    "url": "https://www.speedtest.net/result/c/xxx",
    "scheduled": "0",
    "failed": "0"
  },
  "average": {
    "ping": "6.10624704268813",
    "download": "142.029634942568",
    "upload": "142.991824161838"
  },
  "maximum": {
    "ping": "366.063",
    "download": "175.273408",
    "upload": "166.587064"
  },
  "minimum": {
    "ping": "0.925",
    "download": "0.64456",
    "upload": "1.225048"
  }
}
```

**Describe the solution you'd like**

It would very good if a similar API exists with this app that would make retrieving data and scripting it very easy.

**Additional context**

**Comment by alexjustesen** [comment]
This API is a part of the homelab dashboard support I have planned so going to link to that issue can close this out.

#81
