### ISSUE TITLE
Help Resetting Password

### ISSUE THREAD

**Issue by yeo423** [alexjustesen/speedtest-tracker#436]
I have the same stupid question. Have spent too long trying to figure it out with no success. Found this other post, but I assume the individual asking the question used sqlite.  I on the other hand used mariadb/mysql and can not figure out the tool to use mentioned below.  Any help pointing me in the right direction is greatly appreciated.  

_Originally posted by @alexdelprete in https://github.com/alexjustesen/speedtest-tracker/discussions/346#discussioncomment-4749821_

       > so stupid question, how do I delete the database?

If you use sqlite, it's in the volume mapped folder. If you use mariadb/mysql, you need to use a tool to delete the db.

Show me your docker-compose file, in the volumes: section there's the folder with the sqlite db.

**Comment by alexdelprete** [comment]
I use HeidiSQL. But there are tons of tools to manage DBs...

**Comment by yeo423** [comment]
> I use HeidiSQL. But there are tons of tools to manage DBs...

Thank you!  I will attempt to figure this out.  Ha!
