### ISSUE TITLE
Notifications wont work after enabled

### ISSUE THREAD

**Issue by debiantippse** [alexjustesen/speedtest-tracker#456]
🐛 **Describe the bug**

Notifications will not trigger after being enabled but test notifications work

😀 **Expected behavior**

After enabeling Notifications for Telegram and Database the homepage as well as a telegram message should have been triggered.

😨 **Actual behavior**

The Homepage as well as the Telegram bot does not show any sign of notifications beeing send out.

📷 **Screenshots**

i'll link some screenshots in here for settings and behavior if a test notification event is triggered.
![grafik](https://user-images.githubusercontent.com/90697077/223716078-f57258dc-ca67-4039-9143-981fc9769941.png)
![grafik](https://user-images.githubusercontent.com/90697077/223716163-5d3dc1bf-2517-4ef8-b61c-a4f965301210.png)
![grafik](https://user-images.githubusercontent.com/90697077/223716244-d896a5c1-3ac5-417b-ad9b-a8a3f5615555.png)

Any help is appreciated and i can provide logs if needed.

**Comment by alexjustesen** [comment]
@debiantippse are speedtests running on the schedule as intended?
