### ISSUE TITLE
Different speeds on scheduled and queued

### ISSUE THREAD

**Issue by Daiyamund** [alexjustesen/speedtest-tracker#459]
I've noticed that scheduled tests are always half the expected speeds, while unscheduled tests are running correctly.
Looking at JSON results, it seems the settings are the same in all tests.
I'm running a v0.11.6, if you need any more details - let me know!

![NVIDIA Share_2023-03-09_22-26-14](https://user-images.githubusercontent.com/3599618/224038453-451a6d82-c129-4acc-8e52-1268e74e1eaf.png)

Here's the scheduled test's result details:

```
{
 "type": "result",
 "timestamp": "2023-03-09T13:00:26Z",
 "ping": {
  "jitter": 0.587,
  "latency": 5.514,
  "low": 5.05,
  "high": 6.129
 },
 "download": {
  "bandwidth": 61179997,
  "bytes": 301895304,
  "elapsed": 4911,
  "latency": {
   "iqm": 7.902,
   "low": 6.321,
   "high": 17.786,
   "jitter": 1.513
  }
 },
 "upload": {
  "bandwidth": 57294685,
  "bytes": 773228275,
  "elapsed": 15010,
  "latency": {
   "iqm": 4.152,
   "low": 1.912,
   "high": 15.457,
   "jitter": 1.475
  }
 },
 "packetLoss": 77.77777777777777,
 "isp": "So-net",
 "interface": {
  "internalIp": "10.42.0.78",
  "name": "eth0",
  "macAddr": "CE:4E:##:##:##:##",
  "isVpn": false,
  "externalIp": "110.67.###.###"
 },
 "server": {
  "id": 21569,
  "host": "jp.as.speedtest.i3d.net",
  "port": 8080,
  "name": "i3D.net",
  "location": "Tokyo",
  "country": "Japan",
  "ip": "103.194.167.213"
 },
 "result": {
  "id": "de4a6618-75de-4342-b837-658d6530c7a3",
  "url": "https://www.speedtest.net/result/c/de4a6618-75de-4342-b837-658d6530c7a3",
  "persisted": true
 }
}
```

And here's the queued result I ran 2 minutes after:

```
{
 "type": "result",
 "timestamp": "2023-03-09T13:02:30Z",
 "ping": {
  "jitter": 0.136,
  "latency": 2.955,
  "low": 2.867,
  "high": 3.113
 },
 "download": {
  "bandwidth": 116268591,
  "bytes": 431220090,
  "elapsed": 3713,
  "latency": {
   "iqm": 13.493,
   "low": 2.993,
   "high": 18.036,
   "jitter": 1.162
  }
 },
 "upload": {
  "bandwidth": 96137539,
  "bytes": 728061587,
  "elapsed": 7603,
  "latency": {
   "iqm": 7.752,
   "low": 3.045,
   "high": 17.122,
   "jitter": 1.827
  }
 },
 "packetLoss": 29.333333333333332,
 "isp": "So-net",
 "interface": {
  "internalIp": "10.42.0.78",
  "name": "eth0",
  "macAddr": "CE:4E:##:##:##:##",
  "isVpn": false,
  "externalIp": "110.67.###.###"
 },
 "server": {
  "id": 21569,
  "host": "jp.as.speedtest.i3d.net",
  "port": 8080,
  "name": "i3D.net",
  "location": "Tokyo",
  "country": "Japan",
  "ip": "103.194.167.213"
 },
 "result": {
  "id": "63ebd91b-5b4e-434b-b2f2-cc8e062a21cd",
  "url": "https://www.speedtest.net/result/c/63ebd91b-5b4e-434b-b2f2-cc8e062a21cd",
  "persisted": true
 }
}
```

**Comment by alexjustesen** [comment]
Do you have anything else running at the top of the hour? Just for debugging purposes change your schedule to 5min after the hour and let me know how that goes.

**Comment by Daiyamund** [comment]
I do have around 10 other services up on the same server, it never even crossed my mind that something else could eat half the bandwidth. In fact, it might even be somewhere else in the network...
Well, I've scheduled the test to run every 10 min, and you are absolutely right! The speed is only low at the top of the hour!
Thank you!
![NVIDIA Share_2023-03-10_11-51-21](https://user-images.githubusercontent.com/3599618/224211036-c75a58d9-f5c4-495f-a55c-2c19e81f7ea3.png)

**Comment by alexjustesen** [comment]
Yeah I'd say something else is eating up the bandwidth somewhere else on the network for sure. 

Going to close this out. Feel free to comment if you find otherwise.
