### ISSUE TITLE
[Feature Request] Add read-only switch to allow for external access without auth

### ISSUE THREAD

**Issue by jd3shaw** [alexjustesen/speedtest-tracker#46]
Describe the feature
It would be great if it were possible to configure this docker image locally, then add a switch into the Docker env to disable all the configuration options. Then it should be possible to allow external access without worrying about authentication. Just to monitor or show internet speed over time.

Additional context
I'd like to be able to share a link to the speedtest tracker page and allow others to view the results without authentication. If they are authenticated (I assume) they will be able to change the settings, which is not what I want. This would be handy when showing ISP of significant speed fluctuations/discrepancies.

**Comment by spcqike** [comment]
Maybe one could generate something like this to share it 
https://librespeed.org/results/?id=1ie9v7h

Or also have a API like call to get a JSON of the last or the ten last results?

**Comment by jd3shaw** [comment]
Doing a normal speed test you get a result ID/URL (example https://www.speedtest.net/result/13661739020). If these could be stored in the All Tests table that would be useful as well (maybe the OOKLA_EULA_GDPR setting affects this). But being able to hit a read-only URL externally that is live and will update via schedule, is what my original request is about.
Apologies, I'm still using the abandoned version of this project (https://github.com/henrywhitaker3/Speedtest-Tracker) as I need the history for an issue my ISP is currently investigating.

**Comment by alexjustesen** [comment]
I'll be tracking this feature against issue #45
