### ISSUE TITLE
Added Server with same name not adding data to InfluxDB

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#469]
After added second server Then no data in InfluxDB added when this server checks
was only 21197 , added 13956 .

![image](https://user-images.githubusercontent.com/28630321/224471294-4a69e985-aed8-4a63-b007-c0c098fe1258.png)

![image](https://user-images.githubusercontent.com/28630321/224471939-24528f79-a40f-42cc-a5ac-d687e95655f1.png)

Using latest version in Unraid (linux x64)

**Comment by masterwishx** [comment]
When added another server with different name its OK.
![image](https://user-images.githubusercontent.com/28630321/224472197-ef1f4149-a50a-4aab-a217-8ec4159fb0cd.png)

**Comment by masterwishx** [comment]
but host "speed2.hot.net.il" data for same name 'HOT' is missing in influxDB

**Comment by alexjustesen** [comment]
I suspect it's something with InfluxDB and not Speedtest Tracker. Speedtest Tracker doesn't care what the server attributes are, it just sends the data payload to InfluxDB.

**Comment by masterwishx** [comment]
> just sends the data payload to InfluxDB
i think you right , after checked file:
https://github.com/alexjustesen/speedtest-tracker/blob/f65d35eccd65eebfa15c3edd5a4cff7f93e8f355/app/Jobs/SendDataToInfluxDbV2.php

but no idea what problem in influxDB maybe for it ...

**Comment by alexjustesen** [comment]
Going to close this out as it seems to be an InfluxDb issue

**Comment by masterwishx** [comment]
> Going to close this out as it seems to be an InfluxDb issue

OK, will be good to know if someone using export to influxDB with same name servers have this issue also ?!?

**Comment by masterwishx** [comment]
@alexjustesen 

i think i have error on this check when second server with same name run :

![image](https://user-images.githubusercontent.com/28630321/224712270-e113a4a3-db66-4cb8-9d3d-24b1b5d16f7e.png)
![image](https://user-images.githubusercontent.com/28630321/224712639-1f077bfd-e474-4f5e-8057-1710281ee01c.png)

**Comment by masterwishx** [comment]
i think this server (13956 - HOT) check, somehow dont include key "packetLoss" so becose of it ,dont write to influxdb,
then when 1st server (  21197 - HOT)check return i have next error :

![image](https://user-images.githubusercontent.com/28630321/224715431-96d47242-ff15-48ca-8b1f-692bc22f6f3d.png)

but all checks i have in speedtest tracker available
