### ISSUE TITLE
Add support for Pushover, Prowl notification services 

### ISSUE THREAD

**Issue by nodecentral** [alexjustesen/speedtest-tracker#470]
Hi

Huge thanks for the work you do on this, it’s great !!

**Is your feature request related to a problem? Please describe.**
I’d like to see other notification services added, I use pushover and Prowl, and would love to get alerts via either of them when certain thresholds are met

**Describe the solution you'd like**
First off support for more notification providers Pushover specifically, but Prowl would be good too.
Secondly have the ability to define more rules/triggers/trends for when a notification should be sent, e.g when speed is below or above a specific amount, or within a range, or when a particular trend has been met e.g 4 consecutive speed tests below x  (to make it easier make these template notifications and just choose the provider you want to use)

**Comment by alexjustesen** [comment]
Thanks! I'm tracking all notification services in #40 so going to close this now that it's linked.
