### ISSUE TITLE
Speed test results v 0.11.9 for speeds above 1Gpbs

### ISSUE THREAD

**Issue by horus1963** [alexjustesen/speedtest-tracker#479]
After updating to 0.11.9 now the tracker reports my speeds as 2 Mbps instead of 2.35 Gbps or 2350 Mbps.
![Dashboard - Speedtest Tracker](https://user-images.githubusercontent.com/11258233/224710130-c00add95-a185-4163-8417-c52f75948534.png)

**Comment by Magelo** [comment]
Same behavior here too.

![image](https://user-images.githubusercontent.com/10362303/224763121-3d841729-ee8e-4fda-9421-a83cfccbe8df.png)
![image](https://user-images.githubusercontent.com/10362303/224763147-8c6a837e-a135-4699-be48-2c09c11172fc.png)

compared to :

![image](https://user-images.githubusercontent.com/10362303/224763416-b6d9ffca-0aaa-4ba3-88fd-7f6ea3e1f403.png)
