### ISSUE TITLE
Laravel Automations Failure

### ISSUE THREAD

**Issue by Kaotic3** [alexjustesen/speedtest-tracker#481]
This is the message I am getting and the container is restarting due to this:

`warning: unable to start service laravel-automations:`

Looking at the logs, it also says this:

`[2023-03-13 13:29:56] production.ERROR: The /var/www/html/bootstrap/cache directory must be present and writable. {"exception":"[object] (Exception(code: 0): The /var/www/html/bootstrap/cache directory must be present and writable. at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:178)
`

My apologies, I have written and re-written this like 30 times as I have delved deeper and deeper into the error messaging available.

I am running Ubuntu 20.04 in a virtual machine.

I am using docker compose.  I used the mariaDB example provided, I changed the config location and this was the only change I made.  I checked my PUID etc that was fine.  The mariaDB is running fine, but the container for the speedtest-tracker restarts constantly.

Any help would be great.

**Comment by zvarg** [comment]
Try to wait more time to let container started. 

See this [answer](https://github.com/alexjustesen/speedtest-tracker/discussions/474#discussioncomment-5282918)

Possible [duplicate ](https://github.com/alexjustesen/speedtest-tracker/discussions/474)

What is the hardware under your virtual machine. Try to give it more ram and/or cpu and try again.

**Comment by Kaotic3** [comment]
It is getting past that stage of "Attaching to..." 

` s6-rc: warning: unable to start service laravel-automations: command exited 1`

In a loop that includes 

`prog: fatal: stopping container`

I spun up an entirely new VM to try it out, gave it an extra 4gb of Memory totalling 8gb now 2 core 8 threads.

I noticed that someone in your linked threads, dropped "latest" from the compose and went with a particular numbered version, I may try this...

**Comment by Kaotic3** [comment]
Just for anyone else, removed "latest" from the Compose file seems to have fixed whatever that problem was...

**Comment by alexjustesen** [comment]
Going to close this out as your issue as been solved. I'm looking into why `latest` tag is causing issues lately.

**Comment by Kaotic3** [comment]
I am not sure the info is helpful, but once I had it up and running - it had been performing tests since 5pm - every hour, so I have like 4 hours of tests - which is only a short while after I set up a new VM for it - so it was kinda working but just wouldn't finalise?
