### ISSUE TITLE
When Undefined array key "packetLoss"  then no data sended to InfluxDB

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#487]
to continue of closed [Added Server with same name not adding data to InfluxDB #469](https://github.com/alexjustesen/speedtest-tracker/issues/469)

When Server dont has packetLoss then have next error and NO data sended to InfluxDB : 

production.ERROR: Undefined array key "packetLoss" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"packetLoss\" at /var/www/html/app/Models/Result.php:93)

![image](https://user-images.githubusercontent.com/28630321/224919240-5a510b1e-87ee-4d03-8dbd-7594698353a0.png)
![image](https://user-images.githubusercontent.com/28630321/224920029-bd1cb2d6-9803-4d63-b71d-1ab556e6a14c.png)

**Comment by alexjustesen** [comment]
fixed in #486
