### ISSUE TITLE
influxDB2 not receiving any data from speedtest-tracker docker

### ISSUE THREAD

**Issue by PedroBuffon** [alexjustesen/speedtest-tracker#492]
i have the speedtest-tracker docker with network_mode: bridge, so as the infludb and grafana.

influxdb and grafana can talk to each other, but the speedtest-tracker docker can't send any data to influxDB, i tried searching a fix on the issues page but did not found any.

i also use cloudflare tunnel to expose the speedtest-tracker and influxdb but the IPs i use on the internal config are from the local network

can anyone help?

This is my compose config for speedtest-tracker:

services:
    speedtest-tracker:
        image: ghcr.io/alexjustesen/speedtest-tracker:latest
        container_name: speedtest-tracker
        ports:
            - 8765:443
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=pgsql
            - DB_HOST=10.0.0.2
            - DB_PORT=5432
            - DB_DATABASE=speedtest
            - DB_USERNAME=speedtest
            - DB_PASSWORD=speedtest
        volumes:
            - /docker/speedtest-tracker/data:/config
        restart: unless-stopped
        network_mode: bridge

And my influxDB:

services:
   influxdb:
     image: influxdb:latest
     container_name: influxdb
     restart: always
     ports:
       - 8086:8086
     volumes:
       - /docker/InfluxDB/influxdb-data:/var/lib/influxdb2
       - /docker/InfluxDB/influxdb2-data:/etc/influxdb2
     network_mode: bridge

**Comment by PedroBuffon** [comment]
Update:
I went to my pgAdmin4 to see if there was some log about the influxDB and in the failed_jobs there were a lot of results.

On the exeption column there is a message "ErrorException: Undefined array key "packetLoss" in /var/www/html/app/Models/Result.php:93 ..."

don't know if it will help.

**Comment by alexjustesen** [comment]
fixed in #486

**Comment by PedroBuffon** [comment]
Sadly, i tried the fixes discussed on #486 but it didn't work, how can i fix it?

**Comment by alexjustesen** [comment]
> Sadly, i tried the fixes discussed on #486 but it didn't work, how can i fix it?

Not released yet 😉, coming in `v0.11.11`
