### ISSUE TITLE
Telegram notification cut off information

### ISSUE THREAD

**Issue by garanda21** [alexjustesen/speedtest-tracker#497]
**Describe the bug**
After the latest update and due to the extra lines on the template, telegram notification doesn't shows the entire speedtest info, and force you to open the app. 

**To Reproduce**
Just active telegram notification. 

**Expected behavior**
I think that the main purpose of the notification on telegram is to see on a glance all the information, without the need to interact with your phone. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9530250/225579390-ffa91a90-6d64-4361-9e9b-a01b7a0073e2.jpeg)

**Additional context**
No additional context.

**Comment by alexjustesen** [comment]
I noticed this as well and did this intentionally to get more info into the notification. Closing this issue for now but will keep on the radar to clean up later on.
