### ISSUE TITLE
CPU Usage - Synology Docker

### ISSUE THREAD

**Issue by Lockie85** [alexjustesen/speedtest-tracker#499]
Hey,

I've setup this application on my Synology NAS 1019+ running on Docker and while everything appears to be functioning correctly I am noticing very high CPU Usage when accessing the application via a browser.

Leaving a browser open and on the application webpage, the containers CPU usage will be continuous, jumping between 10% and 50%. Which seems a little odd for just sitting on the dashboard page.

As soon as I close the browser and am now longer on the dashboard. The containers CPU Usage drops to nearly zero.

This doesn't feel like expected behaviour, does anyone else have this issue?

**Comment by alexjustesen** [comment]
It _might_ be the polling the system does every 5s on the dashboard. This is a little high but if I remember correctly the DS1019+ didn't have a very powerful CPU. I see spikes on my DS920+ but not as high as 50%, more like 30-35% and 50+ when running a speedtest.
