### ISSUE TITLE
Sometimes works, sometimes doesn't. "Could not retrieve or read configuration" [BUG]

### ISSUE THREAD

**Issue by mptpro** [alexjustesen/speedtest-tracker#507]
**Describe the bug**
Sometimes works, sometimes doesn't. See screenshot.

I get the error `"Could not retrieve or read configuration"`

I'm running STT in a Docker container, on a Pop_OS machine. 
Laravel v9.52.4
PHP v8.1.16
Filament v2.17.16
Speedtest Tracker v0.11.11

I've search for other similar errors but none that seem to solve my problem.

![ksnip_20230318-210934](https://user-images.githubusercontent.com/40655233/226153510-72c53a98-4067-427d-9953-386bc690a7f2.png)
![ksnip_20230318-210918](https://user-images.githubusercontent.com/40655233/226153516-f1435dba-f539-49bc-9b6e-9a766135653e.png)

**Comment by MarvvanPal** [comment]
Hi @mptpro , I think this issue is already covered in #389 .

**Comment by chr-le** [comment]
Is it possible, that this issue depends on an IPv6-dual-stack installation?
I had about 30 % errors in the dual-stack environment.
Now, I moved the container to a pur IPv4-network and have 0 % errors after 6 attempts ...

**Comment by alexjustesen** [comment]
Closing as duplicate, this error is when the speedtest CLI can't reach the intended speedtest server.
