### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by Sommerbo** [alexjustesen/speedtest-tracker#511]
**Is your feature request related to a problem? Please describe.**
If I want to share my connectivity data with a third person I don't want them to able to alter anything. so a "view only" user class would be good.

**Describe the solution you'd like**
Users are already implemented, what is needed is a user level/role field in the database to only show dashboard and results. 

**Additional context**
This is way down in the prioritization list, it was an idea that popped into my head. 
And as always, I leave it to Alex to decide if/when it will be implemented.

**Comment by alexjustesen** [comment]
Updated the title to reflect the ask, will introduce user roles in a future release. High level tasks...

1. Have 3 levels of users `admin`, `user`, and `visitor`
2. Prevent the deletion of the `admin` user if no other admin users exist
3. `admin` users can do everything
4. `user` users can do some basic things
5. `visitor` users can only read results and view the dashboard

**Comment by Sommerbo** [comment]
A much more structured and eloquent statement of my suggestion. 
Looks very good, I don't have any notes.
