### ISSUE TITLE
Setting "Cron Expression" through Docker environment variables

### ISSUE THREAD

**Issue by armond1978** [alexjustesen/speedtest-tracker#512]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to set the cron expression through docker and I have to go to the web console to change / set it.

**Describe the solution you'd like**
I would like to be able to set a Docker env variable like the following line:
`SCHEDULE=0 15 * * *`

**Comment by alexjustesen** [comment]
Thanks for the suggestion but running scheduled tests are through the UI

**Comment by armond1978** [comment]
@alexjustesen I understand that I can already set/change this option through the web UI. But my request was to be able to initiate it from Docker environment variable side as well.

The end goal here is to have a fully configurable app through docker (100% automated) so that admins don't go through the UI after installation to complete the setup. Imagine you have tens of apps in your home lab and for each one of them you have to do through their UI to complete the setup! I'd strongly prefer a 100% automated setup so that I can set the parameters once in my docker installation scripts and I don't think about them in my future installations.
