### ISSUE TITLE
Include public IP in results + add option to filter per public IP

### ISSUE THREAD

**Issue by shalak** [alexjustesen/speedtest-tracker#513]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but missing usecase - helpful if someone has multiple uplinks. In general, when my main ISP has problems, my router will fallback to LTE, which will cause speedtracker results to become polluted with data that's unrelated to the main ISP and I have no way of excluding those results in my general metrics.

**Describe the solution you'd like**
Add a possibility to filter the test results per public IP.

**Additional context**
AFAIK, speedtest.net replies with the public IP we're testing from, so the data is there to be used.

**Comment by alexjustesen** [comment]
Nice suggestion, something I'll add in a future release

**Comment by upD8R** [comment]
Hi there, I would also like to see the public IP as a column in the results page. Background: My ISP useses different ranges, which seem to have different routings and one of teh ranges had recently an issue. So you would only see this in a speedtest results triggered from a specific IP range.

Thanks!

**Comment by luckman212** [comment]
I have a related idea, not sure if it deserves it's own PR but:

I have a backup internet connection that runs over a metered 4G SIM card. After 20GB is used up, the carrier starts billing me for each additional GB of usage. This can add up fairly quickly with speedtests running every 30 minutes.

It would be great if there was a field in the UI where we could put in e.g 166.141.144.0/22 and it would skip the test if the public IP falls inside that subnet.
