### ISSUE TITLE
Serve on a custom port

### ISSUE THREAD

**Issue by karan** [alexjustesen/speedtest-tracker#519]
**Is your feature request related to a problem? Please describe.**

I'm setting up speedtest within a network of a VPN (`--net=container:vpn`). So my ports are exposed through the VPN container as opposed to the speedtest container. This means that the VPN container needs a mapping for 443 and/or 80 for speedtest. However this is quite limiting since I might have multiple applications routed through the VPN that might only use 80/443.

**Describe the solution you'd like**
Allow a custom HTTP(s) port for the speedtest server.

**Additional context**
This can either be a setting in the GUI (first install uses 80 or 443, then user can customize from the GUI). If possible, an env var override would be better (so I can set it in my docker compose).

**Comment by alexjustesen** [comment]
Hello, ports 80/443 are required internally by nginx. You can however change the mapped ports on the image.
