### ISSUE TITLE
docker: failed to register layer: unlinkat /usr/share/doc/adduser/examples/adduser.local.conf.examples: invalid argument.

### ISSUE THREAD

**Issue by kssathish6** [alexjustesen/speedtest-tracker#526]
**Describe the bug**
While through docker, installation stops by throwing this error

**To Reproduce**

**Expected behavior**
clean installation

**Environment (please complete the following information):**
Ubuntu
-  Architecture: [e.g. arm64, amd64]
 - Version [e.g. v1]

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by alexjustesen** [comment]
I'm going to need some more context like screenshots, if you're using Docker or Docker Composer and the steps you took to install the container and get it running.

Also make sure to reference the [docs ](https://docs.speedtest-tracker.dev/getting-started/installation)

**Comment by alexjustesen** [comment]
Closing as there also a Discussion opened by the author.
