### ISSUE TITLE
SSL certs generated every time the container starts as the contents of /etc/ssl/web are tied to the lifecycle of the container

### ISSUE THREAD

**Issue by repcsi** [alexjustesen/speedtest-tracker#531]
Hi Alex,

I just recently found this project and I moved to it from an older speedtest solution and I like it very much. I'm also interested in learning about laravel so I started digging into it.

The main reason for this issue is that we lose the contents of /etc/ssl/web every time when we stop the container(s) related to speedtest-tracker.

**Describe the bug**
At every start the ssl certs are regenerated, and this can be seen in the logs:
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
🏃‍♂️ An SSL key was not detected, so I'll generate a self-signed SSL certificate pair for you...

After the new certs are generated you need to add them as an exception in the browser as they are self-signed.
This might not be a problem if you keep your system running for longer periods of time but I like to keep up with security and feature updates so at least once every month I reboot. 

**To Reproduce**
1. Startup your container
2. Open the page on https and accept the cert exception to be able to browse the page
3. Stop your container
4. Open the same page again over https, and see that you need to accept the https exception again as the certificates are new now.

**Expected behavior**
After I accept the exception I would expect it to be working as long as the certs expire or the application generates them again.

The issue itself is excepted as is, but easily solvable if we mount /etc/ssl/web in docker-compose and make it persistent. The certificate is generated for a year, so if it expires we can delete them restart the container and we will get brand new ones good for another year again!

**Environment (please complete the following information):**
Running in docker with mariadb:10 in another container.
 - OS: CentOS7
-  Architecture: x86_64
 - Browser Firefox
 - Version 111.0.1

**Screenshots**
I don't think this is necessary.

**Logs**
Before: 
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
🏃‍♂️ An SSL key was not detected, so I'll generate a self-signed SSL certificate pair for you...

After:
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...

🐇  Configuring Speedtest Tracker...

🔒  Fixing app path file permissions...
✅  Permissions fixed.

And uses the old already generated certs! Exception works now after the container stop/start!

**Additional context**
What I did is I added another volume bind entry into my docker-compose file:
volumes:
            - '/path/to/directory/cert:/etc/ssl/web'

If this is a viable solution and you agree with it I can add the modifications to speedtest-tracker-docs so you can work on more important stuff.

**Comment by alexdelprete** [comment]
This was already brought to the dev attention 6 months ago: https://github.com/alexjustesen/speedtest-tracker/issues/56#issuecomment-1287208666

I think @alexjustesen took note of it.

**Comment by repcsi** [comment]
Yeah I see now that you made a comment about this, I did a quick search under the issues before opening this one, but the title and the first entry did not seem relevant to this exact issue. After the easter holiday I will try to add a PR to the docs if that's fine, I think it would be nice if the docs would say something about these installation cases that came up already multiple times in the issues.

**Comment by alexdelprete** [comment]
> @repcsi can you verify if these directions work for? If so I'll add it to the docs. These are from the base image btw.

this has been commented and tested a while ago, I also linked the serversideup docs: https://github.com/alexjustesen/speedtest-tracker/issues/56#issuecomment-1287208666

**Comment by repcsi** [comment]
Hey all, 
Yes it works, that's why I made https://github.com/alexjustesen/speedtest-tracker-docs/pull/12 and now the docs say that if you want to keep your certs, even the self signed ones between stops/starts you need to add that line. 
Tested with these versions through the typical pull update and no issues:
v0.11.12
v0.11.13
v0.11.14
v0.11.15

The relevant part of the doc is here:
https://docs.speedtest-tracker.dev/getting-started/installation#install-with-docker

**Comment by alexdelprete** [comment]
Thanks a lot. I think it's enough. You can close it.

**Comment by repcsi** [comment]
Thank you all for this project, happy to be a user :)
