### ISSUE TITLE
Health update && slow releases for a little bit more

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#537]
Quick update...

I'm sure many of you have noticed the slowdown in releases over the last month and a half. At the end of February I fracture my back which I'm sure you can imagine makes sitting pretty uncomfortable. Good news is I'm healing up well and will be starting physical therapy soon. 

Bad news is while I'm recovering and going through rehabilitation please expect the updates to remain pretty slow. I'm sure as I recover I'll get more comfortable being at my desk and will pick up the update cadence again, just can't tell you when that'll be.

In the meantime keep the issues coming and once I return to full health I'll be back at the priorities of the instability of the Docker container and improving the scheduled task execution.

**Comment by kimpenhaus** [comment]
get well soon 🤞🏼

**Comment by Sommerbo** [comment]
Good luck with physical therapy, it won't be pleasant.

**Comment by ShlomiD83** [comment]
get well!
