### ISSUE TITLE
Support for Fast.com

### ISSUE THREAD

**Issue by micaharies** [alexjustesen/speedtest-tracker#538]
**Is your feature request related to a problem? Please describe.**
Not necessarily, my area doesn't have any speedtest.net servers that test higher than 650-700mbps. Fast.com will almost always test higher for me, and on a gigabit connection the data isn't super useful.

**Describe the solution you'd like**
An ability to use Fast.com servers for the tool. 

**Additional context**
There is a cli tool for fast.com, [sindresorhus' fast-cli](https://github.com/sindresorhus/fast-cli).

**Comment by alexjustesen** [comment]
Thanks for the suggestion, at this time I wont be support non-official SDKs as there is a risk those will just stop working randomly.
