### ISSUE TITLE
Installation returning "production.ERROR: Could not create setting general.auth_enabled because it already exists"

### ISSUE THREAD

**Issue by WingZeroh** [alexjustesen/speedtest-tracker#539]
**Describe the bug**
When installing through Docker Compose (SQLite), the console is returning "production.ERROR: Could not create setting general.auth_enabled because it already exists.

I am unable to initialize the speed tracking application.

**To Reproduce**
1. Install speedtest-tracker using Docker Compose ([YAML](https://pastebin.com/raw/PUw6wRRH))

**Expected behavior**
Docker should initialize and be accessible using the assigned IP and mapped port(s).

**Environment (please complete the following information):**
 - OS: [Linux DSM-01 4.4.180+]
-  Architecture: [Geminilake]
 - Browser [N/A]
 - Version [N/A]

**Screenshots**
N/A

**Logs**
Docker log extract [here](https://pastebin.com/raw/itbCAXbS)

**Additional context**
I added the ports to my firewall allow rule.

**Comment by alexjustesen** [comment]
@WingZeroh stop the container and delete the volume associate with it and try starting it again.
