### ISSUE TITLE
Database migration fails

### ISSUE THREAD

**Issue by Toaaa** [alexjustesen/speedtest-tracker#542]
**Describe the bug**
Cannot migrate Database from old version to new one

**To Reproduce**
Step 1. Get a Database from Speedtest-Tracker [v0.11.2](https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.2)
Step 2. Try to migrate the Table `results` to a Database for Speedtest-Tracker [v0.11.12](https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.12)
Step 3. Now try to refresh the Speedtest-Tracker Page and you will get a `500 Server Error`
Step 4. Cry

**Expected behavior**
I expected that the migration would work and I could therefore migrate my old database to the new version. Unfortunately, I can only migrate the `failed_jobs` and `notifications` tables and for the `results` table I got the following error: [https://ptero.co/raw/umofupokyk](https://ptero.co/raw/umofupokyk)

**Environment (please complete the following information):**
 - OS: Docker (latest image)
 - Version [v0.11.12](https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.12)

**Conclusion**
I don't know if backwards compatibility is a thing, but it would be if it was and if it got fixed

**Comment by alexjustesen** [comment]
@Toaaa are you trying to migrate from the deprecated version?

**Comment by Toaaa** [comment]
deprecated version? Im trying to migrate from this version: https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.2 to this: https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.12
Is v0.11.2 deprecated?

**Comment by alexjustesen** [comment]
So your error wasn't the migration but the widget trying to decode some json. Can you try again with the latest version and let me know if you get any issues?
