### ISSUE TITLE
Doesn't work when VPN is on

### ISSUE THREAD

**Issue by mptpro** [alexjustesen/speedtest-tracker#564]
**Describe the bug**
I'm running this in Docker Container. I have a VPN (PIA) that protects the entire machine. When I have the VPN turn OFF, then speedtest works fine. When the VPN is turned on then it doesn't and I get the error...

`Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}`

**Comment by alexjustesen** [comment]
Try restarting the image, I'm willing to be the root cause of this is something with Docker networking. I was able to run the Speedtest CLI on and off VPN (PIA also and Nord)

**Comment by alexjustesen** [comment]
If it helps my VPN was at my router level not on the machine running my containers

**Comment by alexjustesen** [comment]
This is likely an issue with networking / Speedtest CLI trying to locate a server. I recommend specifying servers if you want to route them though a VPN.
