### ISSUE TITLE
Denied error when pulling image

### ISSUE THREAD

**Issue by mlcampbe** [alexjustesen/speedtest-tracker#566]
Just trying to pull the image to test it out and it is failing even thought I am logged in.

docker pull ghcr.io/alexjustesen/speedtest-tracker:latest
Error response from daemon: Head "https://ghcr.io/v2/alexjustesen/speedtest-tracker/manifests/latest": denied: denied

**Comment by alexjustesen** [comment]
I don't think that's something with the registry specifically but you can also try the Docker Hub if GitHub container registry is having issues. 

https://hub.docker.com/repository/docker/ajustesen/speedtest-tracker
