### ISSUE TITLE
Documentation on non-Docker install

### ISSUE THREAD

**Issue by s3m1s0n1c** [alexjustesen/speedtest-tracker#568]
Great Project...

Is there any install guides us non-docker users?

Thanks
Sonic

**Comment by Itay1787** [comment]
+1

**Comment by alexdelprete** [comment]
Duplicate of #65

**Comment by alexjustesen** [comment]
> Duplicate of #20 and #65

True, at the moment unless you're familiar with running a [Laravel](https://laravel.com/docs/9.x/deployment) application bare metal I wouldn't suggest it.
