### ISSUE TITLE
Telegram notification [returning 500 Server Error]

### ISSUE THREAD

**Issue by sastromo** [alexjustesen/speedtest-tracker#575]
**Is your feature request related to a problem? Please describe.**
I was trying to get the telegram notification to work, but it was always returning a 500 Server Error…
I had the correct token in the correct ".env" variable plus the chat ID, so what was going on?
Well, I mistakenly added the "**_BOT chat ID_**" rather than "**_MY chat ID_**".. 
`Bots can't send messages to bots`, ergo the 500 Server Error.

**Describe the solution you'd like**
Perhaps a clear notification about which "**_chat ID_**" should be added as the recipient? 
Or not, maybe I was the problem 😅  

Thanks

**Comment by alexjustesen** [comment]
Not _really_ a bug but maybe somewhere where the docs could be clarified. Did you follow these directions and got hung up? https://docs.speedtest-tracker.dev/settings/notifications/telegram#setting-up-telegram

**Comment by alexjustesen** [comment]
done
