### ISSUE TITLE
v.0.11.14 - every test runs 3 times instead of once

### ISSUE THREAD

**Issue by ShlomiD83** [alexjustesen/speedtest-tracker#582]
Hi.
after upgrading to v0.11.14 every test runs automatically 3 times.
v0.11.14 also breaks Telegram notifications.

reverting to v0.11.13 solves both issues.

Please assist.

**Comment by ShlomiD83** [comment]
where can I find the logs you need?
what information do you need?

**Comment by ShlomiD83** [comment]
![image](https://user-images.githubusercontent.com/17053215/236817749-e44bc6c7-03e3-40e8-b840-99ca00f147a6.png)
every test ran 3 times except 663.

**Comment by alexdelprete** [comment]
> after upgrading to v0.11.14 every test runs automatically 3 times.
> v0.11.14 also breaks Telegram notifications.

1. Tests are being run correctly here, not duplicated.
2. Confirmed: there's a problem with telegram notifications. I'm not receiving notifications for thresholds, but if I click on "Test Telegram Notification" I receive it. I guess it's the trigger logic that's not working.

**Comment by Adelscott** [comment]
Same here, notification test with button "Test telegram channel" works, but no more notifications on success or threshold.
I'm going back to v.0.11.13 for now

**Comment by alexjustesen** [comment]
Just a heads up, 3x happens on jobs because that's the amount of tries. Probably need to adjust that based on what kind of failure it is.

**Comment by ShlomiD83** [comment]
@alexjustesen after updating to v0.11.15 I get telegram notifications again & every test runs once as expected.

**Comment by alexjustesen** [comment]
Thanks for confirming!
