### ISSUE TITLE
Telegram Notification doesnt not work with version v0.11.14

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#585]
With the latest update to last version 

```
Laravel vv10.9.0
PHP v8.1.18
Filament v2.17.36
Speedtest Tracker v0.11.14
```

the notification via Telgram no longer works.  However if I go into the settings and do "test notification" the notification is correctly delivered.  I set the  -e TELEGRAM_BOT_TOKEN=xxxxxxxxxxxxxxxx  in my docker run.
With the previous version everything worked fine
Thanks

**Comment by corasaniti** [comment]
duplicate of this issue, Can be closed when resolved.
[https://github.com/alexjustesen/speedtest-tracker/issues/582](url)

Thanks

**Comment by alexjustesen** [comment]
Insert :urg: meme

**Comment by corasaniti** [comment]
@alexjustesen 
Probably not a Telegram notifications setup problem, because if I press the "Test notification" in setting page, the notification is delivered successfully. I think it's an error of trigger that activates the notifications.
Thanks
