### ISSUE TITLE
[Question] Is this able to run on a Raspberry Pi (4)?

### ISSUE THREAD

**Issue by Inkertus** [alexjustesen/speedtest-tracker#590]
I keep getting a exec format error when trying to set up and run this project, so I suspect it's related to not being formatted for the Pi.
I also was not able to find anything in the documentation related to the Raspberry Pi.
I did manage to get the ookla speedtest cli running on the Pi and it did get the expected speeds (well above what the browser did), so that aspect works.

Is this able to run on an RPi, and if not, is that a dev path you are interested in in the future?

**Comment by M0UL** [comment]
you can use docker a on pi just fine. i have done that before.

**Comment by alexjustesen** [comment]
Yep, Docker is the way to go. Bare metal installs are possible but without and understanding of Laravel I wouldn't recommend it.
