### ISSUE TITLE
chart timeframe - add longer periods

### ISSUE THREAD

**Issue by thezoggy** [alexjustesen/speedtest-tracker#599]
**Is your feature request related to a problem? Please describe.**
Right now you can only select 24hr/week/month on the chart dropdown. 

Would like to see longer periods such as: 3m/6m/1y/all time

**Describe the solution you'd like**
Add additional time presets to the dropdown

**Additional context**
none

**Comment by alexjustesen** [comment]
Id strongly suggest using something like InfluxDB but something I can add for sure

**Comment by alexjustesen** [comment]
Linking to #448
