### ISSUE TITLE
Alpha 8: scheduler/crontab not working

### ISSUE THREAD

**Issue by alexdelprete** [alexjustesen/speedtest-tracker#60]
I changed the cron expression from 60m to to: `schedule: '*/1 * * * *'` because I wanted to check if latest version tests were working, but no tests have been queued.

The results table in the db is empty.

**Comment by alexdelprete** [comment]
Upgraded to Alpha 8: scheduler not working. Manual tests are ok.

**Comment by alexjustesen** [comment]
Can you check your data directory and if there is a `laravel.log` file? If there is open it up and see if you can isolate a failure. Else you can delete it and adjust the schedule to run again. I'm not having any issues with the schedule.

**Comment by alexdelprete** [comment]
I only mapped a /config directory, should I map /app too in the compose file?

**Comment by alexdelprete** [comment]
Ok, in the container there's a symlink, it should be in the /config dir, but I only have the .env file.

`laravel.log -> /config/laravel.log`

**Comment by alexdelprete** [comment]
Where can I check if the schedule has been effectively read correctly?

It's not using crontab internally:

```
root@07b8b151b113:/config# crontab -l    
* * * * * webuser cd /var/www/html && php artisan schedule:run >> /dev/null 2>&1
root@07b8b151b113:/config# 
```

**Comment by alexjustesen** [comment]
Just kidding, I indeed fucked it... `v0.1.0-alpha.9` coming shortly. Going to grab lunch and let it run for a little.

**Comment by alexjustesen** [comment]
if you run `service cron status` in CLI you'll see it's not running. Good way to test

**Comment by alexdelprete** [comment]
So you were having issues with the schedule too. :)

```
root@07b8b151b113:/config# service cron status
 * cron is not running
```

**Comment by alexjustesen** [comment]
> So you were having issues with the schedule too. :)

Yeah... I didn't realize I was looking at my development environment. I thought I had the built image running
