### ISSUE TITLE
Only do tests when bandwidth usage is under a certain threshold

### ISSUE THREAD

**Issue by d3xt3r01** [alexjustesen/speedtest-tracker#601]
The tests might happen when the bw usage is high. One way would be to only do tests at night when it's low enough, but that wouldn't test when I actually need it.

Would be great if the speedtest checks would be done hourly and the solution would be an additional check. A simple http call to a service which if answered with 200 OK, the test can be done, otherwise skipped or delayed(configurable) by a specified amount of time(configurable).

**Comment by alexdelprete** [comment]
When API will be available, you will be able to automate things. For now, you can only work with the cron scheduler.

> The tests might happen when the bw usage is high. One way would be to only do tests at night when it's low enough, but that wouldn't test when I actually need it.

IMHO, that is a wrong logic: you want to constantly monitor bw, not only when usage is low, when you gather enough data, you'll be able to get a realistic average of the bandwidth and other things.

**Comment by d3xt3r01** [comment]
No, my logic is ok. I want to be able to check the FULL bw when others don't use it. That's what I want to see. Not average .. not other things. Thanks anyway.
