### ISSUE TITLE
speedtest-tracker chooses not the fastest server

### ISSUE THREAD

**Issue by thomasmerz** [alexjustesen/speedtest-tracker#602]
**Describe the bug**
When running your new speedtest-tracker in contrast to old one from [henrywhitaker3](https://github.com/henrywhitaker3/Speedtest-Tracker) I'm getting very poor results:
<img width="930" alt="grafik" src="https://github.com/alexjustesen/speedtest-tracker/assets/18568381/7e0b1f8e-41dd-479c-96a7-8d37c2ae5911">

Ping is good to the chosen one: 47786 (WebseitenDesigner.com)
But speed is lousy:

<img width="379" alt="grafik" src="https://github.com/alexjustesen/speedtest-tracker/assets/18568381/7053aff7-5bdd-484a-8210-de768bb9ab7a">

Vs. old speedtest with realistic results:
<img width="1270" alt="grafik" src="https://github.com/alexjustesen/speedtest-tracker/assets/18568381/425bd760-a96e-4411-af8d-cecfbf591cdf">

**Expected behavior**
Speedtest-tracker should choose wisely the fastest speedtest-server.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
-  Architecture: amd64
 - Version:
```
    Laravel v10.9.0
    PHP v8.1.18
    Filament v2.17.38
    Speedtest Tracker v0.11.15
```

**Screenshots**
See above.

**Logs**
No errors occurred.

**Comment by alexdelprete** [comment]
ST doesn't choose the server: if you don't configure the servers list to test (highly recommended), it simply calls speedtest-cli (by OOKLA) that automatically chooses the server. You can test yourself running speedtest-cli from the container's shell.

**Comment by alexjustesen** [comment]
Correct the cli doesn't choose the fastest just the closest or quickest to respond. 

Definitely recommend specifying your preferred server.
