### ISSUE TITLE
Make Results zoomable without vertical scrolling

### ISSUE THREAD

**Issue by thomasmerz** [alexjustesen/speedtest-tracker#603]
**Feature-Request**
I'm always frustrated when having a look into "Results" and can't see all columns when zooming (out) as you can see on my screenshot:

<img width="873" alt="grafik" src="https://github.com/alexjustesen/speedtest-tracker/assets/18568381/f28ae66c-b0aa-4e6e-810b-a309d870e640">

**Describe the solution you'd like**
Users may want "results" to be zoomable without vertical scrolling to benefit from zooming out to see all columns at one glance.

**Comment by alexjustesen** [comment]
I'm not sure "zoom" is the right word but I can enable wider pages in the UI. I'll noodle on it.

**Comment by thomasmerz** [comment]
I was thinking about "zooming out", not "zooming in". So I think you understand my FR in general 👍🏼 It would really be great if page width would adapt to i.e. 90-100% instead of a fixed size of n pixels.

**Comment by alexjustesen** [comment]
Under "General" settings you can change the content width to "Full". 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/d34b7f37-4311-45b8-90ca-370dc61416f9)
