### ISSUE TITLE
Allow custom server ID

### ISSUE THREAD

**Issue by crazyuploader** [alexjustesen/speedtest-tracker#605]
**Describe the bug**
While searching for a custom server ID, getting incorrect results and not able to set the desired server ID other than servers provided by `speedtest --servers` command.

**To Reproduce**
1. Go to General Settings
2. Click on Speedtest server ID
3. Search for a server ID such as **15797**

**Expected behavior**
If the desired server ID is not from default server list, allow custom server ID to do the speedtest, in my case I want to run a speedtest against server ID **15797** which is not visible in `speedtest --servers` list. 

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS
-  Architecture: arm64
 - Browser: Microsoft Edge
 - Speedtest Tracker Version: v0.11.16 

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/49350241/9e6bed13-a8e3-4326-a833-86c73aff1996)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/49350241/9e37a65d-5a84-4009-9e22-01f519e5549b)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/49350241/c9dfe2ec-c13a-42eb-8059-552c7ac3ac67)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/49350241/7c2949c8-c5ed-4383-9f12-23d3301992ba)

**Comment by alexjustesen** [comment]
So this should actually work when adding a custom/manual server ID. Something broke so I'll take a look at it.

**Comment by alexjustesen** [comment]
Fixed when I upgraded Filament a while back. 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/bcc607b0-0a16-4cd8-a1f1-3a975d132037)
