### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by boelle** [alexjustesen/speedtest-tracker#606]
**Describe the bug**
i get a connection refused when i visit the web interface

**which Branch / PHP Version are you using ?**
php8

**Steps to reproduce**
1. My command to build:

docker run -d --name speedtest-tracker --restart unless-stopped     -p 8765:80     -p 9443:443     -e PUID=1000     -e PGID=1000     -v /path/to/directory:/config     -v /path/to/directory/web:/etc/ssl/web     ghcr.io/alexjustesen/speedtest-tracker:latest
456fd2eed9d7e56508b3a3c9a1b1d29a8d83eab5ebc87e24965ccdc72f230d0a

**Expected behavior**
i expected some sort of webinterface

**Screenshots**

![image](https://github.com/sprintcube/docker-compose-lamp/assets/3832239/8a138139-4d78-400d-b686-5081ff98dcfd)

![image](https://github.com/sprintcube/docker-compose-lamp/assets/3832239/750d93dd-a9db-4e3f-a996-8e419c74e74f)

**Desktop (please complete the following information):**
 - OS: win12 (of my pc) server runs OMV
 - Browser [e.g. chrome, safari]: Chrome
 - Docker Version:
```
docker -v
Docker version 23.0.6, build ef23cbc

**Comment by boelle** [comment]
ohh

PUID and PGID, will try and get those

**Comment by NOXITB** [comment]
I have same issue

**Comment by drewstopherlee** [comment]
> I have same issue

Same here

**Comment by alexjustesen** [comment]
So first issue... `/path/to/directory` needs to be a path to somewhere, that's just the example text.

> docker run -d --name speedtest-tracker --restart unless-stopped -p 8765:80 -p 9443:443 -e PUID=1000 -e PGID=1000 -v /path/to/directory:/config -v /path/to/directory/web:/etc/ssl/web ghcr.io/alexjustesen/speedtest-tracker:latest 456fd2eed9d7e56508b3a3c9a1b1d29a8d83eab5ebc87e24965ccdc72f230d0a

For the user you'll need to figure out which user is actually running the container and has access to the docker user group. You can then use that user's PUID and PGID.

I don't run OMV in my lab so I can't speak specifically on it's nuances but those two items should help you get running.

**Comment by boelle** [comment]
For the user there is only one so that is the easy part... Will have a look
at the paths later

søn. 21. maj 2023 14.33 skrev Alex Justesen ***@***.***>:

**Comment by alexjustesen** [comment]
@boelle any luck? I'm triaging issues over the next couple of days to make a plan for next week

**Comment by drewstopherlee** [comment]
Mine was a permissions issue, I changed the UID and GID to my user and the docker group and gave both read/write access to my bind-mounted folders and it spun up.

**Comment by boelle** [comment]
> @boelle any luck? I'm triaging issues over the next couple of days to make a plan for next week

i gave up on it sadly, i got my old python script to work, it seems that running it on other times than on the hour and half past the hour makes it work
