### ISSUE TITLE
Constant CPU Usage and Disk Write

### ISSUE THREAD

**Issue by coanghel** [alexjustesen/speedtest-tracker#617]
**Describe the bug**
Speedtest-Tracker constantly running a process resulting in a small, but non-zero, amount of disk write and cpu usage.

**To Reproduce**
1. Observe disk write and cpu usage of speedtest-tracker container

**Expected behavior**
No disk write and minimal CPU usage when not performing a speed test.

**Environment (please complete the following information):**
 - OS: Ubuntu Jammy
-  Architecture: arm64
 - Browser chrom
 - Version latest

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/9924637/e0d42a1d-a774-4b89-89a2-f720b49a61b2)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/9924637/a54c1ec1-c2a7-48f5-8453-ae8ef91be869)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/9924637/41f55796-3f73-46d5-b565-11c398c34529)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/9924637/b512f2ec-0abd-40f4-957f-9640aa8c1fe0)

**Logs**
[If applicable, check the logs for any error that might of occurred.](https://pastebin.com/xwAiNY0D)

**Additional context**
Observing in htop in the container points the finger to a php script. Speedtest-tracker is configured with an hourly cron and influxdb link

**Comment by luanupe** [comment]
Hi, this issue with the high CPU usage is happening with me too.
According to ProxMox statistics, I did not noticed any issues with the high disk usage, only with the CPU.

Hardware: ProxMox VM - RAM 1024MB, CPU 2 Core 2Ghz
Platform: Docker (on Debian 11.7)

**Comment by SkoricIT** [comment]
I can literally hear the NAS hard drives work when i open the web ui.

**Comment by alexjustesen** [comment]
There is some significant overhead occurring right now while running the task scheduler and queue. I've got those improvements scheduled for v0.16.0 which I'll add this issue to so the testing is done.

**Comment by alexjustesen** [comment]
Also worth noting, the spike on the hour are the speedtests running as a part of your schedule. Ookla's Speedtest CLI uses a lot of resources when running.

**Comment by SkoricIT** [comment]
This is while the web page is open in browser:

![2023-06-08_17-20](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/3d1beeed-430c-4420-81ee-c5846dcfb6a6)

This is a few seconds after closing the browser tab:
![2023-06-08_17-20_1](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/8c374037-c033-4107-ae89-68b047030544)

The CPU usage alone is concerning, but like I said i can hear the hard drives working permanently while the web UI is open. I can NOT hear them work while the speed test is running without the web page being open.

**Comment by alexjustesen** [comment]
> This is while the web page is open in browser:
> 
> ![2023-06-08_17-20](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/3d1beeed-430c-4420-81ee-c5846dcfb6a6)
> 
> This is a few seconds after closing the browser tab:
> ![2023-06-08_17-20_1](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/8c374037-c033-4107-ae89-68b047030544)
> 
> The CPU usage alone is concerning, but like I said i can hear the hard drives working permanently while the web UI is open. I can NOT hear them work while the speed test is running without the web page being open.

It's got to be the polling then... I'll dig

**Comment by SkoricIT** [comment]
@alexjustesen Thank you very much. If I can help in any way, I'm at your disposal.

**Comment by alexjustesen** [comment]
I made some small changes in the release I just tagged, if you wouldn't mind letting me know if this improves CPU usage that'd be awesome.

https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.17

**Comment by SkoricIT** [comment]
I have pulled the newest image and it shows 0.11.17

![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/4af5c627-ec4f-47f9-8cb5-919fa8545b85)

Unfortunately, the symptoms are the same:
![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/7cb8c0fa-5e49-4b72-92f6-190ee0122e55)
(filtered it down to php-fpm)

Funnily enough, if the tab is in the background (because i'm typing in github) the resource usage goes back to zero:

![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/7558e053-0b2a-4ff9-a082-a02d07458c0b)

**Comment by SkoricIT** [comment]
If it helps for some reason (because it seems like frontend is involved): I'm on Firefox with Manjaro Linux.

**Comment by SkoricIT** [comment]
That seems to be because filament stops updating the widgets:

![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/4c554c44-50a9-4a3e-8731-7ac72ee26db9)

No Idea why the notifications request takes 100% longer when the tab is in foreground?

Also, there is like 5kb of data transferred to the frontend per second but the php-fpm disk writes alone are like 1000KB/s

**Comment by alexjustesen** [comment]
@SkoricIT do you mind also testing with polling disabled? I updated the docs with a new Environment Variables page to help you out

**Comment by luanupe** [comment]
Hey Alex, I haven't had any issues on the last few days with the old version, and to be honest I haven't checked the web GUI of the on the past 4 days.

Just saw the notifications on the thread and I updated my docker image, I'll keep the tab open to verify if it is a front-end related issue and I'll let you know if anything changes.

I also increased the VM cores from 2 to 3 and here's my docker-compose.yml:

```
version: '3.3'

services:
  speedtest-tracker:
    image: 'ghcr.io/alexjustesen/speedtest-tracker:v0.11.17'
    container_name: speedtest-tracker
    ports:
      - '80:80'
      - '443:443'
    environment:
      - PUID=1000
      - PGID=1000
      - DASHBOARD_POLLING=60s
      - RESULTS_POLLING=60s
    volumes:
      - './data/config:/config'
      - './data/web:/etc/ssl/web'
    restart: unless-stopped
```

**Comment by SkoricIT** [comment]
> @SkoricIT do you mind also testing with polling disabled? I updated the docs with a new Environment Variables page to help you out

I set both options to false, which seems to have reduced a lot of requests but it's somehow still polling:

https://github.com/alexjustesen/speedtest-tracker/assets/1708378/528cb81b-e99b-4f13-ab4a-10d241e37ae8

See if you can tell when i change the tab in the browser. :slightly_smiling_face: 

I would be happy without any polling and optionally a simple JS refresh trigger or something. :slightly_smiling_face: 

This is my config:
![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/df3fda7d-fe9b-4b0b-a37c-ddcc76c18d2f)

![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/836af921-3bee-4372-b04d-ca20ac3e1357)

**Comment by SkoricIT** [comment]
BTW this is the CPU usage when i trigger a manual speed test, then quickly swap tab:

![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/fa8c8826-87b7-4b3b-955f-49ebf2a083b6)

**Comment by alexjustesen** [comment]
@SkoricIT and @luanupe have you both set or set the correct values for `PUID` and `PGID`? I'm working on slowing down the polling to reduce usage for the `fpm` pool but I've also seen issues if you're not running the image under the right ids.

**Comment by luanupe** [comment]
> @SkoricIT and @luanupe have you both set or set the correct values for `PUID` and `PGID`? I'm working on slowing down the polling to reduce usage for the `fpm` pool but I've also seen issues if you're not running the image under the right ids.

Hmmm... now that you said Alex it makes sense, I set the PUID and PGID as 1000 following the instructions at `https://docs.speedtest-tracker.dev/getting-started/environment-variables` but the docker container is running on a custom user on the host machine.

I'll fix it up and let your guys know.

**Comment by luanupe** [comment]
Hmm, just checked Alex and ignore my last comment, the ids are correct.

```
docker-user@speedtest:~/app$ id -u docker-user && id -g docker-user
1000
1000
```

**Comment by SkoricIT** [comment]
i forgot to include basic.env:

![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/72ef2348-d364-4f37-b008-b12691d1341f)

![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/1708378/ae20bed4-60e5-477a-91ac-74909ab0aa12)

**Comment by alexjustesen** [comment]
> i forgot to include basic.env:
> 
> ![grafik](https://user-images.githubusercontent.com/1708378/244880192-72ef2348-d364-4f37-b008-b12691d1341f.png)
> 
> ![grafik](https://user-images.githubusercontent.com/1708378/244880211-ae20bed4-60e5-477a-91ac-74909ab0aa12.png)

Thanks, trying to rule out the low hanging fruit. I'll have changes in the next release that polling with default to 60s intervals which should cut down on usage.

**Comment by alexjustesen** [comment]
@coanghel #676 is going to have some process improvements I'd be interested to know if it's going to reduce process usage.

**Comment by SkoricIT** [comment]
@alexjustesen Maybe we can have an option to just completely disable auto-update (have static pages) and only refresh on button press or reload?

**Comment by alexjustesen** [comment]
> @alexjustesen Maybe we can have an option to just completely disable auto-update (have static pages) and only refresh on button press or reload?

I like that, probably disable "polling" by default and let people turn it back on. In the interest of performance first.

**Comment by SkoricIT** [comment]
> > @alexjustesen Maybe we can have an option to just completely disable auto-update (have static pages) and only refresh on button press or reload?
> 
> You can disable polling through the env vars btw: https://docs.speedtest-tracker.dev/getting-started/environment-variables

Have disabled this a while ago.
```yml
    environment:
      - DASHBOARD_POLLING=false
      - RESULTS_POLLING=false
```

**Comment by SkoricIT** [comment]
@alexjustesen Even though i have above in my environment this still happens:

https://github.com/alexjustesen/speedtest-tracker/assets/1708378/a98dc8d7-aafd-447c-8f78-7ed0637dddf2

**Comment by alexjustesen** [comment]
@SkoricIT one contributing factor could be that I left `debug` as the log level which could be filling up the log stream. This was changed in `v0.11.18` so please let me know if this helps.

**Comment by SkoricIT** [comment]
@alexjustesen I just pulled and the instance stopped working. Did you change anything about DB handling?

```
To support Speedtest Tracker visit:
speedtest-tracker  | https://github.com/alexjustesen/speedtest-tracker
speedtest-tracker  | -------------------------------------
speedtest-tracker  | GID/UID
speedtest-tracker  | -------------------------------------
speedtest-tracker  | 
speedtest-tracker  | User uid:    1026
speedtest-tracker  | User gid:    100
speedtest-tracker  | -------------------------------------
speedtest-tracker  | 
speedtest-tracker  | 🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
speedtest-tracker  | 
speedtest-tracker  | 🐇  Configuring Speedtest Tracker...
speedtest-tracker  | 
speedtest-tracker  | 🔒  Fixing app path file permissions...
speedtest-tracker  | ✅  Permissions fixed.
speedtest-tracker  | 
speedtest-tracker  | ✅  Environment file exists.
speedtest-tracker  | 
speedtest-tracker  | 🔗  Creating symlinks for config and log files...
speedtest-tracker  | ✅  Symlinks created.
speedtest-tracker  | 
speedtest-tracker  | ✅  App key exists
speedtest-tracker  | 
speedtest-tracker  | 🔐  Linking the storage...
speedtest-tracker  | [2023-08-31 08:19:34] production.ERROR: Database file at path [/var/www/html/database/database.sqlite] does not exist. Ensure this is an absolute path to the database. (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): Database file at path [/var/www/html/database/database.sqlite] does not exist. Ensure this is an absolute path to the database. (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:801)
speedtest-tracker  | [stacktrace]
```

I did not change anything else, my sql file was working for many version upgrades by now.

**Comment by mooglestiltzkin** [comment]
i also noticed high constant cpu usage compared to all my other containers.

all this app does is schedule to run once a day during off hours to check the internet speed, and keep a log for it. if you want u can even be sent an alert.

but why is the cpu constantly high? hopefully there is a fix :(

**Comment by imcdona** [comment]
The reason for the CPU usage is because this project contains malware to mine crypto. I've reached out to the dev personally and haven't gotten a response.

I haven't tried compling the image myself so it could be that only the pre-built docker images are affected.

**Comment by SkoricIT** [comment]
@imcdona Can you please post proof of your allegations? Thanks!

**Comment by luanupe** [comment]
@imcdona Bro, do you have any proof of your claim? See, you can inspect any docker image (even the pre-built ones) on the dockerhub website... also dockerhub scans the images for malwares and vulnerabilities... sorry but I don't think a bitcoin miner is installed on this application.

**Comment by alexjustesen** [comment]
> The reason for the CPU usage is because this project contains malware to mine crypto. I've reached out to the dev personally and haven't gotten a response.
> 
> I haven't tried compling the image myself so it could be that only the pre-built docker images are affected.

You did? If you did definitely didn't get anything so make sure you follow https://github.com/alexjustesen/speedtest-tracker/security/policy to report issues.

I take these allegations pretty seriously so proof is required and generally speaking it's best to reach out to the dev and allow them to fix any security issues before posting about it.

**Comment by imcdona** [comment]
_I take these allegations pretty seriously so proof is required and generally speaking it's best to reach out to the dev and allow them to fix any security issues before posting about it._

@alexjustesen I only mention this here because I didn't get a response to my first attempted to reach out to you on _FRI MAY 12 9:23 AM_  at sec@alexjustesen.com. The docker image is infected, I'll give you the benefit of the doubt and assume you were oblivious to the fact that the docker image was infected with perfctl. 

See Google [search results](https://www.google.com/search?client=firefox-b-1-d&q=perfctl+): 

When I went looking for the original email I now see that it bounced.

```
This message was created automatically by mail delivery software.
A message that you sent could not be delivered to one or more of its recipients. This is a permanent error.

[sec@alexjustesen.com](mailto:sec@alexjustesen.com), ERROR CODE :550 - 5.1.1 Address does not exist. UrYgPgKuAu1t



Reporting-MTA: dns; mx.zohomail.com
Arrival-Date: Fri, 12 May 2023 09:23:44 -0700
```



**Here is my original security report:**

Hello,

 

I was surprised to find that one of my servers had a large increase in CPU usage. Upon investigation I found that a process named _perfctl_ was running in the speedtest docker instance. I’ve since updated to the latest image and so far, I haven’t seen the process start again.

 

I saw no mention of a fix in the release notes which is why I’m bringing this to your attention.

 

Line from top command. Probably not very useful but I included it nonetheless:

1387213 1000      20   0 3172112   2.3g      0 S 322.2   7.4  23:08.74 perfctl
 

Observium graph showing the spike in CPU utilization.

![1](https://github.com/alexjustesen/speedtest-tracker/assets/2708873/6ddc32bf-a8c9-4f14-b79b-e1d738c2e92c)


Thanks

**Comment by alexjustesen** [comment]
> ```
> This message was created automatically by mail delivery software.
> A message that you sent could not be delivered to one or more of its recipients. This is a permanent error.
> 
> [sec@alexjustesen.com](mailto:sec@alexjustesen.com), ERROR CODE :550 - 5.1.1 Address does not exist. UrYgPgKuAu1t
> 

Please send this again, I've had no other reports of malware in the image or the image Speedtest Tracker is based off of. Additionally please let me know what your build process was in that email so I can attempt to re-produce it.

**Comment by imcdona** [comment]
Why did you mark the comment where I explained the issue along with evidence that it's infected with _perctl_ as a "duplicate" (so it's hidden and nobody can see the evidence I provided) and then request I send you an email with the exact same details I provided in the comment you hid from everyone?

**Comment by imcdona** [comment]
If _perctl_ isn't in the source code then it's being added during the image build process. Out of an abundance of caution, why not remove the image and suggest users build the image from source?

The safety of users is paramount, right?

**Comment by alexjustesen** [comment]
@coanghel high resource usage should be a non-issue while using the new LSIO image. If someone on this thread can verify what I'm seeing I'd like to close this out.

**Comment by SkoricIT** [comment]
@alexjustesen I will check it out with a fresh instance.

**Comment by SkoricIT** [comment]
@alexjustesen Seems fixed for me, even with enabled polling and everything id stays at about 0.1% - 0.34% CPU. On leading dash it jumps to 65% for a second. I think it looks very good now. Thanks!

**Comment by alexjustesen** [comment]
Thanks for confirming I think we can close this out!
