### ISSUE TITLE
Influxdb doesnt work

### ISSUE THREAD

**Issue by vellanix** [alexjustesen/speedtest-tracker#621]
**Describe the bug**
The influxdb integration doesnt work

**Expected behavior**
The data expented in influxdb, but the log show an error

**Environment (please complete the following information):**
 - OS: unraid
-  Architecture: itel
 - Browser chrome

[log.txt](https://github.com/alexjustesen/speedtest-tracker/files/11612161/log.txt)

**Comment by alexdelprete** [comment]
Works fine here, but I have influxdb installed in my homelab, never tested the cloud instance.

Are you sure you configured everything accordingly? Can you show the screenshot of the configuration items? From the type of error, looks like a permission issue:

```log
error writing line 1: Unable to insert iox::column_type::fie
```

make sure org, bucket and token are correct.

**Comment by vellanix** [comment]
It's a cloud instance, influxdb V2 of course, and the token is "all access".

I saw that issue #612 has the same problem.

Here's some screenshot
<img width="898" alt="Screenshot 2023-05-31 alle 15 24 06" src="https://github.com/alexjustesen/speedtest-tracker/assets/72751032/2e555a44-7fe4-442d-a89f-c479640ec600">
<img width="775" alt="Screenshot 2023-05-31 alle 15 17 52" src="https://github.com/alexjustesen/speedtest-tracker/assets/72751032/a0dfbf18-3919-4daa-ae4f-76563438ee30">
<img width="670" alt="Screenshot 2023-05-31 alle 15 15 25" src="https://github.com/alexjustesen/speedtest-tracker/assets/72751032/e24b4d88-9de3-4d36-b5bf-398c1c66b187">

**Comment by vellanix** [comment]
sure, need some times to setup a local instance.. but I'll try

**Comment by batou069** [comment]
In my case even disabling influx db, the scheduler wouldnt run

**Comment by alexjustesen** [comment]
I'll need to test this on the cloud instance of InfluxDB and see if I can narrow down any issues. Haven't tested that service yet.

https://www.influxdata.com/

**Comment by joshoram80** [comment]
I am having InfluxDB complain

`07/15/2023 6:01:32 PM ts=2023-07-15T08:01:32.234673Z lvl=info msg=Unauthorized log_id=0j27tMyW000 error="token required"`

But there is an All Access API key setup in Speedtest-Tracker, it just looks like it's not being sent to the API call

**Comment by alexjustesen** [comment]
> I am having InfluxDB complain
> 
> `07/15/2023 6:01:32 PM ts=2023-07-15T08:01:32.234673Z lvl=info msg=Unauthorized log_id=0j27tMyW000 error="token required"`
> 
> But there is an All Access API key setup in Speedtest-Tracker, it just looks like it's not being sent to the API call

This is likely a different problem, can you open a separate issue to track that?

**Comment by Jiriteach** [comment]
Quick one on this issue - experiencing this same problem. Tried agains the cloud instance and its failing with - 

```
Next InfluxDB2\ApiException: [400] Client error: `POST https://us-east-1-1.aws.cloud2.influxdata.com/api/v2/write?org=s7n&bucket=speedtests&precision=s` resulted in a `400 Bad Request` response:
{"code":"invalid","message":"failed to parse line protocol: error writing line 1: Unable to insert iox::column_type::fie (truncated...)
```

**Comment by alexjustesen** [comment]
> Quick one on this issue - experiencing this same problem. Tried agains the cloud instance and its failing with -

Thanks for verifying this is still an issue, prob wont circle back around to InfluxDB work until I get this Docker image sorted.

**Comment by alexjustesen** [comment]
Integration with InfluxDB is going to be rewritten so closing this issue

**Comment by jiriteach** [comment]
@alexjustesen - Before I retry the cloud version of influxdb - was this rewritten? Thanks

**Comment by alexjustesen** [comment]
@jiriteach it hasn't, Influx integration will be written with history loads when I go to do it.
