### ISSUE TITLE
Kubernetes Manifests

### ISSUE THREAD

**Issue by jmcglock** [alexjustesen/speedtest-tracker#637]
Please provide Kubernetes manifests for this application.

**Comment by alexjustesen** [comment]
Happy to review a PR to add this to the docs but currently out of scope.

**Comment by maximemoreillon** [comment]
I managed to deploy speedtest-tracker to my Kubernetes cluster with the following manifests:

https://github.com/maximemoreillon/kubernetes-manifests/tree/master/speedtest-tracker

I had to set the pod's DNS config manually to get it to work.

**Comment by alexjustesen** [comment]
Thanks, added it to https://docs.speedtest-tracker.dev/getting-started/installation/kubernetes
