### ISSUE TITLE
Dockerfile Improvements

### ISSUE THREAD

**Issue by modem7** [alexjustesen/speedtest-tracker#640]
Heya @alexjustesen, 

I noticed that the docker builds take quite a while, and most of the time is spent on the `chown` command. 

I've been playing around, and I think I may have found a good way to speed things up, and as a bonus, not break the Docker build cache.

```dockerfile
# syntax = docker/dockerfile:latest

FROM serversideup/php:8.1-fpm-nginx AS build

WORKDIR /var/www/html

# Install app dependencies
COPY --link --chown=webuser:webgroup composer.json composer.lock /var/www/html
RUN composer install --no-dev --no-interaction --no-autoloader --no-scripts --no-cache

# Copy app
COPY --link --chown=webuser:webgroup . /var/www/html

# Install app dependencies
RUN <<EOF
    set -xe
    composer dump-autoload --optimize --no-dev --no-interaction --no-cache
    mkdir -p storage/logs
    php artisan optimize:clear
EOF

FROM serversideup/php:8.1-fpm-nginx AS app

# Add /config to allowed directory tree and Enable mixed ssl mode so port 80 or 443 can be used

ENV PHP_OPEN_BASEDIR=$WEBUSER_HOME:/config/:/dev/stdout:/tmp \
    SSL_MODE="mixed"

RUN --mount=type=cache,id=aptcache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=libcache,target=/var/lib/apt,sharing=locked \
    <<EOF
    set -x
    rm -fv /etc/apt/apt.conf.d/docker-clean
    echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
    # Install Speedtest cli & additional packages
    apt-get update
    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash
    apt-get install -y --no-install-recommends \
            speedtest \
            php8.1-pgsql \
            cron

    # Install Cron file
    echo "MAILTO=\"\"\n* * * * * webuser /usr/bin/php /var/www/html/artisan schedule:run" > /etc/cron.d/laravel

    # Clean up 
    apt-get clean
    rm -rf /tmp/* \
           /var/tmp/* \
           /usr/share/doc/*
EOF

# Copy package configs
COPY --link --chmod=755 docker/deploy/etc/s6-overlay/ /etc/s6-overlay/
COPY --link --from=build --chown=webuser:webgroup /var/www/html /var/www/html

VOLUME /config

HEALTHCHECK --timeout=5s --interval=10s --start-period=120s \
  CMD curl -fSs http://localhost/ping || exit 1
```

Currently, I have it building in about 60-70 seconds without utilising the cache.

Let me know if this is of any use, and if so, I'm happy to put in a PR.

**Comment by alexdelprete** [comment]
>1m to build? And how long does it take with current version?

Are you testing with an RPi?

**Comment by modem7** [comment]
> 1m to build? And how long does it take with current version?
> 
> Are you testing with an RPi?

Looks like there was an odd inconsistency whilst testing last night with the recursive chown command for some reason - my end no doubt. Builds from the proposed Dockerfile are now around 50 seconds without a cache. And quite a bit lower depending on which layer gets busted, especially as it can be done concurrently.

Barring that, the way it's currently structured at the moment busts the Docker cache when rebuilding. This can be seen in some of the builds.

Most of the time spent is on the APT downloads, so being able to cache that in a layer would be beneficial regardless. 

But, if it's not useful, then it's not useful.

**Comment by alexdelprete** [comment]
> But, if it's not useful, and doesn't provide any net benefit, then it's not useful, and we can close this off with not planned.

That would be up to @alexjustesen to decide, not me.

If I was you, I'd prepare the PR anyway, so @alexjustesen can simply approve it or not.

**Comment by alexjustesen** [comment]
@modem7 if you're up for it I'm separating the base image to be used, if you've got suggestions how to improve the build process I can add you to that repo as I go through testing

**Comment by modem7** [comment]
> @modem7 if you're up for it I'm separating the base image to be used, if you've got suggestions how to improve the build process I can add you to that repo as I go through testing

Heya,

Sure thing, happy to have a look and pipe in if there's anything I can do to help out!

**Comment by alexjustesen** [comment]
Performance improvements on build/startup coming in #676, haven't split out the image to a separate repo yet.

**Comment by alexjustesen** [comment]
@modem7 latest builds contain a much improved startup time. If this is still an issue tag me and we can re-open this one.
