### ISSUE TITLE
Always display selected Server name and region in Speedtest server ID field

### ISSUE THREAD

**Issue by gokulkgm** [alexjustesen/speedtest-tracker#641]
**Is your feature request related to a problem? Please describe.**
When selecting speedtest servers in speedtest id field, the server's name and region are displayed.
However, after saving the changes and ongoing back to the settings, only server Id is shown.
Hence it becomes difficult to know which servers the Id corresponds to.

**Describe the solution you'd like**
Always display the server's region and name with the Id

**Additional context**
<img width="314" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/8915158/71c2fb86-5c14-4ed0-a869-7ff4bc8822dd">

**Comment by alexdelprete** [comment]
I agree, that section should be a table with 2 columns, ID and Server name with region. With an empty row at the end to add another server.

**Comment by alexjustesen** [comment]
Can't remember when but this is in production...

<img width="824" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/1144087/b220f393-406c-48e8-913d-1f8d2e1258cc">
