### ISSUE TITLE
Results on container are slower than on host 

### ISSUE THREAD

**Issue by levyilan** [alexjustesen/speedtest-tracker#645]
I run the speed test every 10 minutes, the highest result for download is 129Mbps:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/16539237/8a41a99b-4c86-4d62-bd6f-580d6e463136)
While running speed test in CLI mode on the host of the container I get to around the line speed (200Mbps)
https://www.speedtest.net/result/c/1af8c999-d430-46e8-87d5-4c94ca4785d7

**Comment by alexjustesen** [comment]
Can you provide some information on your setup?

**Comment by alexdelprete** [comment]
> While running speed test in CLI mode on the host of the container I get to around the line speed (200Mbps)

In order to do comparisons, you need to be sure you're testing vs the same server, so you need to specify the server id in shell and configure that same server in the configuration of speedtest-tracker.

**Comment by levyilan** [comment]
it's probably it, I chose the same ISP for the speedtest, however it has 2 servers and one of them(the faster one) is not shown on the list.

Thanks.

**Comment by alexdelprete** [comment]
good. Can you close the issue please? Thanks.
