### ISSUE TITLE
Add server name/ID to notifications

### ISSUE THREAD

**Issue by macbean101** [alexjustesen/speedtest-tracker#647]
Would it be possible to add the speedtest server name to the notification sent upon completion?

Something long the lines of:

Speedtest Completed
-----
Server: 12627 (Proximus)
Ping: 97.99 (ms)
Download: 11.03 (Mbps)
Upload: 2.72 (Mbps)

**Comment by svenvg93** [comment]
Its already there right or are you looking for something else 
<img width="533" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/df57756f-c55f-45b5-aacc-e349791ce8d7">

**Comment by macbean101** [comment]
At the time I wrote that, you didn't get that much information.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/25144645/fa5c5c95-c41b-49aa-8de5-e1510bcb3f54)

It looks like it was updated at some point.  I need to update my docker but due to some changes, I'll need to redo it from scratch (I believe) and I haven't taken the time to do it.

**Comment by macbean101** [comment]
After (finally) upgrading:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/25144645/5e7dbd6d-fd9a-4b0d-85e4-8e69c15c3504)

**Comment by alexjustesen** [comment]
Closing since it was implemented at some point
