### ISSUE TITLE
Scheduled test is not running at the correct, scheduled time

### ISSUE THREAD

**Issue by ampersandru** [alexjustesen/speedtest-tracker#649]
In general settings, I have `0 5 * * *` as my scheduled speed test, which should be every day at 5 AM. However, it is running the speed test every day at 22:00, which is 10 PM. I don't believe it's a timezone issue because when I manually run a test, the shown last run time is correct.

**Comment by alexjustesen** [comment]
Double check your time zone as the default is UTC. Also improvements will be made in connection with #194

**Comment by ampersandru** [comment]
> 

Binding /etc/localtime fixed it, I already had TZ: America/Los_Angeles - I believe it was actually running at 5AM PST but displaying 22:00. Adding the /etc/localtime bind seems to have updated the time on the tests to be 5AM

Thanks!

**Comment by alexdelprete** [comment]
@alexjustesen this should be added to the docs, it's one of the most common issues.

**Comment by alexjustesen** [comment]
Yeah that's a good call, I'm opening the issue again until a PR is open or docs updated.

**Comment by alexdelprete** [comment]
> TZ: America/Los_Angeles

PR submitted: https://github.com/alexjustesen/speedtest-tracker-docs/pull/14

**Comment by alexdelprete** [comment]
> I’m trying to figure the code for running scheduled test on the half hour? Is that possible?

ST supports crontab expressions. Under the expression field, it says: "You can also use the cron expression generator [HERE](https://crontab.cronhub.io/) to help you make schedules."

Did you try to use the linked crontab expression generator or at least google it?

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/9be236bc-ba98-4140-9bc8-9db468c47191)

**Comment by LarryT8959** [comment]
I tried that same formula on the expression generator put didn't get it to work. I assume it would yield results on the web page but I guess I was wrong. I placed it in the actual test page an it took, no errors. Thanks

**Comment by alexdelprete** [comment]
> I tried that same formula on the expression generator put didn't get it to work. I assume it would yield results on the web page but I guess I was wrong.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/26008787-a730-4e7d-afde-27bb1c5c7113)

**Comment by LarryT8959** [comment]
Still not working for me, obviously I'm doing something wrong. After entering I press enter and nothing happens? Tried tab also.

**Comment by alexdelprete** [comment]
You don't have to click return or anything...just type...it's dynamic, here's an animated gif so you see what I'm doing:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/68fc6c7b-37f5-4735-aae3-f959238b712a)

**Comment by LarryT8959** [comment]
￼

Crazy

**Comment by alexdelprete** [comment]
I don't see anything in your post.

If it doesn't work, change browser. What browser are you using? What OS?
