### ISSUE TITLE
Speed chart confuses mbps and kbps 

### ISSUE THREAD

**Issue by ks2018ks** [alexjustesen/speedtest-tracker#653]
**Describe the bug**
Test results in kbps shown in chart as mbps

**Screenshots**

<img width="881" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/37977911/a25e64b2-4fe4-460c-9ae3-8b4a5d5f1d2e">

<img width="910" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/37977911/a3939b3b-b22b-40aa-9b78-09132e0a3af0">

**Comment by alexjustesen** [comment]
There's some jank with charting currently. Planning on overhauling this in a future release. Checkout the milestones for planned work
