### ISSUE TITLE
test not execute

### ISSUE THREAD

**Issue by d4nm0** [alexjustesen/speedtest-tracker#654]
my connection tests haven't worked for a few weeks. I haven't changed anything in the vm configuration.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/20597792/691ec3c4-cc17-4ecc-bf97-0a6272a33ccc)

**Comment by alexjustesen** [comment]
Are you specifying a server or relying on the cli to test a server? Also take a look at the output for cli results and share logs. 

Need more information to be helpful
