### ISSUE TITLE
Speed test data usage.

### ISSUE THREAD

**Issue by devanteweary** [alexjustesen/speedtest-tracker#655]
Hey everyone, didn't see a label for discussion but this isn't really an issue/problem.

I'm just wondering how much data these speedtests usually use.
Asking because I've used over 75% (975GB) of my data limit (1.2TB) in 10 days!!

My speedtest-tracker setup is choose the best server and run a test every 10 minutes.
My results come back usually around 400Mbps.

I've had it set up for a couple of weeks so I'm wondering if that's what used up all that data!

Thanks for any convo/discussion!

**Comment by alexdelprete** [comment]
The app uses ookla's official speedtest-cli client to run tests. With default settings, it should use around 1GB of data for download test and 1GB for upload test.

I wouldn't recommend to let speedtest-cli find the best server, try to find the best servers for your location and stick to the most reliabe servers (I use 3 servers and specify their IDs in the options).

Also, I run tests every 1h.

**Comment by devanteweary** [comment]
OK by my calculations, I too was using 1GB per download test!! My uploads is much smaller though.
Wow I was using 6+ GB per hour for the last couple of weeks!! :<

Ha oh well... I love the app, just gotta calm down on it ha

**Comment by alexjustesen** [comment]
Yeah speedtest cli is pretty data heavy, unfortunately a product of their services
