### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by R4toLoko** [alexjustesen/speedtest-tracker#657]
I have spent a crazy amount of time trying to get this to work because of outdated documentation.

I was following this: https://github.com/alexjustesen/speedtest-tracker/blob/main/docker-compose.yml
To deploy it on my kubernetes homelab cluster.

I always wanna check the image and could not find `speedtest-tracker-8.1/app`, I tried to search for `alexjustesen` and no images either.

Luckily, I got into a what appears to be a more updated documentation: https://docs.speedtest-tracker.dev/getting-started/installation

I have no idea how I got into that old `docker-compose`, but I am pretty sure others will find it too.
Either update it and delete it.

Finally got it running fine with a mariaDB pod.

Nice project.

**Comment by alexjustesen** [comment]
PRs welcome to update the docs: https://github.com/alexjustesen/speedtest-tracker-docs
