### ISSUE TITLE
Add ISP value to results, influxdb output, and api.

### ISSUE THREAD

**Issue by Deanosim** [alexjustesen/speedtest-tracker#658]
I'd love to see the ISP value added as an option in results and influxdb if possible, currently the only way to see it is in is by clicking on individual results.
I have a 4G backup connection so it'd be great to be able to tell easily what ISP/connection the test was ran on and possible filter it.

**Comment by strausmann** [comment]
@alexjustesen When can we expect the integration? I have the same problem as the issue owner. I urgently need the ISP in the evaluations in order to be able to better measure the failures of my primary ISP.

Thank you very much

**Comment by alexjustesen** [comment]
Priorities currently:

1. Get the install process back to being stable, something broke or docs could use improvement to reduce confusion.
2. Fix data quality issues #310 .
3. Import and export data, this includes imports from "that other" speedtest tracker.
4. Once those hurdles are stable I'll look into more functionality, a prerequisit to this is enabling API tokens so requests can be authorized.

**Comment by JavierChaparroMX** [comment]
I would love to see this functionality added, I have 2 ISP's for redundant connection, and my results seem to "Round-robin" isps haha 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/99060668/9ad0c12f-2e73-4173-988b-5553085bb9b7)

@Deanosim 
I considered deploying a second instance of the application and using Routing rules to make each container go through a different ISP if that helps. I have not done it yet but we sure can try; What gateway/firewall do you have? I have a UDMse from Ubiquiti.
