### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by sashkab** [alexjustesen/speedtest-tracker#66]
When opening project's README it would be beneficial to have some explanation what this project about for those who has no idea. Would be nice, if you could add a screenshot (or couple of them, if there are more than one view) and feature list.

**Comment by alexdelprete** [comment]
> it would be beneficial to have some explanation what this project about for those who has no idea.

1. Did you read the first line of readme? `"Speedtest Tracker runs a speedtest check against Ookla's Speedtest service on a schedule."`

2. In the second line there's the link to the project it replaces too. So it's not so hard to understand what the project is about. Furthermore, you can contribute to the project via PR, even if you're not a dev, you can contribute to documentation, producing screenshots, etc.

3. In the readme there's also a `Docs` paragraph with the link to the documentation site: https://docs.speedtest-tracker.dev/

Did you open it? It says this:

![image](https://user-images.githubusercontent.com/7027842/197365484-0b0abbac-bfdc-4c54-b577-431fdeb05753.png)

4. The dev has a fulltime job and also a little baby that keeps him very busy, he's waking up very early to create all this (and we should be very grateful to Alex for this), and as usual, he's concentrated on the software side at the moment, resolving the main bugs, etc. I'm sure the documentation will be improved with time, and I'm sure you will contribute to it, at least by reading carefully before asking for something that's already there.

**Comment by alexjustesen** [comment]
Screenshots are so easy it's basically something that flies under the radar. I'll have that done tomorrow before the race

**Comment by alexdelprete** [comment]
> Screenshots are so easy

Yes, it's just a matter of bringing up a container and playing with it a little bit. ;)

Screenshots here:

![image](https://user-images.githubusercontent.com/7027842/197367137-677e2fc5-e969-492b-8eb9-755e483ce8c8.png)

![image](https://user-images.githubusercontent.com/7027842/197367140-97618006-8d0f-44f5-ad47-ac1e0be2fe52.png)

![image](https://user-images.githubusercontent.com/7027842/197367142-10385ffa-bb8b-4fc0-8796-c186e8968311.png)

![image](https://user-images.githubusercontent.com/7027842/197367144-fef4dc4a-2d29-4cea-ad20-354d1d3b790d.png)

**Comment by sashkab** [comment]
Screenshots show a lot. Thanks for posting them. 

For me, speediest-cli runs by crontab, I select servers using `-L` option (if I remember correctly) and then run it via crontab four times an hour, then every day script is run which generates me a report, which I read in an email, showing last seven days worth of averaged data. Which is good enough for me. 

as to README -- readme is a single point of entry into your project, so having everything in the single place is easier, than clicking many links. IMHO, README should have few sections:

1. name of the project and brief history + correct pronounce of the name if it is something non-standard + license information
2. brief explanation what project does and a screenshot or two.
3. quick startup guide + link to more detailed documentation

this allows someone quickly see everything important without jumping hoops to documentation (which is two pages anyways, currently).

**Comment by alexdelprete** [comment]
> Which is good enough for me.

For you, exactly. For me that's absolutely not enough: I prefer a management console with data going into a database and also in a time-series db like influxdb from which I can produce graphs etc. with Grafana. I want to monitor my ISP and be able to produce easy to read graphs etc. in case I have problems with SLAs they declare.

> README should have few sections:

Please feel free to contribute to the project by submitting a PR, since you like producing documentation. :)

> 1. name of the project and brief history

It's already in the readme, but probably you didn't read it.

> 2\. brief explanation what project does and a screenshot or two.

The project has just started, the explanation is in the readme, screenshots will be added.

> 3\. quick startup guide + link to more detailed documentation

There's a link to an external docs site with that info, but you missed it because you didn't read the readme.

> (which is two pages anyways, currently)

We'll write The Divine Comedy (or War and Peace) of speed-tracker, so you can fully appreciate the intricacies of this very very complex project. :)

I can't really believe you didn't understand what this project was about without the screenshots...

**Comment by alexjustesen** [comment]
`README.md` is getting screenshots from the tagged PR and https://docs.speedtest-tracker.dev/ just got a complete list of planned and implemented features. Thanks for the feedback!

**Comment by alexdelprete** [comment]
@alexjustesen will you release the first beta today? :)

**Comment by alexjustesen** [comment]
I'm hoping, I got a 🤏 list I want in place before I call it beta time. This includes multi-arch support at the minimum

**Comment by alexdelprete** [comment]
what about another alpha to test the latest fixes?

**Comment by alexjustesen** [comment]
> what about another alpha to test the latest fixes? is it possible to have a dev branch usable as a tag to test the bleeding edge versions?

soon(tm)
