### ISSUE TITLE
Inconsistent time format for 24/12 hours

### ISSUE THREAD

**Issue by azizLIGHT** [alexjustesen/speedtest-tracker#672]
**Describe the bug**
By default the time format is 24 hours. But if you set it to 12 hours with `M j, Y g:i:s A` it shows correctly in some places but not on the graph.

**To Reproduce**
1. Go to Settings -> General
2. Change Time format to `M j, Y g:i:s A`
3. Look at Dashboard. It says `Last speedtest run at: Aug 3, 2023 2:29:56 PM` This is correct 12 hour format
4. Look at the graph. The axis say: `Aug 03 - 14:29`

**Expected behavior**
The graph axis should say `Aug 03 - 2:29 PM`

**Environment (please complete the following information):**
 - OS: Debian 12
-  Architecture: amd64
 - Browser Firefox 
 - Version 115

**Screenshots**
![Screenshot_20230803_144301](https://github.com/alexjustesen/speedtest-tracker/assets/8013867/35c2d809-9ada-4728-bc39-483fc4c1d443)
![Screenshot_20230803_144403](https://github.com/alexjustesen/speedtest-tracker/assets/8013867/038e1d8b-0a19-4ef1-aa71-0a084afc508d)

**Comment by azizLIGHT** [comment]
It shows fine in Results page too
![Screenshot_20230803_144545](https://github.com/alexjustesen/speedtest-tracker/assets/8013867/1170277c-0d80-427b-98f6-6a3612e1fc1a)

**Comment by alexjustesen** [comment]
This one is on purpose as the longer formatted dates can get a bit crowded imo.
