### ISSUE TITLE
❌ There seems to be a failure in checking the web server + PHP-FPM. Here's the response:

### ISSUE THREAD

**Issue by pwsnla** [alexjustesen/speedtest-tracker#674]
**Describe the bug**

The following error is logged on every container startup:

❌ There seems to be a failure in checking the web server + PHP-FPM. Here's the response:

I am not sure what that error means and if I should be concerned because docker container actually starts and it appears to be working.

I installed Speedtest-tracker on two instances and only one of them is exhibiting this problem. Both are running Ubuntu 22.04 but the instance with this issue is much smaller and AMD64 architecture while the instance that is not showing this problem is larger (4 CPUS) and ARM64 architecture.

I see the same issue was mentioned earlier but it was closed and it mentioned nginx:
https://github.com/alexjustesen/speedtest-tracker/issues/506
I am not using nginx or any other reverse proxies. 

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
-  Architecture: amd64
 - Version [v0.11.17]

**Logs**
✅  All set, Speedtest Tracker started.

[08-Aug-2023 09:40:36] NOTICE: fpm is running, pid 139

[08-Aug-2023 09:40:36] NOTICE: ready to handle connections

[08-Aug-2023 09:40:36] NOTICE: systemd monitor interval set to 10000ms

❌ There seems to be a failure in checking the web server + PHP-FPM. Here's the response:

**Comment by Raithmir** [comment]
I see the same message, but it doesn't appear to affect anything. I assume it's just a false error, and if there was an actual issue it would be after the "Here's the response:" bit.

**Comment by alexjustesen** [comment]
Yeah the notice messages aren't an issue in the logs so you can ignore it
