### ISSUE TITLE
Seems to have problems with Speedtest-cli.

### ISSUE THREAD

**Issue by DWomack** [alexjustesen/speedtest-tracker#680]
**Describe the bug**
Calls to speedtest-cli don't complete with valid data sometimes. Speeds returned are 0.0 and ping times are 0, which is not possible.  Call should be executed again.  This behavior is also exhibited by Speedtest -exporter which also uses Speedtest-cli. 

**To Reproduce**

**Expected behavior**
Every test returns good values. 

**Environment (please
Latest Docker engine and Docker compose. 

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by DWomack** [comment]
I don't have any experience with php, but it looks like ExecSpeedtest.php is where the call is made.

Can you patch it so it re-evaluates Speedtest if there is an error returned.

**Comment by DWomack** [comment]
I think the WAN ip address might be changing in the process and that is causing the problem. It bounces around a lot on the cube.

**Comment by alexjustesen** [comment]
@DWomack I've got mine running in a swamp and haven't noticed it when a IP changed. Can you make sure the pod isn't being dropped during a test?

**Comment by DWomack** [comment]
"Can you make sure the pod isn't being dropped during a test?"

Please explain.

This is the last 24 hours on the internet-pi app...

![A1E834E3-E891-44F4-973F-A754FB1345B1](https://github.com/alexjustesen/speedtest-tracker/assets/7165493/901973b4-dd01-4b56-91ce-95499faf6738)

I had already deleted the zero entries in the one using yours.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7165493/dddc671a-b4f0-4ac0-ade0-5eda2f9dad96)

**Comment by DWomack** [comment]
![A4D63EB1-D724-4755-AFA3-EECF4DD5B872](https://github.com/alexjustesen/speedtest-tracker/assets/7165493/b2e1ea4d-cb5b-432b-9bdf-159735a554f0)

![E09E02D1-CA1B-40E8-8C98-93BC657ECEF2_1_201_a](https://github.com/alexjustesen/speedtest-tracker/assets/7165493/d75dade0-8760-4ae9-9079-cfac42218d4a)

**Comment by DWomack** [comment]
![D6947010-FDFA-4315-8B35-94DB8FDCCB7D_1_201_a](https://github.com/alexjustesen/speedtest-tracker/assets/7165493/2fe5fa80-623a-4cc8-968f-5b0e78a44918)

**Comment by DWomack** [comment]
Data pulled out of VZ Cube.  Notice how often the wan IP changes...

Data is newest first.  Cube power recycled at 5:00am


2023 Aug 21   14:27:09 | [WAN.6][WDHCP] bound wan_61 IP:   10.132.150.222
-- | --
2023 Aug 21 14:27:08 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 14:12:03 | [WAN.6][WDHCP] bound wan_61 IP: 10.134.254.181
2023 Aug 21 14:12:03 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 14:03:24 | [WAN.6][WDHCP] ignore renew wan_62 IP: 75.235.21.23
2023 Aug 21 13:56:53 | [WAN.6][WDHCP] bound wan_61 IP: 10.129.162.9
2023 Aug 21 13:56:53 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 13:41:48 | [WAN.6][WDHCP] bound wan_61 IP: 10.134.8.188
2023 Aug 21 13:41:47 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 13:26:43 | [WAN.6][WDHCP] bound wan_61 IP: 10.135.59.144
2023 Aug 21 13:26:42 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 13:11:10 | [WAN.6][WDHCP] bound wan_61 IP: 10.130.79.248
2023 Aug 21 13:11:09 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 13:03:24 | [WAN.6][WDHCP] ignore renew wan_62 IP: 75.235.21.23
2023 Aug 21 12:56:04 | [WAN.6][WDHCP] bound wan_61 IP: 10.132.17.90
2023 Aug 21 12:56:03 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 12:40:58 | [WAN.6][WDHCP] bound wan_61 IP: 10.132.31.163
2023 Aug 21 12:40:58 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 12:25:53 | [WAN.6][WDHCP] bound wan_61 IP: 10.130.91.246
2023 Aug 21 12:25:53 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 12:10:49 | [WAN.6][WDHCP] bound wan_61 IP: 10.135.92.95
2023 Aug 21 12:10:48 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 12:03:24 | [WAN.6][WDHCP] ignore renew wan_62 IP: 75.235.21.23
2023 Aug 21 11:55:43 | [WAN.6][WDHCP] bound wan_61 IP: 10.131.215.253
2023 Aug 21 11:55:43 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 11:40:31 | [WAN.6][WDHCP] bound wan_61 IP: 10.129.251.138
2023 Aug 21 11:40:30 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 11:25:11 | [WAN.6][WDHCP] bound wan_61 IP: 10.131.11.105
2023 Aug 21 11:25:10 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 11:10:03 | [WAN.6][WDHCP] bound wan_61 IP: 10.132.32.7
2023 Aug 21 11:10:03 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 11:03:24 | [WAN.6][WDHCP] ignore renew wan_62 IP: 75.235.21.23
2023 Aug 21 10:54:58 | [WAN.6][WDHCP] bound wan_61 IP: 10.134.82.31
2023 Aug 21 10:54:58 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 10:39:53 | [WAN.6][WDHCP] bound wan_61 IP: 10.135.52.37
2023 Aug 21 10:39:53 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 10:24:43 | [WAN.6][WDHCP] bound wan_61 IP: 10.132.48.156
2023 Aug 21 10:24:43 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 10:09:38 | [WAN.6][WDHCP] bound wan_61 IP: 10.134.116.108
2023 Aug 21 10:09:37 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 10:03:25 | [WAN.6][WDHCP] ignore renew wan_62 IP: 75.235.21.23
2023 Aug 21 09:54:33 | [WAN.6][WDHCP] bound wan_61 IP: 10.134.92.135
2023 Aug 21 09:54:32 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 09:24:15 | [WAN.6][WDHCP] bound wan_61 IP: 10.135.210.26
2023 Aug 21 09:24:15 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 09:09:09 | [WAN.6][WDHCP] bound wan_61 IP: 10.131.183.184
2023 Aug 21 09:09:08 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 09:03:24 | [WAN.6][WDHCP] bound wan_61 IP: 10.131.183.119
2023 Aug 21 08:53:58 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 08:53:58 | [WAN.6][WDHCP] ignore renew wan_62 IP: 75.235.21.23
2023 Aug 21 08:38:46 | [WAN.6][WDHCP] bound wan_61 IP: 10.129.123.140
2023 Aug 21 08:38:46 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 08:23:39 | [WAN.6][WDHCP] bound wan_61 IP: 10.135.250.48
2023 Aug 21 08:23:38 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 08:08:33 | [WAN.6][WDHCP] bound wan_61 IP: 10.128.27.134
2023 Aug 21 08:08:33 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 08:03:24 | [WAN.6][WDHCP] bound wan_61 IP: 10.132.166.73
2023 Aug 21 07:53:28 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 07:53:28 | [WAN.6][WDHCP] ignore renew wan_62 IP: 75.235.21.23
2023 Aug 21 07:38:23 | [WAN.6][WDHCP] bound wan_61 IP: 10.133.43.214
2023 Aug 21 07:38:23 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 07:23:18 | [WAN.6][WDHCP] bound wan_61 IP: 10.128.111.170
2023 Aug 21 07:23:18 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 07:08:13 | [WAN.6][WDHCP] bound wan_61 IP: 10.132.32.140
2023 Aug 21 07:08:13 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 07:03:24 | [WAN.6][WDHCP] bound wan_61 IP: 10.130.198.227
2023 Aug 21 06:53:01 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 06:53:00 | [WAN.6][WDHCP] ignore renew wan_62 IP: 75.235.21.23
2023 Aug 21 06:37:46 | [WAN.6][WDHCP] bound wan_61 IP: 10.129.212.96
2023 Aug 21 06:37:45 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 06:22:31 | [WAN.6][WDHCP] bound wan_61 IP: 10.133.251.212
2023 Aug 21 06:22:30 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 06:07:23 | [WAN.6][WDHCP] bound wan_61 IP: 10.134.55.118
2023 Aug 21 06:07:23 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 06:03:24 | [WAN.6][WDHCP] bound wan_61 IP: 10.134.44.191
2023 Aug 21 05:52:18 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 05:52:17 | [WAN.6][WDHCP] ignore renew wan_62 IP: 75.235.21.23
2023 Aug 21 05:36:43 | [WAN.6][WDHCP] bound wan_61 IP: 10.132.80.187
2023 Aug 21 05:36:42 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 05:21:30 | [WAN.6][WDHCP] bound wan_61 IP: 10.135.104.140
2023 Aug 21 05:21:30 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 05:06:22 | [WAN.6][WDHCP] bound wan_61 IP: 10.129.162.14
2023 Aug 21 05:06:22 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 05:03:23 | [WAN.6][WDHCP] bound wan_61 IP: 10.131.181.147
2023 Aug 21 05:03:23 | [WAN.6][WDHCP] deconfig wan_61
2023 Aug 21 05:03:23 | [WAN.6][WDHCP] bound wan_62 IP: 75.235.21.23
2023 Aug 21 05:03:22 | [WDHCP] ipv4 wan up
2023 Aug 21 05:02:50 | [WAN.6][WDHCP] deconfig wan_62
2023 Aug 21 05:02:49 | [WDHCP] ipv6 wan up
2023 Aug 21 05:02:02 | [WAN.6][WDHCP] bound wan_61 IP: 10.134.187.104

**Comment by DWomack** [comment]
The wan_61 stuff is the admin channel to manage the cube.  

The wan_62 stuff is WAN address of the cube.  This is your ip address seen from the cloud.

**Comment by DWomack** [comment]
Question: Is the Speedtest-cli code downloaded from Ookla each time just before each execution? Or when the docker is started?

Just looking of similarities with another app showing the same symptoms.  

Thanks.

**Comment by DWomack** [comment]
I have VZ 5G Home Internet via ASK Cube firmware fully patched.  

The issues ie: failures are due to the way the program handles errors that are returned by speedtest cli.  

Speedtest cli occasionally throws errors when on VZ. 

I installed the latest speedtest cli from Ookla on a box with Ubuntu 22.04 fully patched for testing.  Running it from the command line I see it error occasionally. 

I suspect the program is not catching the error and retrying the test when speedtest cli is called.

**Comment by DWomack** [comment]
dennis@xxxx:~$ speedtest --progress=no

   Speedtest by Ookla

      Server: Verizon - Nashville, TN (id: 30809)
         ISP: Verizon Wireless
Idle Latency:    33.71 ms   (jitter: 6.96ms, low: 28.28ms, high: 42.88ms)
    Download:   207.42 Mbps (data used: 374.1 MB)                                                   
                113.92 ms   (jitter: 37.85ms, low: 36.66ms, high: 615.84ms)
      Upload:    20.35 Mbps (data used: 26.3 MB)                                                   
                 83.73 ms   (jitter: 18.81ms, low: 45.79ms, high: 287.21ms)
 Packet Loss:     0.0%
  Result URL: https://www.speedtest.net/result/c/dc596e4c-1e78-4c2f-9c9d-f9aea781045d
dennis@xxxx:~$ speedtest --progress=no

   Speedtest by Ookla

      Server: Verizon - Nashville, TN (id: 30809)
         ISP: Verizon Wireless
Idle Latency:    34.34 ms   (jitter: 5.71ms, low: 29.98ms, high: 39.97ms)
     Latency: FAILED                                            
[error] Cannot read:

**Comment by alexjustesen** [comment]
That to me looks like a Speedtest server failing to run a test. Can you select a different one?

**Comment by DWomack** [comment]
Thanks for replying.  This is the sever that Speedtest selected.  It generally has the lowest ping. From the command line, I can re run the test and the test will complete.  The fail is not a permanent fail.  The problem could be with VZ’s wireless network or in Ookla’s code.  If your code detects an error returned wait 10 seconds and retry.  You might allow 5 retries.  I am not a php programmer so I can’t fix it.  There is a project called Speedtest-exporter written python.  It calls the Ookla code.  It exhibits the same problem. So the problem is Ookla code or VZ.  I am not criticizing your work, just trying to help it work in my situation.  Thank you. DennisSent from my iPhoneOn Aug 31, 2023, at 8:32 AM, Alex Justesen ***@***.***> wrote:﻿
That to me looks like a Speedtest server failing to run a test. Can you select a different one?

**Comment by DWomack** [comment]
Why am I using VZ 5G home internet?  $25 per month. Sent from my iPhoneOn Aug 31, 2023, at 9:11 AM, Dennis Womack ***@***.***> wrote:﻿Thanks for replying.  This is the sever that Speedtest selected.  It generally has the lowest ping. From the command line, I can re run the test and the test will complete.  The fail is not a permanent fail.  The problem could be with VZ’s wireless network or in Ookla’s code.  If your code detects an error returned wait 10 seconds and retry.  You might allow 5 retries.  I am not a php programmer so I can’t fix it.  There is a project called Speedtest-exporter written python.  It calls the Ookla code.  It exhibits the same problem. So the problem is Ookla code or VZ.  I am not criticizing your work, just trying to help it work in my situation.  Thank you. DennisSent from my iPhoneOn Aug 31, 2023, at 8:32 AM, Alex Justesen ***@***.***> wrote:﻿
That to me looks like a Speedtest server failing to run a test. Can you select a different one?

**Comment by alexjustesen** [comment]
No worries, I tried to hit the same server and got the fail as well. I think enabling some retries on failed speedtests is a good enhancement.

For future Alex or someone willing to do a PR the jobs and how to do retries can be found at the links below...

* https://github.com/alexjustesen/speedtest-tracker/blob/main/app/Jobs/ExecSpeedtest.php
* https://laravel.com/docs/10.x/queues#max-exceptions

**Comment by DWomack** [comment]
Thank you, thank you.

I just updated to your latest from two hours ago.  

This is docker running on UnRaid. 


Dennis

**Comment by alexjustesen** [comment]
> This is docker running on UnRaid.

I've got unraid too so I'll verify there as well

**Comment by DWomack** [comment]
I switched from the default VZ Nashville speedtest server to Comcast Nashville.  No errors.  The Nashville VZ server has issues as you saw.  I even see it with the Speedtest app on my phone.  On my phone I would normally use VZ Atlanta.

The reason for using a VZ server is that it stays in their network to connect to the cloud.  Anything else is going to have worse numbers.  

I really appreciate your help.

**Comment by DWomack** [comment]
While you are at it...

The selection of Speedtest server is a pulldown list of servers that Speedtest.net hands you.  

It would help if you could as an alternate just enter the server id number.  

As is it shows me servers around Nashville.  I would like to enter a server id that is in the Atlanta area.  

Thank you.

**Comment by alexjustesen** [comment]
> It would help if you could as an alternate just enter the server id number.

So you actually can if you know the ID of the server you want. Just start typing it in and it'll throw a weird message `[object object]` but that should allow you to use any server ID.

**Comment by alexdelprete** [comment]
> but that should allow you to use any server ID.

We discussed this issue in an old issue: that doesn't work, it leads to a "0" entry:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/7027842/64110cdf-5e09-4525-81f6-f2a46e6060ff)

The only way to add a manual server id I found is editing the mariadb record. :)

**Comment by DWomack** [comment]
VZ finally fixed the issue with their Nashville Speedtest.net server. 

It would help if the home page showed what server you were connecting to.

**Comment by alexjustesen** [comment]
> It would help if the home page showed what server you were connecting to.

So your results page will show which server was used for a successful speedtest, in the future I'll be looking to also log/show which server failed a test as well.
