### ISSUE TITLE
Speedtests are still a bit off..

### ISSUE THREAD

**Issue by JourneyOver** [alexjustesen/speedtest-tracker#69]
Even after the release with https://github.com/alexjustesen/speedtest-tracker/pull/49 implemented, the speeds that are displayed on the dashboard / results are still off from the actual results that the url displays / in the database.

Example:
Dashboard shows ---
![10-22-2022_20-36-32](https://user-images.githubusercontent.com/13910285/197368983-d161714c-30d0-43fa-ad5d-a0d1a5791dce.png)

but going into the database file and grabbing the url for said [run](https://www.speedtest.net/result/c/c648772c-9ff6-4c7c-ad85-9ad8563ef023) shows my actual download speed at `941.63` Mbps and upload at `41.62` Mbps.

The download and upload for the result in the actual database file are reported as:

Download: `117703158` Bytes which equals out the `941.625264` megabits
Upload: `5201880` Bytes which equals out the `41.61504` megabits

which with rounding, the information in the database file come out to where the url speeds are shown when converted, so the calculation is wrong somewhere in terms of the what the dashboard is showing for the speedtest tracker.

**Comment by alexdelprete** [comment]
OMG: I wrote [this](https://github.com/alexjustesen/speedtest-tracker/issues/48#issuecomment-1287472234) post thinking that in the db, in download/upload columns, since the values were so strange, they represented the amount of data sent/received for the test. :)

Thanks for the heads-up.

**Comment by JourneyOver** [comment]
> OMG: I wrote [this](https://github.com/alexjustesen/speedtest-tracker/issues/48#issuecomment-1287472234) post thinking that in the db, since the values were so strange in download/upload columns, they represented the amount of data sent/received for the test. I gave for granted that the conversions were finally fixed. :)
> 
> Thanks for the heads-up.

Lol it's not a problem. The way the json bit in the results section is laid out in the db file from what I can gather is that the `bandwidth` bit is the upload/download speeds in bytes as they are the same values as the upload/download in well the upload/download columns and when converting them to megabits (Mbps) they equal out to the upload/download values that are displayed when you go to the url for the test (albeit with rounding on speedtest.net side of things), while the `bytes` part of the json is actually the data sent/recieved for the test but they dont have their own columns like the upload/download (bandwidth) values do.

Currently the results on speedtest tracker however are still slightly off (more than likely due to a calculation error somewhere) even though the database file has the correct values for everything (short of the timezone stuff being of no-use at the moment as well).

**Comment by JourneyOver** [comment]
@alexjustesen so some testing and I have figured out the issue, in [helpers.php](https://github.com/alexjustesen/speedtest-tracker/blob/main/app/helpers.php) you are using the `Binary definition (1024)` to get the values when in most situations it's better to use `Decimal definition (1000)` to get the values.. Speedtest.net which is what we are using for speedtest tracker uses Decimal definition, which is why the values shown in the speedtest tracker dashboard / results page are showing a bit lower than the values from the speedtest.net url.

So all that really needs to be done is changing the `1024` to instead be `1000` in the helpers.php script. I've already gone and tested this myself, and upon actually changing the `1024` to `1000` in the helpers.php everything on the dashboard is now showing correct, short of the `created at` date ofc.

**Comment by alexjustesen** [comment]
Yeah that's absolutely right, thanks for doing the checking. I'll hopefully have time this morning to fix it. Good news it's just effecting the views

**Comment by alexdelprete** [comment]
So TZ and decimal/binary correction are the main issues right now. The good thing is that it's just the representation in the view, we don't need to clean the db. :)

**Comment by JourneyOver** [comment]
@alexdelprete yep exactly, only thing though is the TZ stuff once fully taken care of and implemented depending on the persons timezone it might show new test results being at an older time than the old test results if said person is behind UTC time, due to the actual database having the `created on` and the timestamp in the json in `data` set at the UTC time. Though we could probably write up something to convert the `created on` and the timestamp in the json in `data` to the corrected time..
