### ISSUE TITLE
Time is displaying as UTC even though my docker container is setup per the docs, and my timezone is set correctly in settings.

### ISSUE THREAD

**Issue by cmerkle** [alexjustesen/speedtest-tracker#696]
In the image below you can see that my latest speeders time is 4 hours ahead of the local time shown in the top left corner of my iPhone screen. I did set the time zone both in the docker compose file as well as in the speed test settings and I also created the volume with /etc/localtime

![image](https://github.com/alexjustesen/speedtest-tracker/assets/33108196/daaf4d9e-52ff-4a8d-970e-b0543ebfb713)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/33108196/fb9a24a5-91d9-46a3-884f-0572341d3c10)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/33108196/3d597cbf-b3a3-44bb-b329-7c31fb195910)

**Comment by luckman212** [comment]
I don't know if it's exactly the same bug, but I just built a brand new container with v0.11.20, and confirmed that `TZ` environment var is set correctly in the compose file. But, after creation, when I logged into the app for the first time, I had to set the Timezone manually from `UTC` to `America/New_York`

Does the `TZ` var need to be set on the MariaDB container as well? (it wasn't...)

**Comment by cmerkle** [comment]
After reading another issue, I tried removing the TZ env variable and the /etc/localtime volume from the docker-compose.yaml and then just setting the TZ in the GUI and that seems to work fine. Maybe update the docs to reflect this?

**Comment by bwirt** [comment]
> After reading another issue, I tried removing the TZ env variable and the /etc/localtime volume from the docker-compose.yaml and then just setting the TZ in the GUI and that seems to work fine. Maybe update the docs to reflect this?

Can confirm this worked for me.

**Comment by alexjustesen** [comment]
Adding to the discussions above...

Setting `TZ` as an environment variable and then mounting the system time updates the container's time zone but unfortunately PHP doesn't pick that up by default and defaults to `UTC`. This is why there is a setting for it currently so you can override `UTC` in views for your current time zone.

Fix planned after I get some other jank with Docker / resource usage fixed.
