### ISSUE TITLE
Connection refused - sqlite

### ISSUE THREAD

**Issue by mTrax-** [alexjustesen/speedtest-tracker#709]
**Describe the bug**
After the update today of the container, I wasn't able to connect to the web interface.
I checked the log and I have this error :
```
[2023-08-31 12:46:06] production.ERROR: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = speedtest_tracker and table_name = migrations and table_type = 'BASE TABLE')
{"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = speedtest_tracker and table_name = migrations and table_type = 'BASE TABLE') at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:801)
```

Then, the container is stopped.

```
31/08/2023 14:46:06
In Connection.php line 801:
31/08/2023 14:46:06
                                                                               
31/08/2023 14:46:06
  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select *  
31/08/2023 14:46:06
   from information_schema.tables where table_schema = speedtest_tracker and   
31/08/2023 14:46:06
  table_name = migrations and table_type = 'BASE TABLE')                       
31/08/2023 14:46:06
                                                                               
31/08/2023 14:46:06
31/08/2023 14:46:06
In Connector.php line 65:
31/08/2023 14:46:06
                                             
31/08/2023 14:46:06
  SQLSTATE[HY000] [2002] Connection refused
```

I'm not sure if it was working before the update, I've not checked the interface for the last few weeks.

**Environment (please complete the following information):**
 - OS:  Ubuntu
-  Architecture: amd64
 - Version: speedtest-tracker_speedtest-tracker updated from ae7429d0e6 to 6991db2ade -  v0.11.20

**Comment by luckman212** [comment]
I was getting similar messages, trying to set up a fresh 0.11.19 (now 0.11.20) but I realized I was just being too aggressive on the timing. It was taking ~30 seconds for my MariaDB container to start up and become ready, so even though there were errors in the log, instead of hitting ⌃c right away, just allowing the main container to restart a few times eventually everything settled, and is now working on 0.11.20 + MariaDB.  A 2-day saga comes to a happy ending 🚀...

**Comment by alexjustesen** [comment]
I left a comment in #701 but the TL;DR is make sure to pass `DB_CONNECTION=sqlite` as an environment variable.
