### ISSUE TITLE
Database file does not exist - sqlite

### ISSUE THREAD

**Issue by briankavanaugh** [alexjustesen/speedtest-tracker#710]
With the new update v0.11.20, I'm getting the below error. I checked, and the database file is still where it has always been.

[previous exception] [object] (Illuminate\\Database\\SQLiteDatabaseDoesNotExistException(code: 0): Database file at path [/var/www/html/database/database.sqlite] does not exist. Ensure this is an absolute path to the database. at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php:34)

My docker compose file is:

version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '9080:80'
            - '9443:443'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - './config:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped

And the database is in the config file:

bkavanaugh@docker2:~/docker/speedtest-tracker/config$ ls
database.sqlite

**Comment by alexjustesen** [comment]
Check out #701 and #709
