### ISSUE TITLE
Feature Request - Show average Download / Upload / Ping Stats in Dashboard

### ISSUE THREAD

**Issue by Pureball** [alexjustesen/speedtest-tracker#712]
Hi Alex,

in the Dashboard Overview you compare the upload / download / ping stats with the previous results and compare them if they were faster or slower:

`$downloadChange = percentChange($result->download, $previous->download, 2);`
`$uploadChange = percentChange($result->upload, $previous->upload, 2);`
`$pingChange = percentChange($result->ping, $previous->ping, 2);`

I can only speak for myself but I find comparing the previous results with the current results not very valuble instead I think you should calculate the average of all results for the upload / download / ping tabs and present the result (as it is done in the original version).

I think this would add more value to the user as he can see at a glance what his average up / down and ping speeds are.

Thank you for considering and keep up the good work!

**Comment by alexjustesen** [comment]
Closing as duplicate, treating #243 as the parent for this feature request.
