### ISSUE TITLE
500 SERVER ERROR"

### ISSUE THREAD

**Issue by dylanrhodes0** [alexjustesen/speedtest-tracker#714]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
-  Architecture: [e.g. arm64, amd64]
 - Version [e.g. v1]

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by repcsi** [comment]
@dylanrhodes0 Seems to be a duplicate of #715, if that's true, can you please close this one?
