### ISSUE TITLE
Unable insert into InfluxDB2 with version 0.11.21

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#725]
**Describe the bug**
Unable insert into InfluxDB2 with version 0.11.21

**To Reproduce**
Update to 0.11.21

**Expected behavior**
Insert Value in influxDB2

**Environment (please complete the following information):**
 - OS: Raspian Bullseye and Debian 11
-  Architecture: arm64, amd64
 - Browser Opera, Chrrome
 - Version 0.11.21

**Logs**
```
Next InfluxDB2\ApiException: [422] Client error: `POST http://192.168.2.190:8286/api/v2/write?org=corasaniti&bucket=speedtest-tracker&precision=s` resulted in a `422 Unprocessable Entity` response:
{"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input  (truncated...)
 in /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php:125

Stack trace:
#0 /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php(83): InfluxDB2\DefaultApi->request()
```

**Comment by alexjustesen** [comment]
That's something I didn't experience during testing.

I'll have to look into the error code.

**Comment by alexjustesen** [comment]
@corasaniti was the (truncated) part something you did or the logs? Any chance you can share a full log?

**Comment by corasaniti** [comment]
@alexjustesen 
This is the log from Portainer. How do I get the full log?
Thanks

**Comment by alexjustesen** [comment]
@corasaniti can you...

1. Set `LOG_LEVEL=debug`
2. Restart the container
3. Run a speedtest
4. Capture the error again and see if it throws some more details

**Comment by alexjustesen** [comment]
I get the feeling it's because some fields are now `null` when no data exists instead of `0`. Do you have any filters that art integer or float limited?

**Comment by corasaniti** [comment]
can I set `LOG_LEVEL=debug` in env docker run?

**Comment by Jiriteach** [comment]
As a heads up - I just tried a new install of Influxdb2 and 0.11.21 and its working with no problems so far.

**Comment by corasaniti** [comment]
@alexjustesen
I enabled `LOG_LEVEL=debug` in my docker run but the log is still truncated
This is the log from Portainer
[_speedtest-alexjustesen_logs.txt](https://github.com/alexjustesen/speedtest-tracker/files/12516437/_speedtest-alexjustesen_logs.txt)



@Jiriteach 
Maybe it works on a fresh InfluxDB2 installation but not on an existing one

**Comment by alexjustesen** [comment]
> As a heads up - I just tried a new install of Influxdb2 and 0.11.21 and its working with no problems so far.

This is probably why my testing didn't capture the error, created a new influxdb instance

**Comment by corasaniti** [comment]
@alexjustesen 
I have not tried a fresh install of InfluxDB2 as I want to keep my data. 
Probably the error occurs only on an already existing Influxdb2 installation. Here is the info of my InlfuxDB2 server
```
InfluxDB v2.7.1
Servers: 407fa62
Frontend: 9d25a2f
```

**Comment by Jiriteach** [comment]
Could be related to a timestamp issue or the rentention policy on your Influxdb - 
https://community.influxdata.com/t/telegraf-outputs-influxdb-v2-plugin-error-422-unprocessable-entity/18926

**Comment by alexjustesen** [comment]
Sooo, was able to track it down to `packet_loss` being the problem....

```
[2023-09-04 20:54:22] local.INFO: InfluxDB2\ApiException: [422] Error connecting to the API (//influxdb:8086/api/v2/write?org=homelab&bucket=speedtest-tracker&precision=s)(: failure writing points to database: partial write: field type conflict: input field "packet_loss" on measurement "speedtest" is type integer, already exists as type float dropped=1) in /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php:157
```
