### ISSUE TITLE
500 Error - Logs: Encryption error

### ISSUE THREAD

**Issue by benjie500** [alexjustesen/speedtest-tracker#734]
**Describe the bug**
When trying to browse to the web interface I am getting a "500 Server Error".

When looking at the logs I see the following:

`[2023-09-05 21:27:09] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
[2023-09-05 21:29:10] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
172.18.0.1 - - [05/Sep/2023:21:29:10 +0100] "GET / HTTP/1.1" 500 6622 "-" "Uptime-Kuma/1.23.1"

[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(77): tap()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(60): Illuminate\\Encryption\\EncryptionServiceProvider->key()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\\Foundation\\Application->make()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
#18 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
"} 
#19 {main}`

I am using WatchTower to pull done the latest image and recreate the container automatically.

My conatiner is running the following image; 

`ghcr.io/alexjustesen/speedtest-tracker:latest@sha256:edc453807258efb9bdb2afedebe4f6f0ce7507f6ac52315c5e95df3daac1f426`

**To Reproduce**
My Docker Compose file is set to the follow:

`speedtest_tracker:

    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'

    volumes:

        - $DOCKER_DIR/speedtest_tracker:/config
 
        - '/etc/localtime:/etc/localtime:ro'
 
    environment:

        - DB_PASSWORD=<redacted>
     
        - DB_USERNAME=<redacted>
       
        - DB_DATABASE=<redacted>

        - DB_PORT=3306

        - DB_HOST=<redacted>

        - DB_CONNECTION=mysql

        - TZ=Europe/London

        - TELEGRAM_BOT_TOKEN=<redacted>

        - TELEGRAM_CHAT_ID=<redacted>

    ports:

        - '8082:80'

    restart: always

    depends_on:

      - mysql`

    

**Expected behavior**

To be able to get to log on page and dashboard

**Environment (please complete the following information):**
 - OS: Docker Container on Debian
 -  Architecture:  amd64
 - Browser: Chome
 - Version:  Latest (Image listed above)

**Logs**

Docker log above

**Comment by samcro1967** [comment]
Seeing the same behavior after the latest update also.

**Comment by Jiriteach** [comment]
Restart the container - fixes the issue else you need to make sure APP_KEY is set on the .env file.

**Comment by samcro1967** [comment]
I do have an API key in .env already and tried a container restart, but still get the same results.

**Comment by benjie500** [comment]
In the mounted volume, I have a ".env" file and it does contain a value for "APP_KEY=base64:<redacted>"

I have restarted the container multiple times.

**Comment by benjie500** [comment]
Thanks @paralovosca, I have now added APP_KEY as an environment variable in my docker compose file. It would be good to update the documentation to include setting the APP_KEY as environment variable in docker compose and docker run command.

**Comment by vdrover** [comment]
Where can i get the APP_KEY? Until then, I downgraded to [v0.11.22](https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.22).

**Comment by alexdelprete** [comment]
> Where can i get the APP_KEY? Until then, I downgraded to [v0.11.22](https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.22).

You can find AGAs in other issues/discussions, you can search the repo: https://github.com/alexjustesen/speedtest-tracker/issues/711#issuecomment-1701229147
