### ISSUE TITLE
SSO Support (OpenID or SAML)

### ISSUE THREAD

**Issue by alexsalex** [alexjustesen/speedtest-tracker#742]
**Is your feature request related to a problem? Please describe.**
It will be really nice to have, 2FA authentication etc.

**Describe the solution you'd like**
I would like to login with Keycloak or Authelila to the application

**Comment by alexjustesen** [comment]
Follow #344 for 2fa and linking to #361 so lineage on SSO is maintained.

**Comment by alexsalex** [comment]
I do not need 2FA from application. I need ONE login and PASWWORD for all my servises. I'm using Keycloak and would like to use it with Speedtest-Tracker.

**Comment by alexsalex** [comment]
there is no duplicate!!!

**Comment by alexdelprete** [comment]
> I do not need 2FA from application.

What does that even mean? You need ST to support 2FA. That's already been requested, as Alex told you.
