### ISSUE TITLE
Not able to connect to front end after ugrading

### ISSUE THREAD

**Issue by pwsnla** [alexjustesen/speedtest-tracker#748]
I just upgraded my version of speedtest-tracker by pulling the latest version available today (8-Sep-2023) and it looks like there is an issue with front end. I am getting 500 Server Error when trying to connect. See below for errors that are logged in the log.

**To Reproduce**
Upgrade speedtest-tracker docker container and restart. Container restarts but attempts to connect to front end fail with error 500.

**Expected behavior**
Be able to connect to speedtest-tracker front-end

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
-  Architecture: arm64
 - Browser Firefox
 - Version Latest

**Screenshots**

**Logs**
[2023-09-08 06:35:00] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)

[stacktrace]

#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()

#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(77): tap()

#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(60): Illuminate\\Encryption\\EncryptionServiceProvider->key()

#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()

#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()

#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()

#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()

#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()

#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()

#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()

#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()

#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()

#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()

#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()

#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()

#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()

#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\\Foundation\\Application->make()

#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()

#18 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()

#19 {main}

**Additional context**

**Comment by Jiriteach** [comment]
Restart the container - if that still fails you need to set APP_KEY in your .env file. See the closed issues. Been a few opened about this issue and they include info on how to get your app key if need.

**Comment by pwsnla** [comment]
I am not quite sure that I understand what the issue is because multiple restarts did not help and APP_KEY was already set in the .env file.

Based on the comments in other issues I've added the same key that was in .env file in my docker compose and that seemed to fix it. Anyway, I will close this now.

**Comment by Jiriteach** [comment]
Should be addressed properly in the next release. There is a PR for this being worked on.

**Comment by alexjustesen** [comment]
#746 was merged yesterday but still working on #736 so it hasn't made a production release yet. Beta release `v0.12.0-beta.4` is incoming shortly should you want to try that one.
