### ISSUE TITLE
Upgrade to latest version of serversideup/docker-php

### ISSUE THREAD

**Issue by jaydrogers** [alexjustesen/speedtest-tracker#750]
### Background
serversideup/docker-php is getting a major overhaul (v3.0). There could be breaking changes that affect this project.

### Current status
Everything currently is in development, but I'd love to have your feedback as I create this new version.

### Project Status
Track this board for the latest:
- https://github.com/orgs/serversideup/projects/14

### Related PRs
This PR specifically is one that could have breaking changes for this project:
- https://github.com/serversideup/docker-php/pull/205

**Comment by alexjustesen** [comment]
Thanks for the heads up Jay!

**Comment by jaydrogers** [comment]
@alexjustesen:

Can you give me some brief examples of where people are mainly running this? I assume it's a bunch of home lab people mainly?

I would guess that means:
- RasperryPis
- Synology
- Unraid
- Proxmox
- etc?

Am I missing anything?

**Comment by alexjustesen** [comment]
Nailed it, with Docker as well. I'm drinking some sponsor dollars at the state fair but happy to help test soon as well

**Comment by alexjustesen** [comment]
@jaydrogers how's progress? At a point where I can start testing?

**Comment by jaydrogers** [comment]
Hope you had a great Thanksgiving @alexjustesen!

Still working on cleaning up a few ends. I am currently documenting the changes this week. Here is what I have so far: https://release-v3-0.docker-php.pages.dev/docs/guide/migrating-from-v2-to-v3

That is a **very alive** document that will be changing a lot as I go through deploying these new images for our own projects.

Will keep you posted as I progress!

**Comment by jaydrogers** [comment]
Beta is available here 🥳 https://github.com/serversideup/docker-php/discussions/254

**Comment by jaydrogers** [comment]
Bummer! They beat me to the punch!! Hahaha, it's fine 😃

It was on my list to submit a PR to this project giving you Spin, GitPod development, etc all running on our new Alpine images. I just wanted to get the beta more stabilized.

Glad you got connected with the LinuxServer folks. They are great people and a wonderful community! Let me know if you need any help in the future 👍

**Comment by alexjustesen** [comment]
Will do man! Got some other projects that I'll take for a _Spin_ 🤣
