### ISSUE TITLE
Tag latest stable image differently

### ISSUE THREAD

**Issue by abelfodil** [alexjustesen/speedtest-tracker#751]
**Is your feature request related to a problem? Please describe.**

Latest tag pulls the latest version, even if it's a beta version. This can lead to instability and breakage. For instance, an APP_KEY was recently introduced and it broke my flow because of auto-updates.

**Describe the solution you'd like**

Tag latest stable version differently with a tag like `stable`.

**Additional context**

**Comment by alexjustesen** [comment]
Closing as duplicate, already mentioned what happened in another issue/discussion but can't find it ATM.

**Comment by alexdelprete** [comment]
> it broke my flow because of auto-updates

Your flow breaks because you don't use strict versioning. `latest` tag doesn't imply stable, that's up to the maintainer. for some projects `latest` might mean bleeding edge.

best practice for reliability is to use strict version tags, and not rely on latest.

**Comment by alexjustesen** [comment]
> > it broke my flow because of auto-updates
> 
> Your flow breaks because you don't use strict versioning. `latest` tag doesn't imply stable, that's up to the maintainer. for some projects `latest` might mean bleeding edge.
> 
> best practice for reliability is to use strict version tags, and not rely on latest.

☝️ this, but next tagged `latest` will be stable releases.

**Comment by alexdelprete** [comment]
> this, but next tagged `latest` will be stable releases.

good to know, but my homelab docker containers will never rely on `latest` tag, because even a "stable" release could break things, or maybe a dev could tag latest to an alpha release by mistake. ;)
