### ISSUE TITLE
Container tries MySQL migrations when not using MySQL as database backend

### ISSUE THREAD

**Issue by devtobi** [alexjustesen/speedtest-tracker#753]
**Describe the bug**
I tried running the speedtest tracker container with SQLite as backend. However, whenever the container starts, it tries to connect to a MySQL database and do the migrations. I have not set any environment variables that indicate I want to use MySQL, so I guess the default SQLite is not picked correctly.

**To Reproduce**
1. Only set the env variables ``PUID`` and ``PGID`` for the container
2. Start the container

**Expected behavior**
The container should start up with SQLite as database backend

**Environment (please complete the following information):**
 - OS: Synology DSM
 - Architecture: amd64
 - Browser: -- not relevant
 - Speedtest-Tracker-Version: 0.11.22

**Screenshots**

**Logs**
```
🐇  Configuring Speedtest Tracker...
🔒  Fixing app path file permissions...
✅  Permissions fixed.
🔗  Creating database symlink...
✅  Database symlink created.
✅  Environment file exists.
🔗  Creating symlinks for config and log files...
✅  Symlinks created.
✅  App key exists
💰  Building the cache...
✅  Cache set.
🚛  Migrating the database...
[2023-09-11 14:45:04] production.ERROR: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE') at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:801)
```

**Comment by alexjustesen** [comment]
As environment variables you'll need to set the following as SQLite is no longer the default database as of `v0.11.20`. Referencing #701

```
DB_CONNECTION=sqlite
DB_DATABASE=/config/database.sqlite
```

**Comment by devtobi** [comment]
Thanks for that quick answer. I wasn't able to find that information in the official documentation so that's why I was a bit confused, but now also found the new default for mysql in ``database.php``. Does the .sqlite file have to be created manually, or is the container able to do so on startup if not found?

**Comment by alexjustesen** [comment]
If it's a new install you'll need to create the file, if its an existing sqlite file you'll be all set.

**Comment by BobFlapjack** [comment]
> If it's a new install you'll need to create the file, if its an existing sqlite file you'll be all set.

How do we create the file?

**Comment by alexjustesen** [comment]
> How do we create the file?

If you have a new install I strongly recommend using MySQL/MariaDB or Postresql as your database as SQLite isn't an officially supported option anymore. You just need to create an empty file in your mounted volume or directory called `database.sqlite`.

It does work, and you can use it. But just because you can, doesn't mean you should.

**Comment by BobFlapjack** [comment]
>You just need to create an empty file in your mounted volume or directory called database.sqlite.
As simple as `touch database.sqlite`?  Thanks.
