### ISSUE TITLE
duckdb support

### ISSUE THREAD

**Issue by zyystudio** [alexjustesen/speedtest-tracker#763]
**Is your feature request related to a problem? Please describe.**
--duckdb is getting popular now. unlike pg or mysql, it doesn't need installation.

**Describe the solution you'd like**
--add duckdb jdbc driver is enough.

**Additional context**
--n/a

**Comment by alexjustesen** [comment]
Thanks for the suggestion but that this time doesn't look like there's good options for PHP/Laravel support. 

To keep complexity down I'll only be supporting what the core framework does from a database perspective. 

https://laravel.com/docs/10.x/database#introduction
