### ISSUE TITLE
Database failure after upgrade to v0.11.22

### ISSUE THREAD

**Issue by MPHxxxLegend** [alexjustesen/speedtest-tracker#765]
**Describe the bug**
Cant start container after update to v0.11.22
Has to stick to v0.11.17

**Environment (please complete the following information):**
 - OS: Unraid
-  Architecture: amd64
 - Browser Firefox
 - Version v0.11.22

**Logs**
```
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.

In Connection.php line 801:
                                                                               
  Database file at path [/var/www/html/database/database.sqlite] does not exi  
  st. Ensure this is an absolute path to the database. (Connection: sqlite, S  
  QL: PRAGMA foreign_keys = ON;)                                               
                                                                               

In SQLiteConnector.php line 34:
                                                                               
  Database file at path [/var/www/html/database/database.sqlite] does not exi  
  st. Ensure this is an absolute path to the database.
``` 

**Additional context**

**Comment by alexjustesen** [comment]
Check out #705 for a resolution

**Comment by mariushosting** [comment]
> Check out #701 for a resolution

@alexjustesen Unfortunately this is not working anymore with this resolution here if you install it in a Docker on a Synology NAS. Only v0.11.17 is working right now on a Synology NAS system.

**Comment by alexjustesen** [comment]
[Using SQLite](https://docs.speedtest-tracker.dev/faqs#using-sqlite) added to FAQ

**Comment by alexjustesen** [comment]
> @alexjustesen Unfortunately this is not working anymore with this resolution here if you install it in a Docker on a Synology NAS. Only v0.11.17 is working right now on a Synology NAS system.

Can you open a new issue for that so it's not lost?
