### ISSUE TITLE
Content width missing in 0.12.0-beta.5 version

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#766]
Hi,
"Content width" missing in the settings of version 0.12.0-beta.5. It was very useful to have the graph in full screen mode.
In addition, **the time and date of the last result** is also missing from the dashboard
Has it been removed or will it be restored?
Thank you

**Comment by alexjustesen** [comment]
> In addition, **the time and date of the last result** is also missing from the dashboard
> Has it been removed or will it be restored?

So this was done on purpose for the time being. There's an issue with Filament v3 where the method I was using to display that timestamp would cause charts to disappear: #756

Once it's fixed I'll bring back that timestamp.

**Comment by corasaniti** [comment]
@alexjustesen 
Do you think you can parameterize the font size in the header and in the results table with an environment variable?
Thanks

**Comment by alexjustesen** [comment]
At the moment there doesn't seem to be a native way to do that in Filament. I'll keep an eye out in case it's added but for now I'm going to say probably not. 

https://filamentphp.com/docs/3.x/panels/themes/

**Comment by corasaniti** [comment]
@alexjustesen 
Just one more question. What is the page where the sidebar is created? I would like to add the sidebarCollapsibleOnDesktop flag. Why did you remove it, do you plan to restore it? By collapsing the sidebar I could recover space in my 4:3 screen
Thank you

**Comment by alexjustesen** [comment]
Oops, forgot about that...

Here are the docs for it, PR welcome and the file is located at `app/Providers/Filament/AdminPanelProvider.php`.

https://filamentphp.com/docs/3.x/panels/navigation/#collapsible-sidebar-on-desktop

**Comment by corasaniti** [comment]
@alexjustesen 
It doesn't matter, if you restore it in the next release I can wait. I thought you deleted it...

**Comment by alexjustesen** [comment]
They moved from config based features to methods based so it was their upgrade process that didn't pick it up and I don't use it so didn't notice

**Comment by corasaniti** [comment]
Thanks, I'll wait for the next release

**Comment by corasaniti** [comment]
@alexjustesen 
Hi Alex I'll leave you a reminder for the next release.
In the dashboard, the arrows indicating the ping trend appear to be backwards. See attach Thanks
![Cattura](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/547e6d12-d33c-4b05-87c8-71adf09c1c47)

**Comment by alexjustesen** [comment]
So that one is correct, lower ping is better

**Comment by corasaniti** [comment]
Hi, No, in my opinion the string must be green but the arrow points up. The upward arrow indicates a better result. 
That's how it was in previous versions...
Thanks

**Comment by alexjustesen** [comment]
I think I chatted about this before somewhere let me see if I can dig that up.

**Comment by alexjustesen** [comment]
@corasaniti https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.12.0-beta.6 collapsible sidebar rolling out
