### ISSUE TITLE
Additional Filters for Graphs - 3h, 6h, 12h

### ISSUE THREAD

**Issue by Jiriteach** [alexjustesen/speedtest-tracker#770]
It would be great to add additional filters for graphs please. 

Last 3h
Last 6h
Last 12h

I run tests every 30 mins and in a 24h view - the graphs are way too full.
Further - would be awesome to have a config option to set default view of this as well so it persists every time.

Thanks

**Comment by alexjustesen** [comment]
Dashboard filters now available: https://filamentphp.com/docs/3.x/panels/dashboard#filtering-widget-data

**Comment by alexjustesen** [comment]
Closing and attaching to original request #448
