### ISSUE TITLE
General  Settings Page Error 500 in 0.12 version

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#792]
With 0.12 verrsion

When I enter the general settings page I get a server error 500 and I am forced to click to close the error.
The page doesn't seem to work fine, infact it doesn't allow me to search for the server from which to perform the speedtest.
If I start typing in the Speedtest Server field I don't get any suggestions and I'm not able to choose the server
Thank you

**Comment by dreamwhite** [comment]
I have the same error. Seems like the issue is described by this log line:

```speedtest-tracker       | [2023-09-19 23:02:04] production.ERROR: App\Filament\Pages\Settings\GeneralPage::App\Filament\Pages\Settings\{closure}(): Argument #1 ($item) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 585 {"userId":1,"exception":"[object] (TypeError(code: 0): App\\Filament\\Pages\\Settings\\GeneralPage::App\\Filament\\Pages\\Settings\\{closure}(): Argument #1 ($item) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 585 at /var/www/html/app/Filament/Pages/Settings/GeneralPage.php:105)
```

**Comment by Jiriteach** [comment]
I've seen this issue setting up a new instance where the db is blank. I've had to use an existing backup of the db or manually insert the record to prevent this issue from happenning, once done, it can be managed via settings. There is another issue opened along the same lines.

**Comment by Jiriteach** [comment]
Issue here - https://github.com/alexjustesen/speedtest-tracker/issues/789

**Comment by dreamwhite** [comment]
Hi, thank you for your reply. Can you please tell me which setting you changed in the db to fix this issue?

**Comment by Jiriteach** [comment]
> Hi, thank you for your reply. Can you please tell me which setting you changed in the db to fix this issue?

See the linked issue.

**Comment by dreamwhite** [comment]
Oh alright, seems to have fixed it.

From a fresh install, I had to manually attach to the container and run the following commands:

```
docker exec -ti speedtest-tracker-db-1 bash
mysql -uUSER -pPASSWORD
use speedtest_tracker
select * from settings where id = 4;
```

this lead to the following result

```
+----+---------+------------------+--------+---------+---------------------+---------------------+
| id | group   | name             | locked | payload | created_at          | updated_at          |
+----+---------+------------------+--------+---------+---------------------+---------------------+
|  4 | general | speedtest_server |      0 | [null]  | 2023-09-19 22:53:15 | 2023-09-19 23:01:53 |
+----+---------+------------------+--------+---------+---------------------+---------------------+
```
then run `UPDATE settings SET payload = '[]' where id = 4;`

**Comment by corasaniti** [comment]
Close this issue as duplicate of https://github.com/alexjustesen/speedtest-tracker/issues/789
