### ISSUE TITLE
Timezone Problem

### ISSUE THREAD

**Issue by zackmuc** [alexjustesen/speedtest-tracker#800]
**Describe the bug**
I set my timezone to Europe/Berlin and it is 12:03 but in the UI i see 10:03

**Expected behavior**
12:03 should be shown 

**Environment (please complete the following information):**
 - OS: Docker
-  Architecture: arm64
 - Browser Edge
 -

**Comment by juhnu1** [comment]
I have the same problem.
Otherwise thank you for great app

**Comment by zackmuc** [comment]
Can be closed solution is here: 

https://github.com/alexjustesen/speedtest-tracker/issues/659#issuecomment-1639104087
