### ISSUE TITLE
Lost admin rights after docker image updated

### ISSUE THREAD

**Issue by alexsalex** [alexjustesen/speedtest-tracker#802]
**Describe the bug**
Lost admin rights after docker image updated

Everything works as expect. Only one thing: I'm not the admin for SpeedTracker. Could somebody help me to get admin rights back without lost the statistics?

**Comment by alexsalex** [comment]
Never mind, add admin attribute in DB
Thank you

**Comment by alexjustesen** [comment]
There's also a cli command now to help fix roles. Check out the docs section.
