### ISSUE TITLE
Timezone on WEB Not Correct

### ISSUE THREAD

**Issue by rssmithtx** [alexjustesen/speedtest-tracker#805]
Running on Docker through Linux mint.  Selected America/Chicago (US Central TIme) via setup page.  Times showing on the Web page are roughly 5 hours ahead of the time.  I have verified that the time on the server is correct tz.

**Comment by alexjustesen** [comment]
So setup covers the container tz but not the display tz which is recorded as GMT. You'll want to also change the display tz in General settings.

**Comment by rssmithtx** [comment]
Within Speedtest-tracker on the general tab.  I have selected the America/Chicago TZ.  However on the dashboard and within results tab the time is displaying 5 hours ahead of my time zone.  Just as additional information.  I have also updated the time format to Y-m-d H:i:s and what I am seeing is 2023-09-22 15:00:23 in both places.   Funny enough I selected America/Adak and the time does correct itself.  It may be some issue with the America/Chicago?  PHP related?

**Comment by alexjustesen** [comment]
I'd expect to see an issue regardless of tz but worth digging into.

Also make sure you pass tz as an environment variable too

**Comment by 1985xman** [comment]
i've got the same issue.
idk if it helps:
I'm in Europe/Berlin and it only shows timestamps -2hours.
It shows the correct time if i update the Time Zone under general to Asian/Baku.
Then I've updated the timezone in my RaspberryPi at the end of the  update it shows me the current "local time" and current "universal time" which is (local time)-2 hours. At least in my case the "universal time" is the same time zone as if i run a speedtest.

**Comment by alexjustesen** [comment]
I'm going to wrap this into upcoming time zone work in a couple releases from now. TZ has been a massive annoyance and I know somewhere in past issues some were able to resolve it.

**Comment by alexjustesen** [comment]
#659 might help... linking to it anyways as that and #194 are the core issues tracking things with time.

**Comment by schmintendo** [comment]
I think I found the problem!

My speedtest-tracker-db instance's date is wrong, when the speedtest-tracker is correct.

![image](https://github.com/alexjustesen/speedtest-tracker/assets/31830900/c09abacd-f98f-4f1f-8e9e-bd0494040223)

**Comment by louisot** [comment]
Hello, 

I agree with @schmintendo I had for a few months this bug and I updated the current docker file with the mariadb in my docker and had the same issue, but I logged into the terminal of the db container and used this command to check what was the time.

I'm using portainer to admin my containers.

assuming you are root if not use SUDO

$ `date -R` and gave me the UTC

since I'm in other region I need to change it. Replace /Country/City for the correct one for you.

$ `ln -sf /usr/share/zoneinfo/Country/City /etc/localtime`

and I redeployed the containers and the time was fixed.

**Comment by thomprn** [comment]
If I can be of any help, here's my experience.

When I run a speedtest manually, the time displayed on the graph and result is always the local time +2h. Example: Manual test at 1:00 p.m., result on graph and result 3:00 p.m. instead of 1:00 p.m.

On the other hand, when it's a shceduled speedtest, the correct time is displayed in the graph and results.

Problem appears only on manual speedtest on my side
Thx

**Comment by PDXUser** [comment]
I have the same issue - I think the container is ignoring the settings:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/20736534/19d06efa-acb8-4998-9fee-1158aa9673be)

The top is the container's time zone which shows as being incorrectly.  I'm in the Pacific Time zone. (America/Los_Angeles)

Since we can't use  the timdatectl within the container, I don't know of a way to set the timezone manually, which I think would also be overwritten if the container was updated or restarted anyway.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/20736534/5244493c-a5ae-47f4-bbf5-1dd7f4427f79)

**Comment by pingZan** [comment]
I have the same problem, maybe it can help
if the time in your docker container is the same as the system time then simply delete this section in the docker compose file
```
volumes:
    **- '/etc/localtime:/etc/localtime:ro'**
    - ...
    - ...
```

then set the TZ variable to your zone and run again, or set it in General Settings on the web UI

**Comment by pingZan** [comment]
using the `/etc/localtime:/etc/localtime:ro` volume might make it double, in my case it should be UTC+7, but it's UTC+5 in the web UI
when the volume is removed it works as it should

**Comment by PDXUser** [comment]
I commented mine out, and it's correctly showing the time:
```        volumes:
#            - '/etc/localtime:/etc/localtime:ro'
            - '/mnt/storage/docker/appdata/speedtestracker:/config'
            - '/mnt/storage/docker/appdata/speedtesttracker/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
```
So this solution works.

**Comment by rssmithtx** [comment]
This solution appears to work for me also.   Thank you.

**Comment by rssmithtx** [comment]
Commented out and Reloaded and time is correct.  Solution worked for me also.

**Comment by roeberp** [comment]
Commenting out  - '/etc/localtime:/etc/localtime:ro' worked for me as well.

**Comment by alexjustesen** [comment]
I really don't want to deal with time but here we gooo... https://github.com/alexjustesen/speedtest-tracker/pull/846

**Comment by DCG81** [comment]
> I have the same problem, maybe it can help if the time in your docker container is the same as the system time then simply delete this section in the docker compose file
> 
> ```
> volumes:
>     - '/etc/localtime:/etc/localtime:ro'
>     - ...
>     - ...
> ```
> 
> then set the TZ variable to your zone and run again, or set it in General Settings on the web UI

thanks this worked :)

**Comment by hoangtran355** [comment]
I had to remove these setting from both speedtest-tracker and speedtest-tracker-db, now it work!
```
    volumes:
      #- /etc/localtime:/etc/localtime:ro

    environment:
      TZ: $TZ
```

**Comment by Deses** [comment]
I'm also having the incorrect datetime in my UI.

Both my postgres and speedtest-tracker containers `date -R` report the correct time.

speedtest-tracker container has `Europe/Madrid` as the Container Variable: `TZ`.
I set the same in the UI settings, but then my graph times are +1 from my current local time.

My workaround has been to set `Europe/London` in the UI for the time being.

**Comment by xragon** [comment]
FWIW commenting out the timezone setting in the volumes section of the docker-compose also resolved this issue for me. Thanks.

**Comment by sloke123** [comment]
Thanks, everyone. Commenting out the local time volume does the trick.

**Comment by dbmtrde** [comment]
I had the same problem and solved it by adding the time zone in Mariadb service environment. 

version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TZ=America/Chicago
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/path/to/directory:/config'
            - '/path/to/directory/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
            **- TZ=America/Chicago            # Added this line**
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:
