### ISSUE TITLE
Homepage dashboards support

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#81]
The following selfhosted homepages reference Speedtest Tracker data for widgets:
- [ ] [benphelps/homepage](https://github.com/benphelps/homepage)
- [ ] [causefx/organizr](https://github.com/causefx/Organizr/tree/v2-master)

**Comment by derpindialer** [comment]
Can we add Heimdall to this list?

- [ ] [linuxserver/Heimdall](https://github.com/linuxserver/Heimdall)

**Comment by zvarg** [comment]
Waiting for homepage support ;)

**Comment by philhagger** [comment]
Would love this!

**Comment by zvarg** [comment]
I am quietly announcing that @alexjustesen is not authorized to delay this feature to later milestone rather than   [v0.14.0](https://github.com/alexjustesen/speedtest-tracker/milestone/8) 🤣🤣

**Comment by alexjustesen** [comment]
Working a bit slower these days... https://twitter.com/alexjustesen/status/1629641625868681223?t=2kDg6llnqM1hqNvfJhk4jw&s=19

**Comment by cinderblockgames** [comment]
How are you converting download/upload into Mbps on the Result detail modal? I've almost got this working, but I need to do the same conversion.

**Comment by alexjustesen** [comment]
@cinderblockgames there is a broken ass method currently doing that conversion, it might be better in the API to not covert any metrics and instead report them as the bytes their stored as.

This also reminds me, I need to create a data model so each attribute is well defined.

**Comment by cinderblockgames** [comment]
@alexjustesen The issue is that Homepage expects it as Mbps. My widget currently shows 45 Tbsp speeds, lol.

**Comment by SAS-1** [comment]
yeah I was playing with it in PowerBI and ended up using this conversion
Download/125000 
rounding to 2 decimal places
same with upload, it looked right when doing a manual check to the web interface. 
Getting it stored properly would be helpful though

**Comment by shamoon** [comment]
> @alexjustesen The issue is that Homepage expects it as Mbps. My widget currently shows 45 Tbsp speeds, lol.

Homepage expects it in bytes

**Comment by alexjustesen** [comment]
> > @alexjustesen The issue is that Homepage expects it as Mbps. My widget currently shows 45 Tbsp speeds, lol.
> 
> Homepage expects it in bytes

That's what I had thought, been a while since I've done any Homepage source code diving though

**Comment by cinderblockgames** [comment]
...Huh.  So, I've got this coming out of the API:

```
{"data":{"id":583,"ping":20.382,"download":45655636,"upload":26669082,
```

And Homepage is showing me this:

![image](https://user-images.githubusercontent.com/79210192/224060524-f09843dd-a8b0-4f60-ae6f-5b7576d3063f.png)

**Comment by alexjustesen** [comment]
@cinderblockgames you'll need to convert bits vs. bytes. Data stored in the table is in `bits` while Homepage expects `bytes`

**Comment by cinderblockgames** [comment]
@alexjustesen That's still a factor of 8, not 125000.  So, 1000000 bits/second = 125000 bytes/second, which matches what's in the UI as well as what Homepage appears to be looking for.

I've got it working with the 125000 division in my fork, if you want to take a look against your Homepage instance: https://github.com/cinderblockgames/speedtest-tracker

**Comment by alexjustesen** [comment]
Let me do some digging... Resources for later Alex to look at:

- Homepage widget: https://github.com/benphelps/homepage/blob/fb15f5dbc9273a3a024bfd70edad4544ebfe9208/src/widgets/speedtest/component.jsx#L28
- henrywhitaker3/Speedtest-Tracker `/speedtest/latest` endpoint: https://github.com/henrywhitaker3/Speedtest-Tracker/blob/8cb2e8a3236850b4a07e887ac376c0d4d5e804f4/app/Http/Controllers/SpeedtestController.php#L112

**Comment by shamoon** [comment]
Ultimately homepage can accept any, https://github.com/benphelps/homepage/blob/fb15f5dbc9273a3a024bfd70edad4544ebfe9208/src/widgets/speedtest/component.jsx#L34 or https://github.com/benphelps/homepage/blob/fb15f5dbc9273a3a024bfd70edad4544ebfe9208/src/widgets/nzbget/component.jsx#L30 etc.

If there's a stable API here Im happy to handle the homepage widget, not clear if that part has been implemented here already? Is it documented?

**Comment by shamoon** [comment]
Oh now I understand. Yea that would be great for sure, alternatively homepage could probably handle any changes (or just a separate widget) but agree would probably be cleaner here.

Let me know if I can help at any point!

**Comment by SAS-1** [comment]
I use Organizr so hopefully it will be the same as Homepage but happy to test for that once ready

**Comment by alexjustesen** [comment]
#463 introduces `/api/speedtest/latest` route which enables support for home lab dashboards like Homepage and Organizer 

At a later date a robust API will be developed, in the interim this endpoint will serve to close the gap with the dashboards.

**Comment by alexjustesen** [comment]
#463 introduces `/api/speedtest/latest` route which enables support for home lab dashboards like Homepage and Organizer 

At a later date a robust API will be developed, in the interim this endpoint will serve to close the gap with the dashboards.

**Comment by alexdelprete** [comment]
> Let me know if I can help at any point!

Is there an importer for dashy config? I'd love to test homepage, but I've spent so much time on dashy that doing it all over blocks me from trying homepage. (#lazymode ON) :D

**Comment by alexjustesen** [comment]
@alexdelprete not that I'm aware of and HOLY CRAP

**Comment by alexdelprete** [comment]
There's more stuff under it...but I stopped there. :)

**Comment by alexjustesen** [comment]
I have dashboard envy

**Comment by SAS-1** [comment]
working great on Organizr
![image](https://user-images.githubusercontent.com/47122073/224248511-f3f63f4b-d129-4b12-988e-30f69e018e1c.png)
Thanks!

**Comment by spupuz** [comment]
In homepage is there an example to how to make it work? This version uses https and user and password Henry version wasn't

**Comment by cinderblockgames** [comment]
@spupuz It's a drop-in replacement; it's exactly the same.

```
        widget:
          type: speedtest
          url: https://speedtest.example.com
```

**Comment by alexjustesen** [comment]
> In homepage is there an example to how to make it work? This version uses https and user and password Henry version wasn't

This legacy endpoint isn't behind any authentication and will work with either `http` or `https` protocols. 

- Speedtest Tracker [docs](https://docs.speedtest-tracker.dev/api/latest-result)
- Homepage [docs](https://gethomepage.dev/en/services/speedtest-tracker/)

**Comment by zvarg** [comment]
I got to do my homewrok here :)
![image](https://user-images.githubusercontent.com/18576529/224566176-54067985-adb5-4aee-937e-4c4e47d970f8.png)

**Comment by neonmaus** [comment]
Something is going wrong for me, on the homepage dashboard the upload is exactly the same value as the download, although my upload speed is only half as high as it is also correctly displayed on the speedtester dashboard

![image](https://user-images.githubusercontent.com/11020494/224700445-8b203d41-f80d-4726-b1dd-fc644fef869e.png)
![image](https://user-images.githubusercontent.com/11020494/224700520-5aeb8d50-6c3d-4899-a273-bc6022358ddf.png)

**Comment by alexjustesen** [comment]
Oops... https://github.com/alexjustesen/speedtest-tracker/blob/main/app/Http/Controllers/API/Speedtest/GetLatestController.php#L32-L33

Unless someone can pr a bugfix it'll be a couple of days until I can circle around to fixing it.

**Comment by alexdelprete** [comment]
> I have dashboard envy

You definitely should. :D

Yesterday I completed the configuration...I like dashoboard, even though it takes a pretty good hit on the servers with all those widgets open while browsing the page. But it's so cool...:)

![image](https://user-images.githubusercontent.com/7027842/225897379-f48dde92-1fa8-4694-b9d0-e735a406812b.png)

![image](https://user-images.githubusercontent.com/7027842/225897535-f9d9d2e4-3224-40a9-a8df-6b1ca982a07d.png)

![image](https://user-images.githubusercontent.com/7027842/225897666-576d0b49-649f-4cb1-bd93-5aa568455757.png)

**Comment by adam50hhh** [comment]
> > I have dashboard envy
> 
> You definitely should. :D
> 
> Yesterday I completed the configuration...I like dashboard, even though it takes a pretty good hit on the servers with all those widgets open while browsing the page. But it's so cool...:)
> 
> ![image](https://user-images.githubusercontent.com/7027842/225897379-f48dde92-1fa8-4694-b9d0-e735a406812b.png)
> 
> ![image](https://user-images.githubusercontent.com/7027842/225897535-f9d9d2e4-3224-40a9-a8df-6b1ca982a07d.png)
> 
> ![image](https://user-images.githubusercontent.com/7027842/225897666-576d0b49-649f-4cb1-bd93-5aa568455757.png)

Are you using homepage?

**Comment by alexdelprete** [comment]
> Are you using homepage?

yes, that is Homepage.

**Comment by adam50hhh** [comment]
> > Are you using homepage?
> 
> yes, that is Homepage.

Odd question but, how did you get the different groups? (Media, Home Automation, etc.) I'm doing mine and it adds them into different columns. :/

**Comment by alexdelprete** [comment]
Totally OT here, anyway, did you read the docs? https://gethomepage.dev/en/configs/settings/

It's the `Layout` setting in `settings.yaml`.

Here's mine:

```yaml
title: HomeLab Dash
theme: dark
color: zinc

layout:
  System Management:
    style: row
    columns: 4
  Network Core:
    style: row
    columns: 4
  Network Services:
    style: row
    columns: 4
  Home Automation:
    style: row
    columns: 4
  Media:
    style: row
    columns: 4
  Productivity:
    style: row
    columns: 4
  Starr apps:
    style: row
    columns: 4

headerStyle: boxed
background:
    image: /images/john-towner-FD_sabE544U-unsplash.jpg
    blur: none # none, sm, "", md, lg, xl see https://tailwindcss.com/docs/backdrop-blur
    saturate: 20 # 0, 50, 100 see https://tailwindcss.com/docs/backdrop-saturate
    brightness: 60 # 0, 50, 75 see https://tailwindcss.com/docs/backdrop-brightness
    opacity: 30 # 0-100

providers:
  openweathermap: xxxx
  weatherapi: yyyy

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: false
    hideVisitURL: false

showStats: true
```

**Comment by adam50hhh** [comment]
> Totally OT here, anyway, did you read the docs? https://gethomepage.dev/en/configs/settings/
> 
> It's the `Layout` setting in `settings.yaml`.
>
> Here's mine:

You rock! Thanks for the share and pointing me to the right area!!!
