### ISSUE TITLE
No application encryption key has been specified

### ISSUE THREAD

**Issue by skubi23t** [alexjustesen/speedtest-tracker#815]
**Describe the bug**
My app stopped working after some update and in logs there is an error:

"No application encryption key has been specified"

**Logs**
[2023-09-25 19:49:44] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)

[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(77): tap()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(60): Illuminate\\Encryption\\EncryptionServiceProvider->key()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\\Foundation\\Application->make()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
#18 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#19 {main}
"} 

**Additional context**

Is there anything I can do to fix?

**Comment by alexjustesen** [comment]
What version are you running? `APP_KEY` is now generated on startup as of `0.12.0`

**Comment by skubi23t** [comment]
<html>
<body>


com.docker.compose.config-hash | df01b913d0a7c3f325f67fc0004d0b1aa850f1a1ff95049e75ef7d6742ec53d0
-- | --
com.docker.compose.container-number | 1
com.docker.compose.depends_on | db:service_started:false
com.docker.compose.image | sha256:7cf430ee7fe5876401ded70405c3291402c2c31a6c53003a4f27bc34cbc8c6b2
com.docker.compose.oneoff | False
com.docker.compose.project | speedtest-tracker
com.docker.compose.project.config_files | /data/compose/15/docker-compose.yml
com.docker.compose.project.working_dir | /data/compose/15
com.docker.compose.replace | 431c937473792db571a640e293a19291d200f2cc65f5d7ad6a0b6a2568edddb9
com.docker.compose.service | speedtest-tracker
com.docker.compose.version | 2.20.2
maintainer | Jay Rogers (@jaydrogers)
org.opencontainers.image.created | 2023-09-22T16:36:18.585Z
org.opencontainers.image.description | Speedtest Tracker is a self-hosted internet performance tracking application that runs speedtest checks against Ookla's Speedtest service.
org.opencontainers.image.licenses | MIT
org.opencontainers.image.ref.name | ubuntu
org.opencontainers.image.revision | 27964058c90979e43e020417238f4a9b33a6b5ea
org.opencontainers.image.source | https://github.com/alexjustesen/speedtest-tracker
org.opencontainers.image.title | speedtest-tracker
org.opencontainers.image.url | https://github.com/alexjustesen/speedtest-tracker
org.opencontainers.image.version | v0.12.2


</body>
</html>

**Comment by skubi23t** [comment]
I had to do this manually and now it works fine..

https://docs.speedtest-tracker.dev/faqs#i-get-a-warning-on-container-start-up-that-the-app_key-is-missing

**Comment by alexjustesen** [comment]
There is an issue with caching env vars I'm aware of that can cause this issue randomly but haven't had time to resolve that yet. Going to close this out as I'm tracking that separately and looks like you're all set.
