### ISSUE TITLE
[Bug] Influx integration sends bytes sent rather than bandwidth measurement

### ISSUE THREAD

**Issue by adamus1red** [alexjustesen/speedtest-tracker#82]
I configured influxdb2 integration and checked data after the first speedtest. These are the available fields I could choose from:

![image](https://user-images.githubusercontent.com/7027842/197293696-793fa989-8da6-4c4a-a889-888a5b72574f.png)

I picked download/upload, but I noticed very low values in influx:

![image](https://user-images.githubusercontent.com/7027842/197294412-04f6bbcd-7db2-4a25-a9fa-a36e874e5597.png)

so I checked the mariadb data (record #7):

![image](https://user-images.githubusercontent.com/7027842/197293860-63e8833d-972d-40f7-886a-05dc9e8ec08c.png)

So the data was ok. But the reported speed of that test was this:

![image](https://user-images.githubusercontent.com/7027842/197293956-39f5520d-f014-474c-af48-41e3e43d1b78.png)

I didn't understand at first...then I thought maybe those download/upload columns in the db represent the amount of data sent/received, and that you get the actual speed values from the json in the data column. Problem is that the data column is not exported to influx.

So, to integrate my OP, I think also the DL/UL speed values should be in their own columns, probably the quantity of data sent/received is not so important, and you could actually reuse those columns. :)

_Originally posted by @alexdelprete in https://github.com/alexjustesen/speedtest-tracker/issues/48#issuecomment-1287472234_

**Comment by alexjustesen** [comment]
SOB, I new I forgot about that somewhere.

**Comment by alexdelprete** [comment]
> SOB, I knew I forgot about that somewhere.

I see same values in MariaDB and InfluxDB. If I multiply them by 8, I have the bandwidth in Mbits/s.

**Comment by alexdelprete** [comment]
I agree...let's stick to a representation then it will be converted as needed at UI level, right?

**Comment by adamus1red** [comment]
I was trying to figure out why my guagues in Grafana were off and ran across @alexdelprete's comment. Having it consistent would be a big plus
