### ISSUE TITLE
failed to create new listening socket: socket(): Address family not supported by protocol (97)

### ISSUE THREAD

**Issue by sruckh** [alexjustesen/speedtest-tracker#820]
**Describe the bug**
I am trying to use docker compose file for use with MariaDB.  I am wanting to integrate with an existing MariaDB instance rather than the instance included in the speedtest-tracker image.

It seems to connect to the DB instance and create the necessary tables.

I have also modified the docker-compose.yml to change the exposed ports to 8980 and 8943 (although I do not really care about the SSL web server as I will terminate the SSL connection with the reverse web proxy).

I have deleted everything below the line, restart: unless-stopped, in docker-compose.yml as I believe it pertains to the MariaDB instance included in the image and is not necessary.

When I try to use docker compose to start up the container, I am getting the following errors:

speedtest-tracker  | [30-Sep-2023 14:55:53] ERROR: failed to create new listening socket: socket(): Address family not supported by protocol (97)
speedtest-tracker  | [30-Sep-2023 14:55:53] ERROR: failed to create new listening socket: socket(): Address family not supported by protocol (97)
speedtest-tracker  | [30-Sep-2023 14:55:53] ERROR: FPM initialization failed
speedtest-tracker  | [30-Sep-2023 14:55:53] ERROR: FPM initialization failed

I have created config/ and web/ sub-directories and have modified the docker-compose.yml to look like the following:
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - './config:/config'
            - './web:/etc/ssl/web'

**To Reproduce**
Perform steps listed above and run 'docker compose up'

**Expected behavior**
No errors to be displayed, and to be able to connect to UI on port 8980

**Environment (please complete the following information):**
 - OS: CentOS
-  Architecture: x86_64
 - Browser [N/A]
 - Version [speedtracker latest as of 2023-09-30]

**Screenshots**
N/A

**Logs**
Error Messages Posted above.  The are continually written to standard out.

**Additional context**

**Comment by alexjustesen** [comment]
Do you mind posting your whole `docker-compose.yml` file contents so we can evaluate the complete stack?

**Comment by sruckh** [comment]
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8980:80'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=1.2.3.4
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=username
            - DB_PASSWORD=password
            - TZ=America/Phoenix
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - './config:/config'
            - './web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped

Username/Password and IP of DB_HOST modified to protect the innocent.

**Comment by alexjustesen** [comment]
So this _might_ have something to do with IPv6, are you using that in your stack?

**Comment by sruckh** [comment]
I have IPv6 disabled as best as it can be everywhere on the host system.  I have verified that port 8980 is available on the host OS.

**Comment by alexjustesen** [comment]
I'll be honest with you, it's got to be something related to CentOS or your stack. I don't run CentOS in mine so it's hard to test and haven't been able to replicate the issue.

**Comment by johntdyer** [comment]
This is not a centos issue... I am getting the same thing on Debian
