### ISSUE TITLE
server error 500 or no speedtest results on synology

### ISSUE THREAD

**Issue by ArthurHuyghe** [alexjustesen/speedtest-tracker#825]
**Is your feature request related to a problem? Please describe.**
I installed this using docker compose with a mariadb database. Everything went well except for when i queued a speedtest, all the speedtests I did had no data. also when I opened general settings I got a server error 500.

after some digging I found the solutions. If you have a firewall enabled with a rule to deny all as the last rule, you should add a rule allowing all ports for the specific IP range from the network compose created. For example if your compose subnet is 172.18.0.0/16, you should add the IP range 172.18.0.1 - 172.18.255.254. Make sure to add this rule above your deny rule!

**Describe the solution you'd like**
I suggest you update your documentation for synology and add this to it . ( I hope this URL can help clarify my poor explanation. [https://drfrankenstein.co.uk/step-3-setting-up-a-docker-bridge-network-in-container-manager/](url) )

**Comment by c-hri-s** [comment]
See this:

https://github.com/alexjustesen/speedtest-tracker/issues/849#issuecomment-1747315423

**Comment by alexjustesen** [comment]
> See this:
> 
> [#849 (comment)](https://github.com/alexjustesen/speedtest-tracker/issues/849#issuecomment-1747315423)

He's right you know.

**Comment by ArthurHuyghe** [comment]
@alexjustesen, I believe you wrongfully closed this issue as it is about a change of documentation. the people above used this issue to report problems releated to #852.

I would love to help you with the documentation, however I'm not sure how...

**Comment by Unrepentant-Atheist** [comment]
It doesn't work for me. Doing this doesn't help: https://github.com/alexjustesen/speedtest-tracker/issues/849#issuecomment-1747315423 .

**Comment by ArthurHuyghe** [comment]
@Unrepentant-Atheist is your issue related to #852? If not please open a new ticket or search for a solution in the other open / closed issues.

This is an issue for a change off documentation, please do not use this for problems with the server 500 error if it isn't caused by the firewall of your host.

**Comment by alexjustesen** [comment]
As mentioned in other tickets, fix is...

1. Generate an `app_key` and place it as an environment variable in your `docker-compose.yml` file.
2. Restart the container

I'll have updates to docs and startup later today.
