### ISSUE TITLE
Result times are still being reported/recorded in UTC even after v0.1.0-alpha.10

### ISSUE THREAD

**Issue by JourneyOver** [alexjustesen/speedtest-tracker#84]
Even after https://github.com/alexjustesen/speedtest-tracker/pull/71 and updating to the `v0.1.0-alpha.10` version, the result times and the database file (in both data / created_at) are still being reported/recorded in UTC instead of the timezone set in the settings panel.

edit: I did try to change https://github.com/alexjustesen/speedtest-tracker/blob/main/app/Filament/Resources/ResultResource.php#L44 to be my timezone as well but sadly that didn't seem to make a difference.

edit: also just a note I thought I'd add in, but the favicon stuff doesn't seem to work either, it just returns a 404.

**Comment by spcqike** [comment]
I thought UTC as storage time is the way to go. One just uses timezone for UI/frontend. 

If you change your timezone in settings it should alter the reported times, as it thinks you are in a different timezone. But it shouldn’t alter the stored time within a database. 

Am I wrong?

**Comment by alexjustesen** [comment]
Would love to get more input on this, it's been my experience also that anytime you're storing records it should be in UTC and then converted for any views

**Comment by bdowden** [comment]
100% should be stored in UTC and converted upon displaying data.

**Comment by alexdelprete** [comment]
> I thought UTC as storage time is the way to go. One just uses timezone for UI/frontend.

Absolutely right. In general, the best practice is always: storage layer contains universal format, presentation layer converts data to user preference.

**Comment by JourneyOver** [comment]
Yes, UTC in storage is the way it's should be, was mainly making a note that it seems that it's just pulling the time straight from from the created_at date instead of doing any actual conversion on the UI side of things.

**Comment by alexdelprete** [comment]
> it seems that it's just pulling the time straight from from the created_at date instead of doing any actual conversion on the UI

That is true, the `created_at` column is in local time format, not UTC.

![image](https://user-images.githubusercontent.com/7027842/197633573-ae27156d-5a7b-4899-bbb7-373905cda88a.png)

> as no matter what you have the timezone set as in the settings, the results page are just always reported as UTC still.

that is not what I'm observing in my results page, it's in local time format:

![image](https://user-images.githubusercontent.com/7027842/197633735-295bae17-e794-4687-a03f-15e0a07c10de.png)

**Comment by JourneyOver** [comment]
@alexdelprete Wait your `created_at` and the json in the `data` are reporting your local time along with the results page? if you was to change the timezone information on the settings page to say something else (as an expample: `America/Chicago` which is my timezone) and do a test would it change the created at times for you?

as that is not what I'm experiencing at all, I can sit there and mess with the timezone in the settings page and run tests all day and it always comes back to just having the created at on the results page in UTC.

I've destroyed the docker container / database file several times over since the release of v0.1.0-Alpha.10 and this is on an extremely fresh build of ubuntu as well..

**Comment by alexdelprete** [comment]
> as that is not what I'm experiencing at all, I can sit there and mess with the timezone in the settings page and run tests all day and it always comes back to just having the created at on the results page and in the database file for `created_at` in UTC.

I found out why: look at the `results` table structure.

![image](https://user-images.githubusercontent.com/7027842/197637805-c32eec67-49d8-4ec1-8329-6aeed002ebe8.png)

The created_at column is a db function. So it gets timestamped by the database, I'm using MariaDB. When I view the records (using HeidiSQL client) I always see local time, probably it's stored as unix epoch time and the client converts it in the UI.

I don't know what happens with sqlite...

**Comment by JourneyOver** [comment]
@alexdelprete So I downloaded the `HeidiSQL client` (I've been using `SQLite Database Browser` any other time) to see the `results` table structure and see if it was the same or different than yours and it is indeed a bit different...

![10-24-2022_17-17-58](https://user-images.githubusercontent.com/13910285/197640863-de644e34-e604-491e-8eb2-e89f5d6f7917.png)

My defaults for some reason are just `no default` while it looks like yours is `current_timestamp()` and your datatype is `TIMESTAMP` while mine is just `DATETIME`..

---

This is what `SQLite Database Browser` shows:
![SQLB](https://user-images.githubusercontent.com/13910285/197641304-9482bf87-a680-4513-84b3-124a63e2c18b.png)

**Comment by alexdelprete** [comment]
In SQLite DB Browser screenshot default I can see DEFAULT `CURRENT_TIMESTAMP`. I think it's a universal value, converted by the client you're using. Probably HeidiSQL is converting it when I view data of the table.

Did you check the Data tab in HeidiSQL? How's the value reported?

**Comment by JourneyOver** [comment]
> Did you check the Data tab in HeidiSQL? How's the value reported?

It's still coming back as UTC time, this was also on a fresh speedtest tracker container with a fresh database the only thing I did was went into the setting page on the WebUI and changed it to my timezone and qeued up a test after setting the timezone.

**Comment by alexdelprete** [comment]
In HeidiSQL there's an inline help for field types:

![image](https://user-images.githubusercontent.com/7027842/197646695-b051e124-2f86-4f3c-adcf-8440cbe30dcd.png)

So, at least if the DB is MariaDB, the value is unix epoch. That means that HeidiSQL is formatting it in the UI.

Probably the TIMESTAMP type doesn't exist in SQLite, and it's handled differently, but it's always UTC.

**Comment by JourneyOver** [comment]
Yea for some reason I can't get the inline help to come up for anything in the fields type and it doesn't let me edit the field types either for ones that are already created, but if I create a new column and mess around with the datatype field it doesn't even have `TIMESTAMP` as an option, only `DATE`, `TIME` and `DATETIME` for the temporal (time) spot.. So I think you are correct that the `TIMESTAMP` type doesn't exist in SQLite at all, so we would need to figure out a different method then for people who use SQLite instead of one of the other options.

**Comment by alexdelprete** [comment]
> we would need to figure out a different method then for people who use SQLite instead of one of the other options.

Why? it's in UTC both on sqlite and MariaDB. And that's what we agreed to do in this thread: UTC in the storage, conversion in the UI.

The difference is only the fact that in my setup, HeidiSQL is showing me those values in local format, at UI level, but data is TIMESTAMP, so epoch format, a universal value.

**Comment by JourneyOver** [comment]
I mean on the webUI side of things not the database side of things, because obviously something is messing up on the webUI side of things that is causing the timezone to not work correctly for whatever reason still and the only difference I see between me and you (and you said it was working for you just fine) is that you are using MariaDB while I'm using sqlite.

**Comment by alexdelprete** [comment]
> I mean on the webUI side of things not the database side of things

Ohhh..ok. You're seeing UTC also in webUI. 

Sqlite doesn't have TIMESTAMP field type:

![image](https://user-images.githubusercontent.com/7027842/197649854-2a91504d-9b92-4ce3-a257-2907a7ded46a.png)

But it offers 6 datetime functions: https://www.sqlite.org/lang_datefunc.html

![image](https://user-images.githubusercontent.com/7027842/197649982-95c85ce7-43ce-478c-91dd-b92abab68ba8.png)

I don't know if data is being managed by filament or by code...maybe with dates and different databases you need to configure something specific. (cc @alexjustesen)

**Comment by JourneyOver** [comment]
> Ohhh..ok. You're seeing UTC also in webUI.

Yes, exactly. I'm seeing UTC in the WebUI no matter what the timezone is set as, that is what spawned this issue thread.

**Comment by alexdelprete** [comment]
After this brainstorming...I'm sure Alex will be able to find the issue: it's the sqlite vs mysql difference with that field type. Probably something in filament.

Goodnight.

**Comment by JourneyOver** [comment]
> After this brainstorming...I'm sure Alex will be able to find the issue: it's the sqlite vs mysql difference with that field type. Probably something in filament (if it manages the different db types, I'm not sure).
> 
> Goodnight.

yea haha, hopefully he can figure something up to fix all this. Have a goodnight

**Comment by alexdelprete** [comment]
> Have a goodnight

And get your sleep! :)

**Comment by JourneyOver** [comment]
> > Have a goodnight
> 
> And get your sleep! :)

lol oh I already got some sleep finally :P but tbh won't be much longer till I go back to bed again either due to the fact I have work tomorrow. There just tends to be days where I stay up way past when I should be getting some sleep xD

**Comment by JourneyOver** [comment]
I can at least attest to the fact that this is just an issue when SQLite, I spun up postgres (since alexdelprete was already running mariadb/mysql and it was working fine for him) and tested with that and it's working correctly on the webUI, changing the timezone works perfectly and the result page updates correctly with the timezone.

So all that really needs to be looked into is the sqlight difference on why it's not updating the webUI correctly.

**Comment by Kostecki** [comment]
I just updated to the beta version and noticed that the "created at" time is wrong in the dashboard. create_at is in my local time in the database, but with my timezone (Europe/Copenhagen) set, the displayed time is 2 hours in the future (which is what i'm ahead of UTC).

Data-field in the database is 20:32, created_at is 22:32 and dashboard shows 00:32.

Did i miss something? I'm running MariaDB which looks like it should work fine?

**Comment by alexdelprete** [comment]
That's not what I'm experiencing. I'm in Rome, same TZ as yours, and times are reported correctly.

MariaDB (you can see json date in UTC and `created_at`):
![image](https://user-images.githubusercontent.com/7027842/198156194-c1c5d7de-d7bc-498c-827b-777bc00c6f8e.png)

Dashboard:
![image](https://user-images.githubusercontent.com/7027842/198156289-ae4ae3c5-b6c8-410b-a213-e33675abe634.png)

**Comment by Kostecki** [comment]
That's interesting. Mine looks like this:
![Skærmbillede 2022-10-27 kl  21 49 11](https://user-images.githubusercontent.com/9408523/198384800-c900da7a-e946-456d-8abd-38316f25cb3a.png)
![Skærmbillede 2022-10-27 kl  21 49 17](https://user-images.githubusercontent.com/9408523/198384806-ce8b97f2-aa74-45ee-a0b1-584ed6faddc3.png)


If i set the timezone to UTC it shows the dashboard times as the right time (my timezone - so 2 hours offset from UTC). `# date` inside the container shows the right time with my timezone - so what did i configure wrong? Why does the application set UTC as 2 hours from the time in the DB?

**Comment by Kostecki** [comment]
![Skærmbillede 2022-10-27 kl  21 49 11](https://user-images.githubusercontent.com/9408523/198388642-24bbe53d-7d03-47a4-ab9f-9afb740823d0.png)
![Skærmbillede 2022-10-27 kl  21 49 17](https://user-images.githubusercontent.com/9408523/198388645-45e6a361-e37c-4e11-8391-d1743537f277.png)

If i set the timezone to UTC it shows the dashboard times as the right time (my timezone - so 2 hours offset from UTC). `date` inside the container shows the right time with my timezone - so what did i configure wrong? Why does the application set UTC as 2 hours from the time in the DB?

**Comment by quentinhayot** [comment]
My take on this is to always store the time in the original timezone as ISO 8601. That way you don't lose the original timezone information and can display the data in whatever timezone you want too.

**Comment by alexdelprete** [comment]
> It makes no sense to convert to UTC if your data format contains the zone information. You are just throwing away information (original zone here).

Absolutely wrong saying _it makes no sense_ (and a bit arrogant if I might add). Maybe it doesn't make sense to you because you didn't think about all the use-cases.

You want to convert to a universal time for reasons that probably you didn't think about: in local time, not all days have fixed length, and you have TZ offsets. So datetime calculations become more difficult if you don't have a universal reference, that's why the simplest and efficient way is converting and storing to a universal representation where all days have fixed length and you have no TZ offsets.

That is why in many DBs you have timestamp field types, and you have built-in functions to easily convert from that universal timestamp to local time: because it's a common best practice that is widely adopted for very good reasons.

If you don't need to do any calculations on datetime, you can also avoid doing this, but if you don't know how the app will evolve, maybe you will need to add datetime calculation functions, it's better having to deal with universal data since the beginning.

![image](https://user-images.githubusercontent.com/7027842/198876935-330a0738-c3b4-4970-8e08-9561ffaf1693.png)

**Comment by alexjustesen** [comment]
Alrighty thanks for the feedback everyone, I'll be locking the conversation and making some enhancements to how time zones are handled within the app. Currently container environment time zones and app time zones are separate from one another. I'll be looking to make this setting universal to provide consistency across views and reporting.
