### ISSUE TITLE
[Feature Request]  Last execution timestamp and hostname on Dashboard

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#840]
I would like to be able to see the timestamp  of the last execution, and also be able to insert static text such as the hostname in the application footer. Thanks in advance

![Cattura1](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/0a96b3b5-4e8c-4cee-9dc6-e940b35dd068)

![Cattura2](https://github.com/alexjustesen/speedtest-tracker/assets/5001932/7480562f-d56e-40dc-8e95-44bab27d6113)

**Comment by corasaniti** [comment]
@alexjustesen 
Hi  I notice that the last execution time is only visible if the admin panel is hidden.  If I activate the admin panel it disappears and I can no longer view it.
Thanks again

PS: 
Could you show me the page where you insert the app version in the footer? I would like to add static text

**Comment by alexjustesen** [comment]
Correct, the date is only visible on the public version because of #756. The admin panel version of the dashboard will be removed shortly. 

Also can you open a new feature request for any other changes so I can track it?
