### ISSUE TITLE
Settings Tab

### ISSUE THREAD

**Issue by pfmp-404** [alexjustesen/speedtest-tracker#850]
**Describe the bug**
When I access to the application, I can´t see the Settings Tab.

**To Reproduce**
1. Go to link of the application
2. Click on nothing

**Expected behavior**
![imagem](https://github.com/alexjustesen/speedtest-tracker/assets/141368592/d14066c2-4d8e-4162-8118-ae73a13fe5af)

**Environment (please complete the following information):**
 - OS: Fedora 38 (docker)
 - Browser Firefox, Chrome
 - Version [e.g. v1]

**Screenshots**
![imagem](https://github.com/alexjustesen/speedtest-tracker/assets/141368592/ad784a45-2745-4ef2-914c-37072b552baf)

**Logs**
I don't see errors on logs

**Additional context**

**Comment by alexjustesen** [comment]
It's likely because the user you're using doesn't have the appropriate role. To fix that use the `app:update-user-role` command from the [docs](https://docs.speedtest-tracker.dev/other/commands).

**Comment by pfmp-404** [comment]
Thank's, problem solved.
