### ISSUE TITLE
500 SERVER ERROR

### ISSUE THREAD

**Issue by dtech77pl** [alexjustesen/speedtest-tracker#852]
After upgrading to the latest version v0.13.1 I have 500 SERVER ERROR

Docker on synology. 

2023/10/05 10:40:20,stdout,"} 

2023/10/05 10:40:20,stdout,#19 {main}

2023/10/05 10:40:20,stdout,#18 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()

**Comment by gionag** [comment]
SAME here
docker on alpine linux

```
speedtest-tracker  | [2023-10-05 10:59:10] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
speedtest-tracker  | [stacktrace]
speedtest-tracker  | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
speedtest-tracker  | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(77): tap()
speedtest-tracker  | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(60): Illuminate\\Encryption\\EncryptionServiceProvider->key()
speedtest-tracker  | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()
speedtest-tracker  | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
speedtest-tracker  | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
speedtest-tracker  | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
speedtest-tracker  | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
speedtest-tracker  | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
speedtest-tracker  | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
speedtest-tracker  | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
speedtest-tracker  | #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
speedtest-tracker  | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
speedtest-tracker  | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
speedtest-tracker  | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
speedtest-tracker  | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
speedtest-tracker  | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\\Foundation\\Application->make()
speedtest-tracker  | #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
speedtest-tracker  | #18 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
speedtest-tracker  | #19 {main}
speedtest-tracker  | "}
```

**Comment by KossikCZ** [comment]
I had the same, restarting the docker container helped in my case.

**Comment by dtech77pl** [comment]
> I had the same, restarting the docker container helped in my case.

Try this couple time, no luck :(

**Comment by mrodus** [comment]
> I had the same, restarting the docker container helped in my case.

Mine doesn't work after the restart either 😕

**Comment by bka-git** [comment]
Hi,
run into the same issue. I am running speedtest-tracker as an docker container on my qnap. Following steps fixed it with my setup:

- in my config volume is a .env file which contains the APP_KEY
- re-created the docker container with a new env property "APP_KEY" and as value the complete string from the .env file

Hope this helps
Bernhard

**Comment by gionag** [comment]
done that... now it is working
https://docs.speedtest-tracker.dev/faqs#i-get-a-warning-on-container-start-up-that-the-app_key-is-missing

**Comment by JFPCreations** [comment]
Having that problem for some time. In the past it was ok after a restart but today, it does not work. Tried a restart of the docker, a stop and start, a kill and start, this is going nowhere. I don't want to have to reboot my server for it to work.

**Comment by mrodus** [comment]
> Having that problem for some time. In the past it was ok after a restart but today, it does not work. Tried a restart of the docker, a stop and start, a kill and start, this is going nowhere. I don't want to have to reboot my server for it to work.

Try the solution suggested by @gionag

**Comment by JFPCreations** [comment]
> > Having that problem for some time. In the past it was ok after a restart but today, it does not work. Tried a restart of the docker, a stop and start, a kill and start, this is going nowhere. I don't want to have to reboot my server for it to work.
> 
> Try the solution suggested by @gionag

Yes thank you.

**Comment by dtech77pl** [comment]
> i have made static the APP_KEY https://docs.speedtest-tracker.dev/faqs#i-get-a-warning-on-container-start-up-that-the-app_key-is-missing maybe this iteration is not handle correctly the auto-generation upon startup

This helps, thank you

**Comment by JFPCreations** [comment]
> Pardon my ignorance but I get "PHP: command not found" when I attempt to run what is in the suggested URL fix. What am I missing here? Thanks.

You have to run it in the docker console, not in the server console.

**Comment by jjervell** [comment]
Thx JFPC for the confirmation..  I was able to get it to run and added that key to my build script..  Still no joy so maybe a rollback as suggestion will be my solution..  Will have to take Watchtower down so it will not auto update.

**Comment by JoatmonX** [comment]
The above didn't work for me.  I had to revert to v0.13.0.

**Comment by TheConanRider** [comment]
Seems like the .env file isn't being read correctly. I have the same issue with the APP_KEY fixed by using an environment  variable [workaround described here](https://github.com/alexjustesen/speedtest-tracker/issues/849#issuecomment-1747315423) and now I am having the same issue with the telegraph bot key. From the comment that pops up when I try to test it I think it can also be fixed by an environment variable.

**Comment by TheConanRider** [comment]
Using the environment variables with the same keys that are in my .env file seems to have fixed my issues.

**Comment by masterwishx** [comment]
same issue in unraid Docker

**Comment by masterwishx** [comment]
Added env var APP_KEY from env file to docker build , Fixed the Error

**Comment by masterwishx** [comment]
it seems that .env file is not reading correctly , after has fixed login , telegram bot is not found now

**Comment by icolumbro** [comment]
I've been having the same problem for a few days (from version 0.13.* onwards?) but only if I try to access from my domain (configuration with Nginx Proxy Manager). If I don't use NPM and log in from local address, everything works fine.
In my case, I think it's a problem to access to correct database address.

**Comment by alexjustesen** [comment]
> Added env var APP_KEY from env file to docker build , Fixed the Error

this, updates coming to docs and startup now that I have capacity again.

**Comment by tfendler** [comment]
I just needed to define the APP_KEY in the .env-file with quotes. After that, it was working normally.

**Comment by DuneJeeper** [comment]
Thank you @tfendler !

**Comment by cyberops7** [comment]
@alexjustesen FWIW I am running `v0.14.4` and just got this error.  Once I generated a key and passed it in as an env var (including the `base64:` prefix), it stopped crashing, but I don't think the autogeneration is working as expected?

**Comment by alexjustesen** [comment]
> but I don't think the autogeneration is working as expected?

It def doesn't work as well as I'd want for sure. Updated the docs so including the `base64:` prefix is noted: https://docs.speedtest-tracker.dev/getting-started/environment-variables
