### ISSUE TITLE
Scheduled tests report much lower DL speeds than queued tests.

### ISSUE THREAD

**Issue by buzzytrent90** [alexjustesen/speedtest-tracker#853]
**Describe the bug**
When test is scheduled the download speed reported is substantially lower and incorrect. When test is manually queued and executed, download speed reports the correct average compared to native test on speedtest.net. The same server is applied to all tests to maintain continuity.

**To Reproduce**
1. Manually queue a test and observe download speed report. (Test A)
2. Run a speedtest natively on speedtest.net and observe download speed report. (Test B)
3. Schedule a test and observe download speed report. (Test C)'
4. Comparing download speed results, Test A & Test B are within an acceptable range of eachother. Test C result is around 8x slower.

**Expected behavior**
Similar download speed average expected across scheduled, queued and Speedtest.net native tests.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS + Docker
-  Architecture: x86_64 GNU/Linux
 - Browser: Brave latest/Windows
 - Version: v0.13.1

**Screenshots**
![Screenshot 2023-10-06 104626](https://github.com/alexjustesen/speedtest-tracker/assets/50114916/ecb5658e-a2af-41cf-8c58-d4eb532c2e4a)

**Logs**
`192.168.0.79 - - [06/Oct/2023:10:25:44 +0100] "POST /livewire/update HTTP/2.0" 200 2596 "https://192.168.0.70:8443/admin/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.79 - - [06/Oct/2023:10:27:37 +0100] "GET /admin/results HTTP/2.0" 200 24599 "https://192.168.0.70:8443/admin/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.79 - - [06/Oct/2023:10:27:44 +0100] "POST /livewire/update HTTP/2.0" 200 2596 "https://192.168.0.70:8443/admin/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.79 - - [06/Oct/2023:10:41:18 +0100] "GET /admin/results HTTP/2.0" 200 24600 "https://192.168.0.70:8443/admin/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.79 - - [06/Oct/2023:10:41:29 +0100] "GET /admin HTTP/2.0" 200 14619 "https://192.168.0.70:8443/admin/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.79 - - [06/Oct/2023:10:41:30 +0100] "POST /livewire/update HTTP/2.0" 200 2659 "https://192.168.0.70:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.79 - - [06/Oct/2023:10:41:31 +0100] "POST /livewire/update HTTP/2.0" 200 1704 "https://192.168.0.70:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.79 - - [06/Oct/2023:10:41:40 +0100] "POST /livewire/update HTTP/2.0" 200 2843 "https://192.168.0.70:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.79 - - [06/Oct/2023:10:42:02 +0100] "GET /admin/results HTTP/2.0" 200 24618 "https://192.168.0.70:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"`

**Additional context**

**Comment by frknakk** [comment]
Scheduled and manually queued speedtests are running the exact same code. There is no difference between them.

But: your speedtests are scheduled hourly on :00 and the speedtest servers are probably busiest at that time. Try changing your "Speedtest schedule" (Settings > General > Speedtest Settings) to e.g. "37 * * * *" and check if the issue persists.

**Comment by buzzytrent90** [comment]
> Scheduled and manually queued speedtests are running the exact same code. There is no difference between them.
> 
> But: your speedtests are scheduled hourly on :00 and the speedtest servers are probably busiest at that time. Try changing your "Speedtest schedule" (Settings > General > Speedtest Settings) to e.g. "37 * * * *" and check if the issue persists.

Solved.

Simple answer to a simple problem. Thank you for the help.
