### ISSUE TITLE
data from .env file is not accepted by app in Last Update also cause Error 500

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#858]
Using Docker in Unraid

Related to https://github.com/alexjustesen/speedtest-tracker/issues/849

Issue fixed by adding APP_KEY as Container Variable  to Docker build in Unraid

but Also Telegram and Mail from .env is not working.

So they also can be added as Container Variable to Docker for the Fix , 
but something was broken in last update or two , will be fixed or we need move all ENV vars to docker as container vars?

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/af711376-0598-43f2-811f-f77117e0d8af)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/46a876e3-35b5-4a8f-b25f-0b70bf7dbe38)

**Comment by alexjustesen** [comment]
You don't need to move _all_ vars just the ones you use (i.e. Telegram and SMTP).

**Comment by masterwishx** [comment]
> You don't need to move _all_ vars just the ones you use (i.e. Telegram and SMTP).

OK no problem, but it will be fixed?
Or it's new realization then will be cool if will be documented?
