### ISSUE TITLE
🛣️ The road to tagging v1

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#86]
As I iterate though functionality and squash bugs its a good idea to have a line in the sand for when I'll tag a stable version 1. This issue has a complete list of features and functionality that I'll be tracking on the road to tagging v1.

## Completed
- #81
- #370 
- #293
- #265
- #216 
- #213 
- #93 
- #85 
- #87 
- #32 
- #55
- #51
- #41 
- #40
- #310

**Comment by Kofl** [comment]
password change for the bultin-user admin@example.com would be great for v1

**Comment by NetixQc** [comment]
Can't wait to have Homepage dashboard supports ! Keep up the good work.

**Comment by alexjustesen** [comment]
> password change for the bultin-user [admin@example.com](mailto:admin@example.com) would be great for v1

now coming in #306!

**Comment by alexjustesen** [comment]
> Can't wait to have Homepage dashboard supports ! Keep up the good work.

Thanks! and me too...
