### ISSUE TITLE
email and telegram notfications not working

### ISSUE THREAD

**Issue by sojab0on** [alexjustesen/speedtest-tracker#864]
**Describe the bug**
I installed it in e ndocker on my synology , de interface and tests work fine but the notifications dont 

**To Reproduce**
1. Go to Notifications
2. Click on setup email and telegram notifications so it should send out the notification on ran tests 
3. Scroll down to click on send test notification 
4. It says notification send but nothing is recieved 

**Expected behavior**
A test notification should apear in telegram and the given email accounts 

**Environment (please complete the following information):**
 - OS: DSM 7.1.1
-  Architecture: AMD64 (intel based nas)
 - Browser Chrome on a macbook air m1
 - Version Laravel v10.13.5
PHP v8.1.20
Filament v2.17.46
Speedtest Tracker v0.11.17

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**
I setup the env file with an SMTP server ( i use Office 365 for my notification mail account) and the generated telegram bot. also setup the same enviorment values in the docker container it self 
ENV file values 
MAIL_MAILER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=xxx(masked)
MAIL_PASSWORD=(masked
MAIL_ENCRYPTION=null(encryption for smtp host is sarttls, but dont know if it supports this)
MAIL_FROM_ADDRESS=xxxx(masked)
MAIL_FROM_NAME="Speedtest Results"

TELEGRAM_BOT_TOKEN=xxx (masked)

Also tried the smtp server of my isp same result

**Comment by alexjustesen** [comment]
answered in #865
