### ISSUE TITLE
[Feature] Silent notifications for Telegram

### ISSUE THREAD

**Issue by xsolinsx** [alexjustesen/speedtest-tracker#868]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [...] I receive messages with sound.

**Describe the solution you'd like**
I'd like to have a flag to switch on/off the sound notification for messages delivered via telegram

**Additional context**
See here https://core.telegram.org/bots/api#sendmessage in particular the `disable_notification` flag

**Comment by alexjustesen** [comment]
News to me, figured that be a phone level setting.

**Comment by xsolinsx** [comment]
actually it's both
- as a bot owner you can send messages to your users with or without sound
- as a user you can decide to turn off notifications completely for that bot or not

given the fact that I use the same bot for different purposes I'd like to have this option configurable to avoid muting the chat entirely

**Comment by alexjustesen** [comment]
Interesting, it's definitely not going to be a top priority but don't see why I can't add that when I get to revamping the notifications
