### ISSUE TITLE
Without docker

### ISSUE THREAD

**Issue by noes14155** [alexjustesen/speedtest-tracker#871]
**Is your feature request related to a problem? Please describe.**
How can i deploy this without docker?
Please add instructions on how to build it locally.
What I tried until now,
composer install
created database in local mariab server.
populated .env file.
php artisan key:generate
php artisan migrate

Nginx config something like this 
location /myapp {
        alias /path/speedtest-tracker/public;
        try_files $uri $uri/ @myapp;

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        }
        
    }
location @myapp {
        rewrite /myapp/(.*)$ /myapp/index.php?/$1 last;
    }

Working until the login page. cannot login

**Comment by alexjustesen** [comment]
At this time I'm not officially supporting a "non-docker" install. If you know how to run a Laravel app on a VM you can follow those docs and the only other requirement is the speedtest cli.
