### ISSUE TITLE
Ability to limit bandwidth from the Docker container?

### ISSUE THREAD

**Issue by luckman212** [alexjustesen/speedtest-tracker#872]
Until https://github.com/alexjustesen/speedtest-tracker/issues/687 (if ever) is implemented, I'm really only interested in tracking **latency** and making sure my bandwidth hasn't dropped below a very low threshold, like from 1Gbit → 100Mbit for example.

So I've set my alerts accordingly, but the ST docker container is still using a lot of bandwidth, and I think occasionally the tests themselves interfere with my VoIP calls, streaming etc.

I've been looking into ways to artifically limit/cap the bandwidth of the container itself, using `tc`. I had to first edit my Docker compose file to include the required `NET_ADMIN` capability, e.g.:

```yml
services:
  speedtest:
    ...
    cap_add:
       - NET_ADMIN
```

But, even after I did that and rebuilt the containers, it just kills the container's network stack as soon as I set up the limiter. For example, I was trying to execute the following from inside the container itself:

```
docker exec -it speedtest sh
```
then
```shell
tc qdisc add dev eth0 root handle 1: htb
tc class add dev eth0 parent 1: classid 1:1 htb rate 100Mbit
tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip src 0.0.0.0/0 flowid 1:1
```

Is this is a dead-end? Does anyone know of a solution to cap bandwidth like this?

**Comment by alexjustesen** [comment]
As far as I know it's not possible with Docker networking.

It's hacky but you could always (depending on your network setup) limit it at the router/switch or do it physically and make a custom cat5 cable with only two of the pairs.

**Comment by luckman212** [comment]
The problem is that I run it on my NAS, so I can't use the switch or the physical cable to limit the bandwidth otherwise everything on the NAS would be capped, including file sharing, NFS etc.

Usinc tc seemed promising but I just can't get it to work. Maybe someone will figure out a way.

E.g. https://github.com/moby/moby/issues/4763#issuecomment-1774218714

**Comment by alexjustesen** [comment]
I'll tinker with it later this week but tbh it's not going to be a priority.

**Comment by alexjustesen** [comment]
Did some digging and couldn't find a good way to limit bandwidth at the container level. I'll keep this in mind but at this time not something I'm planning on working on.
