### ISSUE TITLE
Having a Docker install issue. 

### ISSUE THREAD

**Issue by spartangoalie** [alexjustesen/speedtest-tracker#875]
I am trying to install the speed test tracker but i keep getting an issue with the install i may be missing something but the error i get is:

failed to register layer: unlinkat /usr/share/doc/adduser/examples/adduser.local.conf.examples: invalid argument

**Comment by alexjustesen** [comment]
Can you share your `docker-compose.yml` config and also more details about the host system you're running on?

**Comment by alexjustesen** [comment]
Closed stale convo
