### ISSUE TITLE
Automatically prune results

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#880]
### Discussed in https://github.com/alexjustesen/speedtest-tracker/discussions/877

<div type='discussions-op-text'>

<sup>Originally posted by **Jaxel** October 28, 2023</sup>
I don't know about you guys, but I don't need the results to my speedtests from 6 months ago. Is there a way to set it up so that result logs older than 28 days automatically get deleted?</div>

Add `Prunable` trait to `Results` model to allow for records to be automatically pruned from the database.

Docs: https://laravel.com/docs/10.x/eloquent#pruning-models

**Comment by switchman** [comment]
Agreed its needed.  Just found this project and am trying it out now.  I like it.

**Comment by zyystudio** [comment]
look forward to v0.16

**Comment by ChristophKronberger** [comment]
Hi @alexjustesen 
Looking forward to implementing this. I did something similar in #1141. 

I think there should definitely be a configurable option in the settings.
