### ISSUE TITLE
Log ERROR - absolute Download Threshold Failed 

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#881]
Using lasted version in Docker in Unraid
Threshholds:
DL=400
UP=5
Ping=30

it seems only in log error ,but wasnt befor i think : 

`production.ERROR: absoluteDownloadThresholdFailed(): Argument #2 ($download) must be of type float, null given, called in /var/www/html/app/Listeners/Threshold/AbsoluteListener.php on line 72 {"exception":"[object] (TypeError(code: 0): absoluteDownloadThresholdFailed(): Argument #2 ($download) must be of type float, null given, called in /var/www/html/app/Listeners/Threshold/AbsoluteListener.php on line 72 at /var/www/html/app/helpers.php:37)`

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/6fd0498b-6c27-485f-99a6-c75c7f46b265)

**Comment by alexjustesen** [comment]
It looks like the download test failed for your run, has this happened since or only once? Can def code around these random failures.

**Comment by masterwishx** [comment]
its happened some times , last time 2 days ago :

![image](https://github.com/alexjustesen/speedtest-tracker/assets/28630321/86775ac6-6ae7-4923-a41e-7daf9af605be)

by the logs i was thinking value in setting of thresholds must be float not integer...

**Comment by alexjustesen** [comment]
Yeah it should account for the type for sure and maybe I'll also add some alerting when a piece of the test fails
