### ISSUE TITLE
[SOLVED] Failed to find a working server

### ISSUE THREAD

**Issue by Alexaandre** [alexjustesen/speedtest-tracker#883]
**Describe the bug**
The bug appears when i tries to make a speedtest within the tracker app, job is queed then nothing works . 

**To Reproduce**
1. Go to Dashboard
2. Click on Queue speedtest
3. go to results menu

**Expected behavior**
i Expect to see results and not 2 red cross within red circle

**Environment (please complete the following information):**
 - OS: debian 12
-  Architecture: amd64
 - Browser chrome

**Logs**
If applicable, check the logs for any error that might of occurred.

{"type":"log","timestamp":"2023-10-31T23:43:27Z","message":"Error: [0] Timeout occurred in connect.","level":"error"}

**Additional context**
Tried to accept License by entering in containter then typing spedtest then answering yes to the fact i accept the licence .

**Comment by alexjustesen** [comment]
Are you letting the app select a server or are you specifying a server?

**Comment by Alexaandre** [comment]
_Hi, I tried both, with and without servers, the results are the same._ 

EDIT : i found out my firewall from my router was set to custom, which in this mode, does not allow the connection...
