### ISSUE TITLE
[REQ] Consider adding the ability to use fast-cli  / fast.com for measurement, over speedtest

### ISSUE THREAD

**Issue by jaxjexjox** [alexjustesen/speedtest-tracker#884]
**Is your feature request related to a problem? Please describe.**
speedtest / speedtest-cli relies on an open port 8080, which is entirely not possible in my environment.
(I totally understand, this isn't even remotely your problem)

**Describe the solution you'd like**
Considering all your fantastic work in the rest of the package, I suspect that adding fast-cli for measurement, while not easy, wouldn't be extremely difficult.     I could be totally wrong, of course.

**Additional context**
No, I suspect this all makes sense, hopefully.  

Here's some links:
https://github.com/sindresorhus/fast-cli
https://www.npmjs.com/package/fast-cli

If this is not viable, no problem in the slightest, I appreciate your effort and the effort of the vast majority of you folks producing this stuff.  It's so handy for us all.

Thank you.

**Comment by jaxjexjox** [comment]
Wow I didn't expect you to consider it, that's super kind of you.   Thank you.

If it's too much, don't stress yourself of course.     If I had any skills at all, I'd do it myself!

Ta

**Comment by Peterkal2112** [comment]
Why not both ? Why over speedtest.net if you can make it alongside each other with different scheduled time, OR use just one ....

**Comment by Deses** [comment]
+1
I want to keep using Speedtest

**Comment by jaxjexjox** [comment]
This is not about switching to fast.com - I totally don't want to use fast as default. I also prefer speedtest generally.
I'd just like an option to switch the test engine at the backend.

This is very specific to my needs (and perhaps a small amount of people) where speedtest won't work properly or is unreliable.
@Deses  I assure you, do not want the original functionality reduced.

Perhaps just a flag for the docker launch, "-E  test_engine=fast"  or even a fork of this, which I suspect would be otherwise very similar.

**Comment by alexjustesen** [comment]
To avoid confusion I wont be replacing any tools just adding extra ones. In the future you'll be able to set multiple scheduled tests and each of those tests choose the tool you'd like to use to run the test.

**Comment by alexjustesen** [comment]
Now tracking in https://github.com/alexjustesen/speedtest-tracker/discussions/976
