### ISSUE TITLE
Migrate SQLite to new database

### ISSUE THREAD

**Issue by JKusber** [alexjustesen/speedtest-tracker#886]
Hello Alex,

I've been using Speedtest for quite some time now. I actually wanted to update it again (I haven't updated it for a while).

At first I got an error 500 after restarting the container. I quickly found out that it was due to the SQLite drop (thanks for the good documentation). To get the test running again, I added the SQLite data to my configuration. That worked.

But how should I proceed now, can I somehow switch to a mysql db with a migration of my old data (currently having problems with my provider, so don't want to lose the data). What is the best approach?

Best regards
Johannes

**Comment by alexjustesen** [comment]
In-app I don't have an export/import function yet (planned). But you could browse the sqlite DB with something like DBeaver, export just the `results` table to a CSV, switch to using a MySQL DB and then import that table using DBeaver again.

**Comment by JKusber** [comment]
Thank you for the information. Then I will give it a try.

Is the counter (for the next tests), then just assigning the next ID = count++ or do I need to set it anywhere?

**Comment by JKusber** [comment]
Hi,

I downloaded the old database.sqlite file, exported the results table as csv and set-up the new version. It is up and running, but I fail to establish a connection to MariaDB. Unfortunately, I'm not very familiar with Docker, that's may the reason.

I have tried the following connections in DBeaver:
- SSH tunnel to SynologyNas (where Docker is running) --> successful
- Connection like in the screenshot (tried it also with Server-Host: localhost, 127.0.0.1)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/12516802/52bcc9b0-6f29-479f-a7db-d57144bb0f8b)

But I always get this error during connection:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/12516802/27edb269-1c39-4435-9e1c-12af5832e2cd)

Do you know, how I can access the in the container running database?

**Comment by alexjustesen** [comment]
> Thank you for the information. Then I will give it a try.
> 
> Is the counter (for the next tests), then just assigning the next ID = count++ or do I need to set it anywhere?

That'll be in the settings table, I suggest just recreating your settings in the admin  panel though.

**Comment by alexjustesen** [comment]
You'll want to use `3306` as the DB port and it should be either the IP of the machine you're running it on or if local you can use `localhost`

**Comment by JKusber** [comment]
Mhh, I have no idea why I can't connect? Do I have to forward the port 3306 "out" of the container and include it therefore in the docker-compose file?

**Comment by alexjustesen** [comment]
Correct, you would need to expose that port outside of the container. Making sure nothing is running on the host at `3306` you can do `3306:3306`.

**Comment by JKusber** [comment]
To be honest, I have no idea what I am doing wrong. The SSH tunnel is always successful, but from there I didn't get any connection to the DB (even with the port 3306 exposed in my compose.yaml.

I think I won't follow up the migration.

**Comment by alexjustesen** [comment]
#294 to tie to the base feature

**Comment by HRA42** [comment]
> To be honest, I have no idea what I am doing wrong. The SSH tunnel is always successful, but from there I didn't get any connection to the DB (even with the port 3306 exposed in my compose.yaml.
> 
> I think I won't follow up the migration.

you need to expose the port the host system, like mentioned above, after that you connect to the host ip on port 3306. With an SSH Tunnel you need to use the localhost and expose the port, you can't connect inside the docker network with the ip of the container itself.
