### ISSUE TITLE
Can I modify the UI to show me average speed calculated from all tests DL/UP ?

### ISSUE THREAD

**Issue by Peterkal2112** [alexjustesen/speedtest-tracker#887]
In Dashboard I have "Latest DL/UP", and a % stat of if the test was faster / slower than the previous one...

Would it be possible to change these or add one more stat table the same style but it would not show latest DL/Up but "Average DL/UP" which would be calculated from all of the previous tests ?

**Comment by alexjustesen** [comment]
At the moment no, I'm using a canned stat card from the Filament admin panel.
