### ISSUE TITLE
Showing much slower speeds than speedtest.net/nperf/fast.com, google, etc.

### ISSUE THREAD

**Issue by ks2018ks** [alexjustesen/speedtest-tracker#888]
**Describe the bug**

Speeds reported by the [speedtest-tracker] appear to be much slower than the 

**To Reproduce**
1. view results/dashboard
2. queue test
3. run speedtest from browser at speedtest.net/nperf/fast.com, google,
4. compare results 

**Expected behavior**
More or less similar results

**Environment (please complete the following information):**
Synology installation
 
**Screenshots**
speedtest-tracker results 87 down 58 up
<img width="906" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/37977911/aa0d8e5c-31ab-4ceb-a13d-8c9160701d8b">

https://www.speedtest.net/result/15477106376 186 down 14 up

nperf results 197 down 60 up

Edited by @alexjustesen: removed the screenshots as it had your IP address in them.

**Comment by alexjustesen** [comment]
Couple of things...

1. If you're running those other tests from a separate device it's not apples to apples so it's had to narrow down any issues.
2. Make sure your NAS isn't downloading anything that could effect the performance of a speedtest.
3. Make sure you aren't running duplicate speedtests at the same time (maybe across different applications).
4. Synology Docker networking can have some bottlenecks and I've seen some past reports of that issue. Can happen with older devices or usage of other Docker networks (not host or bridge).

**Comment by ks2018ks** [comment]
Thanks for you messages

> 2. Make sure your NAS isn't downloading anything that could effect the performance of a speedtest.
Nothing else downloading

> 3. Make sure you aren't running duplicate speedtests at the same time (maybe across different applications).
Only one at a time

> 4. Synology Docker networking can have some bottlenecks and I've seen some past reports of that issue. 
How would I go about working out if that's the case and/or how to solve it?
(When I googled "Docker bandwidth bottlenecks", I didn't get much I understood, but I did see [here](https://www.reddit.com/r/docker/comments/5yp3q5/eliw5_what_are_the_bottlenecks_in_docker/) "Docker containers have few bottlenecks. However, if you are using one with a bridged network configuration you will see poor network performance".  Am I right in thinking speedtest-tracker operates this way?  I also saw [this article](https://stackify.com/docker-performance-improvement-tips-and-tricks/), which confused me because it seems any network performance issue could be to do with the app or the environment its running in

**Comment by alexjustesen** [comment]
I'm going to close this issue, if you end up finding a solution feel free to open a new issue so I can add it to the docs.

**Comment by ks2018ks** [comment]
Perhaps before you close it you could give me steer on how I would I go about trying to resolve whether its a app issue and docker issue, a synology issue and how to fix it?

**Comment by alexjustesen** [comment]
I'd try installing the other Speedtest Tracker (link in the docs) and see if the results are similar.

**Comment by ks2018ks** [comment]
I couldn't get the other Henry's Speedtest Tracker to install but...

Comparing fast.com on a PC on the network with running it from the synology through docker (with `docker run -it --rm ghcr.io/ciffelia/fast-speed-test`), it was also much slower via docker on the NAS (85 Mbps on the NAS vs 180Mbs on the PC

When I when I tested another Oookla docker speed test on the NAS (`docker run --rm moutten/speedtest-cli`) it was *much* slower than your Speedtest Tracker ([reported speeds](https://www.speedtest.net/result/c/847fcbfd-233b-4075-9771-90e120bb6d23) 10-15% of of your Speedtest Tracker), but both [much slower than from a pc](https://www.speedtest.net/result/15487759058).

So then I tried OpenSpeedTest (via docker on the NAS) which gives me results quite consistently 25% faster that the your Speedtest Tracker, but also quite consistently [about half the speed from a browser on the PC](https://openspeedtest.com/results/62171872).

The only thing I can conclude from is that the NAS/docker installations are clearly much slower.

What I don't understand though, is whether or not anything can be done to make the docker-installed Speedtest Tracker perform without whatever is causing the results to be so inaccurate.

**Comment by alexjustesen** [comment]
> What I don't understand though, is whether or not anything can be done to make the docker-installed Speedtest Tracker perform without whatever is causing the results to be so inaccurate.

It just seems to be Docker on some Synology NAS's. I've got it running in Docker on a Swarm node on a Raspberry Pi 4b+, on my DS 920+ and my Unraid NAS and all perform the same. It's been a difficult one to track down because its seemingly random 🤷‍♂️.

**Comment by hoorna** [comment]
Speedtest Tracker on my Synology DS920+ gives also correct speeds. The speed measured by Speedtest Tracker exactly matches the subscription speed of my provider (500Mbps down and 50Mbps up).
