### ISSUE TITLE
500 server error, versions after v0.11.17 dont work

### ISSUE THREAD

**Issue by y0nei** [alexjustesen/speedtest-tracker#895]
**Describe the bug**
Nothing much to say, v0.11.17 is the latest version that works, latest (v0.13.1) and versions prior to that just refuse to work properly and throw empty error logs, then freeze and give a 500 error on the UI. 

**Error log:**
```
speedtest-tracker     | ❌ There seems to be a failure in checking the web server + PHP-FPM. Here's the response:
```

`docker-compose.yml`:
```yml
services:
  speedtest-tracker:
    # New releases cause problems, v0.11.17 is stable
    #image: "ghcr.io/alexjustesen/speedtest-tracker:v0.11.17"
    image: "ghcr.io/alexjustesen/speedtest-tracker:v0.13.1"
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=Europe/Warsaw
    ports:
      - "8300:80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./web:/etc/ssl/web"
    depends_on:
      - db

  db:
    image: mariadb:10
    container_name: speedtest-tracker_db
    restart: always
    expose:
      - 3306
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - speedtest-db:/var/lib/mysql

volumes:
  speedtest-db:
    name: "speedtest-db"

networks:
  default:
    name: "speedtest"
```

**Comment by alexjustesen** [comment]
Since you're specifying your environment variables in your `docker-compose.yml` file make sure you remove `.env` from your mounted volume if it exists.

I also don't see an `APP_KEY` in your config so you'll want to add that.

**Comment by KGBist2000** [comment]
I have the same issue

`version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            #- '8080:80'
            - '5443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TZ=Europe/Berlin
            - TELEGRAM_BOT_TOKEN=Replaced:Replaced
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/root/speedtest_tracker/config:/config'
            - '/root/speedtest_tracker/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - /root/speedtest_tracker/mariadb:/var/lib/mysql`


Logs:
 Clearing any previous caches...

[2023-11-12 20:55:48] production.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracker.cache' doesn't exist (Connection: mysql, SQL: delete from `cache`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracker.cache' doesn't exist (Connection: mysql, SQL: delete from `cache`) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822)


[stacktrace]

#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\\Database\\Connection->runQueryCallback()

#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\\Database\\Connection->run()

#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(557): Illuminate\\Database\\Connection->affectingStatement()

#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3615): Illuminate\\Database\\Connection->delete()

#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php(326): Illuminate\\Database\\Query\\Builder->delete()

#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(693): Illuminate\\Cache\\DatabaseStore->flush()

#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Console/ClearCommand.php(69): Illuminate\\Cache\\Repository->__call()

#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Cache\\Console\\ClearCommand->handle()

#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()

#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()

#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()

#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()

#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()

#13 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()

#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()

#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()

#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(40): Illuminate\\Console\\Command->runCommand()

#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(37): Illuminate\\Console\\Command->callSilent()

#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Foundation\\Console\\OptimizeClearCommand->Illuminate\\Foundation\\Console\\{closure}()

#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Factory.php(58): Illuminate\\Console\\View\\Components\\Task->render()

#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(41): Illuminate\\Console\\View\\Components\\Factory->__call()

#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(238): Illuminate\\Foundation\\Console\\OptimizeClearCommand->Illuminate\\Foundation\\Console\\{closure}()

#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(41): Illuminate\\Support\\Collection->each()

#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Console\\OptimizeClearCommand->handle()

#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()

#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()

#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()

#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()

#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()

#29 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()

#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()

#31 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()

#32 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()

#33 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()

#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()

#35 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()

#36 {main}

[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracker.cache' doesn't exist at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:601)


[stacktrace]

#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(601): PDO->prepare()

#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()

#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\\Database\\Connection->runQueryCallback()

#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\\Database\\Connection->run()

#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(557): Illuminate\\Database\\Connection->affectingStatement()

#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3615): Illuminate\\Database\\Connection->delete()

#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php(326): Illuminate\\Database\\Query\\Builder->delete()

#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(693): Illuminate\\Cache\\DatabaseStore->flush()

#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Console/ClearCommand.php(69): Illuminate\\Cache\\Repository->__call()

#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Cache\\Console\\ClearCommand->handle()

#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()

#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()

#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()

#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()

#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()

#15 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()

#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()

#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()

#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(40): Illuminate\\Console\\Command->runCommand()

#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(37): Illuminate\\Console\\Command->callSilent()

#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Foundation\\Console\\OptimizeClearCommand->Illuminate\\Foundation\\Console\\{closure}()

#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Factory.php(58): Illuminate\\Console\\View\\Components\\Task->render()

#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(41): Illuminate\\Console\\View\\Components\\Factory->__call()

#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(238): Illuminate\\Foundation\\Console\\OptimizeClearCommand->Illuminate\\Foundation\\Console\\{closure}()

#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(41): Illuminate\\Support\\Collection->each()

#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Console\\OptimizeClearCommand->handle()

#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()

#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()

#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()

#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()

#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()

#31 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()

#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()

#33 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()

#34 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()

#35 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()

#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()

#37 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()

#38 {main}

"} 

In Connection.php line 822:

                                                                               

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracke  

  r.cache' doesn't exist (Connection: mysql, SQL: delete from `cache`)         

                                                                               

In Connection.php line 601:

                                                                               

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracke  

  r.cache' doesn't exist                                                       

                                                                               

s6-rc: warning: unable to start service laravel-automations: command exited 1

/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

prog: fatal: stopping the container.

**Comment by itzik1058** [comment]
Had the same error (using the docker compose), I set the APP_KEY using `php artisan key:generate --show` and it worked.
It says in the documentation that the key should be generated automatically but it doesn't look like it.

**Comment by KGBist2000** [comment]
> Had the same error (using the docker compose), I set the APP_KEY using `php artisan key:generate --show` and it worked. It says in the documentation that the key should be generated automatically but it doesn't look like it.

Thank you, i done it.

With Version v0.11.17, no issues. With he latest Version its not working.


🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...

🐇  Configuring Speedtest Tracker...

🔒  Fixing app path file permissions...

✅  Permissions fixed.

🧹  Clearing any previous caches...

✅  Cache cleared.

✅  Environment file exists.

🔗  Creating symlinks for config and log files...

✅  Symlinks created.

✅  An application key exists.

💰  Building the cache...

✅  Cache set.

🚛  Migrating the database...

✅  Database migrated.

✅  All set, Speedtest Tracker started.

[12-Nov-2023 21:20:24] NOTICE: fpm is running, pid 123

[12-Nov-2023 21:20:24] NOTICE: ready to handle connections

[12-Nov-2023 21:20:24] NOTICE: systemd monitor interval set to 10000ms

[2023-11-12 21:20:31] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)


[stacktrace]

**Comment by y0nei** [comment]
> Since you're specifying your environment variables in your `docker-compose.yml` file make sure you remove `.env` from your mounted volume if it exists.
> 
> I also don't see an `APP_KEY` in your config so you'll want to add that.

the `.env` file is only used for docker compose variables, I don't mount that file as a volume

**Comment by KGBist2000** [comment]
The *.env file is deleted already.
here the latest version of the docker-compose file from portainer.

version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            #- '8080:80'
            - '5443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - TZ=Europe/Berlin
            - TELEGRAM_BOT_TOKEN=Replaced:Replaced
            - API_KEY=base64:XLBVEvy2wHbwEMEJuwh94r9hCB7YKAW1T5xfJBPA8a0=
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/root/speedtest_tracker/config:/config'
            - '/root/speedtest_tracker/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - /root/speedtest_tracker/mariadb:/var/lib/mysql

**Comment by epiclulz666** [comment]
yeah broken for me too using it via docker on a unraid server. 500 server error

**Comment by alexjustesen** [comment]
> You have API_KEY not APP_KEY

☝️ this, going to close this issue. If the `APP_KEY` update doesn't work feel free to open a new issue and reference this one.

**Comment by yllekz** [comment]
Hi folks, I'm wresting with a similar issue. I'm not clear on what the fix is based on the above comments. Is there official documentation on this? My container was working then suddenly started erroring out with this encryption key error out of nowhere. The default docker compose yml reference file in this repo doesn't mention this.

**Comment by bam7** [comment]
Yeah, it's stated that the API key format is the root of these problems, but I had all that correct and it didn't help.   The only way I could make the container work was a total redo with all config and database cleared out and a fresh install.   I saved all my old data with the hope to import my history back in but it's becoming less likely the more I look at it.

**Comment by Milkysunshine** [comment]
> Hi folks, I'm wresting with a similar issue. I'm not clear on what the fix is based on the above comments. Is there official documentation on this? My container was working then suddenly started erroring out with this encryption key error out of nowhere. The default docker compose yml reference file in this repo doesn't mention this.
> 
> If there was a breaking change, it needs to be more up front for folks who have run this container for a long time.

run this command and get the **APP**_KEY: `docker exec speedtest-tracker php artisan key:generate --show`

I use docker compose (stacks via portainer), so it is as easy as adding the **APP**_KEY to the environment variables.

Here's my entire docker compose: (Key Redacted)
```

version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8686:80'
            - '18443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
            - APP_KEY=InsertTheGibberishThatTheCommandYouRanCrappedOut (Including the base64: prefix)
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/docker/speedtest-tracker/config:/config'
            - '/docker/speedtest-tracker/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
```

I hope this helps.
