### ISSUE TITLE
Link in email notifications is set to localhost.

### ISSUE THREAD

**Issue by ArthurHuyghe** [alexjustesen/speedtest-tracker#907]
**Describe the bug**
In the notifications that get sent with smtp the link to go to speedtest-tracker is set to localhost, which is not gone work for any device other than the one you installed speedtest-tracker on.

**To Reproduce**
Activate email notifications, press test email and open the email you received.

**Expected behavior**
Allow the ability to set a base url in the docker compose file that points to the actual host of speedtest-tracker.

**Comment by alexjustesen** [comment]
If you're using a `.env` file mounted in your volume you'll need to update `APP_URL` there, if you're passing `APP_URL` in your `docker-compose.yml` file you'll want to add it there and that'll fix the issue.

Feel free to close this issue once you've verified the fix.

**Comment by ArthurHuyghe** [comment]
@alexjustesen, I'm sorry. Took an other look at your documentation and found my exact question in the FAQ. Mabye you could add this in the docs to the section discussing notifications and to the environment variables. So others can find this more easily.
Thanks for your patience and help!
