### ISSUE TITLE
Sort the result set in ascending or descending order for DL/UL/Ping etc ... 

### ISSUE THREAD

**Issue by stephdeville** [alexjustesen/speedtest-tracker#924]
**Is your feature request related to a problem? Please describe.**
Not a problem at all but an improvement in the list view of the past results

**Describe the solution you'd like**
Would be nice to have the possibility to sort the result set in ascending or descending order : currently (App: 0.13.3), this is possible already BUT only for the creation date/time of the tests 

**Additional context**
Nothing to add

**Comment by alexjustesen** [comment]
Real easy, will get it into the next release 👍
