### ISSUE TITLE
Login loop on fresh install

### ISSUE THREAD

**Issue by Cakdom** [alexjustesen/speedtest-tracker#930]
**Describe the bug**
upon initial install from the welcome page click to login which works but then dumps back at the welcome page rather than the dashboard. 

**To Reproduce**
1. Go to url which shows basic landing page with links to resources or login
2. Click on "login to admin panel"
3. enter admin@example.com and password and submit
4. page directs back to welcome page and clicking link to login page no longer works. 

**Expected behavior**
after submitting login credentials end up in the settings/dashboard. 

**Environment (please complete the following information):**
 - OS: Ubuntu server on virtual box run via docker compose
 - Browser: tested on chrome and firefox

**Comment by tweek11** [comment]
> FWIW I also had this issue. A workaround was to create the container using using a previous version, seems 0.13.3 works... Set my login info, then update the container to 0.13.4 (latest), and it logins in fine.

Thank you for mentioning the work around - I ran into the server error 500 code and decided to just do a clean install. As you mentioned 13.4 would not open that admin panel at all - but per your suggestion installed 13.3 and then updated to 13.4 resolved the issue on my end. Again thank you.

**Comment by Cakdom** [comment]
I also found an easier workaround where you just add /admin to the url to manually go to the dashboard. Just in case anyone else is finding this error before the merged fix installs automagicly.

**Comment by hoorna** [comment]
Has this issue something to do with #951? I there suggested the same workaround.

**Comment by alexjustesen** [comment]
Tracking this in #962 now so I don't have to monitor closed issues.
