### ISSUE TITLE
Installation docs suck

### ISSUE THREAD

**Issue by Patrick010** [alexjustesen/speedtest-tracker#933]
Yes, I'm ranting, but for the Docker impaired user the instructions are basically useless.
I dont know the docker-compose commandline to kick off the installation and the docker config asumes there already is a mysql server. If the db doesnt exist the container crashes. A full docker-compose command and a howto on to set up the db is something the uninitiated user expects...

**Comment by alexjustesen** [comment]
Couldn't agree more, currently its in a "brain dump" state just to have something. As we get nearer to `v1` I intend on completely overhauling it making it more beginner friendly as it absolutely assumes you have a basic understanding of Docker currently.
