### ISSUE TITLE
I keep being presented with the login screen after clean install using default login

### ISSUE THREAD

**Issue by glenb2** [alexjustesen/speedtest-tracker#938]
**Describe the bug**
I keep being presented with the login screen after clean install using default login. The UI is not giving me an error, it just loads the login screen again.  No admin panel displayed

**To Reproduce**
1. Install Proxmox
2. Create 2 core 2gb ram VM
3. Install Docker/Portainer
4. Install speedtest-tracker with docker compose (modified paths, db password, ports and timezone)
5. Go to login page and enter default admin credentials
6. I am presented with the login screen

**Expected behavior**
The admin panel should display

**Environment (please complete the following information):**
 - OS: [Debian running in Proxmox]
-  Architecture: [amd64]
 - Browser [chrome and safari]
 - Version [0.13.4

**Screenshots**
<img width="962" alt="Screenshot 2023-11-27 at 8 23 21 PM" src="https://github.com/alexjustesen/speedtest-tracker/assets/23586374/0c7e17ea-b64d-44d8-9619-7c810e5b24c0">

**Logs**
<img width="1500" alt="Screenshot 2023-11-27 at 8 24 50 PM" src="https://github.com/alexjustesen/speedtest-tracker/assets/23586374/aad5dd50-997e-465c-a213-013c13466799">
<img width="1505" alt="Screenshot 2023-11-27 at 8 25 00 PM" src="https://github.com/alexjustesen/speedtest-tracker/assets/23586374/5debc49d-7dfa-488b-8a85-ce7220747a86">

**Additional context**
This is happening on a fresh install

**Comment by alexjustesen** [comment]
Fixed in #936
