### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS after login

### ISSUE THREAD

**Issue by hoorna** [alexjustesen/speedtest-tracker#951]
From version 0.13.4 (or perhaps 0.14.0-beta1; I am not really sure) I have a problem with Speedtest-tracker after the login web page. After entering my password (followed by a return of course) I first get an empty page and then after a while a web page with "ERR_TOO_MANY_REDIRECTS". In the address bar of my browser (Chrome) stays then: "admin\login". This behavior was not the case before version 0.13.4.

It does not matter whether I use my internet DNS domain name in the browser (which is routed to the Speedtest container via a Reversed proxy) or the internal IP address of Speedtest-tracker. The result is the same.

After I have entered my password, I can access the Speedtest-tracker web pages by typing, for example, "/admin/results" in the address bar of my browser. "/admin" also works (this takes me to the Dashboard web page).
As soon as I see the Speedtest-tracker web page again, the Speedtest-tracker menu on the left works normally unless I click "Home". That link refers to admin/login whereby I get the above-mentioned error message.

Maybe more people experience this? There may also be a connection with other reported issues (such as the Error 500 message)?

FYI: I log in with my own account with the admin role.

**Comment by alexjustesen** [comment]
Caught this as well this morning. It's likely how I'm handling the "intended" URL after logging in.

**Comment by hoorna** [comment]
To be sure a moment ago I build a new container with Release v0.14.0-beta5 and I deleted my cookies in the Chrome browser. Immediately after entering my password Speedtest tracker tries to open /admin/login. After a while waiting the Err_Too_Many_Redirects shows up. When I delelte "/login" in the address bar the Dashboard page opens.

It does not matter whether I use my internet DNS domain name in the browser (which is routed to the Speedtest container via a Reversed proxy) or the internal IP address of Speedtest-tracker. The result is the same.
It also does not matter if I use Chrome of Edge: in either case the same result.

This is exactly the same behaviour as before (see my first post).

**Comment by hoorna** [comment]
Has this issue something to do with #930 The same workaround is there suggested for a issue that looks someting similar.

**Comment by alexjustesen** [comment]
Tracking this in #962 now so I don't have to monitor closed issues.
