### ISSUE TITLE
No application encryption key specifed

### ISSUE THREAD

**Issue by paytah232** [alexjustesen/speedtest-tracker#959]
Hi,

This has been working for ages, and I think the container updated and now gives the error, log attached:

What can this be?

[
[speedtest.txt](https://github.com/alexjustesen/speedtest-tracker/files/13538479/speedtest.txt)
](url)

**Comment by Kaotic3** [comment]
Can we reopen this and be a bit cheeky and say - those instructions in the FAQ are not very clear given that this is a fundamentally tool breaking problem.

This isn't just the font is the wrong size - the app simply doesn't work until you fix this - I think we should have some clear instructions?  Maybe even a step by step - run this command, get this, run this command, use this, on this variable.

What we have is:

"Add the generated string to your environment variables attached to APP_KEY=generatedstringgoeshere"

What variables attached to APP_KEY - what does that mean? Are there more than one? Why is this plural?   How are they attached? How do I find those variables? Is this in the docker container or outside of the docker container? Do I need them in both?

For an issue that renders the tool entirely unusable, these are not clear instructions, sorry.

**Comment by Kaotic3** [comment]
Here is a suggestion for instructions:

I get a warning on container start up that the APP_KEY is missing

As of v0.12.0 the app key is generated on start-up and it is ok to ignore this warning.  To set a persistent key follow the steps below:

1. Open the CLI of your docker 
 `sudo docker exec -it [docker_container_id] /bin/bash`

2.   Use the command `php artisan key:generate --show` to generate a string, that will begin with base64:

3.  If using Docker Compose you can add a line to your compose file: 

```
environment:
  - PUID=1000
  - PGID=1000
  - DB_CONNECTION=mysql
  - DB_HOST=db
  - DB_PORT=3306
  - DB_DATABASE=speedtest_tracker
  - DB_USERNAME=speedy
  - DB_PASSWORD=password
  - APP_KEY=[base64:value]
```

4. - Else.....

I don't know how to do step 4 or step 5 for people who run this in different ways...

**Comment by alexjustesen** [comment]
Tracking this change for the docs elsewhere but yes, it and the docs need an overhaul.

**Comment by cristiandeschamps** [comment]
strange, I have my `APP_KEY=base64:.....` setup and everything was working fine since a month, but today, I got the error. Not sure why since I already have my key.. I will do a backup of the key and try again. 

```
[2023-12-20 05:45:58] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
...
```

**Comment by dereitz** [comment]
Glad someone else posted an issue about this and pointed out the FAQ.  Between the responses and the FAQ, I was able to get things working once again.  Thanks!

**Comment by somera** [comment]
@dereitz what I did

1. Started the container without the API_KEY -> I got the error
2. `docker exec -it [speedtest-tracker] /bin/bash`
3. Inside the container `php artisan key:generate --show`
4. Add the API_KEY
```
docker run -d --name speedtest-tracker \
    --restart=unless-stopped \
    -p 8765:80 \
    -p 8443:443 \
    -e PUID=1000 \
    -e PGID=1000 \
    -e "DB_CONNECTION=pgsql" \
    -e "DB_HOST=xxx.xxx.xxx.xxx" \
    -e "DB_PORT=5432" \
    -e "DB_DATABASE=speedtest_tracker" \
    -e "DB_USERNAME=xx" \
    -e "DB_PASSWORD=xx" \
    -e APP_KEY=base64:xxxxxxxxx \
    -v /data-files/data/docker/speedtest-tracker:/config \
    -v /data-files/data/docker/speedtest-tracker/web:/etc/ssl/web \
    alexjustesen/speedtest-tracker
```

**Comment by gabeklavans** [comment]
My server was running fine for 6 days, then it started returning a 500 error:

```
production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encrypti
on\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encry
ptionServiceProvider.php:79)
```

My solution was just to restart the docker container. Strange.
