### ISSUE TITLE
After login redirected to the `/` root url instead of the admin panel

### ISSUE THREAD

**Issue by parallax-home** [alexjustesen/speedtest-tracker#967]
I set up a fresh instance of Speedtest-tracker in Docker. On starting up for the first time, I was able to reach the user/login page and after entering the default credentials was returned to the "Getting Started" screen. Clicking on the link to return to the login just reloads the getting started screen. No errors in the logs. I re-pulled the container images with the same result.

I completed the first login in Chrome and since then am able to use Firefox.

Firefox 
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"

**Comment by CartCaved** [comment]
It was also not working for me, either with Chrome or FF.

I reverted to v0.13.3, which resolved it for me.

**Comment by alexjustesen** [comment]
@parallax-home I'm going to change the title of this issue on you just so it stands out and reflects the actual root cause.
