### ISSUE TITLE
Can not access GUI

### ISSUE THREAD

**Issue by nocomment-bln** [alexjustesen/speedtest-tracker#97]
hi guys,

I installed everything but I can not access the webGUI because of SSL error.

how can I turn off SSL ?

is there an environment variable available ?

thanks

**Comment by alexdelprete** [comment]
Yes:

1. `SSL_MODE=mixed` both `http/80` and `https/443` available
2. `SSL_MODE=full` (default) only `https/443` available
3. `SSL_MODE=off` only `http/80` available
