### ISSUE TITLE
Hide unsuccessful results on dashboard

### ISSUE THREAD

**Issue by asmartin** [alexjustesen/speedtest-tracker#993]
**Is your feature request related to a problem? Please describe.**

If there is an unsuccessful result (The "Successful" column on the Results page is red), this is still displayed on the Dashboard and gives a false impression of poor performance (because it causes the graph to dip since there's no data at this point).

**Describe the solution you'd like**
Ideally there would be an option to exclude unsuccessful results from being displayed on the Dashboard

**Additional context**
Thank you for considering this request!

**Comment by zackmuc** [comment]
Could there be a better log to see which server failed?

**Comment by alexjustesen** [comment]
Charts and stats widgets will no longer include failed results as of `v0.16.0`.

**Comment by asmartin** [comment]
Thanks for implementing this!
